### ISSUE TITLE
Live testing in hostile environment - China

### ISSUE THREAD

**Issue by peterpacz1** [jlund/streisand#102]
Hello Streisand team,

After nearly a year of development, I would like to thank all of you - from the smallest contributor to the author of the biggest pull, for helping to free information.

We really haven't seen a documented live test of streisand in a hostile environment, and I since I will be traveling to China on the 21st - it would be an excellent opportunity for us to see how Streisand would cope with a real world test.

I'll try to document this as I go along here - so we can have some additional data about streisand's actual effectiveness.

**Comment by jlund** [comment]
Streisand now mirrors a local copy of the latest version of Shadowsocks for Android.

**Comment by skeeve42** [comment]
Awesome!

**Comment by faddat** [comment]
Skeeve:

"Parallel Internet" is exactly the way I describe it.  Good luck!

**Comment by strixaluco** [comment]
Thanks to all of the people, who are contributing and improving this project.
Today I started testing Streisand, first - with sshuttle. Performance and connection are great and I haven't faced any issues so far, I will try to keep posting here if something worth occurs.
