### ISSUE TITLE
DO | Fails getting latest Debian image

### ISSUE THREAD

**Issue by lukeberry99** [jlund/streisand#104]
This has been working fine before, however after updating both Streisand and Ansible I get the following error.
```
ASK: [genesis-digitalocean | Get the latest 'Debian 7.0 x64' image ID from the DigitalOcean API] ***
failed: [127.0.0.1] => {"changed": true, "cmd": "curl -s 'https://api.digitalocean.com/images/?client_id=xxxx&api_key=xxxx' | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j[\"images\"] if img[\"slug\"]==\"debian-7-0-x64\"][0][\"id\"]'", "delta": "0:00:00.088776", "end": "2014-12-23 02:00:38.743550", "rc": 1, "start": "2014-12-23 02:00:38.654774", "warnings": ["Consider using get_url module rather than running curl"]}
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/__init__.py", line 338, in loads
    return _default_decoder.decode(s)
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 365, in decode
    obj, end = self.raw_decode(s, idx=_w(s, 0).end())
  File "/System/Library/Frameworks/Python.framework/Versions/2.7/lib/python2.7/json/decoder.py", line 383, in raw_decode
    raise ValueError("No JSON object could be decoded")
ValueError: No JSON object could be decoded

FATAL: all hosts have already failed -- aborting
```

**Comment by jlund** [comment]
Apologies for the delayed response! I haven't made the jump to Yosemite on my Mac yet, but the latest Homebrew formula for curl seems to work just fine when accessing HTTPS URLs on Mavericks. Homebrew also does not symlink its `curl` installation into `/usr/local` and displays a warning that using its version alongside the stock OS X version "can cause all kinds of trouble."

Perhaps the formula has been updated to fix the certificate issues sometime in the past couple of months? Perhaps it only affects Yosemite? I'm sorry that I can't offer more help, but I'm confident that there isn't anything Streisand can do to fix this issue or prevent it from happening. A working version of `curl` that can properly verify SSL certificates is a pretty basic requirement, and adding the `-k` or `--insecure` flag would leave the DigitalOcean API credentials vulnerable to a MITM attack.

I would recommend switching back to the stock version of curl that comes with OS X.
