### ISSUE TITLE
DNS resolution through OpenVPN fails when firewall is enabled

### ISSUE THREAD

**Issue by pyrobisqit** [jlund/streisand#105]
There is a firewall info document, telling the sysadmin what ports it requires to be open in order to work normally. What it doesn't say is that port 53/UDP needs to be open for DNS resolution through OpenVPN to work.

Just launch a new instance (I used DigitalOcean, but it doesn't matter what provider you use), install the firewall (I use UFW), open all ports in the documentation, then enable it, connect via OpenVPN direct, and browse to google.com: It won't resolve. However, if you know the IP, the traffic gets pushed through the VPN with 0 issues.

**Comment by jlund** [comment]
I just updated the generated firewall instructions. Thank you for your help in troubleshooting this!
