### ISSUE TITLE
Robots.txt needed to prevent (most) web crawlers from indexing streisand

### ISSUE THREAD

**Issue by peterpacz1** [jlund/streisand#106]
The default nginx directory should include a robots.txt that would prevent most web crawlers from indexing the site.

It's a rather easy thing to fix - just have the script create a robots.txt file in the root directory of the webserver, with the following contents:

    # Disallows ALL robots from indexing ALL subdirectories
    User-agent: *
    Disallow: /

**Comment by jlund** [comment]
They shouldn't be able to index anything because the endpoint requires authentication. Or am I missing something?

**Comment by peterpacz1** [comment]
Attempting to access the ip address without https:// appended in front of it would allow the default streisand homepage to be displayed.

So you probably would want the robots.txt file, at least to prevent the index.html home page to be indexed.

**Comment by jlund** [comment]
It looks like this was also related to #109. Streisand now ensures that nothing is running on port 80, so there's no default "It works!" page to index anymore even if a provider is including the Apache package in their default image.
