### ISSUE TITLE
Ensure that Apache is not installed/running

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#109]
Debian 7 Linode instances appear to have Apache installed by default, which is somewhat disappointing and surprising. Other providers may have images which are similarly affected. While this doesn't directly conflict with Nginx because Nginx only binds to port 443, it is an unnecessary package and there's no need for port 80 to be open at all. Streisand should remove any superfluous Apache packages and ensure that no Apache processes are running.

**Comment by zacharydenton** [comment]
Apache is also installed by default on DigitalOcean. This means that anyone can access the streisand configuration without authenticating by visiting the site over HTTP (port 80).

Something like `apt: pkg=apache2 state=absent` should fix the problem.

**Comment by jlund** [comment]
Fortunately, Apache would never have been configured by default with a vhost that referenced any of the Streisand Gateway files. It was not the case that "anyone [could] access the streisand configuration without authenticating."

Still, even seeing the "It works!" page was annoying. Port 80 is now silent!

**Comment by zacharydenton** [comment]
Great, glad it's fixed. The reason I said that anyone could access the streisand configuration without authenticating is because the default apache vhost (at least on DigitalOcean) has a `DocumentRoot` of `/var/www`. Since the streisand configuration is located in `/var/www/streisand`, this meant that accessing `http://<streisand url>/streisand` displayed the streisand configuration, without prompting for authentication.

`$ cat /etc/apache2/sites-enabled/000-default`
```
<VirtualHost *:80>
        ServerAdmin webmaster@localhost

        DocumentRoot /var/www
        <Directory />
                Options FollowSymLinks
                AllowOverride None
        </Directory>
        <Directory /var/www/>
                Options Indexes FollowSymLinks MultiViews
                AllowOverride None
                Order allow,deny
                allow from all
        </Directory>

        ScriptAlias /cgi-bin/ /usr/lib/cgi-bin/
        <Directory "/usr/lib/cgi-bin">
                AllowOverride None
                Options +ExecCGI -MultiViews +SymLinksIfOwnerMatch
                Order allow,deny
                Allow from all
        </Directory>

        ErrorLog ${APACHE_LOG_DIR}/error.log

        # Possible values include: debug, info, notice, warn, error, crit,
        # alert, emerg.
        LogLevel warn

        CustomLog ${APACHE_LOG_DIR}/access.log combined
</VirtualHost>
```

**Comment by jlund** [comment]
Wow. You are correct. I just added an additional check to further protect against this. Thank you for your help! I really appreciate it.
