### ISSUE TITLE
Upgrade Debian kernel for DigitalOcean users

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#112]
Related to #90 and #111.

**Comment by shenye** [comment]
I'm getting issue #89 now, with a completely new droplet over on Digital Ocean.

```
TASK: [openvpn | Restart OpenVPN so the 10.8.0.0 interface is available to dnsmasq] ***
failed: [###.###.###.###] => {"failed": true}
msg: SIOCSIFADDR: No such device
: ERROR while getting interface flags: No such device
SIOCSIFDSTADDR: No such device
: ERROR while getting interface flags: No such device
SIOCSIFMTU: No such device


FATAL: all hosts have already failed -- aborting
```

**Comment by jlund** [comment]
@shenye I just created a ticket with DigitalOcean about this. The issue is that they have updated their base Debian 7 filesystem image, but they have failed to change the default kernel that new Debian 7 droplets launch with. As such, the instances are coming up in a completely broken state. The workaround for now is to do the following:

1. Go into the droplet's status page in the DigitalOcean Control Panel.
1. Click *Settings*.
1. Click the *Kernel* tab.
1. Click on the drop-down menu and choose the very last option:
    * `Debian 7.0 x64 vmlinuz-3.2.0-4-amd64 (3.2.65-1+deb7u1)`
1. Click *Change*.
1. Click on the *Power* tab and choose the *Power Cycle* option.
1. Wait until the event is no longer "processing".
1. Run Streisand again.

This is super annoying, and I'm hoping that DigitalOcean will respond to the ticket soon and fix this broken configuration. If they don't, I have some ideas on how I can automate this process, but it won't be pretty. I would be surprised if that's necessary though. Typically VPS providers will want their VPS systems to work :)

**Comment by shenye** [comment]
@jlund Worked! Had to scrub, but remaking the droplet kept the 7.0 kernel.

**Comment by jlund** [comment]
Good to hear! DigitalOcean responded to the ticket. The default kernel is now `3.2.65-1+deb7u1` for new Debian 7 droplets. Yay!
