### ISSUE TITLE
Updates on Shadowsocks Clients

### ISSUE THREAD

**Issue by clowwindy** [jlund/streisand#113]
Now the new Windows client (from [shadowsocks-csharp](https://github.com/shadowsocks/shadowsocks-csharp) project) will automatically configure system proxy for you. Simply click `Enable` item in the tray menu, open Chrome, and there you go.

Also, both Windows and OS X clients support scanning QR code from current screen. The configuration is now less painful.

You may want to update instructions :)

**Comment by skeeve42** [comment]
Wow, the windows client works flawlessly! It scanned the QR code off the screen, I enabled global proxy and whatismyip immediately jumped to my VPS server ip.

**Comment by skeeve42** [comment]
And the Mac OS client also works perfectly. Thanks for the heads up and the work on shadowsocks clowwindy.

**Comment by jlund** [comment]
@skeeve42 I don't currently have access to a Windows machine. Would you be willing to help out with a list of steps for configuring the Windows client using a QR code? That will allow me to update the documentation so that it reflects this cool new feature.

**Comment by skeeve42** [comment]
Yes, let me finish up moving, but it shouldn't take long once I sit down and can take a look again--it's a pretty simple and straightforward process.

**Comment by skeeve42** [comment]
#134  You didn't mention OS X, but I figured I would update those too while I was at it.

**Comment by jlund** [comment]
Thanks @clowwindy and @skeeve42. These are big improvements, and I really appreciate the help.
