### ISSUE TITLE
error while deploying to linode

### ISSUE THREAD

**Issue by chespest** [jlund/streisand#117]
TASK: [genesis-linode | Get the default SSH key] ****************************** 
changed: [127.0.0.1]

TASK: [genesis-linode | Get the latest 'Debian 7.7 x64' image ID from the Linode API] *** 
failed: [127.0.0.1] => {"changed": true, "cmd": "curl -s 'https://api.linode.com/?api_key=[redacted]&api_action=avail.distributions' | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j[\"DATA\"] if img[\"LABEL\"]==\"Debian 7.7\"][0][\"DISTRIBUTIONID\"]'", "delta": "0:00:00.445751", "end": "2015-01-23 07:52:36.331892", "rc": 1, "start": "2015-01-23 07:52:35.886141", "warnings": ["Consider using get_url module rather than running curl"]}
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/linode.retry

127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1

**Comment by jlund** [comment]
Thanks for letting me know! First of all, I quickly edited your comment above, but you should immediately change your Linode API key.

This issue has been fixed, and Linode's new naming scheme makes me feel hopeful that they won't be changing the `LABEL` identifier in the future, which is great news.

**Comment by chespest** [comment]
he fix works perfectly.

I've changed my Linode API key before posting it here, but still thank you for your kind advise and quick reply~
