### ISSUE TITLE
Deep packet inspection on 443

### ISSUE THREAD

**Issue by L-Cafe** [jlund/streisand#118]
Hi,

I'm facing a problem at my school's network. Only http and https traffic is allowed. And only http through port 80 and https through port 443.

In my VPS, I'm used to binding stunnel to 443 TCP, to redirect to the OpenVPN port (say 553 TCP). This way, from a firewall point of view, I'm only speaking HTTPS with the remote host, so there's nothing that can be seen.

But with the streisand server we have a problem: nginx is bound to 443.

I thought of two solutions, either moving nginx HTTPS to a different port (and thus, potentially making it unavailable for people with DPI, like me, so installation instructions would have to be gathered somewhere else, rather than HTTPS. For example, the documentation could be copied to the user issuing the command, just like the generated-docs folder is created).

My second solution consists of using sslh, an SSH/OpenVPN/SSL multiplexer. The problem is that HTTPS and SSL traffic look the same. So upon connecting, unless nginx has a specific feature of forwarding certain traffic if a condition is met, stunnel would be speaking to the Nginx server, instead of the stunnel server.

What can we do about it? Would it be possible to moe nginx to a different port to allow stunnel+OpenVPN through 443 and save the documentation in the user's folder rather than serving it through HTTPS? Are there any other options?

I'm willing to contribute, and test whatever scenario fits this problem better. I'd really want to get this fixed, as this is not the first firewall with DPI enabled I find, and I'm certain it won't be the last. This would circumvent censorship big time.

**Comment by ariddell** [comment]
There's sslh, https://github.com/yrutschle/sslh, and I think haproxy can do this too.

**Comment by pyrobisqit** [comment]
There is a problem with the sslh implementation, please read my post again. It conflicts with nginx.

**Comment by ariddell** [comment]
Sorry, I missed that. There's a lot of discussion on the options on HN, as I suspect you might be aware: https://news.ycombinator.com/item?id=8923092

**Comment by kkingori** [comment]
I'm experiencing this too on a corporate network using DPI that wont allow OpenVPN traffic on 443. I think the solution is to have sslh forward SSL traffic to haproxy  then let haproxy forward the connection to either nginx or OpenVPN depending on an acl.

**Comment by pyrobisqit** [comment]
Very interesting, I'll try that this week!

**Comment by peterpacz1** [comment]
I'll be looking forward to hearing your results, as I'm facing the same problem.

**Comment by pyrobisqit** [comment]
This is a decent solution for now: https://github.com/jlund/streisand/issues/140

**Comment by pyrobisqit** [comment]
fteproxy could also work, probably. https://github.com/jlund/streisand/issues/141

**Comment by cpu** [comment]
I believe this issue has since been addressed by the introduction of the `sslh` role. It [multiplexes 443 to nginx, openvpn, and ssh](https://github.com/jlund/streisand/blob/6f0a4ea725e4202a0469b7457054675d822bee0f/playbooks/roles/sslh/templates/sslh.j2#L17).

I'm going to mark this issue closed, but please feel free to reopen if I'm misunderstood something. Thanks!

**Comment by AndreaOrru** [comment]
Sorry to necropost but this hasn't been addressed - Direct OpenVPN is indeed multiplexed by sslh, however stunneled OpenVPN isn't.

Anyone has a solution?

**Comment by Soham3-1415** [comment]
I have a very similar setup. If you are using OpenVPN with Stunnel, the packets will be indistinguishable from HTTPS packets. Sslh will need to check the packets after Stunnel decrypts them.

A setup similar to the one depicted below will need to be implemented.
                                       
                                                                       /==> OpenVPN
TLS ===> server ===> stunnel ===> sslh
                                                                       \==> HTTP
