### ISSUE TITLE
sshuttle error: ipfw/iptables not found on os/x

### ISSUE THREAD

**Issue by yaykyle** [jlund/streisand#120]
On OS/X Yosemite I got the following error when trying to run sshuttle. It might be a problem with sshuttle and not streisand but I thought I would report it and ask if you've seen this before.

```
~/bin/sshuttle • ./sshuttle --dns -r forward@streisand 0/0 -vv
Starting sshuttle proxy.
Binding: 12300
Listening on ('127.0.0.1', 12300).
DNS listening on ('127.0.0.1', 12300).
fatal: can't find either ipfw or iptables; check your PATH
fatal: ['sudo', '-p', '[local sudo] Password: ', 'python', './main.py', 'python', '-v', '-v', '--firewall', '12300', '12300'] returned 99
```

**Comment by jlund** [comment]
Apple removed `ipfw` in Yosemite and replaced it with `pfctl`. Sadly, the last commit to sshuttle happened in August 2012 and it hasn't kept pace with these changes.

I updated the generated documentation to reflect this. sshuttle is such a cool project. I hope it either comes back someday, or someone with time to maintain a fork is able to pick it up.

**Comment by yaykyle** [comment]
Awesome info, thank you!

**Comment by jlund** [comment]
sshuttle is back! (#193)
