### ISSUE TITLE
Deploy to Debain 7 error

### ISSUE THREAD

**Issue by SaberSalv** [jlund/streisand#121]
````
TASK: [streisand-gateway | Attempt to open the instructions on Linux (if applicable). Errors in this task are ignored because the `xdg-open` command is not always available.] *** 
fatal: [107.191.52.167] => error while evaluating conditional: hostvars['127.0.0.1']['ansible_system'] == "Linux"

FATAL: all hosts have already failed -- aborting
````

Server provider is VULTR
My client OS is ArchLinux
I managed to manually ssh into the server and update `/etc/ningx/htpasswd` file. so I can visit `https://<server-ip>`

**Comment by szymonszydelko** [comment]
Had you read the line preceding the error, you'd know that this is expected on linux systems, which seems to be the case

**Comment by SaberSalv** [comment]
I don't know how many steps are remaining in the scripts. (I assume after host browser open the instructions, it's done ?)

I have xdg-open installed on my host OS, but I still get the error and abort the process.

Due to the abort, I don't know the login name and password to the instruction, so I need to manually ssh into the server to fix it.

How do I fix the error or  if this error happened, maybe the script can bypass it and tell me the login name and password from the terminal?

**Comment by szymonszydelko** [comment]
> I don't know how many steps are remaining in the scripts. (I assume after host browser open the instructions, it's done ?)

This is the last step

> Due to the abort, I don't know the login name and password to the instruction, so I need to manually ssh into the server to fix it.

IIRC ansible also tells you that in a `generated-docs` (I could be a bit off with the name though) there is a `.html` file with all necessary passwords.

**Comment by SaberSalv** [comment]
OK, thanks, @szymonszydelko, I'm running the server created by streisand very well. So I closed it.
