### ISSUE TITLE
How do i deploy streisand on local server, instead of deploying it on the cloud?

### ISSUE THREAD

**Issue by fnlctrl** [jlund/streisand#122]
as the title says

**Comment by zjx20** [comment]
+1

**Comment by skeeve42** [comment]
This isn't currently possible, though @jlund has mentioned including this functionality at some point in #93 in a Dec. 18 post.

**Comment by skeeve42** [comment]
Any update on this? It would really make things simpler for me to help others get streisand going who only have access to windows machines and the server they're putting it on.

**Comment by soyuka** [comment]
[uncomment this](https://github.com/jlund/streisand/blob/master/inventory#L16 ) and set it to your server ip address, I remember that I used `localhost` once but docs had wrong adresses.

Add this:
```
host_key_checking = False // line in the ansible.cfg file. That setting
```
to the ansible.cfg file.


Launch the ansible playbook directly:
```
ansible-playbook playbooks/streisand.yml
```

**Comment by skeeve42** [comment]
@soyuka Thanks I'll give it a try!

**Comment by skeeve42** [comment]
@soyuka I finally got around to trying this, but it gave me an immediate error. (data could not be sent to the remote host). Ah well, I'll just install it via another VPS again. Silly, but all I can do!

**Comment by kydan** [comment]
@skeeve42 I too have been able to get this to work on a local machine, and it did require the modifications that @soyuka suggested. I'll try to dig up which line items I had to monkey with to make it work, but I got it runing within a few hours.

**Comment by aeibrahim** [comment]
you could try adding localhost to inventory and run ansible-playbook with --connection=local option

**Comment by ma-tt** [comment]
+1

**Comment by cpu** [comment]
Hi @ma-tt, please avoid +1 comments since they create notifications unneccesarily. Can you [use a Github reaction emoji](https://github.com/blog/2119-add-reactions-to-pull-requests-issues-and-comments) :+1: on the issue itself in the future? Thanks!

**Comment by cpu** [comment]
This has been officially supported since https://github.com/jlund/streisand/pull/724 was merged. The answer to the original thread topic is now:
1) Clone master on the server
2) Follow the setup instructions (installing python, pip, ansible)
3) Running `./streisand`
4) Choosing the local server install.

Closing this issue. Thanks everyone.
