### ISSUE TITLE
Replace ntp with openntpd in common packages

### ISSUE THREAD

**Issue by extempore** [jlund/streisand#123]

**Comment by jlund** [comment]
Good call. Thanks!

**Comment by extempore** [comment]
I changed the same line in my local copy of streisand after filing this issue. The base install of the VPS provider I used included regular ntpd, so for this to take effect we would also need to remove existing ntpd install and add openntpd to init.

**Comment by jlund** [comment]
The `openntpd` package specifially conflicts with `ntpd`, so `ntpd` is automatically removed when the OpenBSD NTP daemon is installed. Debian's `openntpd` package also includes an init script.

I tested that this works properly on a Debian 7 server that already had the traditional `ntp` package installed.

**Comment by extempore** [comment]
Oh never mind then, I was just confused. Thanks for looking into this!
