### ISSUE TITLE
Unable to connect to Streisand Gateway

### ISSUE THREAD

**Issue by fight4truth** [jlund/streisand#124]
I'm in China and really looking forward to accessing the Gateway and freeing up my internet. Just having trouble with the final step which, ironically, should be the easiest for me to solve. I have no programming or networking experience, and I'm only mildly familiar with VPNs because of the service I have for that now (which is hit or miss and why I want to try Streisand). However, I'm able to follow instructions like the simple step-by-step guide for installing Streisand via Python via Github, et al, and even setting up my droplet on Digital Ocean. But the final step has me stumped! Do I need to configure something in my Mac OSX Yosemite 10.10.1 or in Google Chrome 40.0.2214.94 (64-bit) in order to access the SSL or Tor Hidden Service log-in sites? I have placed the certificate in my keychain, and replaced it just in case, and marked as trusted both times. Do I need to change any settings in my network settings like DNS or Proxy etc.? Sorry for the low-level question here, but I just can't seem to figure out what to do next, no matter how I try to google the problem in search of the answer. Thanks for your help, and thanks for the work you are doing towards safe and free internet.
![ssl](https://cloud.githubusercontent.com/assets/10797006/5992240/f2480330-aa5b-11e4-838b-a9a7e24b82d5.png)
![tor](https://cloud.githubusercontent.com/assets/10797006/5992241/f248d774-aa5b-11e4-9d8b-a1e79ae9b410.png)

**Comment by fight4truth** [comment]
I noticed https://github.com/jlund/streisand/issues/125 appears to have a similar problem. I will pay attention to both boards and will close my issue if a solution on 125 works for me as well. Thanks again!

**Comment by jlund** [comment]
Do you still have SSH access to the server? If so, can you run these commands:
* `sudo service sslh status`
* `sudo service nginx status`

**Comment by fight4truth** [comment]
Hi Joshua, thanks for the help on this. I must not have SSH access to the
server because all I get is:

Seans-MacBook-Pro:~ seandoherty$ sudo service sslh status

sudo: service: command not found

Seans-MacBook-Pro:~ seandoherty$ sudo service nginx status

sudo: service: command not found

Seans-MacBook-Pro:~ seandoherty$

**Comment by jlund** [comment]
Oh, sorry. I should have been more clear. Those commands would be run on the server itself. First, you can try to connect with this command:
* `ssh root@<ip-of-the-server>`

Then you can run the other commands above.

**Comment by fight4truth** [comment]
Oh ok, got it. FYI This is for Digital Ocean in the Singapore region. So
doing that, I now get the following:

root@streisand:~# sudo service sslh status

[FAIL] sslh is not running ... failed!

root@streisand:~# sudo service nginx status

[ ok ] nginx is running.

**Comment by jlund** [comment]
OK, so this is the same underlying problem as #125, albeit on a different provider. Can you try this command now?
* `sudo service sslh start`

**Comment by aminbolehvpn** [comment]
Hey, try running this command in the server and see if any other services
is using the port needed by sslh.

netstat -ntlup

**Comment by jlund** [comment]
@fight4truth I just pushed a fix that will hopefully resolve this for you too. Run `git pull` in your local Streisand directory to update, terminate your old server, and try creating a new one. Let me know how it goes.

**Comment by fight4truth** [comment]
Hi Joshua, thanks for the super fast responses on this. I went out for
lunch but am back now and after the below response I was able to enter the
gateway and am now going through the steps to set up the Sshuttle
alternate. Will post back with results.

**Comment by fight4truth** [comment]
well access to the Gateway is not a problem now. I'm struggling with getting any VPN services running properly, after trying Shadowsocks, L2TP/IPsec, and OpenVPN with no success in connecting after carefully following all steps to setup. I'm thinking its because I skipped the "Run git pull" step for the new fix so I will do that after I get back to my computer later tonight. Another basic question, please: when I terminate the old server and create a new one, does that mean going back to "Clone Streisand repository" and execute the Streisand script or something else? Thanks again, and cheers!

**Comment by aminbolehvpn** [comment]
If you are in China, testing Streisand may not be easy as gfw will blocks
traffic and DNS. Vanilla openvpn will most likely fail to get thru the gfw.

**Comment by jlund** [comment]
Plain L2TP/IPSec and OpenVPN don't work well behind the Great Firewall. However, Shadowsocks, OpenVPN (wrapped in stunnel), OpenSSH tunnels, and Tor (with the obfsproxy pluggable transports) are all still functional.

You can just execute the script again to make a new server.

**Comment by fight4truth** [comment]
@aminbolehvpn thanks for your China specific tips. Very helpful!

**Comment by fight4truth** [comment]
hey Joshua, one last thing as I finish up here. I've completed the git pull to receive the update, and now am executing the streisand script again. In the process I received this reply (below) and since I am using the same publis SSH key does this mean I need to destroy the streisand droplet already created in my digital ocean account before I can proceed? Just want to double check before I do that and make sure it is safe to do so (I'm so worried about breaking something!) Thanks!

What is the name of the DigitalOcean SSH key that you would like to use?
  * If you have never uploaded an SSH key to DigitalOcean then the default
    value will work!
  * This key should match your .ssh/id_rsa.pub file.
  * DigitalOcean requires SSH keys to be unique. You cannot upload multiple
    keys that have the same value under different names.

**Comment by fight4truth** [comment]
sorry, I've figured it out so please ignore the last question. Thanks again for all you do here and for the cause of internet freedom (and safety) Joshua!
