### ISSUE TITLE
Novice in China needs help

### ISSUE THREAD

**Issue by SDNel** [jlund/streisand#125]
I live in Beijing, and am so desperate that I have attempted to set up a Streisand server even though I am technically illiterate.

I followed the instructions, and managed to get a server up and running on Amazon. I verified that the server is running, using the Amazon console.

Then I installed the certificates for Chrome and Safari on OSX (version 10.8.5), for Firefox and for iOS. 

Problem: I try to connect to the gateway using one of these browsers, I get the message that the browser cannot connect to the server.  This happens both on my Mac and the iPhone. Thus I am unable to get the step-by-step instructions I need to actually use the gateway. 

In desperation (given my almost complete ignorance of linux), I managed to log on to the server from the Terminal app as admin using ssh, but cannot find the instructions.

Any help would be appreciated. I have several friends, also expatriates, who are in similar dire straits now that their favorite VPB’s have been blocked.

**Comment by fight4truth** [comment]
hi SDNel. I am in Shanghai with a similar issue connecting to Streisand Gateway. I even tested with my current VPN service and the browser still could not connect to the server, so it must be that we are both really novices when it comes to this stuff :-) If our issue is really one in the same, then perhaps we can keep an eye on each other's issue board and duplicate any responses there to save a little trouble for the moderators? Here is mine:  https://github.com/jlund/streisand/issues/124

**Comment by SDNel** [comment]
Yes, I also tested with my current VPN service (which by now has only a few servers not blocked), and cannot connect. I tried on my son's computer, just to make sure there were no issues with my laptop. Again, no luck.

**Comment by faddat** [comment]
Please let me know if it is possible for someone on the outside to help you.  I personally know your pain (2 years there) and am happy to assist.  

faddat at gmail.com

**Comment by aminbolehvpn** [comment]
those in china, testing  is not  going to be  easy but you can use my free
shadowsocks server for testing and see if they are block or not. follow the
shadowsocks client installation and you can route your testing using my
socks proxy. please email me directly if you are interested to do this way.

**Comment by SDNel** [comment]
Any help would be appreciated. How do I email you?

**Comment by aminbolehvpn** [comment]
you email me amin.at.bolehvpn.net.
thanks

**Comment by SDNel** [comment]
Yes, any help would be much appreciated. What do you suggest I try?

From:  Jacob Gadikian <notifications@github.com>
Reply-To:  jlund/streisand
<reply+00a4b0c36293aa594d6f1ec232b0d1e6528bcf18954bf7c192cf0000000110e693b59
2a169ce035954d9@reply.github.com>
Date:  Monday, February 2, 2015 9:24 AM
To:  jlund/streisand <streisand@noreply.github.com>
Cc:  Stanley Nel <stanleynel8888@gmail.com>
Subject:  Re: [streisand] Novice in China needs help (#125)

Please let me know if it is possible for someone on the outside to help you.
I personally know your pain (2 years there) and am happy to assist.

faddat at gmail.com
> On Feb 2, 2015, at 8:20 AM, SDNel <notifications@github.com> wrote:
> 
> Yes, I also tested with my current VPN service (which by now has only a few
servers not blocked), and cannot connect. I tried on my son's computer, just to
make sure there were no issues with my laptop. Again, no luck.
> 
> ‹ 
> Reply to this email directly or view it on GitHub
<https://github.com/jlund/streisand/issues/125#issuecomment-72395622>.
> 

‹
Reply to this email directly or view it on GitHub
<https://github.com/jlund/streisand/issues/125#issuecomment-72395788> .

**Comment by jlund** [comment]
@SDNel Can you SSH into the server and run the following commands?
* `sudo service nginx status`
* `sudo service sslh status`

**Comment by SDNel** [comment]
Here is what I get:


admin@ip-172-31-20-48:~$ sudo service nginx status
[ ok ] nginx is running.
admin@ip-172-31-20-48:~$ sudo service sslh status
[FAIL] sslh is not running ... failed!
admin@ip-172-31-20-48:~$



From:  Joshua Lund <notifications@github.com>
Reply-To:  jlund/streisand
<reply+00a4b0c3df837e3149bed4cc395a870051bb41d6fdcb286992cf0000000110e69d729
2a169ce035954d9@reply.github.com>
Date:  Monday, February 2, 2015 10:05 AM
To:  jlund/streisand <streisand@noreply.github.com>
Cc:  Stanley Nel <stanleynel8888@gmail.com>
Subject:  Re: [streisand] Novice in China needs help (#125)


@SDNel <https://github.com/SDNel>  Can you SSH into the server and run the
following commands?
* sudo service nginx status
* sudo service sslh status
‹
Reply to this email directly or view it on GitHub
<https://github.com/jlund/streisand/issues/125#issuecomment-72397880> .

**Comment by jlund** [comment]
OK, that's good! That means that there's a simple explanation. `sslh` would need to be running in order for you to connect. Which Amazon region did you launch the new server in so that I can try to reproduce the problem?

**Comment by SDNel** [comment]
West: Oregon

**Comment by jlund** [comment]
While I'm waiting for this to run, please try this command:
* `sudo service sslh start`

**Comment by SDNel** [comment]
Get:

[....] Starting ssl/ssh multiplexer:
sslhec2-54-186-74-163.us-west-2.compute.amazonaws.com:https:bind: Cannot
assign requested address
 failed!

From:  Joshua Lund <notifications@github.com>
Reply-To:  jlund/streisand
<reply+00a4b0c3a3fdf3805a7013ed07578770a0fef4369cff9ee392cf0000000110e6a0db9
2a169ce035954d9@reply.github.com>
Date:  Monday, February 2, 2015 10:20 AM
To:  jlund/streisand <streisand@noreply.github.com>
Cc:  Stanley Nel <stanleynel8888@gmail.com>
Subject:  Re: [streisand] Novice in China needs help (#125)


While I'm waiting for this to run, please try this command:
* sudo service sslh start
‹
Reply to this email directly or view it on GitHub
<https://github.com/jlund/streisand/issues/125#issuecomment-72398571> .

**Comment by jlund** [comment]
OK, SDNel. You can do a `git pull` in your Streisand directory to update, terminate the existing EC2 server, and run Streisand again to create a new one. You should be good to go at that point! I was able to reproduce exactly what you were seeing, and the new server I just created worked correctly after applying this fix.

**Comment by SDNel** [comment]
How do I do a git pull in the Streisand directory?

**Comment by jlund** [comment]
Just run the `git pull` command on your local computer in the directory where you checked out Streisand. This would be the directory that was created when you ran the `git clone` command in the setup instructions.

**Comment by SDNel** [comment]
Thanks. Will try.

**Comment by SDNel** [comment]
It works! Thanks very much for such quick assistance. 

I cannot give technical support to this project, but I would love to help in any other way I can. Suggestions welcome.

**Comment by jlund** [comment]
You're welcome! That makes me really happy to hear. Which VPN connection option are you using?

Donating to the underlying projects (e.g. Tor) and spreading the word are probably the two best ways to help at the moment. You can also share the connection instructions with other people too.

**Comment by SDNel** [comment]
I am trying them one by one on my Mac and iPhone so I can see what works
best and then distribute this to friends and family.

So far Shadowsocks seems best. OpenVPN (both with and without tunneling)
works, but I keep getting a message saying that there is a problem
accessing the Internet. I think this is a DNS problem in Tunnelblick, but I
need to investigate more.

Now in the process of setting up Shadowsocks on iOS. Then I will try SSH
and Tor.

The one thing that is not yet working is to connect directly from my Asus
RT-AC66U router, so that the whole family can use it. Will keep working on
that and let you know.

That was possible until a few days ago, when the blocking escalated to a
new level. Even the VPN that still works on the MAC can no longer be
reached via the router.

**Comment by aminbolehvpn** [comment]
AC66U should be working if normal VPN is can be used on the MAC.
Just make sure you have the settings correctly, especially the certs and
the DNS is working correctly.
Make sure that DNS is set to exclusive or strict.

If possible, use the firmware from Merlinwrt for asus ac66u.

**Comment by SDNel** [comment]
Thanks. I will try tomorrow. Kids are back from school and real life intervenes.
