### ISSUE TITLE
gpg: Can't check signature: public key not found

### ISSUE THREAD

**Issue by szymonszydelko** [jlund/streisand#132]
Long story short: do@nyc3, brand new instance, debian7_amd64:
```
TASK: [streisand-mirror | Register GPG signature verification results] ******** 
failed: [xxx.xxx.xxx.xxx] => {"changed": true, "cmd": "for file in *.asc; do gpg --verify $file; done", "delta": "0:00:01.204824", "end": "2015-03-01 11:15:48.579107", "rc": 2, "start": "2015-03-01 11:15:47.374283", "warnings": []}
stderr: gpg: Signature made Wed 25 Feb 2015 07:55:36 AM UTC using RSA key ID F65C2036
gpg: Can't check signature: public key not found
gpg: Signature made Wed 25 Feb 2015 07:54:55 AM UTC using RSA key ID F65C2036
gpg: Can't check signature: public key not found
gpg: Signature made Wed 25 Feb 2015 07:55:16 AM UTC using RSA key ID F65C2036
gpg: Can't check signature: public key not found
gpg: Signature made Wed 25 Feb 2015 07:55:56 AM UTC using RSA key ID F65C2036
gpg: Can't check signature: public key not found

FATAL: all hosts have already failed -- aborting
```

**Comment by szymonszydelko** [comment]
This seems to be this part of the project: https://github.com/jlund/streisand/blob/391c192a1a1826a15dc47cd67417054f05575f58/playbooks/roles/streisand-mirror/tasks/download-and-verify.yml#L29-L32

**Comment by Meroje** [comment]
It seems Erinn Clark doesn't sign releases anymore https://www.torproject.org/docs/signing-keys.html.en
Instead you can use the new Key "Tor Browser Developers (signing key) <torbrowser@torproject.org>" at the bottom of the page. (change here https://github.com/jlund/streisand/blob/391c192a1a1826a15dc47cd67417054f05575f58/playbooks/roles/streisand-mirror/vars/tor.yml#L7-8)

**Comment by peterbourgon** [comment]
I also hit this problem.

**Comment by soyuka** [comment]
#3 ?

**Comment by szymonszydelko** [comment]
@soyuka : I Don't think so. The error is different, also @Meroje's proposed fix worked. Thanks, while we are at it.

**Comment by shelhezan** [comment]
I can confirm what @Meroje suggested. Changing the key id and the fingerprint in the tor.yml to the ones of the Tor Browser Developers signing key results in a fully working Streisand instance.
Because I'm lazy digging out all the references to Erinn Clark's signing key, I propose that @jlund changes all occurrences where the signing key is needed.

**Comment by jlund** [comment]
All set! The new key and fingerprint are in place. Thanks for letting me know.

**Comment by shelhezan** [comment]
Thank you @jlund. That was quick! ;)
