### ISSUE TITLE
AWS CloudFormation template

### ISSUE THREAD

**Issue by bshi** [jlund/streisand#138]
Would be nice to create a CloudFormation template for push-button deployment.

A quick aside: is it possible to cluster streisand instances?

**Comment by webdigi** [comment]
Yes, a cloudformation template will be excellent. 

We just put up a VPN setup here with L2TP, PPTP server with cloudformation here https://www.webdigi.co.uk/blog/2015/how-to-setup-your-own-private-secure-free-vpn-on-the-amazon-aws-cloud-in-10-minutes/

It will be ideal to have Streisand in a template too.

**Comment by jlund** [comment]
CloudFormation's syntax is completely different and this would require porting the Ansible tasks and roles in a step-by-step fashion from scratch. The result also could not be used on any other hosting services, unlike Streisand's Ansible playbooks which are provider-agnostic. As such, it's probably outside of the scope of this project.

@bshi Can you explain what you mean with regard to clustering?

**Comment by roberthl** [comment]
I've been working on a CloudFormation template for Streisand, which I've published to https://github.com/roberthl/streisand-cloudformation. The template uses CloudFormation to create the AWS resources (instance, security group, elastic IP and alarm) and runs the Ansible playbook from within the instance itself when it is launched.  This works well for my use case of wanting to have AWS resources created using CloudFormation where possible to ensure easy tear-down and for audit and reporting purposes, and could also facilitate push-button deployment as suggested above.

I agree that a CloudFormation template probably doesn't have a place in the Streisand project itself, but I am using this on a day to day basis and intend to keep the template in sync with developments to Streisand.  Any comments or feedback would be greatly appreciated.

**Comment by cpu** [comment]
I concur with @roberthl and @jlund's assessment that this is probably not a great fit for the mainline Streisand project but I hope that https://github.com/roberthl/streisand-cloudformation remains in development. Let us know if there are design decisions we can make that would help make the cloudformation template easier to manage. I'm going to close this issue for now since the consensus seems to be that it shouldn't be a Streisand feature. Thanks all!
