### ISSUE TITLE
EC2 Error: "Only Amazon VPC security groups may be used with this operation"

### ISSUE THREAD

**Issue by BBB** [jlund/streisand#139]
I have the following error when trying to provision Streisand with an ec2 instance.

ansible 1.8.3

```bash
TASK: [ec2-security-group | Open the SSH port in the EC2 security group] ******
a10_server                    Manage A10 Networks AX/SoftAX/Thunder/vThunder devices
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/Users/ollie/.ansible/tmp/ansible-tmp-1427280931.97-111066911038941/ec2_group", line 2174, in <module>
    main()
  File "/Users/ollie/.ansible/tmp/ansible-tmp-1427280931.97-111066911038941/ec2_group", line 340, in main
    cidr_ip=ip)
  File "/usr/local/Cellar/ansible/1.8.3/libexec/vendor/lib/python2.7/site-packages/boto/ec2/connection.py", line 3229, in authorize_security_group_egress
    params, verb='POST')
  File "/usr/local/Cellar/ansible/1.8.3/libexec/vendor/lib/python2.7/site-packages/boto/connection.py", line 1226, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Only Amazon VPC security groups may be used with this operation.</Message></Error></Errors><RequestID>4ef72a0a-f2a3-4f36-918f-0067bfc51135</RequestID></Response>


FATAL: all hosts have already failed -- aborting
```

**Comment by BBB** [comment]
Update. This looks to be because my account supports "EC2 Classic".

**Comment by jlund** [comment]
Yeah, other people have run into this as well. I really wish that I could figure out a workaround, but I don't have access to an EC2 account that has Classic enabled.

You can manually bring up a server in Classic and configure it directly. There are instructions in the README for this, and I will be making the process even easier soon.

**Comment by Joe8Bit** [comment]
There is a workaround for this, but it's a little unwieldy. AWS accounts that have Classic enabled were created before a certain date, so creating a new AWS account will mean that *only* VPC is available when provisioning EC2 instances (and therefore Streisand will provision properly).

It's nasty and not possible for everyone, but will work.

**Comment by jlund** [comment]
This has now been fully patched in #371 thanks to @DavidWittman. Better late than never! :)

**Comment by ryanwmarsh** [comment]
What are the proper settings for a VPC and subnet?

I just ran into this issue today. I got further past it by creating my own VPC and subnet however I don't know the correct parameters for these so I'm pretty sure I did it wrong because I cannot access my instance and Streisand errors out at the end that it couldn't reach the instance.

**Comment by DavidWittman** [comment]
@ryanwmarsh just use the IDs of the VPC (vpc-xxxxxx) and Subnet (subnet-xxxxxx) which you just created.

**Comment by tolland** [comment]
@DavidWittman  Do you have an example of how to provide the VPC and Subnet? If you are new to terraform (I am) and following the documentation here;
https://www.terraform.io/intro/getting-started/modules.html

The result is a confusing error;
`$ terraform apply
module.consul.aws_security_group.consul: Creating...
  description:                          "" => "Consul internal traffic + maintenance."
  egress.#:                             "" => "1"
  egress.482069346.cidr_blocks.#:       "" => "1"
  egress.482069346.cidr_blocks.0:       "" => "0.0.0.0/0"
  egress.482069346.from_port:           "" => "0"
  egress.482069346.prefix_list_ids.#:   "" => "0"
  egress.482069346.protocol:            "" => "-1"
  egress.482069346.security_groups.#:   "" => "0"
  egress.482069346.self:                "" => "false"
  egress.482069346.to_port:             "" => "0"
  ingress.#:                            "" => "3"
  ingress.2541437006.cidr_blocks.#:     "" => "1"
  ingress.2541437006.cidr_blocks.0:     "" => "0.0.0.0/0"
  ingress.2541437006.from_port:         "" => "22"
  ingress.2541437006.protocol:          "" => "tcp"
  ingress.2541437006.security_groups.#: "" => "0"
  ingress.2541437006.self:              "" => "false"
  ingress.2541437006.to_port:           "" => "22"
  ingress.3472572478.cidr_blocks.#:     "" => "0"
  ingress.3472572478.from_port:         "" => "0"
  ingress.3472572478.protocol:          "" => "udp"
  ingress.3472572478.security_groups.#: "" => "0"
  ingress.3472572478.self:              "" => "true"
  ingress.3472572478.to_port:           "" => "65535"
  ingress.3544538468.cidr_blocks.#:     "" => "0"
  ingress.3544538468.from_port:         "" => "0"
  ingress.3544538468.protocol:          "" => "tcp"
  ingress.3544538468.security_groups.#: "" => "0"
  ingress.3544538468.self:              "" => "true"
  ingress.3544538468.to_port:           "" => "65535"
  name:                                 "" => "consul_ubuntu"
  owner_id:                             "" => "<computed>"
  vpc_id:                               "" => "<computed>"
Error applying plan:

1 error(s) occurred:

* aws_security_group.consul: Error authorizing security group egress rules: InvalidParameterValue: Only Amazon VPC security groups may be used with this operation.
        status code: 400, request id: 92552034-2992-4c94-99fc-15443a2c86dd`

and the code in here;
https://github.com/hashicorp/consul/blob/master/terraform/aws/consul.tf

doesn't seem to use any Subnet or VPC variables...

**Comment by goswh** [comment]
I know this an old issue, but this just popped for me this morning on macOS Mojave 10.14. I'm a first time user/installer and was following the steps in the readme when this happened. 

I have EC2 Classic in an AWS account that is about 6-7 years old.  Happy to provide an environment to test against if you'd like. 

Also, will try the manual vpc and subnet method recommended.
