### ISSUE TITLE
SoftEther VPN

### ISSUE THREAD

**Issue by dimzon** [jlund/streisand#140]
https://www.softether.org/
It's open source multi-protocol solution, claims is faster than native OpenVPN 
![Chart1](https://www.softether.org/@api/deki/files/4/=1.2.jpg?size=webview)

![Speed comparision](https://www.softether.org/@api/deki/files/12/=1.3.jpg)
Also implements it's own protocol over HTTPS

![Feature comparision](https://www.softether.org/@api/deki/files/680/=comparison3.png)

It will be great to have streisand-like project build on SoftEther VPN

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/19
