### ISSUE TITLE
Use obfsproxy to obfuscate any (SSH/VPN etc) traffic

### ISSUE THREAD

**Issue by dimzon** [jlund/streisand#141]
Actually some VPS providers disallow TOR relays/bridges. At other side you can use obfs as stand-alone tunnel to penetrate any DPI

Also take look at https://fteproxy.org/ - yet another obfuscating tunnel

**Comment by joncamfield** [comment]
There is renewed work on a newer version and spec for obfsproxy to provide support for more "pluggable transports" in one proxy environment (e.g obfs4, fte, and others could all be reached through one proxy system).  This will also hopefully add in UDP support.  

Discussions are (mostly) over at https://groups.google.com/forum/#!forum/traffic-obf

**Comment by cpu** [comment]
The Tor bridge that Streisand deploys today is configured with obfs4. I don't believe this issue is required at present and will close it. Thanks all!
