### ISSUE TITLE
FYI: ShadowVPN

### ISSUE THREAD

**Issue by dimzon** [jlund/streisand#142]
Yet another lightweight VPN protocol for low-end devices (routers etc)

https://github.com/clowwindy/ShadowVPN
https://github.com/clowwindy/ShadowVPN/wiki/Compared-to-Shadowsocks-and-OpenVPN

**Comment by pyrobisqit** [comment]
Are the three major desktop OSes supported? That is: Windows, Mac, and Linux.

Also, the one-server-per-client doesn't seem very attractive for a streisand instance, which is supposed to be shared to circumvent censorship.

Last, what is "protocol sniffing" supposed to mean here: https://github.com/clowwindy/ShadowVPN/wiki/Compared-to-Shadowsocks-and-OpenVPN ? Does it mean that it morphs itself as something else? (such as SoftEtherVPN, that looks like HTTPS)

**Comment by jlund** [comment]
I have been keeping an eye on this and will likely add support for it as another option when it is no longer in beta.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/18
