### ISSUE TITLE
tinc VPN

### ISSUE THREAD

**Issue by strixaluco** [jlund/streisand#144]
I'd wish to suggest this powerful and efficient VPN. It's been in active development for more than 15 years, it supports all the major platforms, but also *BSD's and Solaris.

http://tinc-vpn.org/

**Comment by PiPeep** [comment]
I'm not personally interested in this functionality, because on a single-server network, tinc is no better than openvpn. However, if it helps anyone, I implemented a tinc role for a similar setup [a while ago](https://github.com/PiPeep/ansible-playbooks/tree/master/roles/tinc). Anyone can feel free to use it under the GPLv3 (or any later version) license.

**Comment by jlund** [comment]
I investigated this as an option but the available Android clients were _quite_ rough at the time, and there was nothing whatsoever for iOS users. I also wasn't able to find any reliable information about how well it worked in China or other DPI-enabled countries. I will keep it in mind for future inclusion if more options are necessary in the censorship arms race. It looks like PiPeep's role would be a great place to start.

**Comment by strixaluco** [comment]
Thank you for response, I will try with PiPeep's implementation first. And yes, I didn't take into account lack of mobile clients.

**Comment by PiPeep** [comment]
@strixaluco, a few things to take note of:

- The tinc code as-is has only been tested with a single central server, and only routes LAN traffic. As my use-case has been better fleshed out, I've realized OpenVPN fits my needs better, hence my interest in streisand.
- Those playbooks depend on the non-standard `hash_behaviour = merge` ansible option, so you'll likely have to rewrite the variable names if you don't want to change `hash_behavior`.
- The ansible code doesn't generate certs on the server. Instead it expects you provide them in the secrets folder, although [this is scripted](https://github.com/PiPeep/ansible-playbooks/blob/master/secrets.example/tinc/gen_keypairs.sh). This is a bit different from the streisand model.

You'll probably need to modify it quite a bit to fit whatever your exact use-case is.

**Comment by strixaluco** [comment]
This info will definitely help, I'm very grateful for your kind advices, PiPeep.
