### ISSUE TITLE
Installed 

### ISSUE THREAD

**Issue by 21winner** [jlund/streisand#145]
So I created a ubuntu droplet and went through the steps listed in the document.  I did not know it would create a totally new droplet and have everything installed in there.

Now my problem is where to locate this inventory file and how to get everything operational -  I see openvpn but can't extract or run anything.  Was it even supposed to create a new droplet in digital ocean?  not sure if I am doing it right but it appears to all be there.

any help is appreciated.

**Comment by jlund** [comment]
Right now, Streisand is designed to be run from your laptop or desktop computer to configure a new or existing remote server. It is not meant to be run on a server directly.

I will be adding support very soon for a "Configure this server" option. This seems to be a major point of confusion for people.

In your case, the connection instructions will be in the `generated-docs` folder on the server from which you ran Streisand.
