### ISSUE TITLE
Markdown Theme for Streisand VPN 

### ISSUE THREAD

**Issue by peterpacz1** [jlund/streisand#147]
Not a very big issue - but I would like to know what's the markdown theme for Streisand, and how the docs are generated. I would like to make customized instruction sheets for my community, and I want the style to be the same.

**Comment by szymonszydelko** [comment]
I'm fairly sure it is this theme: https://github.com/jlund/streisand/blob/master/playbooks/roles/common/files/header.html#L10-L297

**Comment by peterpacz1** [comment]
Ah, thank you very much!
