### ISSUE TITLE
Stuck on TASK: [sslh | Generate the sslh port multiplexer configuration file]

### ISSUE THREAD

**Issue by ankeshkothari** [jlund/streisand#148]
Hi,

I am trying to install streisand on digital ocean and nothing is happening after:
TASK: [sslh | Generate the sslh port multiplexer configuration file] **********

The terminal window has not updated anything since an hour... not sure how to proceed. Please help.

**Comment by peterpacz1** [comment]
Delete the server from the DigitalOcean control panel, and run streisand
again. If the issue still happens, reply back with the log files :)

**Comment by jlund** [comment]
Yeah, this can happen if there's a break in your SSH connection. On DigitalOcean, you can also just run Streisand again and pass in the same arguments. The configuration will continue from where it left off, skipping the tasks that have already been completed.
