### ISSUE TITLE
Using Arch Linux and corbanr's pull request for google cloud

### ISSUE THREAD

**Issue by faddat** [jlund/streisand#154]
Here's what I am getting:  I'm thinking it could be one of those wierd Arch-y things with Python and I'm going to give ubuntu a go.  

PLAY [Provision the GCE Server] *********************************************** 

GATHERING FACTS *************************************************************** 
failed: [127.0.0.1] => {"failed": true, "parsed": false}
  File "/root/.ansible/tmp/ansible-tmp-1430142212.72-68706089313455/setup", line 647
    except OSError, e:
                  ^
SyntaxError: invalid syntax

TASK: [Set the GCE Zone fact] ************************************************* 
ok: [localhost]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/google.retry

127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1   
localhost                  : ok=1    changed=0    unreachable=0    failed=0

**Comment by faddat** [comment]
If I should have put this on Corbanr's fork, just let me know.  If there's a way to put it on the pull request, please let me know that, too.  Heck I think I should put on his fork... I will... in addition to here.... 

best

-Jake

**Comment by jlund** [comment]
Are you using Python 2.7 or Python 3?

This PR will be merged soon. I'm planning on reviewing it tonight.

**Comment by faddat** [comment]
You can safely ignore that issue.  So you know though, I am having another:

I forked yours and merged his to it.  All seemed well until.... GCE hangs
just after creating the image.  My first thought is their loony default
settings for anything (over at Google).  Here's Screenshot-age:


​
For the time being I am going to see if my "launcher node" on GCE can cook
up some debian 7 machines also on GCE.

:)!

-Jake


Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +86 186-2612-6079

**Comment by CorbanR** [comment]
@faddat I'm not seeing the screenshot you mention. That may be helpful. 

One thing I probably didn't make clear in my initial update of the documentation was that you need to enable the GCE API for Ansible to work correctly. 

https://console.developers.google.com/project/<name_of_project>/apiui/apiview/compute_component/overview

**Comment by faddat** [comment]
https://drive.google.com/open?id=0BxLj8ItRojN-SGppNmh2Z2d6NmRGUE9yVEJfLWR5alowU3Y0&authuser=0

API was enabled-- this is something else, I think.  Thanks for your help!

-Jake

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +86 186-2612-6079

**Comment by CorbanR** [comment]
I'm sorry your having problems. I have a few more questions. 

What version of Ansible are you running? 
What version of apache-libcloud are you running?

After Ansible fails were you able to test the ssh connectivity? Something like `nc -v 104.199.163.197 22`

If possible can you run the playbook with verbose output? Edit the Streisand script `  3) echo; echo; ansible-playbook playbooks/google.yml -vvvv;;`

**Comment by faddat** [comment]
Yeah, I'm happy to do that-- I am going to re- clone my merged repo now and
let you know what happens in a moment :).

-Jake

Jacob Gadikian
E-mail: faddat@gmail.com
SKYPE: faddat
Phone/SMS: +86 186-2612-6079

**Comment by CorbanR** [comment]
@faddat I have updated the pull request with some changes / updates. I would be interested to know if you are still having the time out issues.

**Comment by faddat** [comment]
@CorbanR 

Should have closed this long ago, and it's working very well the last time I tried :).
