### ISSUE TITLE
DigitalOcean sunsetting v1 API's

### ISSUE THREAD

**Issue by alchemydc** [jlund/streisand#156]
May impact this project

Sunsetting DigitalOcean’s API v1

Since releasing version 2 of our API nearly a year ago and officially bringing it out of beta last month, we’ve seen a tremendous uptake of usage by our community. As the ecosystem of tools and libraries continues to grow, we’ve decided that it is time to sunset version 1 of the API.

Don’t worry! We’re not going to pull the rug out from under you. In order to give everyone time to port their tools, version 1 will not be turned off until November 1st 2015

With its (more) RESTful interface and features like OAuth support, v2 is both powerful and easy to use. Our developer documentation should give you all the information you need to begin the transition. If you have questions, you can always ask on our Community site or on Twitter.

**Comment by jlund** [comment]
It looks like the DigitalOcean v2 API is supported in the Ansible development branch.  I'll be sure to make the switch as soon as the stable version is released. Thanks for the heads up!

**Comment by peterpacz1** [comment]
Just to let you know, DigitalOcean's V2 API is now officially **out of beta**, and completely stable for use:

https://www.digitalocean.com/company/blog/apiv2-officially-leaves-beta/

```
We are very pleased to announce that API v2 is coming out of beta, nine months after its initial release. With this release we wanted to introduce new features not available in v1, while maintaining the level of simplicity developers loved in our first version. To help us keep it simple and stomp out bugs, we called on the community to collaborate with us in a public GitHub repository. The last nine months of collaboration with the community ensured our API remained awesome as we added these new features.
```

Here are links to the developer documentation. It is **vitally important** for us to keep up with these changes, and to go forth to the v2 API before v1 is shut down.

https://developers.digitalocean.com/documentation/v2/

**Comment by jlund** [comment]
DigitalOcean V2 API support is scheduled for release in Ansible 2.0, which should be out very soon. I have already tested it and it works well. Streisand will definitely be ready way before the V1 APIs are shut down in November.

**Comment by protofab** [comment]
Any updates on Digital Ocean V2 API support?

**Comment by jlund** [comment]
With only one day left before the v1 shutdown, I am very happy to report that Streisand has fully transitioned to DigitalOcean's v2 API! I had to do all of this manually because the current stable release of Ansible, 1.9.4, still hasn't been updated. Fortunately, DigitalOcean's new API documentation is pretty fantastic.

The Droplets will continue to flow, next week and beyond. Thanks for your patience everyone!
