### ISSUE TITLE
Different SSHTunnel checksum

### ISSUE THREAD

**Issue by mndfcked** [jlund/streisand#160]
I get the following message while trying to spin up a new instance on a Digitalocean NY2 machine. 
```
TASK: [streisand-mirror | Mirror sshuttle] ************************************ 
failed: [XXX] => {"failed": true}
msg: The SHA-256 checksum for /var/www/streisand/mirror/ssh/sshuttle-master.zip did not match 9eaf00cd179b82614e810d4266d58ae991d12c9a6baf9f8ba129da69c25dc674; it was 94b48ce0f3efff23ba28c4542ca35a88cc3fd8cc00a21b3d7d04022c1fd5c958.

FATAL: all hosts have already failed -- aborting
```
I checked it on mutliple machines over different connections, the checksum is always ```94b48ce0f3efff23ba28c4542ca35a88cc3fd8cc00a21b3d7d04022c1fd5c958```.

But here comes the kicker, apenwarr/sshuttle@9ce2fa00f94c2f2e5c310abeb1a2907ae7e7a7b0 is the latest commit to master and over 2 years old. Even a short diff with both folders won't show any differences. Can someone confirm this?

**Comment by jlund** [comment]
I'm seeing the same new checksum as you, but I'm similarly confused as to why it would have changed. It was probably time to say goodbye anyway. Thank you for the heads up.

If you pull the latest commit, you should be good to go!

**Comment by mndfcked** [comment]
Yeah, works perfectly fine. Thanks mate. :+1:
