### ISSUE TITLE
Remove sshuttle

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#161]
Given the mysterious checksum change (#160), lack of OS X Yosemite support (#120), and a codebase that hasn't been updated in [almost four years](https://github.com/apenwarr/sshuttle/commits/master), it's probably time to say goodbye. I sincerely hope that it is able to return someday.

Farewell, old friend.

**Comment by strixaluco** [comment]
Did you consider this fork? https://github.com/sshuttle/sshuttle
It seems to be under pretty heavy development.

**Comment by jlund** [comment]
No, I wasn't aware of that. I will have to check it out. It looks promising at first glance, but there seem to be some missing commits between the two repos. Thanks for letting me know!

**Comment by strixaluco** [comment]
No problem, glad to help. They've fixed the issues with Yosemite, by the way - sshuttle/sshuttle#4

**Comment by jlund** [comment]
@strixaluco sshuttle is back! (#193)

**Comment by strixaluco** [comment]
Great news! 
Thank you for your work.
