### ISSUE TITLE
Does it work on Ubuntu 14.04?

### ISSUE THREAD

**Issue by Ge0rges** [jlund/streisand#163]
I've seen mentions of it not working in previous issues...

**Comment by jlund** [comment]
I need to try it again. The problems were due to the AppArmor profiles that 14.04 installed that conflicted with Tor when using pluggable transports.

Debian 8 will likely become the future base distro soon, but I'm going to evaluate Ubuntu 14.04 as well.

**Comment by peterpacz1** [comment]
Personally it may be best to go along with Debian 8, since it is designed to be extremely stable and have long term support. We are talking about a click and shoot solution that is probably not going to be maintained - so it should be as stable as possible.

**Comment by jlund** [comment]
Yeah, Debian 8 is the future foundation.

**Comment by jlund** [comment]
The upgrade to Ubuntu 14.04 is almost done and is being tracked in #174. Debian AMIs on Amazon were problematic, and there are some cloud providers like Azure that also have better support for Ubuntu.

**Comment by jlund** [comment]
Upgrade complete. It _does_ work on Ubuntu 14.04 now :)

**Comment by Ge0rges** [comment]
Awesome
