### ISSUE TITLE
Documentation request

### ISSUE THREAD

**Issue by kataflok** [jlund/streisand#165]
I'm a newbie & kinda shocked I managed to get this to work - and seriously impressed with the coding!

But, one simple question:

I assume there must be some sort of maintenance, upgrades needed to be run or just a need to reboot the server at times?

Can anyone point me at where to learn to login to and maintain a Streisand server? (None of the logins/passwords I have even work to login to it through the terminal...)

**Comment by pyrobisqit** [comment]
OK: First of all; To login via SSH, you should not need passwords, the SSH key should already be installed in the server from which you deployed it. From this server, you should have got a folder, with all the documentation necessary related to the server, including one with your passwords, certificates, and such, and other with information for ports and which service uses which.

Second, now that you have your documentation, you must install a certificate into your browser. If you deployed streisand from a remote server (meaning, you SSH'd into a server to deploy streisand), you first have to fetch these documents, it's all very clear with instructions for most browsers on how to import SSL certificates. This is so your connection can't be tampered with, and you know where you're connecting.

Third: Now that you have your certificate, just enter https://<server-ip> where <server-ip> you put the streisand's server IP, obviously; the user is streisand, the password should be written around the bottom of the page from which you installed the SSL certificate. It should be a few words joined with dashes.

Fourth: There's no fourth! If you entered the password correctly, you're all set! All information for connecting is there, including mirrors to the software you'd need to connect for countries like China that censor the web heavily.

About maintenance, you do not need to worry, but if you're super paranoid, SSH into it from time to time, and just run
    sudo apt-get update && sudo apt-get upgrade

**Comment by soyuka** [comment]
I was wondering the same about the system upgrade part. Especially when you have things like:

```
Configuration file `/etc/tor/torrc'
 ==> Modified (by you or by a script) since installation.
 ==> Package distributor has shipped an updated version.
   What would you like to do about it ?  Your options are:
    Y or I  : install the package maintainer's version
    N or O  : keep your currently-installed version
      D     : show the differences between the versions
      Z     : start a shell to examine the situation
 The default action is to keep your current version.
```

Right now I'm lazy and keeping the streisand default conf, but what if new options are covered in a future release?

**Comment by kataflok** [comment]
Hi pyrobisqit,

Thank-you! That last sentence was exactly what I needed to google.

For anyone else wondering the same thing, in terminal (At least on a mac) enter:

ssh root@[IP ADDRESS OF SERVER]

(To remotely login to the server - the Certificate is your pass.)

sudo apt-get update && sudo apt-get upgrade

(To upgrade it.)

sudo shutdown -r now

(To reboot it.)

sudo shutdown now

(To shut it down so you can run a snapshot/backup.)

**Comment by soyuka** [comment]
You don't need to reboot an unix system to take changes into consideration.

**Comment by jlund** [comment]
Automating upgrades using `unattended-upgrades` is on my list of things to do, and is being tracked as Issue #44. Hopefully I'll have time to get to it soon.

Thanks for the great feedback, @kataflok. I'm really glad that it is working for you. Thanks for the helpful comment too, @pyrobisqit.

@soyuka: If new options are needed in the `torrc` file due to a future version of Tor, I'll be sure to update the template. Luckily the configuration for Bridges is pretty straightforward.
