### ISSUE TITLE
Consider using get_url module rather than curl

### ISSUE THREAD

**Issue by yekong90** [jlund/streisand#167]
I got this error messages while executing ./streisand, any ideas?

PLAY [Provision the Linode Server] ********************************************

GATHERING FACTS ***************************************************************
ok: [127.0.0.1]

TASK: [genesis-linode | Get the default SSH key] ******************************
changed: [127.0.0.1]

TASK: [genesis-linode | Get the latest 'Debian 7' image ID from the Linode API] ***
failed: [127.0.0.1] => {"changed": true, "cmd": "curl -s 'https://api.linode.com/?api_key=&api_action=avail.distributions' | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j[\"DATA\"] if img[\"LABEL\"]==\"Debian 7\"][0][\"DISTRIBUTIONID\"]'", "delta": "0:00:00.272107", "end": "2015-06-14 08:32:05.871492", "rc": 1, "start": "2015-06-14 08:32:05.599385", "warnings": ["Consider using get_url module rather than running curl"]}
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/linode.retry

127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1

**Comment by jlund** [comment]
The API output format hasn't changed, so the most likely explanation is that there was a typo in the API key that was entered. Can you try it again?

**Comment by yekong90** [comment]
can you suggest  what I should do  more specific?
thank you

**Comment by yekong90** [comment]
Thank you I tried to generated a new linode API key, seems this is working perfect. 
thanks you so much for pointing out this key for me. Really appreciated.

now it start to install streisand common packages .. :)
![1](https://cloud.githubusercontent.com/assets/12880406/8154848/f09c8712-1370-11e5-9299-7bce41570630.JPG)

**Comment by yekong90** [comment]
everything goes smooth but finally, it still failed. Any ideas?

TASK: [streisand-mirror | Make sure the retrieved fingerprint perfectly matches the expected fingerprint] *** 
ok: [45.79.75.225]

TASK: [streisand-mirror | Mirror the stunnel files and signatures] ************ 
failed: [45.79.75.225] => (item=http://www.stunnel.org/downloads/stunnel-5.17-installer.exe) => {"dest": "/var/www/streisand/mirror/stunnel", "failed": true, "gid": 33, "group": "www-data", "item": "http://www.stunnel.org/downloads/stunnel-5.17-installer.exe", "mode": "0755", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://www.stunnel.org/downloads/stunnel-5.17-installer.exe"}
msg: Request failed
failed: [45.79.75.225] => (item=http://www.stunnel.org/downloads/stunnel-5.17-installer.exe.asc) => {"dest": "/var/www/streisand/mirror/stunnel", "failed": true, "gid": 33, "group": "www-data", "item": "http://www.stunnel.org/downloads/stunnel-5.17-installer.exe.asc", "mode": "0755", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://www.stunnel.org/downloads/stunnel-5.17-installer.exe.asc"}
msg: Request failed
failed: [45.79.75.225] => (item=http://www.stunnel.org/downloads/stunnel-5.17.tar.gz) => {"dest": "/var/www/streisand/mirror/stunnel", "failed": true, "gid": 33, "group": "www-data", "item": "http://www.stunnel.org/downloads/stunnel-5.17.tar.gz", "mode": "0755", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://www.stunnel.org/downloads/stunnel-5.17.tar.gz"}
msg: Request failed
failed: [45.79.75.225] => (item=http://www.stunnel.org/downloads/stunnel-5.17.tar.gz.asc) => {"dest": "/var/www/streisand/mirror/stunnel", "failed": true, "gid": 33, "group": "www-data", "item": "http://www.stunnel.org/downloads/stunnel-5.17.tar.gz.asc", "mode": "0755", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "http://www.stunnel.org/downloads/stunnel-5.17.tar.gz.asc"}
msg: Request failed

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/linode.retry

127.0.0.1                  : ok=8    changed=3    unreachable=0    failed=0   
45.79.75.225               : ok=143  changed=125  unreachable=0    failed=1

**Comment by szymonszydelko** [comment]
@yekong90 : please remove your previous comment asap. your API key is sensitive and could be used to at least harm you financially.

**Comment by db48x** [comment]
Actually you need to get a new API key; not only did we all get an email, everything goes out on the github events api where anyone can see it.

**Comment by yekong90** [comment]
thank you all for the help. I've removed those sensitive info.

**Comment by jlund** [comment]
@yekong90: The 404 error was happening because a new version of stunnel was recently released. If you run `git pull` in the Streisand repository directory, you'll get the latest version where this variable has been updated.
