### ISSUE TITLE
Donation

### ISSUE THREAD

**Issue by df-sh** [jlund/streisand#168]
I was hoping to find a donation link for this project somewhere but haven't had any luck.  Rather than paying Astrill or any of the other expensive VPN services being sold in China, I would much rather give my support to projects like this and shadowsocks.

Keep up the good work!

**Comment by peterpacz1** [comment]
Does this still work in China? I've conducted some live hostile environment testing last summer, and I'm about to go to China again running Streisand - but I heard that they updated the GFW to include better deep packet inspection.

**Comment by nickkilla** [comment]
As of today it is still working. I use it daily as my backup to corp vpn which drops frequently.

**Comment by df-sh** [comment]
I cannot speak for all setups and regions but I can confirm using Rackspace as a provider the streisand playbook works (with minor tweaking of mirror locations but probably due to sourceforge change).

I can also confirm that Shadowsocks and the l2tp vpn servers work in Shanghai using China Telecom (with and without foreign internet package).

Streisand setup still works great :)

**Comment by df-sh** [comment]
I have found a problem with the Amazon genesis script and a workaround for it..  but in the meantime, I can share the information here...

Currently when using the Amazon genesis script, it will fail when it attempts to create the EC2 server because of the image it attempts to use to create the server regardless of what you have signed up for at the Amazon store.

The issue is with the assignment of the aws_ami_id variable.  Part of this occurs in the playbook

determine-ami-id.yml located in streisand/playbooks/roles/genesis-amazon/tasks 

My workaround is to set aws ami id manually for the region I am using.  
 

to replace 

- name: Use the AMI ID for Northern California when the region is us-west-1
  set_fact: aws_ami_id="{{ aws_debian7_california_ami_id }}"
  when: aws_region == "us-west-1"

- name: Use the AMI ID for Northern California when the region is us-west-1
  set_fact: aws_ami_id="ami-da524a9f"
 when: aws_region == "us-west-1"

Here is a current ami list that should be usable.  Its not automatic... but it works.
Region	ID
US East (N. Virginia)	ami-38de9950
US West (Oregon)	ami-4b51097b	
US West (N. California)	ami-da524a9f
EU (Ireland)	ami-0355d974	
Asia Pacific (Singapore)	ami-e46d47b6	
Asia Pacific (Sydney)	ami-33502409
Asia Pacific (Tokyo)	  ami-a6ccd5a7	
South America (Sao Paulo)	ami-376ed22a

**Comment by YEULAB** [comment]
It worked with me, but failed when try to "Mirror Tunnelblick for OS X"

 ______________________________________________________
< TASK: streisand-mirror | Mirror Tunnelblick for OS X >
 ------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||


failed: [52.68.211.74] => {"dest": "/var/www/streisand/mirror/openvpn", "failed": true, "gid": 33, "group": "www-data", "mode": "0755", "owner": "www-data", "response": "Request failed: <urlopen error timed out>", "size": 4096, "state": "directory", "status_code": -1, "uid": 33, "url": "http://softlayer-ams.dl.sourceforge.net/project/tunnelblick/All%20files/Tunnelblick_3.4.1_r3054.dmg"}
msg: Request failed

FATAL: all hosts have already failed -- aborting
-----------------------------------------------------------------------------

**Comment by jlund** [comment]
@df-sh and @YEULAB: I'm happy to report that all of the issues you mentioned have been fixed. @CorbanR resolved the SourceForge mirroring problems, and also added support for Google Compute Engine as another provider. The Amazon AMI IDs have been updated too.

@df-sh: Thank you for your generosity; it really means a lot. However, I'm not looking to make any money off of Streisand. You can donate to one of these fine causes instead:

* [American Civil Liberties Union](https://www.aclu.org/donate/)
* [Debian](https://www.debian.org/donations)
* [Electronic Frontier Foundation](https://supporters.eff.org/donate)
* [Freedom of the Press Foundation](https://pressfreedomfoundation.org/bundle/encryption-tools-journalists)
* [Open Whisper Systems](https://whispersystems.org/blog/bithub/)
* [Tor Project](https://www.torproject.org/donate/donate.html.en)

None of this would be possible without the work that these organizations are doing. The creators of the software that Streisand sets up, like Shadowsocks, deserve a tremendous amount of acclaim for making the Internet a better place too.

I'm excited to hear that Streisand is still working well in China. I've said this before, but that was one of my biggest goals for the project, and it's something that I'm committed to maintaining. Thanks for all of the feedback!
