### ISSUE TITLE
Fail to create EC2 instance [Amazon]

### ISSUE THREAD

**Issue by YEULAB** [jlund/streisand#169]
Every time I run the script, it failed at the same place.
The last part of the output is:
 ________________________________________________
< TASK: genesis-amazon | Create the EC2 instance >
 ------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true}
msg: Instance creation failed => AuthFailure: Not authorized for images: [ami-dfa793de]

FATAL: all hosts have already failed -- aborting
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

           to retry, use: --limit @/home/xxxxx/amazon.retry

127.0.0.1                  : ok=12   changed=5    unreachable=0    failed=1   

---------------------------------------------------------------------------------------

Can any one help?

**Comment by jlund** [comment]
You need to subscribe to the Debian images in the AWS Marketplace. There's a link in the README. Let me know if you have any other questions!

**Comment by YEULAB** [comment]
Thanks for the quick response. I did subscribe to the image, and tried with the instance launched and not launched. but failed every time. Actually I subscribed to all three Debian images found on AWS marketplace. What else could I did wrong?

**Comment by kataflok** [comment]
I second that.

I've subscribed to the linked Debian image (Twice actually) and a number of others as well. Launched instances with all of them successfully.

I repeatedly get this:

TASK: [genesis-amazon | Use the AMI ID for Oregon when the region is us-west-2] *** 
ok: [127.0.0.1]

TASK: [genesis-amazon | Create the EC2 instance] ****************************** 
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true}
msg: Instance creation failed => AuthFailure: Not authorized for images: [ami-ed2864dd]

FATAL: all hosts have already failed -- aborting.

**Comment by jlund** [comment]
I'm working on this now.

**Comment by jlund** [comment]
Fixed! Thank you for letting me know!

**Comment by kataflok** [comment]
Hi jlund,

Thanks for all you are doing here -- remarkable!

I've deleted all previous subscriptions and subscribed following the new link.

I also deleted the entire streisand folder and recloned the streisand repository to my instal machine -- which has already successfully installed to Digital Ocean.

It's still giving the below.

_________________________________________

TASK: [genesis-amazon | Use the AMI ID for Oregon when the region is us-west-2] *** 
ok: [127.0.0.1]

TASK: [genesis-amazon | Create the EC2 instance] ****************************** 
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true}
msg: Instance creation failed => AuthFailure: Not authorized for images: [ami-17510927]

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/Users/userfolder/amazon.retry

127.0.0.1                  : ok=12   changed=5    unreachable=0    failed=1  
________________________________________________________

Are there certain kinds of AWS accounts that lock out Streisand perhaps?

**Comment by df-sh** [comment]
The posted fix https://github.com/jlund/streisand/commit/ccf1633b85477e21dd2c7caa832cf4b59090a961

 wont work even when subscribing to the Debian in the setup.


If you have subscribed to https://aws.amazon.com/marketplace/pp/B00AA289LU from streisand setup:
open playbooks/roles/genesis-amazon/defaults/main.yml and replace whats in there with this:

```
aws_debian7_california_ami_id: "ami-da524a9f"
aws_debian7_ireland_ami_id: "ami-0355d974"
aws_debian7_oregon_ami_id: "ami-4b51097b"
aws_debian7_sao_paulo_ami_id: "ami-376ed22a"
aws_debian7_signapore_ami_id: "ami-e46d47b6"
aws_debian7_sydney_ami_id: "ami-33502409"
aws_debian7_tokyo_ami_id: "ami-a6ccd5a7"
aws_debian7_virginia_ami_id: "ami-38de9950"

aws_instance_type: "t1.micro"
```

Then you get to sit through the slow mirroring of tor and osx tunnelblick but it should work

**Comment by TabTwo** [comment]
https://aws.amazon.com/marketplace/pp/B00AA289LU -> This version of Debian GNU/Linux is not available to new customers.
