### ISSUE TITLE
Failed to restart xl2tpd

### ISSUE THREAD

**Issue by rphillips** [jlund/streisand#171]
```
Provider: Rackspace
Region: DFW
Commit: master:ccf1633b85477e21dd2c7caa832cf4b59090a961
```

A brand new deploy fails with the following error:

```
NOTIFIED: [l2tp-ipsec | Restart strongSwan] ***********************************
changed: [166.78...]

NOTIFIED: [l2tp-ipsec | Restart xl2tpd] ***************************************
failed: [166.78....] => {"failed": true}
msg: Stopping xl2tpd: xl2tpd.
Starting xl2tpd:

FATAL: all hosts have already failed -- aborting

TASK: [streisand-gateway | Success!] ******************************************
FATAL: no hosts matched or all hosts have already failed -- aborting
```

**Comment by df-sh** [comment]
try again (you may or may not want to post the IP address of the server you are building just for future reference.  Did you have any issue setting up your rackspace account?

**Comment by rphillips** [comment]
Good point. No, I haven't had any issue with setting up my account.

**Comment by df-sh** [comment]
How many times did you run into this error?  

I can try to spin up a streisand on same region if you dont mind sharing what region you were attempting to build on  (not sure if that would cause the problem, but may as well check)

**Comment by rphillips** [comment]
I'm trying it again... I'll post back when it's done.

DFW=Dallas in my original post.

**Comment by df-sh** [comment]
My bad, didnt catch that when I first looked, gonna spin up a dallas server once this finishes and let you know

**Comment by rphillips** [comment]
happened again. The tor project downloads seem to take a while as well.

**Comment by df-sh** [comment]
TOR does take forever (if you arent going to use TOR you can # commentout the tor role from the install and it will skip it...

**Comment by jlund** [comment]
I also cannot replicate this problem. Is Streisand creating the server for you, @rphillips, or are you configuring an instance that is being launched elsewhere?

**Comment by rphillips** [comment]
Weird. I'm letting Streisand create the instance. I'll try it again.

**Comment by rphillips** [comment]
Tried it a couple more times; same issue. I tried it from a cloud server creating another cloud server as well... ansible is at 1.9.2

**Comment by df-sh** [comment]
Still trying to help with this in spare time, and I ran into the same error once in Dallas out of 7 Dallas spinups... maybe its a timing problem and the action is taking longer than the script accounts for?

Going to try other locations and see if it happens to any of them (cant test on Amazon as Amazon doesnt Launch the l2tp playbook)

**Comment by filler** [comment]
I too fail with this.

```
NOTIFIED: [l2tp-ipsec | Restart xl2tpd] ***************************************
failed: [166.78.62.155] => {"failed": true}
msg: Stopping xl2tpd: xl2tpd.
Starting xl2tpd:

FATAL: all hosts have already failed -- aborting

TASK: [streisand-gateway | Success!] ******************************************
FATAL: no hosts matched or all hosts have already failed -- aborting
```

However all the `xl2tpd` plays passed prior to the handler:

```
TASK: [l2tp-ipsec | Install xl2tpd] *******************************************
changed: [166.78.62.155]
...
TASK: [l2tp-ipsec | Generate xl2tpd configuration file] ***********************
changed: [166.78.62.155]

TASK: [l2tp-ipsec | Copy xl2tpd secrets file] *********************************
changed: [166.78.62.155]
...
TASK: [l2tp-ipsec | Copy the rsyslog config file that prevents incoming L2TP/IPsec traffic from being logged by completely filtering out all messages from pppd, charon, and xl2tpd.] ***
changed: [166.78.62.155]
```

Moreover interactively whacking the process via `stop`, `start`, `restart` seems to pass:

```
root@streisand:~# sudo /etc/init.d/xl2tpd status
Usage: /etc/init.d/xl2tpd {start|stop|restart|force-reload}
root@streisand:~# pgrep xl2tpd
root@streisand:~# /etc/init.d/xl2tpd start
Starting xl2tpd: xl2tpd.
root@streisand:~# pgrep xl2tpd
5602
root@streisand:~# /etc/init.d/xl2tpd stop
Stopping xl2tpd: xl2tpd.
root@streisand:~# /etc/init.d/xl2tpd restart
Restarting xl2tpd: xl2tpd.
root@streisand:~# pgrep xl2tpd
5843
root@streisand:~# /etc/init.d/xl2tpd restart
Restarting xl2tpd: xl2tpd.
root@streisand:~# pgrep xl2tpd
6077
```

And looking at logs on the host, it appeared to start without issue:

```
Sep 30 15:33:43 streisand ansible-<stdin>: Invoked with dpkg_options=force-confdef,force-confold upgrade=None force=False name=xl2tpd package=['xl2tpd'] purge=False state=present update_cache=False default_release=None install_recommends=True deb=None cache_valid_time=None
Sep 30 15:33:52 streisand xl2tpd[19730]: setsockopt recvref[30]: Protocol not available
Sep 30 15:33:52 streisand xl2tpd[19730]: This binary does not support kernel L2TP.
Sep 30 15:33:52 streisand xl2tpd[19731]: xl2tpd version xl2tpd-1.3.6 started on streisand PID:19731
Sep 30 15:33:52 streisand xl2tpd[19731]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Sep 30 15:33:52 streisand xl2tpd[19731]: Forked by Scott Balmos and David Stipp, (C) 2001
Sep 30 15:33:52 streisand xl2tpd[19731]: Inherited by Jeff McAdams, (C) 2002
Sep 30 15:33:52 streisand xl2tpd[19731]: Forked again by Xelerance (www.xelerance.com) (C) 2006
Sep 30 15:33:52 streisand xl2tpd[19731]: Listening on IP address 0.0.0.0, port 1701
```

Scratching my head.  Ansible 1.9.3.

**Comment by rphillips** [comment]
I commented out the restart stanzas in the ansible scripts for xl2tpd... then after the install restarted the machine.

**Comment by cpu** [comment]
I believe this issue is too dated to be actionable. Please try using the latest code from master on a fresh server instance and if the problem persists open a new issue including the details requested by the issue template. Thanks!
