### ISSUE TITLE
Android 5.1.1 client puts L2TP/IPsec daemon(s) in bad state?

### ISSUE THREAD

**Issue by c0state** [jlund/streisand#173]
Anyone having issues with Android clients (specifically 5.1.1) causing the L2TP/IPsec to not respond?  

When I connect using any of my Android 5.1.1 devices (Nexus 5, Nexus 6), no other client is able to connect afterwards (eg: OS X, iOS).

After issuing the following, I'm then able to connect again using L2TP/IPsec.

```
/etc/init.d/ipsec restart
```

OS X and iOS devices don't seem to have this issue.  I can connect/disconnect numerous times without breaking the daemon.

I know this isn't a streisand issue technically (probably strongswan pluto and/or charon) but has anyone seen this?

I'm going to try Debian 8 to see if this is fixed there...

**Comment by theaquamarine** [comment]
I'm having the same issue- OS X 10.9.4 can connect and re-connect repeatedly until my Android 5.1.1 device connects, after which nothing else can, including the Android phone.

**Comment by c0state** [comment]
i switched to this temporarily for my IPsec VPN needs--it uses LibreSwan from source: https://github.com/philplckthun/setup-simple-ipsec-l2tp-vpn

It seems to not have that issue.  Been testing it for a few weeks on a Nexus 6 with 5.1.1 using always on VPN.

The StrongSwan implementation or version used in Debian 7 seems to be the culprit.

**Comment by kydan** [comment]
I am also seeing this, which is a problem, as OpenVPN over stunnel is just not working out well for me in China.

**Comment by hydrandt** [comment]
This is not a solution to the problem, but I can't recommend more
using shadowsocks on android. Give it a try. China bound traffic goes
directly, so Chinese apps like xiami which detect your location from
your IP still work, and there is no disconnecting.

**Comment by kydan** [comment]
@hydrandt thanks so much for the suggestion. Shadowsocks was gimped on my deployment of streisand on my colo server, but I just deployed to DO and got it working and its been night and day to trying to use openvpn over SSL here. Thanks!

**Comment by dheera** [comment]
After upgrading to 5.1.1 I'm not able to connect to my L2TP/IPSec VPN anymore. However they don't affect my server or service to other clients.

**Comment by jzorn** [comment]
I have the same problem here on Android 7.0 (RC) with Libreswan 3.18 on 4.4.0-34-generic (Ubuntu 16.04.1 x64).

**Comment by cpu** [comment]
I believe this issue is too stale to be actionable. I would encourage those affected to try using the latest code from master on a fresh instance. If up-to-date client software on an Android device still presents this problem please create a new issue providing the requested information from the issue template. Thanks!
