### ISSUE TITLE
Upgrade base foundation to Ubuntu 14.04

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#174]

**Comment by Dimtree** [comment]
No longer possible to subscribe to [the AMI](https://aws.amazon.com/marketplace/pp/B00AA289LU) specified in README.md as of 7/19/15 (not sure about when the change was made). The AMI is only available to people who had subscribed to it previously.

**Comment by jlund** [comment]
That's one of the biggest reasons why this upgrade is being worked on.

**Comment by df-sh** [comment]
use this debian build:

https://aws.amazon.com/marketplace/pp/B00AA27RK4

It has these AMI's
Region	ID
US East (N. Virginia)	ami-819a63ea
US West (Oregon)	ami-3b56520b	
US West (N. California)	ami-a7d621e3	
EU (Frankfurt)	ami-bc92aaa1
EU (Ireland)	ami-42d89d35
Asia Pacific (Singapore)	ami-6a989c38
Asia Pacific (Sydney)	ami-79e39943
Asia Pacific (Tokyo)	 ami-f454f3f4
South America (Sao Paulo)	ami-a3bd3fbe

**Comment by harry-zhang** [comment]
@df-sh I noticed that build doesn't have NVM support so you'll run into some errors.  It also doesn't support the newer t2.micro.  

Here's what I ended up doing. Use this Debian build from AWS (Jessie): https://aws.amazon.com/marketplace/pp/B00WUNJIEE/ref=srh_res_product_title?ie=UTF8&sr=0-3&qid=1441446393617

You'll need to modify:
`roles/genesis-amazon/defaults/main.yml`

Just update the AMIs to match that build:
```aws_debian7_california_ami_id: "ami-a5d621e1"
aws_debian7_ireland_ami_id: "ami-0ed89d79"
aws_debian7_oregon_ami_id: "ami-3d56520d"
aws_debian7_sao_paulo_ami_id: "ami-a5bd3fb8"
aws_debian7_signapore_ami_id: "ami-60989c32"
aws_debian7_sydney_ami_id: "ami-07e3993d"
aws_debian7_tokyo_ami_id: "ami-fe54f3fe"
aws_debian7_virginia_ami_id: "ami-8b9a63e0"```

And modify the instance:
`aws_instance_type: "t2.micro"`

Also you'll need to change dnsmasq reboot as well:
`roles/openvpn/tasks/main.yml`

All you need to do is comment out line 153:
`#  notify: Restart dnsmasq`

I've tested this and tried with the latest Debian build I pointed to on the new AWS instances and it worked flawlessly.  I'll be doing more extensive testing when I travel to China to see how this holds up, but at first glance everything seems to working as expected!

**Comment by jlund** [comment]
I was still running into the occasional AMI issues with Debian 8, in addition to the OpenVPN init problem that is breaking dnsmasq.

I made a [ton of progress tonight](https://github.com/jlund/streisand/commits/1404) on moving Streisand's base foundation to Ubuntu 14.04 utilizing the official AWS AMIs (which means no more marketplace steps!). You can test the latest branch like this:

* `git pull`
* `git checkout 1404`

Then just run Streisand normally.

AWS should be fully functional at this point. I still need to update things for other providers and fix the L2TP/IPsec configuration that is broken, but I'm hoping to get all of that done this weekend. I really appreciate everyone's patience; I'm sorry that this has taken so long to fix properly.

**Comment by jlund** [comment]
I am excited to announce that Ubuntu 14.04 is now the official base foundation for Streisand. All of the necessary changes and upgrades are now part of the master branch for all providers, including Amazon!
