### ISSUE TITLE
feature request: openconnect integration. 

### ISSUE THREAD

**Issue by mveplus** [jlund/streisand#177]
Great job! Thank you! 

 Would you consider integrating [openconnect server] (http://www.infradead.org/ocserv/) in-to the options? There is backward compatibility with Cisco AnyConnect for Android and iOS for mobiles. 

Keep up the good work!
Martin

**Comment by mveplus** [comment]
Can I contribute to this? 
I'm not familiar with Ansible at all. But if you point me in the right direction I could try to add this. 

Kind regards,

**Comment by jlund** [comment]
Sorry about the delayed response. That site is down for me at the moment, unfortunately. More options are always welcome!

**Comment by mveplus** [comment]
@jlund 
No problem, each of us have other thing to do too... 
Here is latest source https://gitlab.com/ocserv/ocserv
and the page will be up I think now? http://www.infradead.org/ocserv/download.html 
Not quite yet for me.... but should be up soon.
Greetings,

**Comment by jlund** [comment]
@mveplus Thanks for the suggestion! OpenConnect / Cisco AnyConnect support was just pushed to the master branch. Ocserv is a really nice piece of software, and this is my new favorite connection method :)
