### ISSUE TITLE
feature request - monitor and re-lauch dead process

### ISSUE THREAD

**Issue by mveplus** [jlund/streisand#178]
Would be very nice to have active monitoring on all processes and if some of the services dies to relaunch it automatically. 
[Monit] (https://mmonit.com/monit/) is a lightweight and does very good job - active monitor and signaling. 

Today I managed to kill shadosocks three times. I had every time to ssh to start it again. 

Keep up the great work!

**Comment by soyuka** [comment]
We could maybe do a side project to monit streisand? Thing is it's supposed
to be nolog. What would you want to monit specifically?

**Comment by Russell-IO** [comment]
I too had a similar issue where dnsmasq had frozen after a fresh install

**Comment by mveplus** [comment]
The only purpose of monit would be to save you time and relaunch the process if it dies or doesn't respond for you, and send you an alert over e-mail or SMS to inform you about the issue. 
It will not change the policy of no logging, because it does not log your connection details! It only monitors processes you want and resources.

**Comment by Russell-IO** [comment]
The configuration I've set up in monit .. doesn't do any alerting or SMS or emails etc.. it simply provides a status page at /monit (requires the same auth as the gateway) & restarts key processes if they have failed.

**Comment by mveplus** [comment]
That was my main idea!  All other notification capabilities of monit are easy to setup and personal preference...
