### ISSUE TITLE
stunnel4 is using hardcoded DH params

### ISSUE THREAD

**Issue by dlmetcalf** [jlund/streisand#179]
stunnel4 package uses static DH params (https://www.stunnel.org/static/stunnel.html#DH-PARAMETERS).

Recommend adding "openssl gendh 2048 >> stunnel.pem" step (now included in stunnel.org's install instructions).
  
This can be skipped once stunnel is upgraded to v5.18 or later, which updates params every 24 hours.

See https://weakdh.org/ for more info on vulnerability.

**Comment by dlmetcalf** [comment]
apologies, code appear to be using latest stunnel.  closing.

**Comment by dlmetcalf** [comment]
nope...  It is indeed stunnel v4.53, so should use openssl gendh  (or upgrade to stunnel-latest like stunnel-mirror is downloading and verifying).

forward@(none):~$ stunnel -version
stunnel 4.53 on x86_64-pc-linux-gnu platform
Compiled/running with OpenSSL 1.0.1e 11 Feb 2013
[...]

**Comment by mveplus** [comment]
Yes, on Debian 7.x is stunnel ver.4.53 , on Debian 8.x is stunnel  ver.5.06

**Comment by jlund** [comment]
stunnel is used in Streisand as an obfuscation layer for OpenVPN whose role does generate unique DH parameters. Still, this should be easy to do so I will leave it open.

**Comment by dlmetcalf** [comment]
Thanks @jlund!  Saw your disable of SSLv3 too cheers!

Just reading [https://www.openssl.org/news/secadv/20160128.txt], it looks like the `SSL_OP_SINGLE_DH_USE` option is now default in OpenSSL >=1.0.2f.  If using that OpenSSL version, it would probably be okay to add the `openssl dhparam -dsaparam` option.  That should reduce performance cost of this task.  If 'safe' primes are still preferred over provisioning performance, then no change necessary obviously.  Best regards.
