### ISSUE TITLE
TCP Timeout on OpenVPN sslh based connections

### ISSUE THREAD

**Issue by Russell-IO** [jlund/streisand#180]
Having issues that connection resets on say corporate networks which clean up idle TCP sessions.

**Comment by kydan** [comment]
I too am having insane issues with connection reset here in China. My preliminary investigation suggests that stunnel is being subjected to heavy DPI and arbitrarily receiving reset packets.

**Comment by mveplus** [comment]
@kydan @Russell-IO Yes that's true! 
Have you find any solution?
If anybody have any suggestion that can be used as a workaround to RST problem?
