### ISSUE TITLE
redeploy server with new public IP

### ISSUE THREAD

**Issue by nickolasclarke** [jlund/streisand#184]
First off, this is more of a troubleshooting issue than an actual bug, and I do not think this is the most appropriate place for a discussion, but alas, it seems this project does not have a IRC/gitter/mailing list so I'm dropping my problem here. I am currently based in China and I am waging a constant battle against the GFW. While it is hard to confirm definitively (given that results are sporadic on a day to day basis) I believe that often my connections to my streisand instance, no matter what protocol or solution I use, after a few days or even hours get blocked. 

For example, right now, while I can SSH to my streisand instance by IP from a jump host and get 0% packet loss from a ping to it from that host, I get around 75% packet loss from my desktop and cannot connect over L2TP/IPSEC or use shadowsocks. However, from my phone I can still successfully connect to the server. While this is not definitive proof, given the constant issues I have with different connections at different locations, I am fairly confident that this is more than simple connectivity issues and is directly related to connection sabotage. the GFW is wildly inconsistent and it is hard to nail down exactly what is causing what. 

 So, one solution I have found is to simply take a snapshot of a streisand host (I am currently using Digital Ocean Singapore) and then whenever my connection seems to have permanently degraded, I spin a new droplet from the snapshot, modify a few configs files by hand, (such as /home/shadowsocks/config.json:$SERVERVAR)  and point my clients at the new IP. This saves having to spin a whole new instance each time, and heavily modify all my client configurations and also seems to fix, albeit temporarily, the problems at hand.

However, I am have not had luck getting l2tp/ipsec to work with this solution, and I have also noticed that the webserver does not seem to be working either. I was hoping to get some help identifying all the requisite configurations that should be modified in order to support a public IP migration since this is the first time I have worked with many of these technologies before. Once I've nailed down the process by hand, I plan to write a tool to quickly redeploy a configured Streisand DO droplet with a new IP which I'll gladly publish here on github.  

If there is a better place to publish requests such as these in the future, please let me know and I'll move this to the appropriate forum. 

On a related note, being able to backup the full set of Streisand configs and feed them into a deployment would be a great feature, but is outside the scope of this initial request, but I thought I would plant the seed :)

**Comment by mveplus** [comment]
Hi kydan, 

Have you tried to change /etc/ipsec.conf server IP address?
There was times UDP (L2TP/IPSEC and OpenVPN) was partly/fully blocked in some parts of China. 
The first defence ring is GWF, + IDS/DPI, automatic + custom rules and dynamic profiling, but also depends on your local ISP provider they tend to have their ring as well, for different geo locations the same ISP have different policy, you can add to this frequent DNS hijacking&poisoning but it you're using IP this is not the case... 

It's time for GFW profiler project, will save days work ....

**Comment by kydan** [comment]
@mveplus I've not since my latest instance has been surprisingly stable. Thanks for the heads up on that config file though.

**Comment by mveplus** [comment]
@kydan great! I'm glad you got it working!

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/17
