### ISSUE TITLE
Failed in "Wait until the server has finished booting and OpenSSH is accepting connections"

### ISSUE THREAD

**Issue by biaocy** [jlund/streisand#187]
Please forgive my poor english... 
I'm try to explain clear... 
Provider is DigitalOcean, droplet has been created, when connect the droplet with OpenSSH, appear following info:
```
failed: [127.0.0.1] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for search string OpenSSH in xxx.xxx.xxx.xxx:22

FATAL: all hosts have already failed -- aborting
```
I can't connect the droplet use following command:
```
ssh root@xxx.xxx.xxx.xxx
```

**Comment by samchelsea009** [comment]
Same problem on google GCE:

TASK: [genesis-google | Wait until the server has finished booting and OpenSSH is accepting connections] *** 
failed: [127.0.0.1] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for search string OpenSSH in 104.154.70.33:22

FATAL: all hosts have already failed -- aborting

**Comment by samchelsea009** [comment]
TASK: [genesis-google | Wait until the server has finished booting and OpenSSH is accepting connections] *** 
failed: [127.0.0.1] => {"elapsed": 300, "failed": true}
msg: Timeout when waiting for search string OpenSSH in XXx.xxx.xxx.xxx:22

FATAL: all hosts have already failed -- aborting

**Comment by jlund** [comment]
I doubled the SSH connection check timeout from five minutes to ten minutes.

On rare occasions, providers are going to launch a server that either takes forever to boot or that might not come up at all. If you're still waiting after ten minutes and can't connect, it is probably best to shut down the malfunctioning server, roll the dice, and try again :)
