### ISSUE TITLE
New putty releas keys

### ISSUE THREAD

**Issue by johnvelan** [jlund/streisand#191]
Please note that there are new putty release keys used from now on:
http://www.chiark.greenend.org.uk/~sgtatham/putty/keys.html

Release Key
RSA, 2048-bit. Key ID: 2048R/B43434E4 (long version: 2048R/9DFE2648B43434E4). Fingerprint: 0054 DDAA 8ADA 15D2 768A  6DE7 9DFE 2648 B434 34E4 

This affects the streisand-mirror role (which now fails as it points to the latest release).

**Comment by jlund** [comment]
Thanks!
