### ISSUE TITLE
Digital Ocean setup failing

### ISSUE THREAD

**Issue by lucastimmons** [jlund/streisand#198]
I'm trying to install to Digital Ocean. It creates a droplet but SSH doesn't connect. 
***SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh***

Not sure what's happening, I had run through the process without problems before. I know they just switched their API to v2. Any help would be appreciated. 

Here's the output:

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the DigitalOcean Server] ************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Retrieve the SSH key ID using the name that was provided] *** 
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Create the server. If this task fails with an "invalid region" error, then DigitalOcean is temporarily not allowing new 512MB Droplets to be provisioned in the selected region. You can either try the same region again later, or choose a different location.] *** 
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Retrieve the IP address of the new Droplet] ***** 
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Wait until the server has finished booting and OpenSSH is accepting connections] *** 
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Create the in-memory inventory group] *********** 
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Set the streisand_ipv4_address variable] ******** 
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Set the streisand_server_name variable] ********* 
ok: [127.0.0.1]

PLAY [Configure the Server and install required software] ********************* 

GATHERING FACTS *************************************************************** 
fatal: [xxx.xxx.xx.xx] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

**Comment by jlund** [comment]
I can't reproduce this. Is it possible that you are attempting to connect using a different SSH key than the name that you specified at the prompt?

**Comment by lucastimmons** [comment]
Oh my goodness I'm dumb. I uploaded the wrong SSH key to Digital Ocean. All good now.

Thanks so much jlund. You rock. This is really great.
