### ISSUE TITLE
Switch to shadowsocks-libev

### ISSUE THREAD

**Issue by pjrobertson** [jlund/streisand#200]
Since the python version of Shadowsocks has been [taken down](https://github.com/shadowsocks/shadowsocks), Streisand should switch to use the -libev version of the library. I've also found this to be a little bit faster than the python version, and it's just as easy to install.

**Comment by skeeve42** [comment]
I saw it was taken down, but does anyone know why, exactly? I have not yet tested the libev version.

**Comment by pjrobertson** [comment]
> I saw it was taken down, but does anyone know why, exactly?

The original developer was Chinese. He was threatened by the Chinese police
and so was forced to take it down.
See
https://en.greatfire.org/blog/2015/aug/chinese-developers-forced-delete-softwares-police
for more info.
The original message about the police was quickly removed, most likely due
to more pressure from the authorities.

Time to switch and continue the Streisand effect...?

>  have not yet tested the libev version

I'm running it on all my 3 servers. Not a single problem to report, and
updating it is nice and easy with apt-get upgrade

**Comment by skeeve42** [comment]
Thanks @pjrobertson . Hope he's alright.
