### ISSUE TITLE
pycurl required for this module

### ISSUE THREAD

**Issue by rissoa** [jlund/streisand#203]
TASK: [genesis-linode | Create the server] ************************************
failed: [127.0.0.1] => {"failed": true, "parsed": false}
failed=True msg='pycurl required for this module'

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/linode.retry

127.0.0.1                  : ok=3    changed=2    unreachable=0    failed=1

**Comment by rissoa** [comment]
I solve it by:

apt-get install python-pycurl

I think it's better to put it into installation guide for newbies:)
ubuntu 14.04 lts

**Comment by jlund** [comment]
What operating system and Python version are you using?

**Comment by jlund** [comment]
Sorry, your second message didn't arrive as an email notification for some reason. I will get that added to the README.

**Comment by jlund** [comment]
Added! Thanks for letting me know.
