### ISSUE TITLE
can not import ssl certificates into keychain

### ISSUE THREAD

**Issue by rissoa** [jlund/streisand#204]
OSX EI Capitan 10.11.1

I import the xxx.xxx.xxx.xxx.crt into Keychain, but nothing happened, any trust issue to EI Captian?

**Comment by jlund** [comment]
Not that I'm aware of. I recently set things up on a new OS X laptop running El Capitan without any issues. Did you see any error messages? Also, did you try double-clicking on the certificate file?

**Comment by rissoa** [comment]
Finally, I found this certificate, it calls Effect Department. Keychain tells me This root certificate is not trusted. So have to manually change it to trust ssl.
