### ISSUE TITLE
Fail on retrieve ip address of new droplet

### ISSUE THREAD

**Issue by ddvzlnz** [jlund/streisand#206]
Hi, I'm new to digital ocean and wanted to try this out.  I'm running streisand on an ubuntu 14,043 server vm here in the office.  When I run streisand it fails at:
TASK: [genesis-digitalocean | Retrieve the IP address of the new Droplet] *****
The last line of the error is "IndexError: list index out of range"
If I open a browser and log into DO the new droplet is there.  Here is the session.  Please let me know if there is something I can try.

wfcadmin@bhc1:~/streisand$ ./streisand

  S T R E I S A N D  

Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: 2

What region should the server be located in?
  1.  Amsterdam        (Datacenter 2)
  2.  Amsterdam        (Datacenter 3)
  3.  Frankfurt
  4.  London
  5.  New York         (Datacenter 1)
  6.  New York         (Datacenter 2)
  7.  New York         (Datacenter 3)
  8.  San Francisco
  9.  Singapore
  10. Toronto
Please choose the number of your region. Press enter for default (#2) region.
 [2]: 7

What should the server be named? Press enter for default (streisand).
 [streisand]: 

New API access tokens can be generated in the DigitalOcean control panel. When generating a new token, please note that the Write Scope is necessary in order to create Droplets.
https://cloud.digitalocean.com/settings/applications

What is your DigitalOcean Access Token?
: XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX (I typed "X" over the real token here and below in the error message)

If you haven't done so already, you must add your SSH public key in the DigitalOcean control panel.
https://cloud.digitalocean.com/settings/security

What is the name of the DigitalOcean SSH key that you would like to use?
 [streisand]: 

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the DigitalOcean Server] ************************************** 

GATHERING FACTS *************************************************************** 
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Retrieve the SSH key ID using the name that was provided] *** 
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Create the server. If this task fails with an "invalid region" error, then DigitalOcean is temporarily not allowing new 512MB Droplets to be provisioned in the selected region. You can either try the same region again later, or choose a different location.] *** 
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Retrieve the IP address of the new Droplet] ***** 
failed: [127.0.0.1] => {"changed": true, "cmd": "curl -s -X GET -H 'Content-Type: application/json' -H 'Authorization: Bearer XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX' \"https://api.digitalocean.com/v2/droplets/8986939\" | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print j[\"droplet\"][\"networks\"][\"v4\"][0][\"ip_address\"]'", "delta": "0:00:00.184688", "end": "2015-11-23 17:32:03.163761", "rc": 1, "start": "2015-11-23 17:32:02.979073", "warnings": ["Consider using get_url module rather than running curl"]}
stderr: Traceback (most recent call last):
  File "<string>", line 1, in <module>
IndexError: list index out of range

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/home/wfcadmin/digitalocean.retry

127.0.0.1                  : ok=3    changed=2    unreachable=0    failed=1   

wfcadmin@bhc1:~/streisand$

**Comment by benpoliquin** [comment]
Ironically, I am having this same issue right now. I did delete and fire up a new droplet and it fixed this, but then I get this error: https://github.com/jlund/streisand/issues/198
My ssh key is correct, unlike the poster of that issue.  Even deleted and re added my key multiple times to test.

**Comment by ddvzlnz** [comment]
Update.  I created a digital ocean droplet (ubuntu 14.04) and ran the playbook against it as if I was creating on bare metal and it seems to have completed without errors.  I'll be testing it today.

**Comment by benpoliquin** [comment]
@ddvzlnz Did it work after testing?

**Comment by jlund** [comment]
I just started 20 droplets in rapid succession, and three of them exhibited this error. There appears to be a race condition where the API is occasionally not ready to respond with the server's IP when that call is made. I'm going to put some retry logic around this step.

**Comment by jlund** [comment]
@ddvzlnz Thanks for the report. This should be fixed now.

@benpoliquin It sounds like there is still an issue with your ability to connect using your key. If this isn't due to a key mismatch, it could be that the relevant key hasn't been added to your SSH agent. Here's a test that you can do completely outside of Streisand:

1. Sign in to the DigitalOcean Control Panel.
1. Click the *Create Droplet* button.
1. Enter a test hostname, select the size, choose a region, and leave Ubuntu 14.04 selected.
1. In the *Add your SSH keys* section, make sure you have checked the key that you are attempting to use with Streisand.
1. Click *Create*.
1. Wait for the server to boot, then attempt to connect: `ssh root@<ip-address-of-the-new-server>`

Are you able to connect? If so, I may need you to email me some additional information to continue troubleshooting. If not, then this is an SSH agent, key, or other connection issue that is happening outside of Streisand.
