### ISSUE TITLE
After a bit of usage vpn stops responding

### ISSUE THREAD

**Issue by ohnotnow** [jlund/streisand#212]
I had an install running happily for a month or two then it stopped. I didn't think anything much of it and thought I'd just spin up another server with an updated copy of the code.  Went find - installed ok, but after a couple of days I'm seeing the same problem (screenshot of the digital ocean console - sorry!)

https://imgur.com/H9I9kmr

I can ssh in ok - the server is fine as far as I can make out. I've rebooted the server a few times just in case - but no luck. The only thing I can think is triggering this is letting my client machine go to sleep while still connected to the vpn? Client OS is MacOS 10.8.

**Comment by jlund** [comment]
L2TP/IPsec doesn't handle roaming clients very well. It also doesn't support more than a single client per IP, so you can't have your phone and laptop connected simultaneously while using the same WiFi access point, for example. In the case of a client that goes to sleep and loses its connection, there can be a timeout period where that client won't be able to connect again. Rebooting the server should clear that state though.

IKEv2 doesn't share these same limitations, but it also isn't as widely supported. A future version of Streisand will allow you to choose between L2TP/IPsec and IKEv2 during the setup process.

**Comment by jlund** [comment]
For reference, IKEv2 support is being tracked in #110.
