### ISSUE TITLE
ssh error on digitalocean droplet creation

### ISSUE THREAD

**Issue by lfxc** [jlund/streisand#213]
The droplet gets created fine, but aborts on streisand playbook execution with the following error:

PLAY [Configure the Server and install required software] ********************* 

GATHERING FACTS *************************************************************** 
<198.199.90.120> ESTABLISH CONNECTION FOR USER: root
<198.199.90.120> REMOTE_MODULE setup
<198.199.90.120> EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/username/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=10 198.199.90.120 /bin/sh -c 'LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'
fatal: [198.199.9.1] => SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh

TASK: [common | Warn users if the server's Linux distribution is not Ubuntu 14.04] *** 
FATAL: no hosts matched or all hosts have already failed -- aborting

I'm running ansible 1.9.4 under debian 8.2

**Comment by stevemcquaid** [comment]
Are you able to ssh into the server manually?
`ssh root@<server_host/ip>`

**Comment by lcanali** [comment]
yes.  ssh works fine.  That's why I'm confused.  It seems like either the
ip or ssh key (or something) is getting dropped in the hand-off between
scripts.

On Thu, Dec 10, 2015 at 12:58 PM, Stephen McQuaid <notifications@github.com>
wrote:

> Are you able to ssh into the server manually?
> ssh root@<server_host/ip>
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlund/streisand/issues/213#issuecomment-163702983>.
>



-- 



Luigi Canali, PMP
_________________________________________
FedCMS
(301) 537-9009 - direct
(202) 318-7628 - fax
LCanali@FedCMS.com
www.FedCMS.com



______________________________________________________________________

Confidentiality Notice: The information contained in this message is
intended only for the use of the
addressee, and should be considered confidential and/or privileged. If the
reader of this message is not the intended recipient, or the employee or
agent responsible to deliver it to the intended recipient, you are hereby
notified that any dissemination, distribution or copying of this
communication and its contents is strictly prohibited.  If you have
received this communication in error, please notify the sender immediately.
______________________________________________________________________

**Comment by jlund** [comment]
Do you have multiple keys in your SSH agent, and what type of key are you using (RSA, ed25519, etc.)? Also, does this happen consistently?

If you can successfully SSH to the IP as root, Ansible should be able to do the same thing without any issues.

I can't reproduce this. Droplet creation works every time for me, on multiple platforms and machines. Hopefully we can figure out what is going on.

**Comment by lcanali** [comment]
Testing on DO, No multiple ssh keys, standard ssh keygen keys, happens
every time.

I just tried running everything form an ubuntu 14.04 host machine and it
worked fine.  I also reinstalled from scratch on Debian 8 and got the same
failed results.   It appears that it won't run on a debian 8 host.  It
fails at the same point every time after droplet reboot.

Here's the putput.  It seems to fail when exexcutingthe streisand.yml file:
treisand will now set up your server. This process usually takes around ten
minutes. Press Enter to begin setup...
:

***BEGIN OUTPUT***

PLAY [Provision the DigitalOcean Server]
**************************************

GATHERING FACTS
***************************************************************
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Retrieve the SSH key ID using the name that
was provided] ***
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Create the server. If this task fails with an
"invalid region" error, then DigitalOcean is temporarily not allowing new
512MB Droplets to be provisioned in the selected region. You can either try
the same region again later, or choose a different location.] ***
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Retrieve the IP address of the new Droplet]
*****
changed: [127.0.0.1]

TASK: [genesis-digitalocean | Wait until the server has finished booting
and OpenSSH is accepting connections] ***
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Create the in-memory inventory group]
***********
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Set the streisand_ipv4_address variable]
********
ok: [127.0.0.1]

TASK: [genesis-digitalocean | Set the streisand_server_name variable]
*********
ok: [127.0.0.1]

PLAY [Configure the Server and install required software]
*********************

GATHERING FACTS
***************************************************************
fatal: [198.211.115.87] => SSH Error: data could not be sent to the remote
host. Make sure this host can be reached over ssh

TASK: [common | Warn users if the server's Linux distribution is not Ubuntu
14.04] ***
FATAL: no hosts matched or all hosts have already failed -- aborting


PLAY RECAP
********************************************************************
           to retry, use: --limit @/home/lcanali/digitalocean.retry

127.0.0.1                  : ok=8    changed=3    unreachable=0    failed=0

198.211.115.87             : ok=0    changed=0    unreachable=1    failed=0


***END OUTPUT***


Could you try a run from a debian 8.2 x64 box?

On Fri, Dec 11, 2015 at 1:12 PM, Joshua Lund <notifications@github.com>
wrote:

> Do you have multiple keys in your SSH agent, and what type of key are you
> using (RSA, ed25519, etc.)? Also, does this happen consistently?
>
> If you can successfully SSH to the IP as root, Ansible should be able to
> do the same thing without any issues.
>
> I can't reproduce this. Droplet creation works every time for me, on
> multiple platforms and machines. Hopefully we can figure out what is going
> on.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/jlund/streisand/issues/213#issuecomment-164006991>.
>



-- 



Luigi Canali, PMP
_________________________________________
FedCMS
(301) 537-9009 - direct
(202) 318-7628 - fax
LCanali@FedCMS.com
www.FedCMS.com



______________________________________________________________________

Confidentiality Notice: The information contained in this message is
intended only for the use of the
addressee, and should be considered confidential and/or privileged. If the
reader of this message is not the intended recipient, or the employee or
agent responsible to deliver it to the intended recipient, you are hereby
notified that any dissemination, distribution or copying of this
communication and its contents is strictly prohibited.  If you have
received this communication in error, please notify the sender immediately.
______________________________________________________________________

**Comment by lcanali** [comment]
I was able to resolve the issue by adding the --private-key param to the
command line in the streisand executable:

--private-key=~/.ssh/blah-key

Unfortunately, I don't know enough about ansible to figure out what's
broken with it on debian 8.  It's obviously something to do with the ssh
key getting passed correctly to the execution of the streisand.yml playbook.

On Mon, Dec 14, 2015 at 8:21 AM, Luigi Canali <lcanali@fedcms.com> wrote:

> Testing on DO, No multiple ssh keys, standard ssh keygen keys, happens
> every time.
>
> I just tried running everything form an ubuntu 14.04 host machine and it
> worked fine.  I also reinstalled from scratch on Debian 8 and got the same
> failed results.   It appears that it won't run on a debian 8 host.  It
> fails at the same point every time after droplet reboot.
>
> Here's the putput.  It seems to fail when exexcutingthe streisand.yml file:
> treisand will now set up your server. This process usually takes around
> ten minutes. Press Enter to begin setup...
> :
>
> ***BEGIN OUTPUT***
>
> PLAY [Provision the DigitalOcean Server]
> **************************************
>
> GATHERING FACTS
> ***************************************************************
> ok: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Retrieve the SSH key ID using the name that
> was provided] ***
> changed: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Create the server. If this task fails with
> an "invalid region" error, then DigitalOcean is temporarily not allowing
> new 512MB Droplets to be provisioned in the selected region. You can either
> try the same region again later, or choose a different location.] ***
> changed: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Retrieve the IP address of the new Droplet]
> *****
> changed: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Wait until the server has finished booting
> and OpenSSH is accepting connections] ***
> ok: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Create the in-memory inventory group]
> ***********
> ok: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Set the streisand_ipv4_address variable]
> ********
> ok: [127.0.0.1]
>
> TASK: [genesis-digitalocean | Set the streisand_server_name variable]
> *********
> ok: [127.0.0.1]
>
> PLAY [Configure the Server and install required software]
> *********************
>
> GATHERING FACTS
> ***************************************************************
> fatal: [198.211.115.87] => SSH Error: data could not be sent to the remote
> host. Make sure this host can be reached over ssh
>
> TASK: [common | Warn users if the server's Linux distribution is not
> Ubuntu 14.04] ***
> FATAL: no hosts matched or all hosts have already failed -- aborting
>
>
> PLAY RECAP
> ********************************************************************
>            to retry, use: --limit @/home/lcanali/digitalocean.retry
>
> 127.0.0.1                  : ok=8    changed=3    unreachable=0
>  failed=0
> 198.211.115.87             : ok=0    changed=0    unreachable=1
>  failed=0
>
> ***END OUTPUT***
>
>
> Could you try a run from a debian 8.2 x64 box?
>
> On Fri, Dec 11, 2015 at 1:12 PM, Joshua Lund <notifications@github.com>
> wrote:
>
>> Do you have multiple keys in your SSH agent, and what type of key are you
>> using (RSA, ed25519, etc.)? Also, does this happen consistently?
>>
>> If you can successfully SSH to the IP as root, Ansible should be able to
>> do the same thing without any issues.
>>
>> I can't reproduce this. Droplet creation works every time for me, on
>> multiple platforms and machines. Hopefully we can figure out what is going
>> on.
>>
>> —
>> Reply to this email directly or view it on GitHub
>> <https://github.com/jlund/streisand/issues/213#issuecomment-164006991>.
>>
>
>
>
> --
>
>
>
> Luigi Canali, PMP
> _________________________________________
> FedCMS
> (301) 537-9009 - direct
> (202) 318-7628 - fax
> LCanali@FedCMS.com
> www.FedCMS.com
>
>
>
> ______________________________________________________________________
>
> Confidentiality Notice: The information contained in this message is
> intended only for the use of the
> addressee, and should be considered confidential and/or privileged. If the
> reader of this message is not the intended recipient, or the employee or
> agent responsible to deliver it to the intended recipient, you are hereby
> notified that any dissemination, distribution or copying of this
> communication and its contents is strictly prohibited.  If you have
> received this communication in error, please notify the sender immediately.
> ______________________________________________________________________
>
>
>


-- 



Luigi Canali, PMP
_________________________________________
FedCMS
(301) 537-9009 - direct
(202) 318-7628 - fax
LCanali@FedCMS.com
www.FedCMS.com



______________________________________________________________________

Confidentiality Notice: The information contained in this message is
intended only for the use of the
addressee, and should be considered confidential and/or privileged. If the
reader of this message is not the intended recipient, or the employee or
agent responsible to deliver it to the intended recipient, you are hereby
notified that any dissemination, distribution or copying of this
communication and its contents is strictly prohibited.  If you have
received this communication in error, please notify the sender immediately.
______________________________________________________________________
