### ISSUE TITLE
openntpd failed to install

### ISSUE THREAD

**Issue by RaymiiOrg** [jlund/streisand#215]
I was hit by this bug on Ubuntu 14.04: https://bugs.launchpad.net/ubuntu/+source/openntpd/+bug/458061

The provided workaround works:

    dpkg --purge ntp
    invoke-rc.d apparmor restart
    apt-get install openntpd

**Comment by jlund** [comment]
Which VPS provider were you using?

**Comment by RaymiiOrg** [comment]
Digitalocean and vultr

**Comment by jlund** [comment]
Sorry about the delay on this. I am looking into adding official Vultr support. I switched back to the standard NTP daemon, which resolves this conflict.
