### ISSUE TITLE
Error with Linode Setup

### ISSUE THREAD

**Issue by terrierlips** [jlund/streisand#216]
Error code:

TASK: [genesis-linode | Get the latest Ubuntu 14.04 image ID from the Linode API] *** 
failed: [127.0.0.1] => {"cmd": "curl -s 'https://api.linode.com/?api_key=<KEY>api_action=avail.distributions' '|' python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j[\"DATA\"] if img[\"LABEL\"]==\"Ubuntu 14.04 LTS\"][0][\"DISTRIBUTIONID\"]'", "failed": true, "rc": 2}
msg: [Errno 2] No such file or directory

FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/linode.retry

127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1

**Comment by genewitch** [comment]
per https://www.linode.com/docs/websites/lamp/lamp-on-ubuntu-14-04 and the "deploy an image" on their web interface, they do have 14.04LTS.

Maybe it's a bug in their API?

**Comment by terrierlips** [comment]
Yeah, I stood up a 14.04 instance yesterday to test and make sure they worked, and it did. Might be an API change. Only thing I can think of.

**Comment by jlund** [comment]
I think this was a temporary API glitch. I was just able to create 5 test Linode servers without any issues.
