### ISSUE TITLE
Create a usb stick with a raspberry pi zero

### ISSUE THREAD

**Issue by mingodad** [jlund/streisand#218]
Hello !

A project like this is a good candidate to create a usb stick (with a raspberry pi zero or similar plus wifi/bluetooth) that can be used to tether a secure internet connection.

We also need DNS (something like https://github.com/BII-Lab/DNSoverHTTP).

I'm inviting anyone interested on creating it and probably get the project on kickstarter.

**Comment by faddat** [comment]
@mingodad I'd be really happy to discuss creating both client and server side hardware with you, for markets outside of China.

**Comment by cpu** [comment]
This deployment model isn't a goal of the Streisand project. I hope you are able to coordinate externally on a solution that respects the Streisand license and meets your needs. Thanks!
