### ISSUE TITLE
TASK: [ufw | Ensure UFW is enabled and denies by default]

### ISSUE THREAD

**Issue by apollux** [jlund/streisand#220]
I got the following error after running streisand on a fresh Ubuntu 14.04 install. 

The ip address has been replaced with: <Ip address removed>

TASK: [ufw | Ensure UFW is enabled and denies by default] ********************\* 
<<Ip address removed>> ESTABLISH CONNECTION FOR USER: user
<<Ip address removed>> REMOTE_MODULE ufw state="enabled" policy="deny" direction="incoming"
<<Ip address removed>> EXEC ssh -C -v -o ControlMaster=auto -o ControlPersist=60s -o ControlPath="/home/andre/.ansible/cp/ansible-ssh-%h-%p-%r" -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o ConnectTimeout=10 178.21.113.75 /bin/sh -c 'sudo -k && sudo -H -S -p "[sudo via ansible, key=wrizizjpuvyyuxkugzksygbndljkermv] password: " -u root /bin/sh -c '"'"'echo BECOME-SUCCESS-wrizizjpuvyyuxkugzksygbndljkermv; LANG=en_US.UTF-8 LC_CTYPE=en_US.UTF-8 /usr/bin/python'"'"''
failed: [<Ip address removed>] => {"failed": true}
msg: ERROR: problem running ufw-init
ip6tables-restore: line 73 failed

Problem running '/etc/ufw/before6.rules'

FATAL: all hosts have already failed -- aborting

**Comment by jlund** [comment]
What provider were you using?

**Comment by apollux** [comment]
No provider, it just a simple vps. I have edited the inventory file
accordingly.

After looking into it a bit more, it seems related to IPv6. I have
commented out the lines starting with “IPT_MODULES” and “IPV6” in the file
/etc/default/ufw. After making these changes the playbook runs fine.

**Comment by cpu** [comment]
It sounds like you were able to work around the problem and it might be specific to your VPS provider & kernel. I'm going to close this issue but please feel free to open a new issue if you find the same problem happens with a 16.04 host and the latest git master Streisand. Thanks!
