### ISSUE TITLE
problem connecting to shadowsocks server

### ISSUE THREAD

**Issue by luckman27** [jlund/streisand#223]
Hi! I have successfully installed Streisand already three times, but each time I cannot connect to the shadowsocks server; everything else, like Tor, works fine, only shadowsocks doesn't. I have tried connecting with different computers and with the phone, but it doesn't connect. Any idea what can be the problem?

**Comment by df-sh** [comment]
try rebooting the server after the setup has completed

**Comment by luckman27** [comment]
Well, there is good news and bad news. I rebooted the server and after that, shadowsocks started to work. The problem now is that it seems that the tor bridge doesn't work anymore, because I can't connect to tor anymore. I have tried with another server, and the same thing, the bridge stops working after rebooting. Is there another way of solving this? Thanks.

**Comment by df-sh** [comment]
manually restart the tor related services through ssh

**Comment by luckman27** [comment]
Hi,
I tried to reboot a new server, and again the same thing happened, shadowsocks started working, but Tor not anymore. 
For manually restarting tor, I used `sudo service tor start` and I got this:
```sudo: unable to resolve host xxxxx
     * Starting tor daemon...                                                       aa-exec: ERROR: profile 'system_tor' does not exist```

and I also tried `sudo /etc/init.d/tor start` and got the following:

 ```* Starting tor daemon...                                                       perl: warning: Setting locale failed.
perl: warning: Please check that your locale settings:
	LANGUAGE = (unset),
	LC_ALL = (unset),
	LC_CTYPE = "UTF-8",
	LANG = "en_US.UTF-8"
    are supported and installed on your system.
perl: warning: Falling back to the standard locale ("C").
aa-exec: ERROR: profile 'system_tor' does not exist      fail]```

What you suggest?

**Comment by luckman27** [comment]
Ok, I found the way, just had to login the server and restart the shadowsocks server with this command:
`sudo /etc/init.d/shadowsocks-libev restart`

**Comment by jlund** [comment]
There was a bug in the Shadowsocks task that wasn't restarting the service after the configuration file had changed. This should be fixed now!
