### ISSUE TITLE
Use LetsEncrypt to make installing cert unnecessary.

### ISSUE THREAD

**Issue by snakecharmer1024** [jlund/streisand#227]
I may be misunderstanding something, but I think we can just get recognized by a root certificate authority for free, automated. 
https://letsencrypt.org/

It still would be good to check the fingerprints, but maybe this will make it easier to get running.

**Comment by snakecharmer1024** [comment]
https://github.com/letsencrypt/letsencrypt

**Comment by snakecharmer1024** [comment]
I'd be willing to put a little time into this if someone could let me know what needs to be done. I have moderate knowledge of these topics, but would like guidance.

**Comment by jlund** [comment]
Let's Encrypt doesn't support issuing SSL certificates for a bare IP.

This could be a nice alternate option for people who already have their own domain name, but unless I'm missing something, it couldn't be the default.

**Comment by snakecharmer1024** [comment]
Ah, you're right, that's an important point...I wonder why they don't do it for bare IP. I asked about it over here, https://github.com/letsencrypt/letsencrypt/issues/2217

I'll close for now until this becomes viable.
