### ISSUE TITLE
IPsec/L2TP does not work with Android 6.0

### ISSUE THREAD

**Issue by deverant** [jlund/streisand#231]
As can be read in the libreswan [wiki](https://libreswan.org/wiki/FAQ#Android_6.0_connection_comes_up_but_no_packet_flow) the current VPN implementation in Android 6.0 is based on a draft and doesn't work as you'd expect. Apart from the sha2 truncation problem it seems Android also wants a very specific cipher suite.

I was able to get everything working by adding `aes256-sha2_256` to `phase2alg` and also including `sha2-truncbug=yes` option in `ipsec.conf`.

No idea currently if and how this affects the other clients and what the security implications are. For clients I can check iOS later.

Not sure if the better option here would be to edit ipsec.conf or just tell Android users to use OpenVPN for now. Figured I'll make an issue regardless so the next guy wondering why it doesn't work out of the box would have an easier time. And if this was already mentioned somewhere then let this issue be a reminder to me to buy glasses.

**Comment by jlund** [comment]
This should be fixed. My Android device hasn't been upgraded to 6.0 yet (thanks, carriers!) so if there's any way that you could try this again, I would appreciate it. iOS devices and the other clients that I tried all still work as well.

Thanks for the bug report!

**Comment by ArievanDuin** [comment]
Have just Upgraded my Motorola to Android 6.0 Cannot setup a VPN to my Vigor anymore. Found a lot of older entries about Android using not RFC. Stupid. Strange I need to Update a File. Question Do you need to root the device to see/update  this ipsec.conf ?
