### ISSUE TITLE
failed to run on amazon 

### ISSUE THREAD

**Issue by andreagrax** [jlund/streisand#232]
maybe a silly question 

freshly cloned streisand ,on ubuntu 14.04
 launched 
ansible-playbook -vvvvvv  playbooks/amazon.yml 

aws credential working correctly , but it stops without creating the instance 

```
TASK [genesis-amazon : include] ************************************************
task path: /home/andrea/_ansible/ansible_data/external_playbooks/streisand_vanilla/playbooks/roles/genesis-amazon/tasks/main.yml:23
included: /home/andrea/_ansible/ansible_data/external_playbooks/streisand_vanilla/playbooks/roles/genesis-amazon/tasks/determine-ami-id.yml for 127.0.0.1

PLAY [Configure the Server and install required software] **********************
skipping: no hosts matched

PLAY [Open all service ports] **************************************************

TASK [Set the streisand_host fact to the value of the new server. This fact will be used to retrieve the obfsproxy port values.] ***
task path: /home/andrea/_ansible/ansible_data/external_playbooks/streisand_vanilla/playbooks/amazon.yml:134
fatal: [127.0.0.1]: FAILED! => {"failed": true, "msg": "'dict object' has no attribute 'streisand-host'"}

NO MORE HOSTS LEFT *************************************************************

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=12   changed=5    unreachable=0    failed=1   
```
`

any clue? 
I'm missing something?

**Comment by jlund** [comment]
Did you get prompted for the variables? I can only replicate this if some of the required fields are missing--specifically the region. What version of Ansible are you using?

**Comment by andreagrax** [comment]
yes , i was prompted for the variables .
i choosed 
  5. EU               (Germany)

ansible is 2.1.0


`ansible 2.1.0 (devel 2b02e8e2b4) last updated 2016/01/25 14:42:31 (GMT +200)
  lib/ansible/modules/core: (detached HEAD 09e2457eb0) last updated 2016/01/25 14:42:59 (GMT +200)
  lib/ansible/modules/extras: (detached HEAD e8427cb32a) last updated 2016/01/25 14:42:40 (GMT +200)
  config file = 
  configured module search path = Default w/o overrides
`

**Comment by andreagrax** [comment]
also tried on different regions 

- eu ireland
- singapore

same error on all

**Comment by jlund** [comment]
I still can't replicate this. What version of boto do you have installed?

**Comment by andreagrax** [comment]
`boto-2.38.0`

**Comment by df-sh** [comment]
Are you invoking the streisand script or are you running it on already created server?

I dont understand what this line means
ansible-playbook -vvvvvv playbooks/amazon.yml

but the streisand-host is defined in one of two places
1.  If deploying on an existing server, in the inventory file (by uncommenting -[streisand-host] and uncommening the 255.255.255.255 and replacing it with your target server IP

2.  If creating a new server, in the genesis playbook of whatever provider you selected.

Just out of curiosity, what name do you choose for server when setting up?  I found some wonky issues similar to this popping up when using umlauts numbers or spaces in the server name for some reason...

**Comment by andreagrax** [comment]
i am running the playbook from my laptop , launching directly the amazon playbook instead of the streisand script which later will do the same.
i have used the default server name , streisand

**Comment by jlund** [comment]
It's a longshot, but can you try running with the latest stable release of Ansible instead of the devel branch? You should just be able to check out the tag.

**Comment by df-sh** [comment]
Is that a complete log of the streisand output?


Using ansible 2.0.0.2 boto 2.38 on a 
this is relevant log from a new amazon server (using a gnome ubuntu vm from osboxes.org)

`
TASK [genesis-amazon : include] ************************************************
included: /home/osboxes/streisand/playbooks/roles/genesis-amazon/tasks/determine-ami-id.yml for 127.0.0.1

TASK [genesis-amazon : Use the AMI ID for Northern Virginia when the region is us-east-1] ***
ok: [127.0.0.1]

TASK [genesis-amazon : Create the EC2 instance] ********************************
changed: [127.0.0.1 -> localhost]

TASK [genesis-amazon : Wait until the server has finished booting and OpenSSH is accepting connections] ***
ok: [127.0.0.1]

TASK [genesis-amazon : Create the in-memory inventory group] *******************
changed: [127.0.0.1]

TASK [genesis-amazon : Set the streisand_ipv4_address variable] ****************
ok: [127.0.0.1]

TASK [genesis-amazon : Set the streisand_server_name variable] *****************
ok: [127.0.0.1]

PLAY [Configure the Server and install required software] **********************

TASK [setup] *******************************************************************
ok: [My,new.IP.address]
`

Can you check amazon.yml starting from line 76 till end of file and post here?

**Comment by andreagrax** [comment]
switched to 
`ansible 2.0.0.2 (v2.0.0.2-1 7de237c5a1) last updated 2016/02/19 14:27:30 (GMT +200)`
now it create the correctly the vm.
it throws one error later but i will investigare it further.

**Comment by jlund** [comment]
Thanks for the update. I'm glad to hear that it's working now. It looks like this is a bug in the development branch of Ansible that should be fixed before the final release.
