### ISSUE TITLE
UNREACHABLE on digital ocean

### ISSUE THREAD

**Issue by pcragone** [jlund/streisand#237]
Having some trouble getting this set up with DigitalOcean as my provider.  Continually fails here:

```
TASK [setup] *******************************************************************
fatal: [xxx.xxx.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "ERROR! SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=8    changed=4    unreachable=0    failed=0
xxx.xxx.xxx.xxx              : ok=0    changed=0    unreachable=1    failed=0
```

It's worth pointing out that I can, in fact, ssh into the server in question using the key I instructed streisand to use.

**Comment by git-sgmoore** [comment]
I'm getting the same error in every datacenter.

**Comment by jlund** [comment]
I'm looking into this now. Probably a minor API change.

**Comment by jlund** [comment]
It appears as though DigitalOcean servers now sometimes take a long time to actually start accepting connections even after the OpenSSH daemon has started. In my testing, this happened 7 out of 20 times.

Ansible's default SSH connection timeout is 10 seconds. I have increased this to 100 seconds, and I can no longer duplicate the issue at all. Thanks for the bug report!

**Comment by pcragone** [comment]
Unfortunately, this did not fix the issue for me.  Still having the same error, still able to actually ssh into the server.

**Comment by jlund** [comment]
What type of key are you using? Standard RSA?

**Comment by jlund** [comment]
@pcragone Can you try it again now? Hopefully that fixes it.

**Comment by pcragone** [comment]
Nope =(

**Comment by jlund** [comment]
What operating system and Ansible version are you using?

**Comment by pcragone** [comment]
```
$ uname -a
Darwin eiger 15.3.0 Darwin Kernel Version 15.3.0: Thu Dec 10 18:40:58 PST 2015; root:xnu-3248.30.4~1/RELEASE_X86_64 x86_64
```
```
$ ansible --version
ansible 2.0.0.2
  config file = /Users/pragone/Dropbox/projects/streisand/ansible.cfg
  configured module search path = ./library:/usr/share/ansible
```

**Comment by jlund** [comment]
Thanks. Are you using the standard SSH client that ships with OS X, or have you installed a different version via Homebrew?

**Comment by pcragone** [comment]
Standard SSH

```
$ which ssh
/usr/bin/ssh
$ ssh -V
OpenSSH_6.9p1, LibreSSL 2.1.8
```

**Comment by git-sgmoore** [comment]
I was having this problem yesterday, but was able to spin up 3 different servers in three different Digital Ocean datacenters without a problem today. It did take the extra 90 seconds or so.

Thank you for the invaluable service you provide the public.

**Comment by pcragone** [comment]
Any thoughts on how we can increase the logging in order to dig into this a bit more? I'm not at all familiar with ansible; I've been trying to dive into it, but my schedule is quite busy.

**Comment by pcragone** [comment]
I added '-vvvv' to the ansible-playbook command in ./streisand, and this was one of the logs:
```
<192.81.214.186> SSH: EXEC ssh -C -vvv -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=100 -o ControlPath=/Users/pragone/.ansible/cp/ansible-ssh-%h-%p-%r 192.81.214.186 'LANG=en_US.UTF-8 LC_ALL=en_US.UTF-8 LC_MESSAGES=en_US.UTF-8 /usr/bin/python'
```

I'm not sure if the SSH key is being set elsewhere, but there's no key being specified in this command.

Not sure if that helps or not. I'll keep poking around.

**Comment by pcragone** [comment]
Ok so looks like this is my fault for not completely understanding the directions.  Moving around my ssh keys so the keys for digital ocean are labeled "id_rsa" & "id_rsa.pub" locally got it to work.  The way I read the instructions initially seemed to me that I was giving streisand the name of the ssh key on my machine to use; I did not realize it was going to use id_rsa/id_rsa.pub automatically.

Not sure if we should just close it out here, or if it's worthwhile to output some sort of clearer error message that would help pinpoint the ssh key being the problem.

**Comment by jlund** [comment]
I appreciate your help in troubleshooting the issue, and I can see why it was confusing. I have updated the setup text to make this step more clear. I'm really glad that it's working for you now!
