### ISSUE TITLE
dnsmasq throwing "fail" error at boot but seems to be running

### ISSUE THREAD

**Issue by kennyluk** [jlund/streisand#238]
dnsmasq throwing "fail" error at boot time, see below

![screen shot 2016-02-02 at 14 46 54](https://cloud.githubusercontent.com/assets/8308109/12742223/bfeeb64e-c9be-11e5-93c8-f3efbb02faa9.png)

but a netstat shows that it is running

![screen shot 2016-02-02 at 15 06 36](https://cloud.githubusercontent.com/assets/8308109/12742208/9aa730f0-c9be-11e5-9f2c-3edb7fc1d3d2.png)

**Comment by jlund** [comment]
What's happening here is that the dnsmasq configuration [tells it to bind to the 10.8.0.1 interface that OpenVPN creates](https://github.com/jlund/streisand/blob/master/playbooks/roles/openvpn/templates/etc_dnsmasq.conf.j2#L99), but OpenVPN hasn't started yet so it can't do that. The solution is to tell dnsmasq to try starting again later in the cycle, [which happens here](https://github.com/jlund/streisand/blob/master/playbooks/roles/rc-local/templates/rc.local.j2#L23).

There are almost certainly more elegant ways to do this, but I'll probably save them for Ubuntu 16.04 and systemd.
