### ISSUE TITLE
Support GreenQloud hosting

### ISSUE THREAD

**Issue by pallih** [jlund/streisand#24]
The AWS 'clone' GreenQloud is a reasonable hosting company in Iceland:
https://www.greenqloud.com/

They support boto:
https://github.com/greenqloud/api-examples

and even run a tor node:
http://torstatus.blutmagie.de/cgi-bin/whois.pl?ip=46.149.18.10

**Comment by peterpacz1** [comment]
You might want to also look at support for vultr.com - another up and coming digitalocean 'clone' that's offering servers in multiple cities.

**Comment by cpu** [comment]
At this point I don't believe we have the resources to maintain any additional providers. I would encourage you to use the localhost provisioning or existing server provisioning support that was recently added. These should work with most providers capable of giving you a Ubuntu 16.04 instance with a network interface that has a public IPv4 address. Thanks!
