### ISSUE TITLE
Tunnelblick updated

### ISSUE THREAD

**Issue by kennyluk** [jlund/streisand#241]
New version of Tunnelblick was released on Feb 1, 2016. Streisand install is now stalling on mirroring the OSX client.

See https://tunnelblick.net/downloads.html

**Comment by jlund** [comment]
Variables updated. Thanks for the bug report!

**Comment by kennyluk** [comment]
I would provide a patch myself, but more a desktop user than a developer and afraid of not doing this right. I will be going to a country with high censorship soon for two weeks, will be deploying some more copies of streisand as backup and will report any new issues.

**Comment by jlund** [comment]
No problem. I appreciate the feedback. I hope that it works well for you.

**Comment by df-sh** [comment]
tunnelblick osx updated again to 	Tunnelblick 3.5.7 (build 4270.4517)

playbooks/roles/streisand-mirror/vars/openvpn.yml 

42	# OS X
43	tunnelblick_version: "3.5.7"
44	tunnelblick_build: "4270.4517"

fixes the current problem, though I feel there should be a better way than manually updating the version numbers every update...

**Comment by jlund** [comment]
Unfortunately, the Tunnelblick project doesn't sign their releases. If they did, we could do the same thing that happens with Tor and Stunnel where the latest version number is automatically detected and mirrored. The Tunnelblick checksum has to be manually updated. Errors can be handled more gracefully though, for sure.
