### ISSUE TITLE
Unable to login to newly created server

### ISSUE THREAD

**Issue by git-sgmoore** [jlund/streisand#245]
I am unable to login to the server that the script created on Digital Ocean. I'm trying to use the same SSH key which was used to create the streisand server, but it is not working. I understand there is a gateway, but I want to login into the server proper to look around. I'm positive the password I'm entering is correct.

`Permission denied (publickey). NaCl plugin exited with status code 255.`

I'm also unable to use `Console Access` in Digital Ocean to login to the server because it is asking me for a login and password, and I do not know what it is.

**Comment by kennyluk** [comment]
Try logging into your Droplet on DO using the console. See here:

https://www.digitalocean.com/community/tutorials/how-to-use-the-digitalocean-console-to-access-your-droplet

Then make sure your ssh public keys are in the ~root/.ssh/authorized_keys file and that the file is chmod 600.

**Comment by jlund** [comment]
You should just be able to run `ssh root@<ip-address>`. That's also how Ansible connects.
