### ISSUE TITLE
What setting to change to use my own DNS servers?

### ISSUE THREAD

**Issue by git-sgmoore** [jlund/streisand#246]
I see that when I use OpenVPN and L2TP it uses Google's DNS servers. I have my own that I would I like to use. I've tried adjusting a couple of config files with no luck.

Is there one setting or config file I can change to use my own DNS servers?

**Comment by jlund** [comment]
Yup, you can change the defaults by modifying the `upstream_dns_servers` variable in the `playbooks/group_vars/all` file.
