### ISSUE TITLE
How do you change upstream DNS server on installed vpn server?

### ISSUE THREAD

**Issue by git-sgmoore** [jlund/streisand#248]
How do you change the upstream dns server used for openvpn and l2tp on a server where this script has already ran?

**Comment by jlund** [comment]
## L2TP/IPsec
1. Edit `/etc/ppp/options.xl2tpd`.
1. Modify the `ms-dns` lines to point to the IP addresses of your desired DNS server.
1. Restart the ipsec and xl2tpd services:
   * `service ipsec restart`
   * `service xl2tpd restart`

## OpenVPN
1. Edit `/etc/dnsmasq.conf`.
1. Modify the `server=` lines to point to the IP addresses of your desired DNS server.
1. Restart dnsmasq:
   * `service dnsmasq restart`
