### ISSUE TITLE
known_hosts prompt

### ISSUE THREAD

**Issue by pejvan** [jlund/streisand#249]
During the installation, the script prompts the user about whether or not the host should be added in the "known_hosts" file, which blocks or even breaks the deploy:
 
> PLAY [Configure the Server and install required software] **********************
> 
> TASK [setup] *******************************************************************
> The authenticity of host '46.101.85.207 (46.101.85.207)' can't be established.
> ECDSA key fingerprint is SHA256:plcwFwBvUSwb2uKAud34I4AucLgPQx7zB5MDZAr9Tjg.
> Are you sure you want to continue connecting (yes/no)? yes

The [know_hosts](http://docs.ansible.com/ansible/known_hosts_module.html) module should be able to resolve this issue.

**Comment by jlund** [comment]
Were you running the playbook against an existing server? This doesn't happen by default.

If you changed `host_key_checking` to True in the ansible.cfg file, then this is working as designed. You confirm the key, and the execution continues.

I might be misunderstanding what you mean though.

**Comment by pejvan** [comment]
It happened several times against both existing servers I had never SSHed into, and against new ones.
I havent touched the config files. 
I'll try to review your playbooks and see if I find anything, but the fact that it happened several times leads me to believe that it was not a one-off glitch.

**Comment by jlund** [comment]
I don't think it's a glitch either, but something about your environment is overriding the `host_key_checking` value. This could be a separate Ansible config file in your home directory or in `/etc/ansible`. I'm not sure, but I have verified on multiple platforms and multiple computers that the behavior you are describing is not happening by default. 

Having said that, I'm still probably going to refactor things to use the module that you mentioned. That module didn't exist at the time I started on this project, and it's a good recommendation.

**Comment by pejvan** [comment]
Hi Joshua,

You're right, I found out that the issue was coming from the git extensions
of my shell and not the Ansible set up script.

Thanks for integrating my suggestion, I'll have a couple more suggestions
to make in the coming days, hope you'll find them useful as well.

Pejvan

**Comment by jlund** [comment]
It turns out that there's a little bit of a chicken/egg problem. The `known_hosts` Ansible module requires you to specify the public host key; there's no way to tell it to trust-on-first-use. We could use `ssh-keyscan` and add each of the lines that it returns, but this feels like it could be somewhat fragile--I'm not sure if `ssh-keyscan` is even installed by default on OS X, for instance. Are you on OS X?

I'm going to keep things the way that they are for now, but I'm looking forward to your other suggestions! I appreciate the help.
