### ISSUE TITLE
How to block ads? Ignoring hosts file?

### ISSUE THREAD

**Issue by git-sgmoore** [jlund/streisand#250]
The end result of this setup seems like it ignores the hosts file where I have added 34,826 entries to block domains. They still seem to be getting through. Is there a way to enable the adblocking without breaking anything? Maybe stopping dnsmasq or something?

**Comment by andreagrax** [comment]
from the  etc_dnsmasq.conf.j2  it seems that it must read the hosts file (as per default in dnsmasq).

but yes , you usually have to  reload the dnsmasq service to re-read the hosts file

**Comment by git-sgmoore** [comment]
Thank you for the response, but after reloading and restarting everything, it doesn't appear to be working. Below is the top portion of my `/etc/hosts` file.

> #Your system has configured 'manage_etc_hosts' as True.
> #As a result, if you wish for changes to this file to persist
> #then you will need to either
> #a.) make changes to the master file in /etc/cloud/templates/hosts.tmpl
> #b.) change or remove the value of 'manage_etc_hosts' in
> #/etc/cloud/cloud.cfg or cloud-config from user-data
>127.0.1.1 a a
>127.0.0.1 localhost
> 
> #The following lines are desirable for IPv6 capable hosts
> ::1 ip6-localhost ip6-loopback
> fe00::0 ip6-localnet
> ff00::0 ip6-mcastprefix
> ff02::1 ip6-allnodes
> ff02::2 ip6-allrouters
> ff02::3 ip6-allhosts
> 
> #MalwareDomainList.com Hosts List           #
> #http://www.malwaredomainlist.com/hostslist/hosts.txt   #
> #Last updated: Thu, 04 Feb 16 14:20:35 +0000      #
> 
> 0.0.0.0 0koryu0.easter.ne.jp
> 0.0.0.0 1-atraffickim.tf
> 0.0.0.0 10-trafficimj.tf
> 0.0.0.0 109-204-26-16.netconnexion.managedbroadband.co.uk
> 0.0.0.0 11-atraasikim.tf
> 0.0.0.0 11.lamarianella.info
> etc....

I can still successfully visit these domains and view various ads while on the VPN after this.

**Comment by andreagrax** [comment]
could you attach the output of  ?

 ` grep dnsmasq /var/log/syslog`

**Comment by jlund** [comment]
Comment out the `no-resolv` line in the dnsmasq configuration and restart the daemon.

Just out of curiosity, why not use uBlock Origin or other client-side filtering?

**Comment by git-sgmoore** [comment]
That did the trick. I do use uBlock Origin and uMatrix on browsers that support it. I'm using this VPN network wide which is also being used on mobile devices that lack the capability.

**Comment by jlund** [comment]
Ah, that makes sense. Glad that this is working for you now!
