### ISSUE TITLE
Documentation: iOS Cisco Anyconnect

### ISSUE THREAD

**Issue by kennyluk** [jlund/streisand#257]
Step 14:

Tap Import in the top-right corner.

On my iOS Cisco AnyConnect the word "Continue" is at the top-right corner at this point.

**Comment by df-sh** [comment]
Just tried with anyconnect 4.0.03016 on ipad 9.0.2 and it says Import like described.

Will check iphone later, what version of anyconnect are you using?

**Comment by kennyluk** [comment]
4.0.03016

![6742596143547110_3561929539036231547](https://cloud.githubusercontent.com/assets/8308109/13194904/3eb22f80-d7dc-11e5-9c81-eed4308eadbf.jpg)

![6742596143547109_5085611179073986779](https://cloud.githubusercontent.com/assets/8308109/13194905/4454d050-d7dc-11e5-84f4-b8e055c51e37.jpg)

**Comment by jlund** [comment]
Thanks for the screenshots! That's really helpful.

AnyConnect won't let you trust a certificate if both of those reasons (mismatched CN and untrusted source) are true. Mismatched CN shouldn't be true though unless you configured the connection with something other than the IP address (like a hostname, for instance). When it's just untrusted source, you'll see the import option.

For what it's worth, 4.0.03016 is also what I was using on my phone when I wrote the documentation.

**Comment by kennyluk** [comment]
That makes sense, the CN is matched due to a testing configuration here.
