### ISSUE TITLE
Enable certificate-based authentication for OpenConnect/AnyConnect

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#263]
The situation for iOS users running Cisco AnyConnect is pretty rough with password-based authentication:

* Connections take a long time to be established, and the user is required to repeatedly tap the screen as they traverse through multiple dialog boxes.
* The password cannot be saved; it must be copy/pasted or entered by hand every single time the VPN disconnects. This is incredibly tedious.
* "Connect On Demand" and other advanced functionality is unavailable.

Certificates will fix all of these problems and provide a nice option on other platforms as well.

Let's get certificate-based authentication set up on new servers!

**Comment by kydan** [comment]
Excellent! I'll spin a new one this afternoon. Do we have a solution for a
Windows client? I'm trying to get my hands on a copy of the Cisco client
but haven't been able to as of yet.

sent from my mobile
2016年2月25日 10:23，"Joshua Lund" <notifications@github.com>写道：

**Comment by jlund** [comment]
Cool! I'm excited to hear how it works for you.

Although the official Cisco AnyConnect client works better, there's an open source client for Windows. It's a bit rough around the edges, but it is functional. Documentation gets generated for it, and the client setup executable is also mirrored too.
