### ISSUE TITLE
Issues with streisand and DO

### ISSUE THREAD

**Issue by dylanypyen** [jlund/streisand#267]
S T R E I S A N D  

Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: 2

What region should the server be located in?
  1.  Amsterdam        (Datacenter 2)
  2.  Amsterdam        (Datacenter 3)
  3.  Frankfurt
  4.  London
  5.  New York         (Datacenter 1)
  6.  New York         (Datacenter 2)
  7.  New York         (Datacenter 3)
  8.  San Francisco
  9.  Singapore
  10. Toronto
Please choose the number of your region. Press enter for default (#2) region.
 [2]: 9

What should the server be named? Press enter for default (streisand).
 [streisand]: 

New API access tokens can be generated in the DigitalOcean control panel. When generating a new token, please note that the Write Scope is necessary in order to create Droplets.
https://cloud.digitalocean.com/settings/applications

What is your DigitalOcean Access Token?
<REDACTED>

If you haven't done so already, you must add your SSH public key (e.g. id_rsa.pub) in the DigitalOcean control panel:
https://cloud.digitalocean.com/settings/security

What is the name assigned to the SSH key in the DigitalOcean control panel that you would like to use?
 [streisand]: striesand

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the DigitalOcean Server] ***************************************

TASK [setup] *******************************************************************
ok: [127.0.0.1]

TASK [genesis-digitalocean : Retrieve the SSH key ID using the name that was provided] ***
changed: [127.0.0.1]

TASK [genesis-digitalocean : Create the server. If this task fails with an "invalid region" error, then DigitalOcean is temporarily not allowing new 512MB Droplets to be provisioned in the selected region. You can either try the same region again later, or choose a different location.] ***
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "curl -s -X POST -H 'Content-Type: application/json' -H 'Authorization: Bearer <REDACTED>' -d '{'private_networking': None, 'backups': False, 'ssh_keys': [1720900], 'name': 'streisand', 'ipv6': False, 'user_data': None, 'region': 'sgp1', 'image': 'ubuntu-14-04-x64', 'size': '512mb'}' \"https://api.digitalocean.com/v2/droplets\" | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print j[\"droplet\"][\"id\"]'", "delta": "0:00:00.310862", "end": "2016-03-01 14:31:43.663767", "failed": true, "rc": 1, "start": "2016-03-01 14:31:43.352905", "stderr": "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nKeyError: 'droplet'", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=2    changed=1    unreachable=0    failed=1 

my SSD pub key is on DO, is there any way to set up streisand without a pub key? (eg user/password login)

I am a linux/VPS n00b.

Thanks.

**Comment by df-sh** [comment]
On the machine you are entering these commands, you created an SSH Key.  You uploaded this SSH Key to Digital Ocean.  You then properly entered the name of the ssh key when requested (as it was listed on the digital ocean page) and you still received this error?

**Comment by dylanypyen** [comment]
Yes, I typed in the name of the ssh keys, and I still received this error. I am not sure what is going on or how I can fix this :/

**Comment by df-sh** [comment]
This is a digital ocean problem not streisand with regards to passing and naming the ssh key

https://www.digitalocean.com/community/tutorials/how-to-configure-ssh-key-based-authentication-on-a-linux-server

As I don't have experience with digital ocean, reading that page suggests you should look at ~/.ssh/authorized_keys on your digital ocean server for the key to use

You may want to look search for "How To Copy a Public Key to your Server" on that page for a bit more info.  Sorry I can't help more than that :(

**Comment by dylanypyen** [comment]
Thanks so much for taking the time to help :). I’ll do what I can, but it’s not much. :?\/

**Comment by dylanypyen** [comment]
Just another question (sorry)
Is there any way that streisand can be directly installed on the host machine?
Thanks.
Dylan.

**Comment by df-sh** [comment]
From the mainpage:

**Comment by jlund** [comment]
@dylanypyen Thanks for the bug report! These tasks worked just fine on Ansible version 2.0.0.2, but broke due to some changes in the latest stable release of Ansible (2.0.1.0).

I just pushed a commit that updates how DigitalOcean droplets are created. You should be able to do the following:

1. Run `git pull` wherever you checked out this repository to get the latest commit.
1. Run `sudo pip install dopy` to install the DigitalOcean Python module.
1. Run Streisand as normal.

Everything should work this time. Let me know how it goes!

**Comment by jlund** [comment]
You'll want to install `dopy` version 0.3.5 (`sudo pip install dopy==0.3.5`) if you're on a Mac. Version 0.3.7 is currently broken on OS X.

**Comment by dylanypyen** [comment]
sorry, dopy 0.3.5 didn't help :/
fatal: [127.0.0.1]: FAILED! => {"changed": true, "cmd": "curl -s -X GET -H 'Content-Type: application/json' -H 'Authorization: Bearer xxx' \"https://api.digitalocean.com/v2/account/keys\" | python -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [key for key in j[\"ssh_keys\"] if key[\"name\"]==\"streisand\"][0][\"id\"]'", "delta": "0:00:01.105577", "end": "2016-03-03 09:32:01.373190", "failed": true, "rc": 1, "start": "2016-03-03 09:32:00.267613", "stderr": "Traceback (most recent call last):\n  File \"<string>\", line 1, in <module>\nIndexError: list index out of range", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT *************************************************************
	to retry, use: --limit @playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=1    changed=0    unreachable=0    failed=1

**Comment by dylanypyen** [comment]
Could you please also put in the document that you must uninstall dopy before installing the old version?
(`sudo pip2 uninstall dopy; sudo pip2 install dopy==0.3.5`)

**Comment by dylanypyen** [comment]
well, I installed dopy 0.3.5 but stil getting this error:
TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't already exist] ***
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "You do not have access for the attempted action."}

```
TASK [genesis-digitalocean : fail] *********************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "failed": true, "msg": "The SSH key either already exists under a different name, or the dopy Python module is not installed. Use `pip install dopy==0.3.5` to install this module. On the latest version of OS X, dopy > 0.3.5 is currently broken."}
```

**Comment by jlund** [comment]
Installing that specific version should automatically remove any new versions. It does in my testing, at least. Looks like we're getting close!

The "You do not have access for the attempted action" error appears if you use an API token that does not have the "Write" Scope enabled. You can either edit the existing token in the DigitalOcean Control Panel to enable the Write Scope, or generate a new token.

The Write Scope checkbox is checked by default when you create a new API token.

**Comment by dylanypyen** [comment]
Hi,

Looks like installing it went well.
However, the installer didn't finish all the way :/

TASK [setup] *******************************************************************
fatal: [128.199.207.246]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
	to retry, use: --limit @playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=9    changed=3    unreachable=0    failed=0   
128.199.207.246            : ok=0    changed=0    unreachable=1    failed=0   

ON ANOTHER NOTE: are there currently any operating public streisand that I can borrow for a bit, as I am heading into a country where the internet is heavily censored (China)? If there are could you please direct me to them, as I can't get my own set up at this moment? Thanks a ton!

**Comment by jlund** [comment]
It looks like something is wrong with your machine's configuration that prevents you from connecting to the new server over SSH using the key that you specified. That's not a Streisand issue, and it's going to be difficult to troubleshoot. This is inspiring me to work on the option to run Streisand on the server itself to make it easier for people who are just starting out.

I would be happy to help you get something going.

You can add my SSH public key to a new server:

```
ssh-rsa AAAAB3NzaC1yc2EAAAABIwAAAQEA6pzj4ImFFRNDWFG58QANrBwCpF+twlAnGpIlhT3BQYJ1CcQCmfHhrg3GWSr1lfaNfmXtgZ0nzlW+tngXU71RDwW41KJGmhVff6Tz2Z6berum6Zc7bb7z7w9CgNUrs15ydqdIfT50IfsQ7FFElTHUj01rgumDD2BIlqjNgC/iciSCrX20kAWEXuPDoXnSj/lZ6b1xFhsxqJiQi+0JXlQ+rg7Uqh8fQkpOmMdJqb7jA5LoShs2zehPbhmIqrbMB8h6vkT1qTlVFxg3B9ZB1tGobS07mO+z4VMEDC+wYFb7Ersg/vKIw8ukliSke9IC+Myo4ulnknFovl8Jxl4ONfbZYQ==
```

Then just email me the IP so I can run the playbook against it. My address is josh@joshlund.com.
