### ISSUE TITLE
[Suggestion] Mirroring 'SSLDroid' and 'OpenVPN for Android' apk files

### ISSUE THREAD

**Issue by denoza** [jlund/streisand#268]
Hi,

In countries where Google Play Store is blocked, it could be pretty difficult to obtain apps like 'SSLDroid' and 'OpenVPN for Android' esp. under tightly restricting conditions. I think it will be a good idea to mirror them on the streisand host server upon setup. Just a suggestion for the sake of further betterment.

**Comment by jlund** [comment]
I do that for Shadowsocks, but that project makes it easy by putting their APK on GitHub. I will have to see if some similarly official sources are available for these packages.

**Comment by denoza** [comment]
I searched and found out that both of these projects are hosted on github and are under GPL. In fact 'OpenVPN for Android' apk files are also hosted on a separate server other than Google Play, I have mentioned the urls for your reference as under.

OpenVPN for Android:
https://github.com/schwabe/ics-openvpn
http://plai.de/android/

SSLDroid:
https://github.com/blint/SSLDroid

**Comment by dimzon** [comment]
Nice idea. How about to host OpenVPN, Shadowsocks etc clients for all platforms?

**Comment by cpu** [comment]
Pull requests welcome.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/15
