### ISSUE TITLE
Requirements for the server to run streisand?

### ISSUE THREAD

**Issue by ovizii** [jlund/streisand#270]
I haven't seen any minimum requirements listed so I guess i.e. the smallest instance of a DigitalOcean droplet with 512MB RAM will be enough for a basic installation?

Do you have any figures i.e. what amount of RAM is needed for what amount of users? I know this probably depends on the type of connection used but a rough ballpark figure would suffice.

**Comment by denoza** [comment]
I have used DigitalOcean's 512 MB as well as Vultr's 768 MB instances. I haven't had any performance related issues. However, I haven't used a lot of simultaneous connections since I have used 'Streisand' inside my family circle.

**Comment by ovizii** [comment]
Thanks!
