### ISSUE TITLE
error at "TASK [openconnect : Enable NAT]"

### ISSUE THREAD

**Issue by nowherecat** [jlund/streisand#271]
I am running into the following error and am not sure how to troubleshoot it:

```
TASK [openconnect : Enable NAT] ************************************************
fatal: [195.154.104.74]: FAILED! => {"changed": false, "cmd": "iptables -t nat -A POSTROUTING -j MASQUERADE", "failed": true, "msg": "[Errno 2] No such file or directory", "rc": 2}
```

server is a dedicated root running ubuntu 14.04, insatlled via debootstrap

**Comment by jlund** [comment]
It looks like the server doesn't have iptables installed. Can you install that and try running the playbook again?

I thought that package was included by default 100% of the time, but I can add it to the list of common packages if this resolves the issue for you.

**Comment by nowherecat** [comment]
Ha! That did the trick, apparently iptables was not included by default...

Thanks for the quick hint

**Comment by jlund** [comment]
Good to hear! This is included in the list of common packages now. Thanks for the report.
