### ISSUE TITLE
EC2 instance size

### ISSUE THREAD

**Issue by crushspread** [jlund/streisand#273]
Hi, 
Is it possible to change which EC2 instance size it setup? Currently it runs a Micro instance but I'm wondering if there could be an option to setup a Nano instance since it's cheaper.

It's possible to resize the instance down to Nano but this re-assigns the IP address and all the documentation then is using the old IP.

Thanks

**Comment by jlund** [comment]
Yeah, the default instance type that gets created is determined by the `aws_instance_type` variable in the `playbooks/roles/genesis-amazon/defaults/main.yml` file. If you change that variable to `t2.nano`, that is what Streisand will create.

Let me know how the Nano instance works out for you. I'm not opposed to making that the new default as long as the performance is good enough.

**Comment by fortinj1354** [comment]
Any word on how this worked for you @crushspread ? I'm considering doing the same as long as performance is suitable.

**Comment by crushspread** [comment]
@fortinj1354 worked fine for me. I didn't have many devices using it, but worked fine

**Comment by bpinto** [comment]
@jlund what do you think about using nano instead of micro by default?
