### ISSUE TITLE
Openconnect/Anyconnect connects but can't receive data. 

### ISSUE THREAD

**Issue by dylanypyen** [jlund/streisand#274]
The openconnect/anyconnect clients on all platforms won't connect on a DigitalOcean droplet. I have tried restarting the server, but to no avail.

Please advise.

**Comment by jlund** [comment]
Did you figure out what the issue was?

**Comment by dylanypyen** [comment]
Not sure, but I tried restarting the openconnect daemon and checked all the ports, and it seemed as if after the connection was established, openconnect would drop all incoming packets. I created another droplet using the streisand playbook and it works again (for the time being).

**Comment by kydan** [comment]
I believe I am also seeing this, at least with the windows client. Things work for about 2-3 minutes and then drop off. I once was able to do a quick IP test showed a china IP, despite supposedly being connected. I've not been able to recreate this however as of yet. I'll also be testing with my phone tonight and provide more info if I can provide proper steps for reproducing.

**Comment by jlund** [comment]
I'm fairly certain that this is a client issue, not a server issue. The Windows OpenConnect client has not been updated for a while. Things work flawlessly when using the official Cisco AnyConnect client, but that can be challenging to find in the absence of a valid Cisco license.

I have been using OpenConnect on my Linux laptop as my primary VPN connection and haven't noticed any issues at all. The server daemon is still functioning properly after several weeks of uptime, and I can stay connected for hours at a time without any problems.

There's a new version of the server that was just released, and I'm going to switch to that tonight. I will also see if I can find out why the Windows open source implementation seems to have stalled.

**Comment by kydan** [comment]
I tend to agree. I'm on the search for the official client. I am currently
running things on my phone right now and its pretty stable. After about 5
false starts, the windows client seems to be pretty stable as well. On a
separate note, I noticed that osx does have a client in homebrew. @jlund
are you aware of any gui client for osx? Also, should we consider using
something like gitter/slack/irc for many of the support ticket-esque issues
that have been coming through lately?

Nick

**Comment by denoza** [comment]
I have also used openconnect on my linux mint desktop as well as ios and android devices, and I have not faced any problems with it lately.

**Comment by ldbster** [comment]
DO and openconnect not working for me either. Have tried from Android and the brew command line on OSX, which fails as below: 
```
Attempting to connect to server xxx.xxx.xxx.xxx:4443
Failed to connect to host xxx.xxx.xxx.xxx
Failed to open HTTPS connection to xxx.xxx.xxx.xxx
Failed to obtain WebVPN cookie
```

**Comment by unstatusthequo** [comment]
Having exact same issue. OSX .sh script fails with: 
Attempting to connect to server xxx.xxx.xxx.xxx:4443
Failed to connect to host xxx.xxx.xxx.xxx
Failed to open HTTPS connection to xxx.xxx.xxx.xxx
Failed to obtain WebVPN cookie

iPhone won't connect either. Removed app, removed cert, reinstalled all. Happened on two installs of Streisand so far.

**Comment by cpu** [comment]
I believe this issue is too stale to be actionable. If using the latest code from master & an up to date OpenConnect client still presents this problem please open a new issue providing the information requested by the issue template. Thanks!
