### ISSUE TITLE
How do I view the HTML file with connection instructions?

### ISSUE THREAD

**Issue by aypez** [jlund/streisand#276]
Hi,

I was able to set up everything fine and follow your instructions. However, I am having trouble using the html file that was generated with the instructions. 

I can use nano or cat to view the html file, but it appears to have some certificates embedded. I am not sure how to extract these to use on my machine. 

Is there an easy way to download the html file to my local machine? 

I am using a VPS with DigitalOcean.

Thanks! 

Apologies if this is a dumb question, but I am not as tech savvy as I wish I was!

**Comment by aypez** [comment]
Never mind, I'm an idiot. 

I connected to my server with Filezilla, navigated to the html instructions file and downloaded from there.

**Comment by jlund** [comment]
No worries! For future reference, you can also open the Instructions HTML file in your web browser.

**Comment by amio** [comment]
Here's my solution:

```bash
# Set the http auth info
$ htpasswd -c /etc/nginx/htpasswd <username>

# Make nginx reload config
$ nginx -s reload
```

then login to https://example.com (your server, remember the `https`) with auth info created before, you have the html in browser.
