### ISSUE TITLE
OpenWRT Openconnect client setup

### ISSUE THREAD

**Issue by SummerStorm** [jlund/streisand#280]
[luci-proto-openconnect](https://github.com/openwrt/luci/tree/master/protocols/luci-proto-openconnect) provides a GUI for setting up a openconnect client connect on OpenWRT. I'm trying to figure out the right parameters for it.

For the [first page](http://i.imgur.com/dGXZUwQ.png), I'm not sure how to get the server's SHA1 hash and the the "AuthGroup".

For the [second page](http://i.imgur.com/LiZFYl0.png), I used openssl to convert my client.p12 file to the user certificate PEM and user private key PEM, but they're in the following format:

```
Bag Attributes
    localKeyID: XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX
    friendlyName: streisand-openconnect-XXX.XXX.XXX.XXX
subject=/OU=users/CN=XXX.XXX.XXX.XXX
issuer=/O=Streisand Effect Automated Signing, Inc./CN=Streisand
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
```

Do I include the whole PEM file or just the 

```
-----BEGIN CERTIFICATE-----
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
-----END CERTIFICATE-----
```

part?

**Comment by braian87b** [comment]
I didn't tried yet openconnect or shadowsocks (I will try both some day) if you want to use OpenVPN see this (I just posted it the step-by-step instructions tutorial):

https://github.com/jlund/streisand/issues/166#issuecomment-231841621

**Comment by cpu** [comment]
I believe this question has been answered so I'm going to close this issue. Thanks!

**Comment by dz0ny** [comment]
There are docs in https://github.com/openwrt/packages/tree/master/net/openconnect
For Googlers :)
AuthGroup is DEFAULT
SHA1 is sha1 of your server public key

**Comment by jacob210** [comment]
> [luci-proto-openconnect](https://github.com/openwrt/luci/tree/master/protocols/luci-proto-openconnect)提供了一个用于在OpenWRT上设置openconnect客户端连接的GUI。我正在尝试找出正确的参数。
> 
> 对于[第一页](http://i.imgur.com/dGXZUwQ.png)，我不确定如何获取服务器的SHA1哈希和“ AuthGroup”。
> 
> 对于[第二页](http://i.imgur.com/LiZFYl0.png)，我使用openssl将client.p12文件转换为用户证书PEM和用户私钥PEM，但是它们的格式如下：
> 
> ```
> Bag Attributes
>     localKeyID: XX XX XX XX XX XX XX XX XX XX XX XX XX XX XX
>     friendlyName: streisand-openconnect-XXX.XXX.XXX.XXX
> subject=/OU=users/CN=XXX.XXX.XXX.XXX
> issuer=/O=Streisand Effect Automated Signing, Inc./CN=Streisand
> -----BEGIN CERTIFICATE-----
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> -----END CERTIFICATE-----
> ```
> 
> 我要包含整个PEM文件还是仅包含
> 
> ```
> -----BEGIN CERTIFICATE-----
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
> -----END CERTIFICATE-----
> ```
> 
> 部分？

How did you solve this problem?

**Comment by zee-shany** [comment]
i couldn't still. 
hoping to get some guidelines.

**Comment by jacob210** [comment]
I have solved it. See my blog https://www.jianshu.com/p/bcbd16a0cdc9

**Comment by jacob210** [comment]
> i couldn't still.
> hoping to get some guidelines.

I have solved it. See my blog https://www.jianshu.com/p/bcbd16a0cdc9

**Comment by zee-shany** [comment]
> I have solved it. See my blog https://www.jianshu.com/p/bcbd16a0cdc9

hello,
Thanks for your guide link.

I'm using a striesand server on AWS ec2 instance, which has openconnect server installed.

i've tried to follow your steps but i don't see any traffic passing from OC-VPN interface.

I'm using streisand user and password

when i run below command it gives -ash:openssl: not found. But i installed `opkg install openvpn-openssl` already.

```
root@OpenWrt:~# openssl s_client -connect 157.x.x.x:x -showcer
ts 2>/dev/null </dev/null | awk '/-----BEGIN/,/-----END/ { print $0 }'
 | openssl x509 -noout -fingerprint -sha1 | sed 's/Fingerprint=//' | s
ed 's/://g'
-ash: openssl: not found
```
Please can you help me point what step i'm doing wrong?

Thanks in advance and appreciate your support.

**Comment by trochdewei** [comment]
@jacob210 your link returns 404 now
