### ISSUE TITLE
Restart OpenVPN fail

### ISSUE THREAD

**Issue by kataflok** [jlund/streisand#282]
Hi,

I'm installing Streisand on BudgetVM -- I've successfully done so a number of times on this provider -- except on this particular server.

I'm repeatedly getting the following error. Can anyone point me at a fix?

`TASK [openvpn : Copy OpenVPN configuration file into place] ********************
changed: [**.**._._*\* ]

TASK [openvpn : Restart OpenVPN so the 10.8.0.0 interface is available to dnsmasq] ***
fatal: [**.**._._*\* ]: FAILED! => {"changed": false, "failed": true, "msg": " \* Stopping virtual private network daemon(s)...\n \*   No VPN is running.\n \* Starting virtual private network daemon(s)...\n \*   Autostarting VPN 'server'\n"}

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [openconnect : Restart ocserv] *********************************

RUNNING HANDLER [l2tp-ipsec : Restart Libreswan] *******************************

RUNNING HANDLER [l2tp-ipsec : Restart xl2tpd] **********************************
    to retry, use: --limit @playbooks/streisand.retry

PLAY RECAP *********************************************************************
**.**._._*\*                : ok=95   changed=88   unreachable=0    failed=1  `

**Comment by CalHenze** [comment]
I just went through this with them -- the Playbook does work on Budget but you have to contact their CSRs and have them repair their template. They sent me the following response:

***************************************************************************************************************

Please note as per my original reply I reconfigured the Network Interface, unfortunately our Ubuntu template seems to create an incorrect configuration. i.e. I changed the subnet masks as listed in /etc/network/interfaces, this is why you were receiving the: NO MORE HOSTS LEFT and Unreachable Warnings you listed below. For some odd reason between the time I replied and Alex replied your SSH service had gone down as well so of course Alex restarted this. You may wish to additionally reboot your VPS to make sure after the reboot that your configuration stays in place.

***************************************************************************************************************
Don't give up on them -- for a budget company selling $35/yr servers, I'm getting some of the best speeds and lowest latency I've seen in a long time. (Though, I did first have to complain and have them move me to a different node.)

Good people to deal with too.

Cal.

**Comment by hydrandt** [comment]
If you're using their "OpenVZ VPS" ( = openvz container), you have to enable the tun/tap interface first. Go to the customer portal -> VPS servers -> Manage -> Advanced Settings -> Manage Tun/Tap and click Enable.

Then rerun Streisand and openvpn step should be fine.

**Comment by cpu** [comment]
I don't believe this issue is applicable anymore, or is too stale to be actionable. I'm going to close it but please open a new issue providing the information requested by the issue template if this is still a problem for you with the latest code from master. Thanks!
