### ISSUE TITLE
Help! Unable to deploy. Getting error at openconnect step

### ISSUE THREAD

**Issue by gwardatdemo** [jlund/streisand#284]
Seems the ocserv server is down. Is there a backup location it can be downloaded from?

ASK [openconnect : Install the ocserv dependencies] ***************************
changed: [107.170.232.164] => (item=[u'expect', u'gnutls-bin', u'libev-dev', u'libgnutls28-dev', u'libnl-route-3-dev', u'libpam0g-dev', u'libreadline-dev', u'libseccomp-dev', u'libwrap0-dev', u'pkg-config'])

TASK [openconnect : Retrieve the ocserv source code] ***************************
fatal: [107.170.232.164]: FAILED! => {"changed": false, "dest": "/usr/local/src/ocserv-0.11.1.tar.xz", "failed": true, "msg": "Request failed", "response": "Request failed: <urlopen error ftp error: timed out>", "state": "absent", "status_code": -1, "url": "ftp://ftp.infradead.org/pub/ocserv/ocserv-0.11.1.tar.xz"}

**Comment by jlund** [comment]
I just switched things to use a mirrored copy until the official server returns. Thanks for the bug report!

**Comment by rexdf** [comment]
I don't know why. But ftp.infradead.org block DigitalOcean IP.

**Comment by jlund** [comment]
I'm not able to reproduce this. What region is the server in where you were unable to connect to the FTP?

**Comment by rexdf** [comment]
NY3: shadowsocks open ftp.infradead.org in firefox "425 Security: Bad IP Connecting"

Try to deploy a new droplet 3 times in  San Francisco, all failed.

I changed back to `https://missingm.co/` in ` playbooks/roles/openconnect/tasks/main.yml `.
But still failed in `playbooks/roles/streisand-mirror/vars/openconnect.yml` and there is no `generated-docs' folder.

**Comment by jlund** [comment]
What was the failure message when you changed back to the alternate download location?

**Comment by rexdf** [comment]
```
...
TASK [streisand-mirror : Mirror the OpenConnect clients] ***********************
failed: [45.55.13.128] (item={u'url': u'ftp://ftp.infradead.org/pub/openconnect/openconnect-7.06.tar.gz', u'checksum': u'sha256:facf695368dc4537a6a30e2147be90b1d77ee3cb2d269eaef070b6d9ddab70f2'}) => {"dest": "/var/www/streisand/mirror/openconnect", "failed": true, "gid": 33, "group": "www-data", "item": {"checksum": "sha256:facf695368dc4537a6a30e2147be90b1d77ee3cb2d269eaef070b6d9ddab70f2", "url": "ftp://ftp.infradead.org/pub/openconnect/openconnect-7.06.tar.gz"}, "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "OK (1343870 bytes)", "size": 4096, "state": "directory", "status_code": null, "uid": 33, "url": "ftp://ftp.infradead.org/pub/openconnect/openconnect-7.06.tar.gz"}
changed: [45.55.13.128] => (item={u'url': u'https://github.com/openconnect/openconnect-gui/releases/download/v1.3/openconnect-installer.exe', u'checksum': u'sha256:894ce16fbfbb4be0f205dc5bc55323b5d99306e81672ad5d631bd9bab0d586b1'})
...
PLAY RECAP *********************************************************************
127.0.0.1                  : ok=9    changed=3    unreachable=0    failed=0
45.55.13.128               : ok=188  changed=174  unreachable=0    failed=0
```

**Comment by jlund** [comment]
It's a shame that they're blocking access to those files. I'll get them mirrored on a more permanent location. Thanks for letting me know!

**Comment by rexdf** [comment]
Thanks.
Btw, is this the reason that there is no 'generated-docs' folder?

**Comment by jlund** [comment]
That gets generated near the end when the connection instructions are downloaded. So if the playbook is failing before it gets to that point, then the folder wouldn't be there.

**Comment by rexdf** [comment]
Right now I can `wget ftp://ftp.infradead.org/pub/ocserv/ocserv-0.11.2.tar.xz` in SF.

**Comment by cpu** [comment]
I believe this issue is sufficiently stale to be unactionable. If using an up to date OpenConnect client against a fresh Streisand instance created with the latest code from master still displays this problem I would encourage you to open a new issue providing the information requested by the issue template. Thanks!
