### ISSUE TITLE
obfs3 "missing pluggable transports"...

### ISSUE THREAD

**Issue by umbrageous** [jlund/streisand#286]
On each of my DigitalOcean Ubuntu 14.04 servers, obfs3 is failing to work. For example, when I put the bridge, as per instructions, into Tor Messenger, I get...

"Tor failed to establish a Tor network connection.

Retrieving network status failed (missing pluggable transport - xx.xx.xx.xx:yyyyy)." 

Tor Browser just hangs and will not connect.

I have tried both with hidden bridges I got from elsewhere, and they both work with them.

I have, via ssh, updated, upgraded, rebooted server, and restarted Tor. No positive outcome.

Any suggestions would be appreciated, please, as to ways forward. Do I need to reinstall Tor on the server, and, if so, how? Should I regenerate an obfs3 proxy - and, again, if so, how?

Thanks!

**Comment by umbrageous** [comment]
I replaced the DigitalOcean droplets with new ones, and spun up new servers. The problem seems to have resolved.

**Comment by jlund** [comment]
Good to hear!
