### ISSUE TITLE
Installation on hosthatch fails on "Restart OpenVPN" step

### ISSUE THREAD

**Issue by rngadam** [jlund/streisand#288]
- Got a Ubuntu 14.04 instance on hosthatch.com (OpenVZ)
- configured public key access
- Modified inventory to point to new IP
- ran `ansible-playbook playbooks/streisand.yml`

Fails at:

```
TASK [openvpn : Restart OpenVPN so the 10.8.0.0 interface is available to dnsmasq] ***
fatal: [153.92.45.9]: FAILED! => {"changed": false, "failed": true, "msg": " * Stopping virtual private network daemon(s)...\n *   No VPN is running.\n * Starting virtual private network daemon(s)...\n *   Autostarting VPN 'server'\n"}
```

I can reproduce at the command-line

```
# cd /etc/openvpn
# openvpn --config /etc/openvpn/server.conf 
Thu Apr 21 22:50:58 2016 WARNING: --ifconfig-pool-persist will not work with --duplicate-cn
Thu Apr 21 22:50:58 2016 ERROR: Cannot open TUN/TAP dev /dev/net/tun: No such file or directory (errno=2)
```

As far as I can gather, this is due to OpenVZ host not having the tun module (guests containers can't load their own modules).

I tried commenting out openvpn from the playbook but this fails later due to a dependency:

```
TASK [rc-local : Generate rc.local with Firewall and dnsmasq settings for OpenVPN and L2TP/IPsec] ***
fatal: [153.92.45.9]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'openvpn_firewall_rules' is undefined"}
```

**Comment by CalHenze** [comment]
See my reply to Kataflok below -- I just went through this with BudgetVM. (Exact same thing seen at command line as well.)

**Comment by rngadam** [comment]
@CalHenze below?

**Comment by CalHenze** [comment]
9 days ago post titled:

Restart OpenVPN fail

**Comment by hydrandt** [comment]
That's because openvz containers don't have tun interfaces enabled by default. You have to either find an option to enable it in hosthatch control panel, or ask their support to do it for you.

More info on tun in openvz: https://openvz.org/VPN_via_the_TUN/TAP_device

**Comment by cpu** [comment]
I believe this issue is sufficiently stale to be unactionable. If a fresh Streisand instance created with the latest code from master still displays this problem I would encourage you to open a new issue providing the information requested by the issue template. Thanks!
