### ISSUE TITLE
SSH Configuration

### ISSUE THREAD

**Issue by nzkarit** [jlund/streisand#290]
Hi,

I have been looking at some SSH Configuration. I think there are some changes which could be made to make the installation more robust by disabling the weak ciphers and such. One use cases for streisand being avoiding nation state man in the middle, I feel cipher setup is import.

There is a site which will evaluate SSH cipher setup:
https://discovery.cryptosense.com/
This is like SSL Labs for HTTPS:
https://www.ssllabs.com/ssltest/

Working with the Mozilla SSH Config guide and cryptosense I made the follow changes for SSH.
https://wiki.mozilla.org/Security/Guidelines/OpenSSH

Firstly I made the RSA key 4096
```
rm /etc/ssh/ssh_host_rsa_key*
ssh-keygen -h -t rsa -b 4096 -f /etc/ssh/ssh_host_rsa_key -N ''
```

Next follow the Mozilla Guide
I removed the following line
```
HostKey /etc/ssh/ssh_host_dsa_key
```
Added
```
KexAlgorithms curve25519-sha256@libssh.org,ecdh-sha2-nistp521,ecdh-sha2-nistp384,ecdh-sha2-nistp256,diffie-hellman-group-exchange-sha256
Ciphers chacha20-poly1305@openssh.com,aes256-gcm@openssh.com,aes128-gcm@openssh.com,aes256-ctr,aes192-ctr,aes128-ctr
MACs hmac-sha2-512-etm@openssh.com,hmac-sha2-256-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-512,hmac-sha2-256,umac-128@openssh.com
```
Changed UsePrivilegeSeparation to be sandbox rather than yes. As sandbox is the openssh default and more secure. The yes is apparently a work around.
```
UsePrivilegeSeparation sandbox
```

Cryptosense I notice the stunnel also had issues currently don't the openvpn stunnel and not totally around the config for it but did add the following to /etc/stunnel/stunnel.conf just to get rid of some of the known SSL vulnerabilities:
```
options = NO_SSLv2
options = NO_SSLv3
options = NO_TLSv1
ciphers = HIGH
```

**Comment by jlund** [comment]
New Streisand servers now get an "A" rating on Cryptosense Discovery with no warnings.

**Comment by jlund** [comment]
Thanks for your help!

**Comment by jlund** [comment]
I'm also going to revisit the cipher selection for OpenVPN as well.
