### ISSUE TITLE
Recommend to add instructions about connecting L2TP VPN from Windows  behind a NAT device

### ISSUE THREAD

**Issue by rexdf** [jlund/streisand#291]
All other device works well while my Windows 10 tablet always complains:

> The network connection between your computer and the VPN server could not be established because the remote server is not responding. This could be because one of the network devices (e.g., firewalls, NAT, Router etc.) between your computer and the remote server is not configured to allow VPN connections. Please contact your Administrator or your service provider to determine which device may be causing the problem.

Windows 10 error message doesn't contain string `Error 809`.

Details from microsoft https://blogs.technet.microsoft.com/isablog/2010/08/04/more-than-one-l2tp-vpn-connection-from-behind-a-nat-device-fails-with-error-809-when-tmg-2010-has-been-configured-as-a-vpn-server/

Solution:
https://documentation.meraki.com/MX-Z/Client_VPN/Troubleshooting_Client_VPN#Common_Connection_Issues

Recommend to add following to L2TP/IPsec Windows instructions html page

### Client behind NAT devices
Solution: Modern Windows devices do not support L2TP/IPsec connections when the Windows computer or VPN server are located behind a NAT. If the Windows VPN client fails with Error 809 when trying to establish a VPN connection to an MX located behind a NAT, add the "AssumeUDPEncapsulationContextOnSendRule" DWORD value to the Windows registry. This DWORD value allows Windows to establish security associations when both the VPN server and the Windows based VPN client computer are behind NAT devices.

#### For Windows XP:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\IPSec

RegValue: AssumeUDPEncapsulationContextOnSendRule

Type: DWORD

Data Value: 2
 

#### For Windows Vista, 7, 8, 10, and 2008 Server:

HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Services\PolicyAgent 

RegValue: AssumeUDPEncapsulationContextOnSendRule

Type: DWORD

Data Value: 2

Note that after creating this key you will need to reboot the machine

**Comment by kydan** [comment]
! That explains so much.

**Comment by GhostTravels** [comment]
Good solution, already solved!

**Comment by ramesh4500** [comment]
* Can anyone give me a solution to set up L2TP based VPN client in windows 10. When ever I tried to hit the remote server it gives me the error "error 789: The L2TP connection attempt failed because the security layer encountered a processing error during initial negotiations with remote computer".

* This is on a server 2008 r2 platform with a L2TP\IPSEC VPN with a preshared key.

* I only have mapped port 1701, do I need 4500 and 500 also?

* Also I'm using the Cisco E4200 router to connect to the internet.

* Can any one provide me a suggestion.

**Comment by tsmith512** [comment]
@ramesh4500 , if you're still having trouble, maybe you're seeing the same issue I did: I'm on Windows 10 using the IPSec/L2TP configuration. I have the preshared key entered, as well as the username and password. I had to execute the registry change mentioned above by @rexdf (Thank you!). At that point, I was able to see some connection activity but it always errored out with a message like "The connection was terminated by the remote computer before it could be completed." Looking in the Event Viewer, it did end up being a security layer error. I needed to also check this box in the VPN connection's Options tab:

![image](https://cloud.githubusercontent.com/assets/1486573/24564097/58d42b7e-1616-11e7-9b30-1322835fca3a.png)

I found this in this other project: https://github.com/hwdsl2/setup-ipsec-vpn/issues/7

Works fine for me now.

**Comment by nopdotcom** [comment]
(Hi there, Google!)

Here's a one-liner to paste into an administrator PowerShell that sets that registry value:

```powershell
Set-ItemProperty HKLM:\SYSTEM\CurrentControlSet\Services\PolicyAgent -Name AssumeUDPEncapsulationContextOnSendRule -Value 2 -Type DWord
```

FWIW, the corresponding one-liner for adding an L2TP VPN is:

```powershell
Add-VpnConnection -Name streisand-lax2 -ServerAddress 192.0.2.72 -AuthenticationMethod Chap -EncryptionLevel Optional -L2tpPsk version-surprise-fatigue -TunnelType L2tp
```
