### ISSUE TITLE
SSH config broken by commit 0daa52c

### ISSUE THREAD

**Issue by SummerStorm** [jlund/streisand#292]
I checked out the latest version, ran it, and successfully setup the streisand server with no error messages and all the non-SSH services seems to work. Then I tried to SSH in but couldn't (full SSH log at the bottom).

Thinking maybe I did something wrong, I tried again and setup a second server using the identical steps, and got the identical error.

Since I successfully setup a streisand server without any SSH problems about a month ago, I suspected that maybe some recent changes, i.e. commit 0daa52c, have made the SSH configs overly strict. So I checked out e0b8564 and repeated the setup a third time and third time was the charm.

Here's the the client side SSH log with a single v (let me know if you need `-vvv`):

```
XXX@XXX:~/.ssh$ ssh -v SERVER_NAME
OpenSSH_7.2p2 Ubuntu-1, OpenSSL 1.0.2g-fips  1 Mar 2016
debug1: Reading configuration data /home/XXX/.ssh/config
debug1: /home/XXX/.ssh/config line 13: Applying options for vpn-sing
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: Connecting to XXX.XXX.XXX.XXX [XXX.XXX.XXX.XXX] port 22.
debug1: Connection established.
debug1: key_load_public: No such file or directory
debug1: identity file /home/XXX/.ssh/streisand_rsa type -1
debug1: key_load_public: No such file or directory
debug1: identity file /home/XXX/.ssh/streisand_rsa-cert type -1
debug1: Enabling compatibility mode for protocol 2.0
debug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-1
debug1: Remote protocol version 2.0, remote software version OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.4
debug1: match: OpenSSH_6.6.1p1 Ubuntu-2ubuntu2.4 pat OpenSSH_6.6.1* compat 0x04000000
debug1: Authenticating to XXX.XXX.XXX.XXX:22 as 'forward'
debug1: SSH2_MSG_KEXINIT sent
debug1: SSH2_MSG_KEXINIT received
debug1: kex: algorithm: curve25519-sha256@libssh.org
debug1: kex: host key algorithm: ecdsa-sha2-nistp256
debug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: none
debug1: expecting SSH2_MSG_KEX_ECDH_REPLY
debug1: Server host key: ecdsa-sha2-nistp256 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX
debug1: Host 'XXX.XXX.XXX.XXX' is known and matches the ECDSA host key.
debug1: Found key in /home/XXX/.ssh/known_hosts:8
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS sent
debug1: expecting SSH2_MSG_NEWKEYS
debug1: rekey after 134217728 blocks
debug1: SSH2_MSG_NEWKEYS received
debug1: SSH2_MSG_SERVICE_ACCEPT received
debug1: Authentications that can continue: publickey
debug1: Next authentication method: publickey
debug1: Offering RSA public key: XXX@XXX
debug1: Authentications that can continue: publickey
debug1: Trying private key: /home/XXX/.ssh/streisand_rsa
debug1: Authentications that can continue: publickey
debug1: No more authentication methods to try.
Permission denied (publickey).
```

The client-side logs probably doesn't help as much as the server-side logs, but unfortunately since I don't have SSH access I can't grab the server-side sshd logs.

**Comment by hydrandt** [comment]
To me it seems you are trying to authenticate with a wrong key.
How did you deploy this server?

**Comment by Meroje** [comment]
Are you using the same private key from a month ago ? It should generate a stronger one to go with the stricter settings now

**Comment by SummerStorm** [comment]
> To me it seems you are trying to authenticate with a wrong key.

It's the correct key. I doubled-checked a dozen times. I made two more streisand servers today (using old code) and I can SSH in just fine.

>How did you deploy this server?

I just did `./streisand and` followed the instructions.

>Are you using the same private key from a month ago ? It should generate a stronger one to go with the strict settings now

There are two sets of keys in question:
1. The public/private key pair generated on my local machine
2. The public/private key pair generated on the streisand server, where the private key stays on the streisand  server and the public keys gets downloaded for SSH access.

Which pair are you asking about? 

The #1 pair was indeed generated a month ago, but that shouldn't matter since it's only used during the server setup I believe (someone please correct me if I'm wrong).

The #2 pair was freshly generated on the streisand server today during streisand setup.

**Comment by Meroje** [comment]
I'm thinking of 1, I don't think it matters that you can setup the server as the strict settings are probably reloaded only at the end of the process

**Comment by muamma** [comment]
Similar problem here on new DO droplet, spun up yesterday - Ubuntu 14.04. Opening ssh tunnel via Putty on Win 7, connection throws up:-

"Disconnected: No supported authentication methods available (server sent: public key)".

**Comment by SummerStorm** [comment]
@muamma I suggest you try commit e0b8564 just like I did. With any luck it should work.

**Comment by Meroje** [comment]
Reading it again, I realize streisand does not generate the root pubkey, so you have to generate a strong key yourself before setting up the server. The instructions should mention that

**Comment by SummerStorm** [comment]
With commit e0b8564

https://discovery.cryptosense.com/ reports that "Server keys: RSA 2048-bit"

Going to https://XXX.XXX.XXX.XXX/ssh/#linux-and-osx and download a fresh set of keys:

ssh-keygen -lf streisand_rsa 
2048 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX no comment (RSA)

The key length matches.

==============================================

With commit b77194bf (latest commit as of writing)

https://discovery.cryptosense.com/ reports that "Server keys: RSA 3072-bit"

But if I go to https://XXX.XXX.XXX.XXX/ssh/#linux-and-osx and download a fresh set of keys:

ssh-keygen -lf failed_streisand_rsa 
2048 SHA256:XXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXXX no comment (RSA)

There's a mismatch in the key length.

**Comment by muamma** [comment]
Is there any way I can solve my ssh problem without dumping the current droplet and spinning up a new one with that latest commit? Thanks!

**Comment by CorbanR** [comment]
@muamma I only received the error ""Disconnected: No supported authentication methods available (server sent: public key)" when I didn't provide the key location. You need to either save the login settings  or specify the key each time. 

The following article gives contains some screenshots on how to do so. 
https://www.digitalocean.com/community/tutorials/how-to-use-ssh-keys-with-putty-on-digitalocean-droplets-windows-users

**Comment by CorbanR** [comment]
@SummerStorm the key you generated and the host key size don't have to match. I am using a 2048 key with no problems. 

What command are you using to ssh to the box? Have you made sure your either specifying the private key `ssh -i ~/.ssh/id_rsa` or ensuring the key is in your ssh-agent? For example, you can see what keys are in your agent by running `ssh-add -l` and add a key with `ssh-add ~/.ssh/id_rsa` 


Also can you provide what OS your using?

**Comment by SummerStorm** [comment]
@CorbanR 

I tried both `ssh -i ~/.ssh/KEY_FILE forward@XXX.XXX.XXX.XXX` and the config file method:
```
 Host XXXXXXX
   User         forward
   Port         22
   HostName     XXX.XXX.XXX.XXX
   IdentityFile ~/.ssh/KEY_FILE
```
method provided by the /ssh/#linux-and-osx page of the Streisand server.

Both of these methods work for all my other Streisand servers (created on commit e0b8564 or earlier). 

I'm on Ubuntu 16.04.

**Comment by CorbanR** [comment]
@SummerStorm I was able to recreate the issue and have submitted a pull request which should fix it. 

@jlund ^

**Comment by jlund** [comment]
Thanks, craun!

**Comment by jlund** [comment]
@SummerStorm Although it wasn't directly related to the issues that you were having, I just pushed a commit that makes the generated RSA key 3072-bit as well. Thanks for catching that!

**Comment by jlund** [comment]
I apologize for not spotting this issue earlier. It seems like it was only affecting non-root logins. I will be sure to thoroughly test any further SSH daemon configuration changes using unprivileged users (like `forward`) as well.
