### ISSUE TITLE
Support ed25519 client keys

### ISSUE THREAD

**Issue by Synchro** [jlund/streisand#294]
Just as [the SSH server config prefers ed25519 keys](https://github.com/jlund/streisand/blob/0daa52c01d2dd86f9553eb041e34e4855526ec76/playbooks/roles/ssh/files/sshd_config), so should the client config. At present all client SSH key references are hard-coded with `~/.ssh/id_rsa.pub`. It would be better to pick the "best" one, or ideally, support all of the standard names, particularly `~/.ssh/id_ed25519.pub`. If you've got a key with a non-standard name, you probably know how to add it manually.

**Comment by cpu** [comment]
I think this request is a subset of https://github.com/jlund/streisand/issues/300 so I'm going to close it in favour of #300. Thanks!
