### ISSUE TITLE
Tunnelblick mirror...

### ISSUE THREAD

**Issue by umbrageous** [jlund/streisand#295]
Just to note that I received an error report when installing via the latest commit, 3c5c378, that there was a fatal error in the installation of the Tunnelblick mirror.

**Comment by jlund** [comment]
I'll get that updated. Was the error handled gracefully?

**Comment by umbrageous** [comment]
Yes, it was: everything else installed without a problem.

By the way, Streisand is an excellent resource: thank you for it!

**Comment by jlund** [comment]
You're welcome! Thanks for your help!
