### ISSUE TITLE
Streisand stops with no error message

### ISSUE THREAD

**Issue by samchelsea009** [jlund/streisand#296]
Using Streisand on OSX to setup a GCE server. I get to the task below, then I get a play recap but no documentation is generated. Any ideas?

TASK [gce-network : Open the OpenVPN port in the GCE firewall] *****************
ok: [127.0.0.1 -> localhost]

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=20   changed=3    unreachable=0    failed=0  
130.XXXXXX            : ok=166  changed=151  unreachable=0    failed=0

**Comment by cpu** [comment]
@samchelsea009 Do you still experience this problem with the latest git master of Streisand and a fresh google cloud instance?

**Comment by cpu** [comment]
There's been no response so I'm going to close this issue. Thanks!
