### ISSUE TITLE
Arch linux: Invalid Syntax Error

### ISSUE THREAD

**Issue by obilodeau** [jlund/streisand#299]
Local `inventory` file should have the following on Arch because /usr/bin/python defaults to python3:

```
[localhost]
127.0.0.1 ansible_python_interpreter=python2
```

I don't think the README suggestion done in #30 is sufficient since I knew I had python2 installed but streisand still didn't work.

I think that changing the default value of ansible_python_interpreter to python2 would be acceptable since it has been available that way for a while now but I don't know what's the story for OS X so I didn't create a pull request.

**Comment by jlund** [comment]
Yeah, that suggestion would work for Ubuntu as well, but I don't know if `python2` means anything on OS X.

@CorbanR Can you check to see if OS X ships with a `python2` command?

**Comment by CorbanR** [comment]
OSX has `/usr/bin/python2.7`(The only exception is if you override the local install with brew)

so 

```[localhost]
127.0.0.1 ansible_python_interpreter=python2``` would not work as a default. 

I wonder if we could add something to the striesand wrapper to detect OSX and dynamically set the proper `ansible_python_interpreter=python2` local variable based on that?

**Comment by obilodeau** [comment]
Actually anything that would make the error more obvious that it is an
interpreter version issue would be already an improvement.

**Comment by cpu** [comment]
The `./streisand` wrapper correctly sets the `ansible_python_interpreter` based on the system. I'm going to close this issue since it works as-expected on my Arch machine. Thanks!
