### ISSUE TITLE
NixOps Specification

### ISSUE THREAD

**Issue by tomberek** [jlund/streisand#302]
Create [NixOps](https://nixos.org/nixops/) specification to deploy Streisand.

**Comment by cpu** [comment]
@tomberek can you expand on this feature request? What would a NixOps specification help with and how do you see it interacting with the current Ansible tooling?

**Comment by cpu** [comment]
Closing this issue as stale. I believe it needs more fleshing out to be a feature request we have a chance of implementing. Thanks!
