### ISSUE TITLE
Native Azure Support

### ISSUE THREAD

**Issue by mikeactual** [jlund/streisand#304]
To whoever is working on Azure support; I have a bunch of free Azure resources and want to put up a Streisand VM on their cloud. I'm not much use for coding but I can offer up test resources and assistance plus I can doc the crap out of everything that is done. I can also write up how-to docs at the end of the project. Any takers?

**Comment by joaocc** [comment]
Hi,
What things do you see as specific to Azure?
Thx

**Comment by mikeactual** [comment]
Beats me? The readme reads that Native Microsoft Azure support is an upcoming feature. I'm going to stand up an Ubuntu vm with Streisand in the Azure cloud. I'm not a skilled developer but I'm pretty good with infrastructure and I can write well enough. I'm offering what I can do (test and write how-to's) to help the project. 

If there isn't any interest in working on it with me, I'll take notes while I stand up the vm and post them back here for comment.

Regards,
mike

**Comment by joaocc** [comment]
From a quick read, we would have to create a new "genesis-azurerm" role.

**Comment by mikeactual** [comment]
OK, I'm new to the project and don't know what that means. However I'll put up an Azure vm this evening and start installing Streisand. I'll keep an eye out for any mention of roles while I'm reading the install guide and I'll take detailed notes during the process.

If there is anything that you want me to specifically try or test, just let me know.

Regards,
mike

**Comment by joaocc** [comment]
Sorry. I don't think it will work. The scripts I am referring to are the ones that instantiate the VM in Azure. I  believe that, at this point in time, the best is to install streisand on an existing (or newly created VM) instead of using the script to create the VM and install.

**Comment by mikeactual** [comment]
Ah, I see what you're saying. That is what I was planning to do anyway.

Well my offer stands. I'm happy to offer test resources and help when/if the community begins work on scripts for Azure.

**Comment by philbritton** [comment]
I'd recommend checking out the ARM (Azure Resource Manager) templates and ultimately, for best user experience, try to use that to create a 'deploy to azure' button. 
[Using custom ARM templates with the Deploy to Azure button | Elliott ...]
(https://goo.gl/XOefyF) here's more info.

**Comment by joaocc** [comment]
@philbritton: from the (little) I understand of Streisand, the "genesis*.yml" files are ansible plays, meaning, they can be scripted to use the azure_rm methods of ansible (https://docs.ansible.com/ansible/list_of_cloud_modules.html). Any particular reason to go through ARM templates? Thx

**Comment by mikeactual** [comment]
From what I can tell after a quick look at ARM you can manage VM's but not deploy them:

https://azure.microsoft.com/en-us/documentation/articles/virtual-machines-windows-ps-manage/

I'm not at all conversant in ansible yet. From what I know about it I don't think ARM adds anything though. Current state still seems to be that you need to manually deploy an Ubuntu Trusty vm to Azure and then run Steisand from your workstation. That's what I'm going to try anyway.

**Comment by joaocc** [comment]
See https://github.com/jlund/streisand/issues/4

**Comment by jlund** [comment]
@joaocc Looking really good so far! I'm excited for the PR :)

**Comment by joaocc** [comment]
Thx. Unfortunately I will be busy for the next week or so. If you have the chance, please pick it up and incorporate it, as I will not be able to do so. Cheers!

**Comment by Russell-IO** [comment]
I'll be happy to work on the Azure integration - @mikeactual are you happy to provide access to an Azure account to work on the provisioning ?

**Comment by mmathys** [comment]
how's the progress going?

**Comment by mmathys** [comment]
Is it implemented as of now?

**Comment by jlund** [comment]
Azure support was just merged into the master branch. Thanks to @blotzu and @joaocc for making it happen!
