### ISSUE TITLE
FATAL Error at Configure Server and Install Software (Amazon)

### ISSUE THREAD

**Issue by aseem1234** [jlund/streisand#305]
Hi all,

I've been trying to run the script and everything works until the following task:

PLAY [Configure the Server and install required software]

I get a fatal: UNREACHABLE: SSH ERROR: data could not be sent to the remote host.

I tried again, but not sure if I typed the command correctly:

./streisand --limit @playbooks/amazon.retry

The command worked, but seemed to follow the same steps as usual. It failed again at the same spot. I was using region 9 (US WEST - Oregon) for this server. 

Any ideas? 

Thanks in advance.

**Comment by df-sh** [comment]
what country are you trying this from?  I know it SHOULDNT matter... but as of today, I can't make SSH connections internationally from within china without first going through a vpn

**Comment by aseem1234** [comment]
I am trying this from the United States. I think there shouldn't be any issue connecting over SSH from here. Not sure what the issue is. Any help would be appreciated.

**Comment by df-sh** [comment]
using amazon console, see if you can connect to the server that streisand created through ssh

**Comment by df-sh** [comment]
I am still getting tons of ssh errors, not sure what the story is.. both amazon and rackspace tossing up ssh connections errors all over the place

**Comment by jarrydfillmore** [comment]
+1, getting this too!

**Comment by cpu** [comment]
@jarrydfillmore, @df-sh, @aseem1234 Are any of you able to confirm this issue is still affecting you using the tip of master & a brand new AWS instance? This issue is quite old and I will likely close it in the next few weeks unless there is someone able to reproduce it & able to coordinate on a fix.

**Comment by cpu** [comment]
I have been able to provision fresh AWS instances using the code from master. Since this issue is stale & I can't reproduce it I'm going to close it. Thanks all!
