### ISSUE TITLE
OpenVPN xor patch

### ISSUE THREAD

**Issue by zhabkab** [jlund/streisand#306]
Hi, I think it would be excellent to integrate the OpenVPN xor patch (see DD-WRT repo version of OpenVPN or https://github.com/clayface/openvpn_xorpatch) as this can pass through most typical DPI that checks for OpenVPN, I have personally tested that it works in shall we say a certain communist country.  I have no idea why the OpenVPN developers themselves are so hostile to this patch which makes their product useful there, hopefully this project will not have the same attitude.

**Comment by kydan** [comment]
FWIW, I've also heard good things about the performance of this patch, but
am not terribly up to date on the politics of why it has not been
incorporated into the main project.

**Comment by alimakki** [comment]
This would mean maintaining a separate fork of OpenVPN.
There was some discussion on a PR on the OpenVPN repository: 

Relevant comments:
https://github.com/OpenVPN/openvpn/pull/7
https://github.com/OpenVPN/openvpn/pull/3

**Comment by zhabkab** [comment]
OpenVPN devs are completely against it (I have tried to convince it and you can read their responses in those comments), something about it being an arms race but I completely disagree.  Every user can make a unique xor key, or the principle could be expanded to generate unique random obfuscation data per user or even new data for each session.  They keep calling it an arms race but to me it just seems like a challenge they aren't willing to take on.  They point to just using obfsproxy but TCP in TCP already has terrible performance, and using obfsproxy with OpenVPN means triple layered TCP (ultimate slowness).  Yes it means maintaining a fork of OpenVPN but DD-WRT already do it, the patch seems to rarely conflict with changes.

**Comment by jlund** [comment]
This requires a patched client too, correct?

**Comment by zhabkab** [comment]
It does, except for DD-WRT which has it built in already.  Unfortunately the windows client was a bit of pain to build too last time I tried..

**Comment by hybtoy** [comment]
OpenVPN working without stunnel in our country but I preffered Shadowsocks, because it is faster, easy to setup, can be used on almost all known operating systems. 
It is the matter of time when OpenVPN will be blocked by DPI on our country but I think SS will live if not forever, at least long time :)

**Comment by cpu** [comment]
I don't believe we have the resources/interest in maintaining a patched version of OpenVPN. Thanks!
