### ISSUE TITLE
[Suggestion] Inclusion of Bangalore Datacenter BLR1 for DigitalOcean

### ISSUE THREAD

**Issue by denoza** [jlund/streisand#307]
Hi Joshua,
Recently, Digitalocean announced the availability of their new datacenter in Bangalore, India. I think its availability as a supported location in the streisand script will be great.
Best,

**Comment by alimakki** [comment]
I added a PR to add the bangalore region, see PR #309

**Comment by jlund** [comment]
And...merged!
