### ISSUE TITLE
Amazon deploy hangs at Diffie-Hellman creation

### ISSUE THREAD

**Issue by cottmann** [jlund/streisand#310]
Trying to deploy with Amazon in Europe (Frankfurt) region. Everything works fine until it tries to create the Diffie-Hellman parameters, where it hangs. Latest try was 10 hours overnight. 

Any idea on how to overcome this would be appreciated.

**EDIT** Nevermind. After starting from scratch again, it stopped hanging at the DH creation. Maybe it also helped to double the CPU resources on the Virtualbox VM that I use to run Streisand (but should that really matter?)

Thank you, @jlund for the great work!

**Comment by jlund** [comment]
You're welcome! Thanks for the feedback.

I just pushed a tiny change that should make this task much faster on `t2.micro` instances that are somewhat CPU-constrained.

**Comment by cottmann** [comment]
Thank you -- that will help.
