### ISSUE TITLE
unattended-upgrades not updating tor, nginx and shadowsocks deb packages

### ISSUE THREAD

**Issue by supershovel** [jlund/streisand#313]
The unattended-upgrades uses `50unattended-upgrades` to define what repos to pull updates from. The default options (listed below) wont match the tor, nginx and shadowsocks repos that were added as part of the install. This means that when security updates are released for any of those packages they will not be automatically installed
```
    "${distro_id} stable";
    "${distro_id} ${distro_codename}-security";
```

**Comment by alimakki** [comment]
Working on fixing this, just testing out the changes. Stay tuned!

**Comment by alimakki** [comment]
and done, see PR  #324

**Comment by jlund** [comment]
The great @alimakki strikes again!
