### ISSUE TITLE
sshd config allows root logins

### ISSUE THREAD

**Issue by supershovel** [jlund/streisand#314]
Should never log into a system as root as a basic security principal. The sshd config should disable root logins.

**Comment by jlund** [comment]
There's an explanation in the [comments in the sshd_config file](https://github.com/jlund/streisand/blob/master/playbooks/roles/ssh/files/sshd_config). Password-based logins are disabled. Users can only connect with a valid SSH keypair, thereby preventing brute-force attacks against the root user.

Following through on this suggestion would prevent most people from being able to configure their new server or reconfigure an existing server. The default OpenSSH configuration value on an overwhelming majority of VPS providers is indeed `PermitRootLogin Yes`. DigitalOcean, Linode, Rackspace, Vultr...the list goes on nearly forever, and all of them start new servers that require you to connect as root. Allowing people to connect to their servers is also a basic principal :)

We could hypothetically do the following:

1. Connect as root.
1. Create a new user.
1. Grant that user sudo access.
1. Choose one of these somewhat cheesy options:
   * Create a new keypair, transfer the private key to the machine running Streisand, instruct the user to put the file in the right location, and reconfigure their SSH client to use it.
   * Or we could theoretically just do a wholesale copy of root's `authorized_keys` file to the new user, which may not be an entirely appropriate thing to do.
1. Disconnect.
1. Reconnect as the new non-root user.
1. _Immediately_ escalate to root to continue setup.

That's a **lot** of complexity for little to no gain. We would get through seven (or more) steps just to end up effectively connecting as root anyway, which is the privilege level that the playbook requires given the services it is configuring.

I wish that more VPS providers followed Amazon's lead and provisioned new servers using a non-root user like `ubuntu`. Sadly, that's not the reality we live in, and Streisand has to work in real-world conditions.
