### ISSUE TITLE
Fails with UNREACHABLE!

### ISSUE THREAD

**Issue by yurivict** [jlund/streisand#316]
I am using Amazon, Nor Cal region. streisand fails like this:

```
TASK [genesis-amazon : New EC2 servers are occasionally slow to process incoming SSH connections even after the OpenSSH daemon has started up. Pause for 90 seconds.] ***
Pausing for 90 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [127.0.0.1]

PLAY [Configure the Server and install required software] **********************

TASK [setup] *******************************************************************
fatal: [54.67.18.69]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
        to retry, use: --limit @playbooks/amazon.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=19   changed=7    unreachable=0    failed=0   
54.67.18.69                : ok=0    changed=0    unreachable=1    failed=0   
```

When I create instances manually I can always access them via IP. So involved IPs should not be unreachable.

FreeBSD 10.3

**Comment by aasiegel** [comment]
I'm having the same issue with DigitalOcean.  Tried generating an SSH pair as sudo and as the individual user, no dice.  Tried multiple reattempts, but also no luck there.  Error message:

UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
	to retry, use: --limit @playbooks/digitalocean.retry

**Comment by yurivict** [comment]
It also left instances running, one per failed attempt.

**Comment by KishCom** [comment]
Removed the "@" from my SSH key name on Digital Ocean ... it works now.

**Comment by wubwubwubwubwubwubwubwub** [comment]
Uh, same problem using DO, Amsterdam data center 3 - I was all set to expunge the @ from by SSH key name, but I don't have one.  I have not been able to find a name for my key that works.  I have no trouble connecting to the new droplet over ssh as root, once I ask for a root password for the new droplet.  90 seconds can be a really loooooong time...

**Comment by aasiegel** [comment]
I ended up getting this fixed, but it took a bit to troubleshoot.  Had to kill the instance on DO, then add my SSH key back into DO itself.  Looks like there was a corrupted character buried in the SSH key when I pasted things over from Terminal.  Once that was fixed, it chugged away and got things done.

**Comment by df-sh** [comment]
Been having trouble with ssh connections out of china for streisand setup
recently, got same error... my solution involved connecting to anyconnect
from a previous streisand setup which allowed the script to complete... not
sure what the deal is

**Comment by wubwubwubwubwubwubwubwub** [comment]
When I create a DO droplet using an ssh key during creation, the only user is root, and I can't log in by console or ssh without a password.  The only way to get a password is by asking through the web interface.  How in the heck is Streisand supposed to log back in to the newly created droplet without a password?  Or perhaps if I knew how to explain the necessary remote password to Streisand I could make a second attempt at configuring the existing droplet.

**Comment by wubwubwubwubwubwubwubwub** [comment]
I installed sshpass and created a /etc/ansible/hosts file containing the IP address of the droplet Streisand created.
Then I ran this command:

ansible myhostname -k -a "/bin/ls"

and now ansible asked me for the password I need to connect to the system by ssh.
I used tcpdump on the DO console to watch the traffic coming in from my laptop (but it gets confusing once there is any output on the console)  after a few packets go back and forth, my droplet asks  Google's public DNS to resolve my laptop's IP address, which is just a dynamic pool address.  I wonder if this could have something to do with the connection failure?

**Comment by alimakki** [comment]
@wubwubwubwubwubwubwubwub Your public ssh key is copied over to the Streisand droplet during genesis, so after it completes setup you should be able to log into the server using public key authentication. Password authentication is disabled on the server, this mitigates brute force attacks.

**Comment by wubwubwubwubwubwubwubwub** [comment]
That's what I think should happen, but >every< time I create a droplet at Digital Ocean using my ssh key, I am still asked for a password.  And the key does seem to work, because I checked with a different laptop from the same IP address and could not log in with the same user/password combination.  I even need a password to use the console at DO's site, despite using the laptop with the correct ssh key.

If your explanation is correct, and I'm just doing it wrong, this would mean that the key I transmitted to DO is corrupt somehow?  But it still works at my end?  When I did the test above from a different laptop and could not log in, I then moved the private key from the first laptop to the second, and then I could ssh in.   But I still needed a user/password combination to do so.  

I am very confused about the real nature of the trouble.

**Comment by alimakki** [comment]
@wubwubwubwubwubwubwubwub that seems strange. I ran into this issue once, and only because the setting up streisand failed midway (I was testing some new code).

Did your setup complete successfully? Is it always failing in the same region or did you try different ones?

If all else, can you try creating a new ssh keypair and running streisand again; see if that helps solves your issue.

**Comment by wubwubwubwubwubwubwubwub** [comment]
Began again, new droplet.  Here are the first few lines from auth.log:

Jun  5 17:21:26 ducksoup sshd[922]: Server listening on 0.0.0.0 port 22.
Jun  5 17:21:26 ducksoup sshd[922]: Server listening on :: port 22.
Jun  5 17:21:38 ducksoup sshd[1124]: Did not receive identification string from w.x.y.z
Jun  5 17:23:09 ducksoup sshd[1126]: Connection closed by w.x.y.z [preauth]
Jun  5 17:24:39 ducksoup sshd[1129]: Connection closed by w.x.y.z [preauth]

So I'm guessing that Streisand isn't even attempting to send the private key.  Besides, it never asked me for the passphrase, which might also be expected to happen?  Maybe I need ssh<whatchacallit> to automatically send private keys?

**Comment by alimakki** [comment]
Private are never supposed to leave the system it was generated on; they are used to d crypt data which are encrypted by the matching public key.

If the setup completes successfully you should never be asked for the password when logging into ssh; Streisand has a task to disable password based authetnication completely. 

DO has a section where you can copy your public keys and Streisand prompts you for one of them at the very beginning of setup.

**Comment by jlund** [comment]
It's tough to know exactly what might be happening when an UNREACHABLE error happens because there are so many possibilities. At a high level, Ansible isn't trying to do anything more complicated than SSH to the server. By default, it uses the standard `ssh` client to do so. It's very likely that most of these connection issues are not specific to Streisand, and I cannot currently duplicate anything that has been described so far.

@yurivict Are you using an AWS-specific SSH key, or just standard `id_rsa`? What version of Ansible do you have installed? I don't have very much experience with FreeBSD, sadly.

@aasiegel I'm glad to hear that you got it figured out. Accidentally leaving off the final character of an SSH public key is one that has gotten me several times too.

@KishCom Interesting. I'll have to see if there's a way around that.

@wubwubwubwubwubwubwubwub It sounds like there might be a more general SSH issue happening on your system.. What kind of key are you trying to use (RSA, ED25519, etc.)? Is the key in your SSH agent (`ssh-add -l`)? If you add your keys to your SSH agent first (`ssh-add`) does that change the result when logging into new servers? Adding the key to your agent should prompt you for its passphrase too, but afterwards should allow for seamless logins.

**Comment by wubwubwubwubwubwubwubwub** [comment]
I have an RSA key generated almost following the DO support suggestion.  Somewhere along the line I ended up with a private key called id_rsa.private.  I also thought I had the SSH agent working. but just now ssh-add -l turned up nothing.  So I renamed my private key.  That's all it took...  Wow.  Sorry to bother you, I did not realize just how techy some of these things can be.  It's just chugging away at the moment, for the first time.

**Comment by yurivict** [comment]
I found the reason: '''id_rsa''' was empty for some reason. Now when I re-generated it streisand started successfully.

**Comment by vmcvpn** [comment]
I too am having this issue with Linode.   I don't have the issue that wubwubwubwubwubwubwubwub had, i have no @ in my key and am quite befuddled.  I regenerated my local and Linode keys and still no luck. I am able to ssh into the server though.  Any ideas would be really appreaciated.

Thanks!

fatal: [xxx.xxx.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
	to retry, use: --limit @playbooks/linode.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=8    changed=4    unreachable=0    failed=0   
xxx.xxx.xxx.xxx             : ok=0    changed=0    unreachable=1    failed=0

**Comment by chun-guo** [comment]
I'm having this problem, 

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}

As mentioned in the README file, "Once login information and API keys are entered, Streisand will begin spinning up a new remote server", but it seems for some reasons it can't connect to this new remote server streisand created.

Anybody knows why?

**Comment by DavidWittman** [comment]
@chun-guo Can you SSH to the server with the key at `~/.ssh/id_rsa` after the streisand run fails? That just looks like an authentication failure.

**Comment by chun-guo** [comment]
Thanks for the quick reply, @DavidWittman, but would you be able to guide me how to "SSH to the server with the key at ~/.ssh/id_rsa"? 

It fails after I execute the Streisand script "./streisand", see below for the log please:


Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the DigitalOcean Server] ***************************************

TASK [setup] *******************************************************************
ok: [localhost]

TASK [genesis-digitalocean : Set the DigitalOcean Access Token fact to the value that was entered, or attempt to retrieve it from the environment if the entry is blank] ***
ok: [localhost]

TASK [genesis-digitalocean : Get the default SSH key] **************************
changed: [localhost]

TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't already exist] ***
ok: [localhost]

TASK [genesis-digitalocean : Create the new Droplet] ***************************
ok: [localhost]

TASK [genesis-digitalocean : Wait until the server has finished booting and OpenSSH is accepting connections] ***
ok: [localhost]

TASK [genesis-digitalocean : Create the in-memory inventory group] *************
changed: [localhost]

TASK [genesis-digitalocean : Set the streisand_ipv4_address variable] **********
ok: [localhost]

TASK [genesis-digitalocean : Set the streisand_server_name variable] ***********
ok: [localhost]

PLAY [Prepare the new server for Ansible] **************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
fatal: [***.***.***.***]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", "unreachable": true}
	to retry, use: --limit @/root/streisand/playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
***.***.***.***            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=9    changed=2    unreachable=0    failed=0   


Cheers

**Comment by DavidWittman** [comment]
@chun-guo `ssh -i ~/.ssh/id_rsa root@1.2.3.4` where 1.2.3.4 is the IP address of your Digital Ocean droplet.

**Comment by alimakki** [comment]
@chun-guo, what OS are you using to run Streisand? Is it macOS Sierra by any chance?

**Comment by yurivict** [comment]
The error should be fixed to be meaningful. No matter what, "UNREACHABLE!" doesn't convey any meaning, so this is a bug in streisand.

**Comment by DavidWittman** [comment]
@alimakki I just tried a new build on macOS Sierra w/ DigitalOcean and had no issues.

@chun-guo Can you try increasing the verbosity in the Ansible run so we can get more useful information regarding to your issue? Open up `./streisand` in your text editor and change line 27 to read:

```
  2) echo; echo; ansible-playbook -vvv playbooks/digitalocean.yml;;
```

Then try to create a new streisand server as normal.

**Comment by chun-guo** [comment]
@alimakki, you are correct, it is Sierra, anything to do with macOS?

@DavidWittman, thanks for you reply again. I've tried `ssh -i ~/.ssh/id_rsa root@1.2.3.4` after the streisand run fails, but it still ends up with the same problem.

I've just changed ./streisand in nano as you mentioned by adding "-vvv", and here is the new log:
```
PLAY [Prepare the new server for Ansible] **************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
task path: /root/streisand/playbooks/streisand.yml:10
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: root
<1.2.3.4> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=100 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 1.2.3.4 '/bin/bash -c '"'"'apt update && apt install python -y'"'"''
fatal: [1.2.3.4]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", 
    "unreachable": true
}
	to retry, use: --limit @/root/streisand/playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
1.2.3.4            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=9    changed=2    unreachable=0    failed=0   
```

**Comment by alimakki** [comment]
@chun-guo, Apple made some changes in the defaults for ssh in sierra, such as deprecating dsa keys, v1 protocol and requiring larger keys for supported algorithms (2048 bit min for rsa vs 1024).

You may be in a situation where you'll need to regenerate your own key pair and upload the new public keys to DO for use with Streisand.

I hope that helps.

http://jeffreifman.com/2016/10/01/fix-macos-sierra-upgrade-breaking-ssh-keys/

https://medium.freecodecamp.com/upgrading-to-macos-sierra-will-break-your-ssh-keys-and-lock-you-out-of-your-own-servers-f413ac96139a#.k7d4jxd3e

**Comment by chun-guo** [comment]
@alimakki, I've followed all the step in the first link you shared, but streisand still failed, here is the full log, 

```
root@ubuntu-512mb-sfo1-01:~/streisand# ./streisand

  S T R E I S A N D  

Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: 2


Using /root/streisand/ansible.cfg as config file
statically included: /root/streisand/playbooks/roles/common/tasks/set-default-variables.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/openconnect.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/openvpn.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/download-and-verify.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/shadowsocks.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/ssh.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/download-and-verify.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/stunnel.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/download-and-verify.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/tor.yml
statically included: /root/streisand/playbooks/roles/streisand-mirror/tasks/download-and-verify.yml

PLAYBOOK: digitalocean.yml *****************************************************
3 plays in playbooks/digitalocean.yml
What region should the server be located in?
  1.  Amsterdam        (Datacenter 2)
  2.  Amsterdam        (Datacenter 3)
  3.  Bangalore
  4.  Frankfurt
  5.  London
  6.  New York         (Datacenter 1)
  7.  New York         (Datacenter 2)
  8.  New York         (Datacenter 3)
  9.  San Francisco    (Datacenter 1)
  10. San Francisco    (Datacenter 2)
  11. Singapore
  12. Toronto
Please choose the number of your region. Press enter for default (#2) region.
 [2]: 9

What should the server be named? Press enter for default (streisand).
 [streisand]: 


New API access tokens can be generated in the DigitalOcean control panel.
https://cloud.digitalocean.com/settings/applications
  * When generating a new token, please note that the Write Scope is necessary
    in order to create Droplets.

If this field is left blank, the environment variable DIGITALOCEAN_API_KEY
will be used.

What is your DigitalOcean Access Token?
: ---token-number---


The following information can be found on your DigitalOcean control panel.
https://cloud.digitalocean.com/settings/security

What is the name of the DigitalOcean SSH key that you would like to use?
  * If you have never uploaded an SSH key to DigitalOcean then the default
    value will work!
  * This key should match your .ssh/id_rsa.pub file.
  * DigitalOcean requires SSH keys to be unique. You cannot upload multiple
    keys that have the same value under different names.

    If you see an error that says 'SSH Key failed to be created' once the setup
    process starts, then this is the problem. You can retry the setup process
    using the name of the existing SSH key from the DigitalOcean control panel
    that matches the contents of your RSA public key.
 [streisand]: newkey

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the DigitalOcean Server] ***************************************

TASK [setup] *******************************************************************
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/system/setup.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'python && sleep 0'
ok: [localhost]

TASK [genesis-digitalocean : Set the DigitalOcean Access Token fact to the value that was entered, or attempt to retrieve it from the environment if the entry is blank] ***
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:2
ok: [localhost] => {
    "ansible_facts": {
        "do_access_token": "---token-number---"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "do_access_token": "---token-number---"
        }, 
        "module_name": "set_fact"
    }
}

TASK [genesis-digitalocean : Get the default SSH key] **************************
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:6
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/commands/command.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'python && sleep 0'
changed: [localhost] => {
    "changed": true, 
    "cmd": [
        "cat", 
        "~/.ssh/id_rsa.pub"
    ], 
    "delta": "0:00:00.002876", 
    "end": "2016-10-20 13:17:27.201709", 
    "invocation": {
        "module_args": {
            "_raw_params": "cat ~/.ssh/id_rsa.pub", 
            "_uses_shell": false, 
            "chdir": null, 
            "creates": null, 
            "executable": null, 
            "removes": null, 
            "warn": true
        }, 
        "module_name": "command"
    }, 
    "rc": 0, 
    "start": "2016-10-20 13:17:27.198833", 
    "stderr": "", 
    "stdout": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHFCpO5e+yhj75MU11OLSEiwE/lqimw+toZ5t14vPTVvCRnskvWSP1kyvvrHcgOxPjCg99lOhsoIsa041nyAvi7Yug17qa0DZ+XCj/txH3dHAcvLDidODrtlRX0mk2jrMl2r+IzV2nJ+Tmi3md0iPuXRtV8m2jo9sqyNb2RjEf8l5OAtkHUKRF3bJUZhHaEcZXMjdp/iZ37sojziWUhIYdaorYumoVp7VhYbpIVtsnYPxqEDdPEbydpHQKyObetd2Iv/Ml/ZT7AZzfTbumTTRDHap/Jq78qNkPFdVngOZu0mc7OvtPTu4490ANjIAKoJsvTTvFx/gpT3Zi5+cWitcV root@mac.local", 
    "stdout_lines": [
        "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHFCpO5e+yhj75MU11OLSEiwE/lqimw+toZ5t14vPTVvCRnskvWSP1kyvvrHcgOxPjCg99lOhsoIsa041nyAvi7Yug17qa0DZ+XCj/txH3dHAcvLDidODrtlRX0mk2jrMl2r+IzV2nJ+Tmi3md0iPuXRtV8m2jo9sqyNb2RjEf8l5OAtkHUKRF3bJUZhHaEcZXMjdp/iZ37sojziWUhIYdaorYumoVp7VhYbpIVtsnYPxqEDdPEbydpHQKyObetd2Iv/Ml/ZT7AZzfTbumTTRDHap/Jq78qNkPFdVngOZu0mc7OvtPTu4490ANjIAKoJsvTTvFx/gpT3Zi5+cWitcV root@mac.local"
    ], 
    "warnings": []
}

TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't already exist] ***
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:11
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/cloud/digital_ocean/digital_ocean.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'python && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "backups_enabled": false, 
            "command": "ssh", 
            "id": null, 
            "image_id": null, 
            "ipv6": false, 
            "name": "newkey", 
            "private_networking": false, 
            "region_id": null, 
            "size_id": null, 
            "ssh_key_ids": null, 
            "ssh_pub_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQDHFCpO5e+yhj75MU11OLSEiwE/lqimw+toZ5t14vPTVvCRnskvWSP1kyvvrHcgOxPjCg99lOhsoIsa041nyAvi7Yug17qa0DZ+XCj/txH3dHAcvLDidODrtlRX0mk2jrMl2r+IzV2nJ+Tmi3md0iPuXRtV8m2jo9sqyNb2RjEf8l5OAtkHUKRF3bJUZhHaEcZXMjdp/iZ37sojziWUhIYdaorYumoVp7VhYbpIVtsnYPxqEDdPEbydpHQKyObetd2Iv/Ml/ZT7AZzfTbumTTRDHap/Jq78qNkPFdVngOZu0mc7OvtPTu4490ANjIAKoJsvTTvFx/gpT3Zi5+cWitcV root@mac.local", 
            "state": "present", 
            "unique_name": false, 
            "user_data": null, 
            "virtio": true, 
            "wait": true, 
            "wait_timeout": 300
        }, 
        "module_name": "digital_ocean"
    }, 
    "ssh_key": {
        "fingerprint": "bd:ad:16:d2:d6:62:3f:0d:3c:c7:99:ac:60:df:46:f3", 
        "id": 4136750, 
        "name": "newkey", 
        "public_key": "ssh-rsa AAAAB3NzaC1yc2EAAAADAQABAAABAQCo5QVJdUG8akxjau70qJp+u8gTl6fwg8KOyA/mi9ZivifuUFwvfWqwZoFaD/Bg3BVQ4tssfVvl3V9Ot9xAHql5v3k0LR4xvVodrVrYOdYYQxEKOUn5aw5Hj0Mx2gJRWJ7JyJj54+mJWy8RarroVtJ44mibgN2meUO8108goWQccOSdK74C+KUp4edlmffg+q5L5a3rFLrWdFb4MR2Ge8CI7l1DJwH8sRL8Vn3Wt26GgAJoW3hB7OBGI4ScoYT7BB+BHKGm+wH6ExYY0HsVD6MYRVVD9lv72/E1rdWxT0oPZCXbB0JnMC92SD9F6qbuH+adm2NfYhvtbxaREzPVfM7T root@mac.local"
    }
}

TASK [genesis-digitalocean : Create the new Droplet] ***************************
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:23
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/cloud/digital_ocean/digital_ocean.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'python && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "droplet": {
        "backup_ids": [], 
        "created_at": "2016-10-20T11:58:24Z", 
        "disk": 20, 
        "features": [
            "virtio"
        ], 
        "id": 29840174, 
        "image": {
            "created_at": "2016-10-18T16:32:41Z", 
            "distribution": "Ubuntu", 
            "id": 20361313, 
            "min_disk_size": 20, 
            "name": "16.04.1 x64", 
            "public": true, 
            "regions": [
                "nyc1", 
                "sfo1", 
                "nyc2", 
                "ams2", 
                "sgp1", 
                "lon1", 
                "nyc3", 
                "ams3", 
                "fra1", 
                "tor1", 
                "sfo2", 
                "blr1"
            ], 
            "size_gigabytes": 0.35, 
            "slug": "ubuntu-16-04-x64", 
            "type": "snapshot"
        }, 
        "ip_address": "1.2.3.4", 
        "kernel": null, 
        "locked": false, 
        "memory": 512, 
        "name": "streisand", 
        "networks": {
            "v4": [
                {
                    "gateway": "107.170.192.1", 
                    "ip_address": "1.2.3.4", 
                    "netmask": "255.255.240.0", 
                    "type": "public"
                }
            ], 
            "v6": []
        }, 
        "next_backup_window": null, 
        "region": {
            "available": true, 
            "features": [
                "private_networking", 
                "backups", 
                "ipv6", 
                "metadata"
            ], 
            "name": "San Francisco 1", 
            "sizes": [
                "512mb", 
                "1gb", 
                "2gb"
            ], 
            "slug": "sfo1"
        }, 
        "size": {
            "available": true, 
            "disk": 20, 
            "memory": 512, 
            "price_hourly": 0.00744, 
            "price_monthly": 5.0, 
            "regions": [
                "ams1", 
                "ams2", 
                "ams3", 
                "blr1", 
                "fra1", 
                "lon1", 
                "nyc1", 
                "nyc2", 
                "nyc3", 
                "sfo1", 
                "sfo2", 
                "sgp1", 
                "tor1"
            ], 
            "slug": "512mb", 
            "transfer": 1.0, 
            "vcpus": 1
        }, 
        "size_slug": "512mb", 
        "snapshot_ids": [], 
        "status": "active", 
        "tags": [], 
        "vcpus": 1, 
        "volume_ids": []
    }, 
    "invocation": {
        "module_args": {
            "api_token": "VALUE_SPECIFIED_IN_NO_LOG_PARAMETER", 
            "backups_enabled": false, 
            "command": "droplet", 
            "id": null, 
            "image_id": "ubuntu-16-04-x64", 
            "ipv6": false, 
            "name": "streisand", 
            "private_networking": false, 
            "region_id": "sfo1", 
            "size_id": "512mb", 
            "ssh_key_ids": [
                "4136750"
            ], 
            "ssh_pub_key": null, 
            "state": "present", 
            "unique_name": true, 
            "user_data": null, 
            "virtio": true, 
            "wait": true, 
            "wait_timeout": 300
        }, 
        "module_name": "digital_ocean"
    }
}

TASK [genesis-digitalocean : Wait until the server has finished booting and OpenSSH is accepting connections] ***
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:39
Using module file /usr/local/lib/python2.7/dist-packages/ansible/modules/core/utilities/logic/wait_for.py
<localhost> ESTABLISH LOCAL CONNECTION FOR USER: root
<localhost> EXEC /bin/sh -c 'python && sleep 0'
ok: [localhost] => {
    "changed": false, 
    "elapsed": 0, 
    "invocation": {
        "module_args": {
            "connect_timeout": 5, 
            "delay": 0, 
            "exclude_hosts": null, 
            "host": "1.2.3.4", 
            "path": null, 
            "port": 22, 
            "search_regex": "OpenSSH", 
            "state": "started", 
            "timeout": 600
        }, 
        "module_name": "wait_for"
    }, 
    "path": null, 
    "port": 22, 
    "search_regex": "OpenSSH", 
    "state": "started"
}

TASK [genesis-digitalocean : Create the in-memory inventory group] *************
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:46
creating host via 'add_host': hostname=1.2.3.4
changed: [localhost] => {
    "add_host": {
        "groups": [
            "streisand-host"
        ], 
        "host_name": "1.2.3.4", 
        "host_vars": {}
    }, 
    "changed": true, 
    "invocation": {
        "module_args": {
            "groups": "streisand-host", 
            "name": "1.2.3.4"
        }, 
        "module_name": "add_host"
    }
}

TASK [genesis-digitalocean : Set the streisand_ipv4_address variable] **********
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:51
ok: [localhost] => {
    "ansible_facts": {
        "streisand_ipv4_address": "1.2.3.4"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "streisand_ipv4_address": "1.2.3.4"
        }, 
        "module_name": "set_fact"
    }
}

TASK [genesis-digitalocean : Set the streisand_server_name variable] ***********
task path: /root/streisand/playbooks/roles/genesis-digitalocean/tasks/main.yml:55
ok: [localhost] => {
    "ansible_facts": {
        "streisand_server_name": "streisand"
    }, 
    "changed": false, 
    "invocation": {
        "module_args": {
            "streisand_server_name": "streisand"
        }, 
        "module_name": "set_fact"
    }
}

PLAY [Prepare the new server for Ansible] **************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
task path: /root/streisand/playbooks/streisand.yml:10
<1.2.3.4> ESTABLISH SSH CONNECTION FOR USER: root
<1.2.3.4> SSH: EXEC ssh -C -o ControlMaster=auto -o ControlPersist=60s -o StrictHostKeyChecking=no -o KbdInteractiveAuthentication=no -o PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey -o PasswordAuthentication=no -o User=root -o ConnectTimeout=100 -o ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r -tt 1.2.3.4 '/bin/bash -c '"'"'apt update && apt install python -y'"'"''
fatal: [1.2.3.4]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", 
    "unreachable": true
}
	to retry, use: --limit @/root/streisand/playbooks/digitalocean.retry

PLAY RECAP *********************************************************************
1.2.3.4            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=9    changed=2    unreachable=0    failed=0   
```

**Comment by alimakki** [comment]
@chun-guo, looking at the error in your logs:

`"msg": "Failed to connect to the host via ssh: Permission denied (publickey,password).\r\n", `

It appears that the wrong ssh keys are being used when you're trying to log into the server after the DO instance is spun up. Assuming you have regenerated your keypair, did you upload the new one to DO's control panel?

**Comment by chun-guo** [comment]
@alimakki , thanks for answering all my questions, I still can't manage to get it working, but thank you.

**Comment by oseau** [comment]
Same problem here. Solved by doing:

1. Add your ssh key at this page.
https://cloud.digitalocean.com/settings/security

2. Enter the 'name' of your ssh key when streisand ask "What is the name of the DigitalOcean SSH key that you would like to use?". Don't use default option.

**Comment by vacuumboots** [comment]
I had the same problem, fixed by following instructions one and two from @oseau and from @jlund to add the key via ssh-add. Worked perfect after that. I used Sierra.

**Comment by stokes84** [comment]
I was able to resolve this issue by letting Streisand create my droplet for me. By creating my droplet and running the config against it remotely it was failing with this same output every instance.

**Comment by ricemark9** [comment]
I am having a similar issue with GCE with macOS Sierra.  Initially I generate key using ssh-keygen, and the only time it placed it in /Users/username/.ssh/id_rsa was when I left the name blank.  After I run the keygen command I run the ssh-add.  I check the .ssh folder after this and can see the two keys, id_rsa and id_rsa.pub.  I uploaded the .pub information to the SSH keys in GCE. When I run through the ./streisand command it has an error at the [Wait for cloud-init to complete] task and calls out the "fatal: [ip address]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'ip address' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}" error code.

I've also added a name during the keygen process rather than leaving it blank but it has a fatal error at the [genesis-google : Get the default SSH key] task indicating there's no such file or directory.

They key being generated is an RSA 2048 key.

I appreciate any help or advice.

**Comment by DrewHeath** [comment]
This is frustrating. I have a new DigitalOcean droplet with Ubuntu 16.X, everything is updated, and the installer fails repeatedly here:

```
PLAY [Checking instance status] *************************************************************************************

TASK [Wait for cloud-init to complete] ******************************************************************************
fatal: [XXX.XXX.XXX.XXX]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Permission denied (publickey).\r\n", "unreachable": true}
	to retry, use: --limit @/home/drew/streisand/playbooks/digitalocean.retry

PLAY RECAP **********************************************************************************************************
XXX.XXX.XXX.XXX            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=9    changed=2    unreachable=0    failed=0
```

I know the SSH key works because I'm using it. I've also tried letting the Streisand script generate its own key, that failed as well at the same step.

**Comment by ricemark9** [comment]
The problem I was having was from me already having a VM instance started
and then trying to run the script.  When I deleted the VM and re-ran the
script it worked just fine and created its own VM instance in GCE.  I just
had to make sure I was putting the correct JSON file that was generated for
my service account in the streisand folder before running the script.

**Comment by cpu** [comment]
This issue is quite stale and covers a few separate subproblems at this point. I'm going to close it and encourage anyone still having trouble using the latest code from master to create a new issue providing the information requested by the issue template. Thanks!
