### ISSUE TITLE
DNS leak under Windows 10

### ISSUE THREAD

**Issue by krootee** [jlund/streisand#317]
If you run OpenVPN under Windows 10 then by default it will use all available connections to issue DNS requests - this leads to DNS leak.

To combat this issue OpenVPN merged patch in 2.3.9 - you need add following configuration to client .ovpn config:
setenv opt block-outside-dns

This settings is ignored by OpenVPN clients on non-Windows platform, so its safe to use.

**Comment by jlund** [comment]
Thanks for the heads up!

I chose to push the option on the server-side so that any clients that do not use an .ovpn profile will still be covered.
