### ISSUE TITLE
How to find root password

### ISSUE THREAD

**Issue by egalpin** [jlund/streisand#327]
Hi there,

Not sure this is possible but I'm trying to make install additional software on my `streisand` configured server.  However, to do so, I need `superuser` privileges.  How/where can I find these credentials? Is there a default?

This is perhaps an opportunity to add a configuration option at the install phase.

**Comment by Trikolon** [comment]
Streisand has ssh key-authentication enabled. Just login to root@[hostname] using your ssh-key.
In a linux terminal:  'ssh root@[hostname]'

**Comment by egalpin** [comment]
Haha, worked perfectly (like everything with `streisand`). Thanks!

**Comment by muamma** [comment]
I wonder whether someone could point me in the right direction on a related issue.

I run Ubuntu in a VM on a (Windows) machine) from which I ssh into my server(s): H1.

I also have another machine which runs Ubuntu [H2], and I want to be able to ssh into my server(s) from that machine too.

1) Do I try to copy my id_rsa key from H1 to H2, and if so how?

2) Or do I generate a new (public and private) key on H2, and presumably copy the public element to the server(s)? Again, any pointers would be appreciated.

One further question. From H1, there is no need to enter a password to ssh into the server(s). How do I ensure that I don't have to put a password in every time when I use H2 for this purpose?

Thanks!

**Comment by edwinyzh** [comment]
@Trikolon, I have a recent VPS auto setup by streisand and I want to find out the `username` for logging into the shee so that I can install `Final Speed`.
When logging in with Putty (the latest 0.7) I got the following error when login with `root` or `streisand`, any help would be appreciated, thanks!
```
---------------------------
PuTTY Fatal Error
---------------------------
Disconnected: No supported authentication methods available (server sent: publickey)
---------------------------
Ok
---------------------------

```

**Comment by edwinyzh** [comment]
OK, I figured it out - I have to copy the OpenSSH private key to my Windows machine, convert it to .ppk file using PuttyGen.exe, and then use it in Putty along with the 'root' user name, for my Ubuntu installation in Linode.
Thanks and the above info might be useful to others.
