### ISSUE TITLE
Streisand setup fails to complete

### ISSUE THREAD

**Issue by sudoyum999** [jlund/streisand#331]
I'm using Fedora23 and have made numerous failed attempts to setup Streisand. Below is the output of my attempts. Can anyone see what I'm doing wrong? Please keep it simple - I'm a NEWBIE!
TASK [ec2-security-group : Create the EC2 security group] **********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>3f3dcc95-32d7-42b6-a974-3a729281de77</RequestID></Response>
fatal: [127.0.0.1 -> localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_GIS1qR/ansible_module_ec2_group.py\", line 472, in <module>\n    main()\n  File \"/tmp/ansible_GIS1qR/ansible_module_ec2_group.py\", line 271, in main\n    for curGroup in ec2.get_all_security_groups():\n  File \"/usr/lib/python2.7/site-packages/boto/ec2/connection.py\", line 2984, in get_all_security_groups\n    [('item', SecurityGroup)], verb='POST')\n  File \"/usr/lib/python2.7/site-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 403 Forbidden\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>3f3dcc95-32d7-42b6-a974-3a729281de77</RequestID></Response>\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}

**Comment by jlund** [comment]
It looks like the AWS Access Key ID and Secret Access Key that you provided do not have permission to create a new EC2 Security Group. You'll need to grant those permissions to the corresponding IAM user, or it's possible that they were just entered incorrectly. Typos can be fun :)
