### ISSUE TITLE
Please disregard 

### ISSUE THREAD

**Issue by AdamBunn** [jlund/streisand#333]
I recently set up Streisand on a Ubuntu 14.04 server and found that there were multiple SSL/TLS vulnerabilities that enable man-in-the-middle attacks. These issues can likely all be resolved by updating the configuration during the initial setup. 

I've attached a report with remediation steps for many of the vulnerabilities.

[report.html.zip](https://github.com/jlund/streisand/files/307689/report.html.zip)

**Comment by jlund** [comment]
What did you use to generate this report, and which ports were scanned?

New Streisand servers get top scores on the Qualys SSL Labs test and on Cryptosense Discovery. I'm not ready to discount the whole thing yet without answers to those questions, but this pretty much looks invalid to me so far.

**Comment by jlund** [comment]
Kind of bummed out about the sensationalist issue title given that _none_ of the scanners that I've tried are finding any issues.

**Comment by jlund** [comment]
The scanner that generated this report is also getting confused by the fact that Streisand intentionally shares ports with other common services (like IMAPS) in order to mitigate port blocking.

**Comment by AdamBunn** [comment]
Hi, Sorry for causing alarm.

I was going to follow up on this last night but it seems I have incorrectly configured the server and scanner. Please disregard!

**Comment by jlund** [comment]
No worries! That's a relief. Let me know if you need help with anything else.
