### ISSUE TITLE
Redirect all traffic through Tor

### ISSUE THREAD

**Issue by lnalex** [jlund/streisand#334]
I'd like know if it's possible to redirect all traffic on the server side to _Tor_. 

We just have to connect to _OpenVPN_ or _L2TP/IpSec_ and not required to install any Tor software on the client to finally to not being traced with our unique server IP.

**Comment by alimakki** [comment]
Redirecting OpenVPN traffic through Tor on the server side is certainly [doable](https://askubuntu.com/questions/703694/send-all-openvpn-traffic-through-proxy-or-tor-proxy).

That being said, one of the overarching goals of Tor is anonymity, and for that they have customized and hardened Firefox into the Tor browser bundle as to leave as small of a footprint as possible (deleting cookies after closing the browser, not keeping browser history, no plugins like flash that can reveal your IP address to name a few).

Use at your own risk :)

**Comment by jlund** [comment]
Yeah, this isn't something that I would want to build into the project because I think it offers a false sense of security. The client side is equally if not more important. There's nothing that the server can do to protect against a misconfigured client leaking its IP.
