### ISSUE TITLE
How to stop running streisand server?

### ISSUE THREAD

**Issue by bmzhao** [jlund/streisand#335]
After installing dependencies, cloning, and running the streisand script (and giving an AWS key id), I can't find a running ec2 instance under my aws account that corresponds to the Streisand server that was just created. Am I connecting to some other existing server? Or does Streisand spawn a new EC2 instance under my account? And if so, why can't I see it?

**Comment by jlund** [comment]
The AWS console only shows EC2 resources within one region at a time. In the AWS console you'll find a drop-down in the top-right that will let you change your region. If you select the region in which you launched the server, you'll see it.

**Comment by bmzhao** [comment]
Thank you!
