### ISSUE TITLE
AWS Setup failure: Ansible/"NO MORE HOSTS LEFT" error, possible misconfigured keys?

### ISSUE THREAD

**Issue by Rich700000000000** [jlund/streisand#337]
I recently downloaded Streisand, and attempted to install it.  After a few hours of trying to get the keys activated, I proceeded with the installation, only to get the same error multiple times in a row:

```
TASK [setup] *******************************************************************
fatal: [127.0.0.1]: FAILED! => {"changed": false, "cmd": "/sbin/capsh --print", "failed": true, "msg": "Traceback (most recent call last):\n  File \"/tmp/ansible_qwivonz8/ansible_modlib.zip/ansible/module_utils/basic.py\", line 2110, in run_command\n    stdout += dat\nTypeError: Can't convert 'bytes' object to str implicitly\n", "rc": 257}

NO MORE HOSTS LEFT *************************************************************
    to retry, use: --limit @playbooks/amazon.retry

PLAY RECAP *********************************************************************
127.0.0.1                  : ok=0    changed=0    unreachable=0    failed=1   
```

What error is this, and how can I fix it?    

Any help would be appreciated.

**Comment by jlund** [comment]
I haven't ever seen that before. What version of Ansible are you using, and what OS are you using?

The issue might be related to `capsh`. Is that your default shell?

**Comment by Rich700000000000** [comment]
I'm on Ubuntu 14.04 LTS, and `ansible --version` returns:

    ansible 2.1.0.0
      config file = 
      configured module search path = Default w/o overrides

It told me to update ansible, which I did (it was at version 1.8 or something)  and then the error came back.

What's `capsh`?

**Comment by jlund** [comment]
I'm just seeing it in the output from your initial comment.

It looks like things are dying with a generic error in an Ansible task (the `setup` module) that isn't even part of Streisand. That's just the step where Ansible gathers facts about the system, etc. and it's crashing with a Python error (`Can't convert 'bytes' object to str implicitly`).

I'm kind of drawing a blank right now, unfortunately. What is the output of `python --version` on your system?

**Comment by Rich700000000000** [comment]
Python 2.7.6

But I also have python 3.3.6, 3.4.3 and 3.5.1(Anaconda 4.0.0) installed.

**Comment by Rich700000000000** [comment]
Hey, is my issue dead? Should I resubmit it?

**Comment by jlund** [comment]
I'm not sure how to troubleshoot further. Are you getting the same thing with the latest version of Ansible and the latest set of commits? Based on what you have posted so far, this isn't a Streisand issue. It looks like Ansible isn't even working correctly--possibly because of your mix of Python interpreters.

I am still willing to help however I can, but I'm totally mystified at the moment.

**Comment by TheNomad11** [comment]
I also get something similar:  "No matching hosts left" - maybe it's realted?  Ubuntu 14, Vultr. Installation via http://jerrygamblin.com/2016/07/10/the-vpn-you-should-be-using/

```
Cloning into 'streisand'…
remote: Counting objects: 5590, done.
remote: Total 5590 (delta 0), reused 0 (delta 0), pack-reused 5590
Receiving objects: 100% (5590/5590), 1.00 MiB | 0 bytes/s, done.
Resolving deltas: 100% (3231/3231), done.
Checking connectivity… done.


PLAY [Prepare the new server for Ansible] **************************************
skipping: no hosts matched

PLAY [Configure the Server and install required software] **********************
skipping: no hosts matched

PLAY RECAP *********************************************************************

sed: can't read ../generated-docs/streisand.html: No such file or directory

```

**Comment by hobbsAU** [comment]
Ansible is probably picking up your Python3. Try changing the inventory file..

`$ sed -i "s/=python/=python2/" ./inventory`

**Comment by Rich700000000000** [comment]
It gave me an error:

    sed: can't read ./inventory: No such file or directory

**Comment by hobbsAU** [comment]
Do it immediately after install step #1 

1. Clone the Streisand repository and enter the directory.

`git clone https://github.com/jlund/streisand.git`
`cd streisand`
`$ sed -i "s/=python/=python2/" ./inventory`

Then execute the Streisand script.

`./streisand`

**Comment by Rich700000000000** [comment]
Understood. I'll try this and get back to you.

**Comment by cpu** [comment]
@Rich700000000000 Any updates on trying @hobbsAU's workaround? Does this issue still affect you with the latest Streisand code cloned from master & a fresh 16.04 host?

**Comment by cpu** [comment]
There hasn't been a response to my question in over a month. Closing this issue as stale. Thanks all - please open a new issue if you are still experiencing the problem using the tip of master & a fresh provisioning process.
