### ISSUE TITLE
streisand failed to install on ubuntu 14.4 server on Xarix

### ISSUE THREAD

**Issue by covici** [jlund/streisand#338]
I have gotten an error while trying to set up a Ubuntu 14.4 server.

Here is the relevant portion of the build, if you need it, I can send the whole log.

TASK [tor-bridge : Add the Tor repository] *************************************

[0;31mAn exception occurred during task execution. To see the full traceback, use -vvv. The error was: apt.cache.FetchFailedException: E:The method driver /usr/lib/apt/methods/https could not be found.[0m

[0;31mfatal: [209.198.22.222]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_DzeUSw/ansible_module_apt_repository.py\", line 522, in <module>\n    main()\n  File \"/tmp/ansible_DzeUSw/ansible_module_apt_repository.py\", line 512, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: E:The method driver /usr/lib/apt/methods/https could not be found.\n", "module_stdout": "", "msg": "MODULE FAILURE", "parsed": false}[0m

NO MORE HOSTS LEFT *************************************************************

RUNNING HANDLER [openconnect : Restart ocserv] *********************************

RUNNING HANDLER [l2tp-ipsec : Restart Libreswan] *******************************

RUNNING HANDLER [l2tp-ipsec : Restart xl2tpd] **********************************

RUNNING HANDLER [openvpn : Restart dnsmasq] ************************************

RUNNING HANDLER [stunnel : Restart stunnel] ************************************

RUNNING HANDLER [shadowsocks : Restart shadowsocks-libev] **********************

RUNNING HANDLER [ssh : Restart SSH] ********************************************

RUNNING HANDLER [tinyproxy : Restart Tinyproxy] ********************************

```
to retry, use: --limit @playbooks/streisand.retry
```

PLAY RECAP *********************************************************************

[0;31m209.198.22.222[0m             : [0;32mok[0m[0;32m=[0m[0;32m142[0m  [0;33mchanged[0m[0;33m=[0m[0;33m135[0m  unreachable=0    [0;31mfailed[0m[0;31m=[0m[0;31m1[0m

**Comment by alimakki** [comment]
What cloud provider are you using?

**Comment by alimakki** [comment]
Can you try running

<pre>
sudo apt-get install apt-transport-https
</pre>

Then re-running streisand?

**Comment by covici** [comment]
This is my own server that I spun up on a provider you probably never
heard of called xarix.

alimakki <notifications@github.com> wrote:

> What cloud provider are you using?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/338#issuecomment-225500635
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by covici** [comment]
Well, it got much  further this time, but failed here
TASK [streisand-gateway : Convert the Markdown Gateway index,
instructions, and firewall information into HTML and surround them with
the header and footer template] ***
changed: [209.198.22.222] => (item={u'md':
u'/var/www/streisand/index.md', u'html':
u'/var/www/streisand/index.html'})
failed: [209.198.22.222] (item={u'md': u'/tmp/(none).md', u'html':
u'/tmp/(none).html'}) => {"changed": true, "cmd": "markdown
/tmp/(none).md | cat /tmp/header.html - /tmp/footer.html >
/tmp/(none).html", "delta": "0:00:00.004121", "end": "2016-06-13
03:23:07.071192", "failed": true, "item": {"html": "/tmp/(none).html",
"md": "/tmp/(none).md"}, "rc": 2, "start": "2016-06-13 03:23:07.067071",
"stderr": "/bin/sh: 1: Syntax error: \"(\" unexpected", "stdout": "",
"stdout_lines": [], "warnings": []}
failed: [209.198.22.222] (item={u'md':
u'/tmp/(none)-firewall-information.md', u'html':
u'/tmp/(none)-firewall-information.html'}) => {"changed": true, "cmd":
"markdown /tmp/(none)-firewall-information.md | cat /tmp/header.html -
/tmp/footer.html > /tmp/(none)-firewall-information.html", "delta":
"0:00:00.003924", "end": "2016-06-13 03:23:07.358550", "failed": true,
"item": {"html": "/tmp/(none)-firewall-information.html", "md":
"/tmp/(none)-firewall-information.md"}, "rc": 2, "start": "2016-06-13
03:23:07.354626", "stderr": "/bin/sh: 1: Syntax error: \"(\"
unexpected", "stdout": "", "stdout_lines": [], "warnings": []}

NO MORE HOSTS LEFT
*************************************************************

RUNNING HANDLER [sslh : Restart sslh]
******************************************

RUNNING HANDLER [monit : Restart Monit]
****************************************

RUNNING HANDLER [nginx : Restart Nginx]
****************************************
        to retry, use: --limit @playbooks/streisand.retry

PLAY RECAP
*********************************************************************
209.198.22.222             : ok=260  changed=121  unreachable=0
failed=1
 
alimakki <notifications@github.com> wrote:

> Can you try running
> 
> <pre>
> sudo apt-get install apt-transport-https
> </pre>
> 
> Then re-running streisand?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/338#issuecomment-225502236
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by covici** [comment]
Well, after fixing up my hostname, I have tried 3 times to rerun the
yml, first it died during tor-bridge, and then it died in another place
there, so I purged tor and tried again.  Then it failed trying to open
/root/ca/private/key ... and I deleted the directory and tried again and
this time it did work!  Seems fragile to me, maybe we should have a
start over which would restore the server to before we started so we
could have a clean slate, or something, that might have some problems.

alimakki <notifications@github.com> wrote:

> Can you try running
> 
> <pre>
> sudo apt-get install apt-transport-https
> </pre>
> 
> Then re-running streisand?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/338#issuecomment-225502236
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by jlund** [comment]
I haven't used Xarix before, but it looks like there are quite a few issues with their base setup. It looks like they've got a free trial, so I'll give it a shot when I have some time.

**Comment by covici** [comment]
I did eventually get it installed, it was lacking a method in apt and
that basically fixed it, although it had some strange problems, but it
eventually got going.

Joshua Lund <notifications@github.com> wrote:

> I haven't used Xarix before, but it looks like there are quite a few issues with their base setup. It looks like they've got a free trial, so I'll give it a shot when I have some time.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/338#issuecomment-225784522
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by cpu** [comment]
It sounds like you were able to get things running and I believe only 16.04 is considered a supported host OS at this point. I'm going to close this issue and recommend that if you are still having trouble that you re-open it after testing with the latest Streisand master from git and a 16.04 host. Thanks!
