### ISSUE TITLE
cannot download certificate

### ISSUE THREAD

**Issue by covici** [jlund/streisand#340]
Hi.  After my setup is complete, I am unable to download the certificate.  I can open the download link, but after doing so, the information bar contains nothing.

**Comment by alimakki** [comment]
I just tried it on Firefox and it worked. I'm not sure about IE as I don't use it.  Perhaps someone else with more experience can chime in.

Also the file you attached contained the password to your server; anyone that views this thread will be able to gain access.

**Comment by covici** [comment]
hmmm, so how do I change the password, then?

alimakki <notifications@github.com> wrote:

> I just tried it on Firefox and it worked. I'm not sure about IE as I don't use it.  Perhaps someone else with more experience can chime in.
> 
> Also the file you attached contained the password to your server; anyone that views this thread will be able to gain access.
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/340#issuecomment-225598719
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by alimakki** [comment]
At this point the safest course of action for you to re-run Streisand again; since you posted the generated docs to access your Streisand VPN credentials here you should consider it "compromised". 

Perhaps @jlund could chime in some more?

**Comment by covici** [comment]
I was able to download using firefox after rerunning the setup.

alimakki <notifications@github.com> wrote:

> At this point the safest course of action for you to re-run Streisand again; since you posted the generated docs to access your Streisand VPN credentials here you should consider it "compromised". 
> 
> Perhaps @jlund could chime in some more?
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/340#issuecomment-225604485
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by jlund** [comment]
I removed the attached file too. It looks like the only way to make IE work is to change its default security settings. Using a different browser on Windows is probably the best way to go.

**Comment by covici** [comment]
OK, thanks.  Which securityh setting should be changed?

Joshua Lund <notifications@github.com> wrote:

> I removed the attached file too. It looks like the only way to make IE work is to change its default security settings. Using a different browser on Windows is probably the best way to go.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/340#issuecomment-225784263
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com
