### ISSUE TITLE
OpenVPN + STunnel Slow DNS Lookup

### ISSUE THREAD

**Issue by williclarkam** [jlund/streisand#341]
Hello,

Thank you Sir for this outstanding work.
OpenVPN direct doesn't work where I live, so I have to use OpenVPN + STunnel, and it connects perfectly without any issues, but the DNS lookup time it's high! for example, when I enter github.com it took about 5 - 10 seconds to resolve the name!

Best regards,
william

**Comment by jlund** [comment]
Hey, William. Thanks for the positive feedback! Which provider are you using, and in which region? I can try to recommend some DNS servers that may work better than the default of Google Public DNS.

**Comment by williclarkam** [comment]
Hi Sir,
sorry for the delay.
I am using Vultr - Frankfurt. (768 MB RAM - 1 Core)
Actually I have found the problem, `block-outside-dns` is causing the problem! When I remove this line, DNS Server resolves the website fast, but then DNS Leak happens! So I am not sure, whether this issue is related to OpenVPN or Windows 10.
So I am pretty sure that your awesome script doesn't have any issue.
Is there any alternatives to stop DNS leakage without using `block-outside-dns` ?

Thanks

**Comment by williclarkam** [comment]
Okay, So after some time, like 10 Minutes, the DNS lookup will be okay again, could not find what caused the issue, but everything looks to work properly, hence closing this issue.
Sorry man, and thanks for your OUTSTANDING work.
