### ISSUE TITLE
iphone cannot connect to l2tp server

### ISSUE THREAD

**Issue by covici** [jlund/streisand#342]
Hi.  Using an iPhone 6+, I cannot connect to my l2tp server.  If I am using my wifi, the connection times out, if I turn the wifi off, it says the server is unreachable immediately rather than timing out.  The browser connects fine.  Do I have to listen on any additional ports in my router (actually the Linux box)?  Seems strange that with wifi off, it says unreachable.

Thanks.

**Comment by jlund** [comment]
That does seem strange. In #348 you mentioned that you're able to get your Mac to connect successfully. You may be running into the same issue here. L2TP/IPsec really struggles with multiple connections from clients that are coming from the same source IP.

I'll be adding IKEv2 support via Libreswan soon. In addition to just being a better protocol in general, it's also much better at dealing with NATs.

In the meantime, I would recommend using one of the other connection options if you would like to have multiple computers and mobile devices connected simultaneously. OpenVPN, OpenConnect/AnyConnect, etc. will all handle this, no problem.

**Comment by covici** [comment]
I did get the iphone to work, but I am glad you mentioned this
limitation of l2tp, since if I am traveling, this might be the case, so
I will await your new addition.


Joshua Lund <notifications@github.com> wrote:

> That does seem strange. In #348 you mentioned that you're able to get your Mac to connect successfully. You may be running into the same issue here. L2TP/IPsec really struggles with multiple connections from clients that are coming from the same source IP.
> 
> I'll be adding IKEv2 support via Libreswan soon. In addition to just being a better protocol in general, it's also much better at dealing with NATs.
> 
> In the meantime, I would recommend using one of the other connection options if you would like to have multiple computers and mobile devices connected simultaneously. OpenVPN, OpenConnect/AnyConnect, etc. will all handle this, no problem.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/342#issuecomment-226907846
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by jlund** [comment]
Cool! I'm working on it.
