### ISSUE TITLE
Apple Configurator not found in Mac App Store - US

### ISSUE THREAD

**Issue by peterood** [jlund/streisand#344]
streisand/generated-docs/streisand.html currently links to https://itunes.apple.com/us/app/apple-configurator/id434433123?mt=12 which returns not found in Mac App Store - US

I believe the link should be updated to https://itunes.apple.com/us/app/apple-configurator-2/id1037126344?mt=12

**Comment by jlund** [comment]
Thanks for the report!

**Comment by peterood** [comment]
Sure thing! Thanks for your work!
