### ISSUE TITLE
AnyConnect broke itself overnight - libgnutls28 missing on Digital Ocean

### ISSUE THREAD

**Issue by emirpprime** [jlund/streisand#345]
Did a vanilla install on Digital Ocean yesterday, and AnyConnect worked fine. This morning it wouldn't connect. I ssh'd in and found ocserv couldn't start because of missing libgnutls.so.28. 
Not sure what happened - maybe an auto-upgrade overnight broke something? Running 'apt-get install libgnutls28' sorted it.
Not sure if this was a freak occurance or something that needs tackling - my linux skills arn't up to much... Let me know if there's anything else I can add to help.

**Comment by jlund** [comment]
I received a few other comments about this, so you're not alone :)

This latest commit should fix it. Thanks for the bug report!
