### ISSUE TITLE
[question] How to add a new server with same certs and passwords

### ISSUE THREAD

**Issue by anonymous--** [jlund/streisand#347]
How can I add a new server with the same loin/certs?
i want to be able to do the following with ease
vpnserver.bla
         |
     vpn server 1
        or
    vpn server 2
via a name records that i already set

**Comment by kydan** [comment]
Currently not supported, but if you search you'll find a few different
issues that detail how replace your SSL cert as well as how to move some
credentials. I'm on a phone or I'd help out with the issue numbers. There
is active discussions on how and if this should be supported

**Comment by cpu** [comment]
This isn't presently supported and I don't believe we have the resources to try and accommodate this specific niche use case. I'm going to close this issue for now. Thanks!
