### ISSUE TITLE
problems connecting windows to vpn server

### ISSUE THREAD

**Issue by covici** [jlund/streisand#348]
Hi.  I am having problems connecting my windows 10 client to a Streisand vpn server I have set up.  This is Windows 10, so some of your instructions were not exact, but I think I got them correct, but maybe not.  What happens when I connect is that it connects for a second and then opens a settings window.  I cleared the signin info, entered the password and the secret key again, but still no joy -- and I entered by copying and pasting from the web page.  So, how to troubleshoot such?  Is there something on the server I can temporarily enable to see what is happening?  I have a MAC on the same network which works fine.

Thanks in advance for any suggestions.

**Comment by jlund** [comment]
One of the limitations of L2TP/IPsec is that you can't have multiple clients connecting from behind the same NAT. If you have a Mac that is currently connected to the server, that might be what is happening.

**Comment by covici** [comment]
Its not connected at the moment, but it might be, so I will try another
method.    Will the open connect work under those circumstances?

Thanks.

Joshua Lund <notifications@github.com> wrote:

> One of the limitations of L2TP/IPsec is that you can't have multiple clients connecting from behind the same NAT. If you have a Mac that is currently connected to the server, that might be what is happening.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/348#issuecomment-226901639
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by covici** [comment]
OK, I managed to connect with open-connect but I had to try 3 times
before it would work and in the course of this I missed the prompt to
select whether the pc is discoverable -- so how can I check/fix after
the fact?

Joshua Lund <notifications@github.com> wrote:

> One of the limitations of L2TP/IPsec is that you can't have multiple clients connecting from behind the same NAT. If you have a Mac that is currently connected to the server, that might be what is happening.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/348#issuecomment-226901639
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by cpu** [comment]
This issue is sufficiently stale that I don't believe it is actionable. If you are still experiencing problems I recommend you open a new issue providing the information the issue template requests. Thanks!
