### ISSUE TITLE
Barcode Scanner (apk) should be mirrored for Android Shadowsocks

### ISSUE THREAD

**Issue by pjrobertson** [jlund/streisand#349]
Shadowsocks for Android requires the 'Barcode Scanner' app to be installed in order to scan the QR Codes generated and displayed in the Streisand HTML docs.

I assume the Shadowsocks Android APK is mirrored by the Streisand server since it is sometimes not possible for people without a VPN to download from the Google Play Store (e.g. in China).
Still, since Bacrode Scanner is also required for the Shadowsocks APK to work fully, a connection to the Play Store is still required at some point, defeating the purpose of the mirrored file.

It would be great if the apk could also be mirrored and instructions added along the lines of "If you want to scan the QR Code, then also install Barcode Scanner alongside Shadowsocks"

A mirror to the Barcode Scanner APK: https://github.com/zxing/zxing/releases

**Comment by df-sh** [comment]
Shadowsocks android actually suggest using a different Barcode scanner

According to their wiki

https://play.google.com/store/apps/details?id=tw.com.quickmark

**Comment by pjrobertson** [comment]
Interesting, does that Barcode Scanner work?
If I try to scan a QR Code without a barcode scanner installed on my phone, it recommends the Barcode Scanner app.
The code does mention the Quickmark barcode scanner. Whichever one works is fine. As long as this one has been tested

https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala#L281 <https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala#L281>

**Comment by df-sh** [comment]
I've used both scanners...  They both work...  I've had less problems among
a vast variety of roms with quickmark rather than zxing.. And even though
zxing was the official Google bar code scanner at some point...  The
chinese name deters some of my more skeptical expats from using it.

**Comment by pjrobertson** [comment]
> The chinese name deters some of my more skeptical expats from using it.

Doesn’t zxing stand for ‘zebra crossing’?!

**Comment by df-sh** [comment]
Haha that it does...  But that doesn't stop them from thinking it's Chinese
malware...  I am based in china and for most of the expats I deal with,  if
it looks Chinese it probably is.

Even though shadowsocks was developed by a Chinese citizen... I try to help
assuage their fears but you know how it is...
On Jun 20, 2016 2:59 PM, "Patrick Robertson" <notifications@github.com>
wrote:

> The chinese name deters some of my more skeptical expats from using it.

Doesn’t zxing stand for ‘zebra crossing’?!


> On 20 Meh 2016, at 14:35, df-sh <notifications@github.com> wrote:
>
> I've used both scanners... They both work... I've had less problems among
> a vast variety of roms with quickmark rather than zxing.. And even though
> zxing was the official Google bar code scanner at some point... The
> chinese name deters some of my more skeptical expats from using it.
> On Jun 20, 2016 2:32 PM, "Patrick Robertson" <notifications@github.com>
> wrote:
>
> > Interesting, does that Barcode Scanner work?
> > If I try to scan a QR Code without a barcode scanner installed on my
> > phone, it recommends the Barcode Scanner app.
> > The code does mention the Quickmark barcode scanner. Whichever one works
> > is fine. As long as this one has been tested
> >
> >
> >
https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala#L281
> > <
> >
https://github.com/shadowsocks/shadowsocks-android/blob/master/src/main/scala/com/github/shadowsocks/ProfileManagerActivity.scala#L281
> > >
> >
> > > On 20 Meh 2016, at 14:23, df-sh <notifications@github.com <mailto:
> > notifications@github.com>> wrote:
> > >
> > > Shadowsocks android actually suggest using a different Barcode scanner
> > >
> > > According to their wiki
> > >
> > > https://play.google.com/store/apps/details?id=tw.com.quickmark <
> > https://play.google.com/store/apps/details?id=tw.com.quickmark>
> > >
> > > On Sun, Jun 19, 2016, 9:22 AM Patrick Robertson <
> > notifications@github.com <mailto:notifications@github.com>>
> > > wrote:
> > >
> > > > Shadowsocks for Android requires the 'Barcode Scanner' app to be
> > installed
> > > > in order to scan the QR Codes generated and displayed in the
Streisand
> > HTML
> > > > docs.
> > > >
> > > > I assume the Shadowsocks Android APK is mirrored by the Streisand
> > server
> > > > since it is sometimes not possible for people without a VPN to
download
> > > > from the Google Play Store (e.g. in China).
> > > > Still, since Bacrode Scanner is also required for the Shadowsocks
APK
> > to
> > > > work fully, a connection to the Play Store is still required at some
> > point,
> > > > defeating the purpose of the mirrored file.
> > > >
> > > > It would be great if the apk could also be mirrored and instructions
> > added
> > > > along the lines of "If you want to scan the QR Code, then also
install
> > > > Barcode Scanner alongside Shadowsocks"
> > > >
> > > > A mirror to the Barcode Scanner APK:
> > > > https://github.com/zxing/zxing/releases <
> > https://github.com/zxing/zxing/releases>
> > > >
> > > > —
> > > > You are receiving this because you are subscribed to this thread.
> > > > Reply to this email directly, view it on GitHub
> > > > <https://github.com/jlund/streisand/issues/349 <
> > https://github.com/jlund/streisand/issues/349>>, or mute the thread
> > > > <
> >
https://github.com/notifications/unsubscribe/ALeLWdnGc5L6QPSjlmMGGhsaUUXOlZd_ks5qNJnpgaJpZM4I5Eb7
> > <
> >
https://github.com/notifications/unsubscribe/ALeLWdnGc5L6QPSjlmMGGhsaUUXOlZd_ks5qNJnpgaJpZM4I5Eb7
> > >>
> > > > .
> > > >
> > > —
> > > You are receiving this because you authored the thread.
> > > Reply to this email directly, view it on GitHub <
> > https://github.com/jlund/streisand/issues/349#issuecomment-227059176>,
or
> > mute the thread <
> >
https://github.com/notifications/unsubscribe/AAJLn6gSw9K0CBKN3xOdGiKlJZGXsA4cks5qNjHzgaJpZM4I5Eb7
> > >.
> > >
> >
> > —
> > You are receiving this because you commented.

> > Reply to this email directly, view it on GitHub
> > <https://github.com/jlund/streisand/issues/349#issuecomment-227060307>,
> > or mute the thread
> > <
https://github.com/notifications/unsubscribe/ALeLWR_grGn5uXKm-i7PuxPt1fX7cQzzks5qNjPrgaJpZM4I5Eb7
>
> > .
> >
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub <
https://github.com/jlund/streisand/issues/349#issuecomment-227060795>, or
mute the thread <
https://github.com/notifications/unsubscribe/AAJLn8eRx3wyBzh3Z0PqvF_QojPM04Suks5qNjSzgaJpZM4I5Eb7
>.
>

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jlund/streisand/issues/349#issuecomment-227064098>, or mute
the thread
<https://github.com/notifications/unsubscribe/ALeLWdGt-5C6r9bLZ9h6EwbrtL5z3DXEks5qNjo5gaJpZM4I5Eb7>
.

**Comment by pjrobertson** [comment]
So it seems some latest changes to the Shadowsocks Android APK [integrates a barcode scanner](https://github.com/shadowsocks/shadowsocks-android/commit/a537a7fc0a0ca339e53936f49e49088eddd8762d) so this issue was a little premature :)

It doesn't seem to work for me right now, but I'm guessing it might work for others.
Once my latest PR is merged and v2.10.5 of the Shadowsocks Android APK is mirrored, this can be closed

**Comment by pjrobertson** [comment]
@jlund any chance this can be re-opened? It seems the latest Shadowsocks APKs have removed the built-in barcode scanner, and you're left with the message "please install a zxing-compliant QR code scanning app". Would be great to have a mirror for the app.

Seems the change was made in https://github.com/shadowsocks/shadowsocks-android/commit/d78e823ce2013bffc29079a0465a88f74de42ece

**Comment by cpu** [comment]
@pjrobertson Thanks for flagging - reopened.

**Comment by pjrobertson** [comment]
I am also in discussion with the Shadowsocks android devs to see if they can re-instate it.
See https://github.com/shadowsocks/shadowsocks-android/issues/1273#issuecomment-306075798 for more details

**Comment by cpu** [comment]
@pjrobertson The Shadowsocks Android folks cut a 4.1.8 release a few hours ago that restores the QR code scanner. I opened a PR to bump the Streisand mirror accordingly: https://github.com/jlund/streisand/pull/727

Thanks for doing the legwork with upstream, I appreciate it!

**Comment by pjrobertson** [comment]
Awesome, they're quick workers over there... as are you here!

Glad to see this change in, and I'm glad I could help out in a small way!
