### ISSUE TITLE
vpn server will not stay connected

### ISSUE THREAD

**Issue by covici** [jlund/streisand#351]
Hi.  I installed Streisand on my ubuntu 14.4 server and at least on the network I am using now, it does not stay connected for very long.  I am using an iPhone 6+ and the server I installed a couple of weeks ago.  Sometimes I get a dialog saying pop not responding and sometimes it just dies.  Should I use another method ?

Thanks in advance for any suggestions.

**Comment by kydan** [comment]
Which method are you using? What vps provider are you using, if any? What
country are you based in? Is this on wifi or mobile data? Lots more details
needed. There are many factors why this may be the case.

**Comment by covici** [comment]
I was using l2tp, and a serrver I set up on ubuntu  14.4.  It was a wifi
in a hotel in Utah.  I can no longer test it as I didn't see the email
till I left the hotel, but I am trying other methods in general to see
if they work better.

Nick Clarke <notifications@github.com> wrote:

> Which method are you using? What vps provider are you using, if any? What
> country are you based in? Is this on wifi or mobile data? Lots more details
> needed. There are many factors why this may be the case.
> On Jun 21, 2016 9:47 PM, "covici" <notifications@github.com> wrote:
> 
> > Hi. I installed Streisand on my ubuntu 14.4 server and at least on the
> > network I am using now, it does not stay connected for very long. I am
> > using an iPhone 6+ and the server I installed a couple of weeks ago.
> > Sometimes I get a dialog saying pop not responding and sometimes it just
> > dies. Should I use another method ?
> >
> > Thanks in advance for any suggestions.
> >
> > —
> > You are receiving this because you are subscribed to this thread.
> > Reply to this email directly, view it on GitHub
> > <https://github.com/jlund/streisand/issues/351>, or mute the thread
> > <https://github.com/notifications/unsubscribe/ACE5KC7Wym0NouO94rFnhsNzw7aULd7wks5qN-t9gaJpZM4I6wMV>
> > .
> >
> 
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/351#issuecomment-227482081
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by jlund** [comment]
iOS does not allow VPN connections to remain running in the background. Some clients, like the official OpenVPN app, will automatically attempt to reconnect when the phone wakes up, but the built-in L2TP/IPsec support in iOS does not.

Hopefully Apple provides a little more flexibility in future versions of the operating system, but the requirement to manually reestablish a L2TP/IPsec VPN connection after a period of inactivity is just the way things work right now on iOS, unfortunately.

**Comment by covici** [comment]
Oh, I had no idea of that.  Very strange.

Joshua Lund <notifications@github.com> wrote:

> iOS does not allow VPN connections to remain running in the background. Some clients, like the official OpenVPN app, will automatically attempt to reconnect when the phone wakes up, but the built-in L2TP/IPsec support in iOS does not.
> 
> Hopefully Apple provides a little more flexibility in future versions of the operating system, but the requirement to manually reestablish a L2TP/IPsec VPN connection after a period of inactivity is just the way things work right now on iOS, unfortunately.
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/351#issuecomment-230109730
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com
