### ISSUE TITLE
problem with openconnect on ios9

### ISSUE THREAD

**Issue by covici** [jlund/streisand#352]
Hi.  The open connect install on ios9 does not accept the password provided in the instructions.  It works fine on the mac, but does not work on ios.  I copied and pasted the password, but it was not accepted.

**Comment by covici** [comment]
To make this a bit clearer, this was using the install on Ubuntu 14.4 server.

**Comment by jlund** [comment]
I can't reproduce this. The password seems to work just fine for me.

In any event, you probably want to follow the iOS configuration instructions and use the certificate-based method of authentication. The iOS AnyConnect client doesn't support saving the passphrase, which means you have to type it in manually every time you connect. Combined with the fact that iOS does not allow VPN connections to remain running in the background, this means that you would have to type the passphrase _a lot_ :)

**Comment by covici** [comment]
It was exactly in the certificate that the password was not recognized,
but I have gone to using openvpn which does not have the problem, but it
seemed strange to me, so I made the issue.

Joshua Lund <notifications@github.com> wrote:

> I can't reproduce this. The password seems to work just fine for me.
> 
> In any event, you probably want to follow the iOS configuration instructions and use the certificate-based method of authentication. The iOS AnyConnect client doesn't support saving the passphrase, which means you have to type it in manually every time you connect. Combined with the fact that iOS does not allow VPN connections to remain running in the background, this means that you would have to type the passphrase _a lot_ :)
> 
> ---
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub:
> https://github.com/jlund/streisand/issues/352#issuecomment-231447811
> 
> ----------------------------------------------------
> Alternatives:
> 
> ----------------------------------------------------

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com
