### ISSUE TITLE
openvpn documentation problem

### ISSUE THREAD

**Issue by covici** [jlund/streisand#353]
Hi.  Using the openvpn direct instructions for ios, it was a bit confusing that you had to download the profiles on a computer rather than the phone itself and then transfer them.  It could be a bit clearer.

Thanks.

**Comment by cpu** [comment]
@covici Can you suggest improved language?

**Comment by covici** [comment]
Its been so long that I forget what the issue is about.

On Fri, 16 Jun 2017 18:11:59 -0400,
Daniel McCarney wrote:
> 
> [1  <text/plain; UTF-8 (7bit)>]
> [2  <text/html; UTF-8 (7bit)>]
> @covici Can you suggest improved language?
> 
> ―
> You are receiving this because you were mentioned.
> Reply to this email directly, view it on GitHub, or mute the thread.
> 

-- 
Your life is like a penny.  You're going to lose it.  The question is:
How do
you spend it?

         John Covici
         covici@ccs.covici.com

**Comment by cpu** [comment]
@covici No problem - apologies for letting it sit for so long. I'm going to close it for now. Thanks!
