### ISSUE TITLE
Documentation Update for sshuttle on OSX / Linux

### ISSUE THREAD

**Issue by unstatusthequo** [jlund/streisand#363]
Noticed in the OSX/Linux directions Step 6 for , they said to use: .`/src/sshuttle --dns -r forward@streisand 0/0 -vv`
When it should really be: `
./run --dns -r forward@streisand 0/0 -vv`
(at least on OSX) 

Also, it would be good to put a line in there to chmod the streisand_rsa to be read-write by owner only and not anyone else, or sshuttle will ignore the key and fail to connect. 

Works great with those two modifications.

**Comment by jlund** [comment]
Thanks!
