### ISSUE TITLE
cannot install

### ISSUE THREAD

**Issue by gvsurenderreddy** [jlund/streisand#364]
Thanks for the great software.
--limit @playbooks/digitalocean.retry
I have tried several times i just fails or make new IPS from digital ocean but cannot go further than this.

How can i install manual without ANisible please.

**Comment by andreagrax** [comment]
Hello,
Ansible is doing the heavy work, so you need it.
Can you show the error that you are having?
Andrea

**Comment by gvsurenderreddy** [comment]
root@pptp:~/streisand# ./streisand

  S T R E I S A N D

Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: 2


What region should the server be located in?
  1.  Amsterdam        (Datacenter 2)
  2.  Amsterdam        (Datacenter 3)
  3.  Bangalore
  4.  Frankfurt
  5.  London
  6.  New York         (Datacenter 1)
  7.  New York         (Datacenter 2)
  8.  New York         (Datacenter 3)
  9.  San Francisco    (Datacenter 1)
  10. San Francisco    (Datacenter 2)
  11. Singapore
  12. Toronto
Please choose the number of your region. Press enter for default (#2)
region.
 [2]: 2

What should the server be named? Press enter for default (streisand).
 [streisand]:


New API access tokens can be generated in the DigitalOcean control panel.
https://cloud.digitalocean.com/settings/applications
  * When generating a new token, please note that the Write Scope is
necessary
    in order to create Droplets.

What is your DigitalOcean Access Token?
: 4560833928027f6d23349491b71ac368bfa953f688906c076f690b3148e5c36d


The following information can be found on your DigitalOcean control panel.
https://cloud.digitalocean.com/settings/security

What is the name of the DigitalOcean SSH key that you would like to use?
  * If you have never uploaded an SSH key to DigitalOcean then the default
    value will work!
  * This key should match your .ssh/id_rsa.pub file.
  * DigitalOcean requires SSH keys to be unique. You cannot upload multiple
    keys that have the same value under different names.

    If you see an error that says 'SSH Key failed to be created' once the
setup
    process starts, then this is the problem. You can retry the setup
process
    using the name of the existing SSH key from the DigitalOcean control
panel
    that matches the contents of your RSA public key.
 [streisand]: streisand

Streisand will now set up your server. This process usually takes around
ten minutes. Press Enter to begin setup...
:

PLAY [Provision the DigitalOcean Server]
***************************************

TASK [setup]
*******************************************************************
ok: [162.243.240.77]

TASK [genesis-digitalocean : Get the default SSH key]
**************************
changed: [162.243.240.77]

TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't
already exist] ***
ok: [162.243.240.77]

TASK [genesis-digitalocean : Create the new Droplet]
***************************
changed: [162.243.240.77]

TASK [genesis-digitalocean : Wait until the server has finished booting and
OpenSSH is accepting connections] ***
ok: [162.243.240.77]

TASK [genesis-digitalocean : Create the in-memory inventory group]
*************
changed: [162.243.240.77]

TASK [genesis-digitalocean : Set the streisand_ipv4_address variable]
**********
ok: [162.243.240.77]

TASK [genesis-digitalocean : Set the streisand_server_name variable]
***********
ok: [162.243.240.77]

PLAY [Configure the Server and install required software]
**********************

TASK [setup]
*******************************************************************
fatal: [188.166.52.29]: UNREACHABLE! => {"changed": false, "msg": "SSH
Error: data could not be sent to the remote host. Make sure this host can
be reached over ssh", "unreachable": true}
to retry, use: --limit @playbooks/digitalocean.retry

PLAY RECAP
*********************************************************************
162.243.240.77             : ok=8    changed=3    unreachable=0    failed=0
188.166.52.29


I did try again and it fails again.

**Comment by gvsurenderreddy** [comment]
root@pptp:~/streisand# ./streisand

  S T R E I S A N D

Which provider are you using?
  1. Amazon
  2. DigitalOcean
  3. Google
  4. Linode
  5. Rackspace
: 2


What region should the server be located in?
  1.  Amsterdam        (Datacenter 2)
  2.  Amsterdam        (Datacenter 3)
  3.  Bangalore
  4.  Frankfurt
  5.  London
  6.  New York         (Datacenter 1)
  7.  New York         (Datacenter 2)
  8.  New York         (Datacenter 3)
  9.  San Francisco    (Datacenter 1)
  10. San Francisco    (Datacenter 2)
  11. Singapore
  12. Toronto
Please choose the number of your region. Press enter for default (#2)
region.
 [2]: 1

What should the server be named? Press enter for default (streisand).
 [streisand]:


New API access tokens can be generated in the DigitalOcean control panel.
https://cloud.digitalocean.com/settings/applications
  * When generating a new token, please note that the Write Scope is
necessary
    in order to create Droplets.

What is your DigitalOcean Access Token?
: 4560833928027f6d23349491b71ac368bfa953f688906c076f690b3148e5c36d


The following information can be found on your DigitalOcean control panel.
https://cloud.digitalocean.com/settings/security

What is the name of the DigitalOcean SSH key that you would like to use?
  * If you have never uploaded an SSH key to DigitalOcean then the default
    value will work!
  * This key should match your .ssh/id_rsa.pub file.
  * DigitalOcean requires SSH keys to be unique. You cannot upload multiple
    keys that have the same value under different names.

    If you see an error that says 'SSH Key failed to be created' once the
setup
    process starts, then this is the problem. You can retry the setup
process
    using the name of the existing SSH key from the DigitalOcean control
panel
    that matches the contents of your RSA public key.
 [streisand]: streisand

Streisand will now set up your server. This process usually takes around
ten minutes. Press Enter to begin setup...
:

PLAY [Provision the DigitalOcean Server]
***************************************

TASK [setup]
*******************************************************************
ok: [localhost]

TASK [genesis-digitalocean : Get the default SSH key]
**************************
changed: [localhost]

TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't
already exist] ***
ok: [localhost]

TASK [genesis-digitalocean : Create the new Droplet]
***************************
changed: [localhost]

TASK [genesis-digitalocean : Wait until the server has finished booting and
OpenSSH is accepting connections] ***
ok: [localhost]

TASK [genesis-digitalocean : Create the in-memory inventory group]
*************
changed: [localhost]

TASK [genesis-digitalocean : Set the streisand_ipv4_address variable]
**********
ok: [localhost]

TASK [genesis-digitalocean : Set the streisand_server_name variable]
***********
ok: [localhost]

PLAY [Configure the Server and install required software]
**********************

TASK [setup]
*******************************************************************
fatal: [146.185.171.105]: UNREACHABLE! => {"changed": false, "msg": "SSH
Error: data could not be sent to the remote host. Make sure this host can
be reached over ssh", "unreachable": true}
to retry, use: --limit @playbooks/digitalocean.retry

PLAY RECAP
*********************************************************************
146.185.171.105            : ok=0    changed=0    unreachable=1    failed=0
localhost

**Comment by gvsurenderreddy** [comment]
Hello sir,
Finally i could get it installed Thanks for the script .Can u please
suggest me how to see the username and password to login into webroswer to
get the details

I  have installed xdc-open it has not open my details  please update me.

**Comment by gvsurenderreddy** [comment]
Hello sir thanks i have fixed all now its working.I need to test it

**Comment by gvsurenderreddy** [comment]
hello sir I have a major issue when i try to create it creates two droplets on DigitalOcean but installs only on one.WHo can i sole solve this please

**Comment by jlund** [comment]
This was an issue with the latest version of Ansible and has already been fixed in the master branch. A git pull will get you the latest code.

**Comment by jlund** [comment]
Let me know if you have any other questions.
