### ISSUE TITLE
Update for HostHatch

### ISSUE THREAD

**Issue by GuBo88** [jlund/streisand#365]
Can the provider:
https://hosthatch.com
be added? They have a server location in HK which should ensure low latency from CN.

Thanks

**Comment by jlund** [comment]
I can look into this. There isn't a native Ansible module for this provider, but if their API is pretty simple it might not be too bad to hack something together using the `curl` module. I'm constantly tempted to do this for Vultr.

**Comment by cpu** [comment]
At present we do not have the resources to support new providers. Please use the [methods described in the README](https://github.com/jlund/streisand#running-streisand-on-other-providers-advanced) for other providers. Thanks!
