### ISSUE TITLE
[question] where can I increase VPS size

### ISSUE THREAD

**Issue by summerjob** [jlund/streisand#366]
I'd like to know where I can change VPS size from 512mb to 1GB?

**Comment by alimakki** [comment]
Which VPS provider are you using?

**Comment by summerjob** [comment]
currently digitalocean

**Comment by alimakki** [comment]
Click on the name of your currently deployed droplet. On the left column you will see a link to Resize.

![doresize](https://cloud.githubusercontent.com/assets/920624/17272799/1ec4688a-566e-11e6-9671-32fce2de2539.png)

**Comment by summerjob** [comment]
Thanks alimakki!

**Comment by Kyslik** [comment]
Its done by using [`size_slug`](https://developers.digitalocean.com/documentation/changelog/api-v2/new-size-slugs-for-droplet-plan-changes/)

and change it in ansible variables `roles/genesis-digitalocean/defaults.main.yaml`, $5 is `s-1vcpu-1gb`.

(This only works when creating new droplet ofc)
