### ISSUE TITLE
Ubuntu 14.04 - ocserv bugs and unreachable gateway

### ISSUE THREAD

**Issue by oleskiewicz** [jlund/streisand#369]
Hi @jlund, thanks for your great work! During installation I ran into the following bugs with:
- `ocserv`:
  - compilation task would not complete - it can be fixed by adding `autogen` to the list of `ocserv` dependencies
  - `ocpasswd` was not found in the path - it builds smoothly, but the executable stays in `/usr/local/src/ocserv-0.11.2/src/ocpasswd/` directory for some reason; can be fixed by manually copying it to `/usr/local/bin/` manually if need be
- `openvpn`:
  - needed to have `apt-transport-https` package installed - fixed by added it to the dependencies list in the common role

Note that these problems only happened on a Scaleway VPS, they went away once I tried again on DigitalOcean.

I got the documentation and a happy success message at the end, however - the gateway is completely unreachable.

ssh works normally, nginx service status is running - *should* I be seeing something if I point my browser to the server IP address? Is there a guide on how to connect to other services? Has anyone had a similar issue before?

**Comment by jlund** [comment]
Thanks for the feedback! It sounds like there are some issues with the default Scaleway VPS image.

The gateway page where the instructions are hosted is only accessible via SSL. So you'd go to https://server-ip-goes-here. I assume you found the instructions in the `generated-docs` folder?

**Comment by oleskiewicz** [comment]
I get different errors depending on the browser in use - in Safari, it is "Safari can't establish a secure connection with https://ip"; in Firefox, it simply says "Connection is Not Secure" at the information icon behind the address bar. I haven't tested different browsers, or a different network connection though.

I have made sure that I have the "Streisand Effect Department" certificate in my keychain… Perhaps I will attempt to reinstall on a fresh server and see if it works.

**Comment by kkingori** [comment]
I've consistently had the same issue of an unreachable gateway, the browser is unable to establish an SSL connection but a restart of the server fixes it.

**Comment by oleskiewicz** [comment]
A full reinstall of the latest version (on 16.04 Digital Ocean image) works flawlessly!

**Comment by jlund** [comment]
Awesome! That's great to hear.

**Comment by kkingori** [comment]
Can confirm, Streisand on 16.04 deploys with no issues.

**Comment by haarts** [comment]
Just to chip in, I've been trying to install on a C1 (arm architecture) from Scaleway. I had to install `apt-transport-https` manually to progress in the playbook. (Ubuntu 16.04)

**Comment by jlund** [comment]
The `apt-transport-https` package is now part of the common setup role and is automatically installed on providers that don't include it by default.
