### ISSUE TITLE
Small install issue (OSX stunnel)

### ISSUE THREAD

**Issue by philcryer** [jlund/streisand#37]
During the OSX stunnel install, after brew install stunnel, running stunnel gives the error:

    ...stunnel[27619]: LOG3[27619:140735268004608]: Cannot create pid file /usr/local/Cellar/stunnel/4.56/var/run/stunnel/stunnel.pid

Don't know if this is a brew issue or what, but it's easily fixed with

    mkdir -p /usr/local/Cellar/stunnel/4.56/var/run/stunnel/

**Comment by philcryer** [comment]
I no longer see this issue, thank you.

**Comment by jlund** [comment]
Thanks for the update. That is good to hear.
