### ISSUE TITLE
Problems with BBC iPlayer Live

### ISSUE THREAD

**Issue by abulgatz** [jlund/streisand#372]
I cannot get live video to play through the BBC iPlayer using a Streisand configured VPN. It doesn't give me the location error message. I get the error: "This content doesn't seem to be working."

Flash gives me this error:

> Error code : EmpBaseErrorVO
> code = 3024
> type = All net connections failed
> detail = 
> 
> severity = critical
> responsibility = Application
> info = 

My Streisand server in Linode London. I have a Mac. I have tried OpenVPN TCP and UDP (through tunneblick) both checking and unchecking the option to route all IPv4 traffic through the VPN. I have tried native L2TP/IPsec. I have tried Shadowsocks. I have tried disabling the ubuntu firewall through ssh and `ufw disable`. No luck

Any help?

**Comment by alimakki** [comment]
It could be BBC themselves blocking Linode's UK IP addresses, doubt it's a problem with Streisand. How long ago did you start seeing this error?

**Comment by abulgatz** [comment]
I only installed Streisand for the first time two days ago.

I first tried installing Streisand on DigitalOcean London, but when I went to the BBC iPlayer, I was still getting the Geo warning, "sorry but you're not in the UK" message.

Then I installed Streisand on Linode London. I no longer get the Geo warning, just the "This content doesn't seem to be working" message. I guess it could still be a blocked IP, but I thought if it were, I'd get the "not in the UK message" maybe not though.

**Comment by DavidWittman** [comment]
@abulgatz Have you tried using a different browser and/or upgrading Flash?

**Comment by DavidWittman** [comment]
@abulgatz You may also want to try disabling Adblock/uBlock/NoScript if you're running them.

**Comment by abulgatz** [comment]
I've already updated flash, disabled uBlock in Chrome and Firefox (not running NoScript), created new Chrome and Firefox profiles, tried Safari, cleared caches and cookies. No luck.

As an update, I purchased ExpressVPN. ExpressVPN offers their own client, but they also provide UDP OpenVPN profiles for all of their different locations, so I plugged those into Tunnelblick. For their locations which are blocked by the BBC, I get the "not in the UK" message, but for their locations that work, they work in all of my browsers.

Because ExpressVPN is working on my computer through Tunnelblick, there probably isn't a problem with my computer. It seems either my Linode IP is being blocked (but I don't get the "not in the UK message") or the configuration of the Streisand server has problems with the BBC iPlayer.

I will keep paying for ExpressVPN for now, but I would much rather run my own server.

I am happy to give someone access to my server if that will help diagnose the problem.

**Comment by iml** [comment]
When an IP is in the UK but blocked you will get that generic error message. I've experienced this with DO's London network as well.

**Comment by jlund** [comment]
Thanks for the report, but I don't think that this is an issue with Streisand. The BBC is doing some pretty crazy things to restrict access to iPlayer, including rumored [detection vans](http://www.telegraph.co.uk/news/2016/08/05/bbc-to-deploy-detection-vans-to-snoop-on-internet-users/) that will roam throughout British streets in an attempt to discover iPlayer users who haven't paid the licensing fee.

Blacklisting DigitalOcean's UK IP space (along with other providers) is a comparatively easy thing for them to do.
