### ISSUE TITLE
Beta testers wanted for Ubuntu 16.04 (Xenial) on DigitalOcean

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#375]
Do you have a DigitalOcean account and a desire to test the latest version of Streisand that has been upgraded to run on Ubuntu 16.04 Xenial? You're in luck!

1. `git clone git@github.com:jlund/streisand.git streisand-xenial`
1. `cd streisand-xenial && git checkout xenial`
1. `./streisand`
1. Choose Option 2 for DigitalOcean and follow the prompts.

In addition to using the latest LTS release, other notable changes include:
* Lots of cleanup and bug fixes.
* A version of Python that natively supports SNI without hacky workarounds!
* An upgraded version of Libreswan.
* The introduction of the obfs4 Tor pluggable transport (to replace the stalwart but fading obfs3 protocol).
* ...and many more! (31 commits and counting)

I haven't finished converting the launch process for other providers yet, and I still have a number of things to complete before this gets released, but that list is getting smaller and I think it's ready for the brave among you to try out.

Thanks in advance for your help and feedback.

**Comment by TheNomad11** [comment]
Is this an beginner-friendly easy one-click install? No need for all the hassle as in the previous version (using remote machine etc)? In this case I'd be happy to try. I wasn't able to get the previous version running

**Comment by kydan** [comment]
I can probably hop on this band wagon. I'll spin a new instance in the next
few days and report back.

Nick

**Comment by bozogeek** [comment]
I am having a permissions issue. Not sure why.

`Warning: Permanently added 'github.com,192.30.253.XXX' (RSA) to the list of known hosts.
Permission denied (publickey).
fatal: Could not read from remote repository.

Please make sure you have the correct access rights
and the repository exists.`

**Comment by johnvelan** [comment]
Works well. Took about 45 minutes. Ran through clean on DO SF1. OpenVPN, OpenVPN stunnel and Shadowsocks working (rest not tested).

**Comment by c0state** [comment]
Provisioning looks successful--took about 20 minutes to provision an instance on DigitalOcean region NYC3 (from NYC location). 

===== Failed
L2TP/IPsec VPN service didn't work. Pluto process was running. /var/log/ppp.log shows the following error (from my last connection attempt, IPs obfuscated). Not familiar enough to investigate further.
```
Sun Aug  7 13:07:16 2016 : publish_entry SCDSet() failed: Success!
Sun Aug  7 13:07:16 2016 : publish_entry SCDSet() failed: Success!
Sun Aug  7 13:07:16 2016 : l2tp_get_router_address
Sun Aug  7 13:07:16 2016 : l2tp_get_router_address 1yy.yyy.yyy.yyy from dict 1
Sun Aug  7 13:07:16 2016 : L2TP connecting to server '1xx.xxx.xxx.xxx' (1xx.xxx.xxx.xxx)...
Sun Aug  7 13:07:16 2016 : IPSec connection started
Sun Aug  7 13:07:16 2016 : IPSec phase 1 client started
Sun Aug  7 13:07:16 2016 : IPSec phase 1 server replied
Sun Aug  7 13:07:46 2016 : IPSec connection failed
```
==========

===== Works
OpenVPN Direct looks good.
==========

Will update as I test more services.

**Comment by jzorn** [comment]
Apparently, ipsec does not start after a machine reboot; I had to manually start it using `ipset setup start`. (DigitalOcean, Ubuntu 16.04.1 x64, Amsterdam 2)

**Comment by jlund** [comment]
Thanks for all of the feedback. Ubuntu 16.04 support was just merged into the master branch.
