### ISSUE TITLE
No connection after restarting a stopped AWS EC2 instance

### ISSUE THREAD

**Issue by tamberg** [jlund/streisand#380]
Installing and deploying Streisand to AWS EC2 worked like a charm. To prevent hosting cost while not in use, I stopped the AWS EC2 instance. After starting the AWS EC2 instance again later on, the Tunnelblick OSX client no longer seems able to connect. Is this expected, or should the server work again after stopping and restarting the AWS EC2 instance?

**Comment by jlund** [comment]
Hm. I can't seem to reproduce this one either. Did the Elastic IP remain attached to the instance while it was stopped?

**Comment by kevinchau** [comment]
I'm also having this issue - Everything would connect except Tunnelblick (both Direct & stunnel), I went to reboot my EC2 instance, and now nothing will connect, including L2TP.

**Comment by bpinto** [comment]
Experiencing the same problem also on AWS. I can't connect using OpenVPN after starting my machine (it worked correctly when it was created) and I'm using the same IP (elastic IP).

**Comment by tamberg** [comment]
@jlund, yes, public IP did "remain attached to the instance while it was stopped".

**Comment by bdon** [comment]
Having the same problem on AWS. Ran fine for roughly a week and then became unreachable even after reboot (needed to stop -> force stop instance). Was also using L2TP successfully before. Elastic IP is still associated

**Comment by gladiator26** [comment]
I am also having the same outcome after changing the instance type from the free one to a t2.medium. Not sure how to troubleshoot.

**Comment by FLIINO** [comment]
Same here, after a clean install on AWS and then rebooting the machine it becomes unreachable.

PS. I've noted that if the name given in the configuration phase has a blank space it aborts the install, "Family VPN" doesn't work but "Family-VPN" is fine.

**Comment by FlyClover** [comment]
I'm seeing similar issue on GCE #414 . The hard part of debugging this problem is that I cannot even ssh into the instance to get the logs.

**Comment by jlund** [comment]
This should be resolved and I can no longer reproduce this. Can someone who was affected please test and confirm?
