### ISSUE TITLE
Streisand stopping at Install Nginx

### ISSUE THREAD

**Issue by denoza** [jlund/streisand#381]
My Streisand setup is giving me a fatal error, on DO SF Data center 2, I am sharing the error message as under:

`fatal: [xxx]: FAILED! => {"cache_update_time": 0, "cache_updated": false, "changed": false, "failed": true, "msg": "'/usr/bin/apt-get -y -o \"Dpkg::Options::=--force-confdef\" -o \"Dpkg::Options::=--force-confold\"     install 'nginx'' failed: E: There are problems and -y was used without --force-yes\n", "stderr": "E: There are problems and -y was used without --force-yes\n", "stdout": "Reading package lists...\nBuilding dependency tree...\nReading state information...\nThe following packages were automatically installed and are no longer required:\n  apache2-data libgnutls-xssl0 libgnutlsxx28 nettle-dev ssl-cert\nUse 'apt-get autoremove' to remove them.\nThe following NEW packages will be installed:\n  nginx\n0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.\nNeed to get 639 kB of archives.\nAfter this operation, 2386 kB of additional disk space will be used.\nWARNING: The following packages cannot be authenticated!\n  nginx\n", "stdout_lines": ["Reading package lists...", "Building dependency tree...", "Reading state information...", "The following packages were automatically installed and are no longer required:", "  apache2-data libgnutls-xssl0 libgnutlsxx28 nettle-dev ssl-cert", "Use 'apt-get autoremove' to remove them.", "The following NEW packages will be installed:", "  nginx", "0 upgraded, 1 newly installed, 0 to remove and 7 not upgraded.", "Need to get 639 kB of archives.", "After this operation, 2386 kB of additional disk space will be used.", "WARNING: The following packages cannot be authenticated!", "  nginx"]}`

**Comment by Impulss** [comment]
I too am also getting that issue on DO.

**Comment by MartiUK** [comment]
I can confirm I am having this issue too with GCE europe-west1-b.

**Comment by MartiUK** [comment]
Looks like the key needs to be updated: 
http://nginx.org/keys/nginx_signing.key
is visibly newer than the one here: 
https://github.com/jlund/streisand/blob/master/playbooks/roles/nginx/files/nginx_signing.key

**Comment by willbank** [comment]
Mine also - could someone post the right process for re-running the Nginx installation part of the Streisand process once this failure has happened?

(Also, presumably due to the early termination from this failure, I have no `generated-docs` folder...)

**Comment by willbank** [comment]
I have been able to successfully install Nginx from ssh into the streisand box but I need to run the streisand configuration on it so that it completes the full installation and provides the streisand.html in the generated-docs folder... :-(

**Comment by MartiUK** [comment]
You could apply the changes I've made in #382 and rerun it over the same server, I've had no issues doing that.

**Comment by bethnull** [comment]
Hi, it worked for me but not in an existing droplet where nginx has failed to install, however in a new one it works.

Thanks.

**Comment by MartiUK** [comment]
@bethnull Ah okay, re-running it might only work with GCE.

**Comment by Impulss** [comment]
I couldn't rerun on DO either, I had to create a new droplet. It's so trivially easy it wasn't really a problem

Thanks for your help @MartiUK

**Comment by jlund** [comment]
Sorry that this was outstanding for a couple of days. I just got back into town :)

Thanks for the fix, @MartiUK!
