### ISSUE TITLE
Other Provider Issues

### ISSUE THREAD

**Issue by hacakir** [jlund/streisand#384]
```
root@if2:/streisand# ansible-playbook playbooks/streisand.yml

PLAY [Prepare the new server for Ansible] **************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
fatal: [2xx.xx.xxx.xx2]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
        to retry, use: --limit @playbooks/streisand.retry

PLAY RECAP *********************************************************************
2xx.xx.xxx.xx2             : ok=0    changed=0    unreachable=1    failed=0

```

Ubuntu 16.04 64 Bit @ time4vps

**Comment by jlund** [comment]
This means that Ansible wasn't able to establish an SSH connection to the server and things failed before the Streisand playbook even started running. Can you give me an example of an SSH command that works on this server?

**Comment by avanvoorhis** [comment]
@jlund @hacakir On a DO instance had the same issue as above. What worked for me was to login to DO account. Goto Username>Settings>Security>SSH Keys, Then remove my old streisand ssh key. Reran the script and everything installed perfectly.

**Comment by hacakir** [comment]
@jlund i don't now. how can i get this list? login as root.

**Comment by jlund** [comment]
@hacakir When you SSH to a new DigitalOcean server, how do you do it? Do you have to pass any additional flags to the SSH command?

**Comment by hacakir** [comment]
@jlund no at digitalocean.

**Comment by hacakir** [comment]
root@vps:~/streisand# ansible-playbook playbooks/streisand.yml

PLAY RECAP *********************************************************************

I'm still trying, but it is not. :/

**Comment by brackenhill-mob** [comment]
Just ran into the same problem. Solution is easy ;)

The contents of ~/.ssh/id_rsa.pub on the local PC need to be copied to /root/.ssh/authorized_keys on the target server (assuming root is your user name)

HTH

**Comment by cpu** [comment]
This issue is stale and I believe the checks done by the "existing server" provisioning [described in the README](https://github.com/jlund/streisand#running-streisand-on-other-providers-advanced) will ensure SSH keys are present where expected and can be used to connect to the server that you are trying to provision. I'm going to close this issue - thanks!
