### ISSUE TITLE
streisand.yml does not take into account the remote_user

### ISSUE THREAD

**Issue by pydo** [jlund/streisand#389]
I modified the streisand.yml's remote_users to take into account the user I was using on my vps.
When running ansible-playbook playbooks/streisand.yml it had no effect.

The ansible script didn't SSH as the correct user so it fails to even connect.

```
ansible-playbook playbooks/streisand.yml 

PLAY [Prepare the new server for Ansible] **************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***

fatal: [000.00.000.00]: FAILED! => {"changed": false, "failed": true, "rc": 100, "stderr": "", "stdout": "W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)\r\nE: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)\r\nE: Unable to lock directory /var/lib/apt/lists/\r\nW: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)\r\nW: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)\r\nE: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)\r\nE: Unable to lock the administration directory (/var/lib/dpkg/), are you root?\r\n", "stdout_lines": ["W: chmod 0700 of directory /var/lib/apt/lists/partial failed - SetupAPTPartialDirectory (1: Operation not permitted)", "E: Could not open lock file /var/lib/apt/lists/lock - open (13: Permission denied)", "E: Unable to lock directory /var/lib/apt/lists/", "W: Problem unlinking the file /var/cache/apt/pkgcache.bin - RemoveCaches (13: Permission denied)", "W: Problem unlinking the file /var/cache/apt/srcpkgcache.bin - RemoveCaches (13: Permission denied)", "E: Could not open lock file /var/lib/dpkg/lock - open (13: Permission denied)", "E: Unable to lock the administration directory (/var/lib/dpkg/), are you root?"]}
```
The docs say `The servers should be accessible using SSH keys, and root is used as the connecting user by default (though this is simple to change by updating the streisand.yml file or ansible.cfg file).`
So any ideas on how I can get ansible to connect as the correct user?
 Thanks in advance!

**Comment by jlund** [comment]
Ansible was connecting as the remote user that you specified, but it doesn't escalate privileges by default. This meant that it didn't have permission to run the APT update command (or any of the rest of the tasks). I added a directive to the configuration that makes this easier.

Another way to resolve this would have been by adding `become: yes` underneath the `remote_user` directive in the `streisand.yml` playbook.
