### ISSUE TITLE
[feature request] including ZeroTier

### ISSUE THREAD

**Issue by strixaluco** [jlund/streisand#390]
Wanted to suggest ZeroTier, which is zero-configuration multiplatform software-based FOSS switch.
[Technical FAQ](https://www.zerotier.com/tech_faq.shtml)

Clients:
[ZeroTier One](https://www.zerotier.com/product-one.shtml)
Linux / macOS / Windows / Android / iOS

**Comment by cpu** [comment]
@strixaluco the technical FAQ you linked to is no longer there. It's not clear what need a software based switch addresses for you. Can you expand on your feature request?

**Comment by strixaluco** [comment]
@cpu you can refer to the [manual](https://www.zerotier.com/manual.shtml) instead.
The idea behind feature request is to use ZeroTier protocol as one more type of VPN bundled into Streisand.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/13
