### ISSUE TITLE
Locked out of server after Streisand-install "No matching mac found"

### ISSUE THREAD

**Issue by TheNomad11** [jlund/streisand#391]
It happened every time I tried to install Streisand. After the successful installation I can no longer access the VPS, neither via Terminal (ssh) nor SFTP  - the same result either eI use password or the ssh key. "No matching mac"  is the start of the error message, followed by ciphers like "client hmac-md5,hmac-sha1,umac-64@openssh.com,hmac-ripemd160".  

Is there something I should have done before installing? I remember vaguely I 've had issues before when I tried to restrict vps access to ssh-key only. I am newbie and still learning...

I installed Streisand via http://jerrygamblin.com/2016/07/10/the-vpn-you-should-be-using/

I used a VPS on Digitalocean and Vultr, both with the same result.

Thanks for your help! 

PS: login via web console possible

**Comment by josephlhall** [comment]
Is there a reason you followed those instructions from July rather than the instructions @jlund maintains here on github? Can you try using those instructions?

**Comment by TheNomad11** [comment]
Yes, when I tried the official install one or two months ago, I got stuck, I suppose it was because of incompatability as I am still using a prehistoric Mac OSX 10.7 machine and for some of the tasks a newer version was required if I remember correctly. At that time I found the whole process too geeky. Therefore I was happy to see a simplified version and tried it. I have learned a lot during the recent weeks, though, so I might have a new try but my mac might still be too old...

**Comment by TheNomad11** [comment]
Now I know. I am struggling to get Ansible installed without  X-code, my laptop is too old, and it's a 4GB download… , so therefore I welcome the simplified install by @jgamblin

**Comment by kydan** [comment]
A workaround to your old version of osx would be to use another instance on
whichever VPS service you are using. I think I recall you saying you were
using digital ocean, so this would be another droplet based on Ubuntu
server or debian or whatever you are comfortable with, preferably with a
GUI to easily get at the connection instructions. Then you can install all
the dependencies quickly, spin an instance of Streisand, and then destroy
it once your done.

Perhaps even more simple is to do it from a virtual machine on your laptop,
using virtual box or another hypervisor you like. That's what I do to spin
instances from a Windows machine.

sent from my mobile

**Comment by kkingori** [comment]
You don't need to download the entire Xcode application to install ansible. Install command line tools for Xcode (around 140Mb for osx 10.7).

**Comment by TheNomad11** [comment]
Thanks for your answers, I found old Git and Xcode versions, installed them  but then the process stopped with running Ansible that does not seem to be compatible to OSX 10.7.5

I then tried the install process via a Digital Ocean droplet and I came quite far, I started running./streisand but also here it stopped with the error that others had before

```
TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
fatal: [138.68.79.212]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh.", "unreachable": true}
	to retry, use: --limit @playbooks/digitalocean.retry
```

**Comment by TheNomad11** [comment]
Tried to install it on Vultr, followed the instructions and got the same error message

**Comment by TheNomad11** [comment]
hopeless case, about to give up and stick with the simplified version that locked me out :(

**Comment by kkingori** [comment]
I'm not sure what's going on but I also got that error. Comment out the install python task and try again. Solved it for me.

**Comment by TheNomad11** [comment]
thanks for this suggestion, sorry to ask: Where can I comment out the install pyton task? Thanks again

**Comment by TheNomad11** [comment]
I think I found out now

**Comment by TheNomad11** [comment]
but same result

**Comment by kydan** [comment]
That error is often present when you don't have your SSH key pair properly
configured I believe. Be sure to follow the instructions on how to generate
and add a key pair to digital ocean and ensure it's also on the temporary
host you are using to spin the instance.

On Aug 31, 2016 08:01, "TheNomad11" <notifications@github.com> wrote:

I think I found out now

—
You are receiving this because you commented.

Reply to this email directly, view it on GitHub
<https://github.com/jlund/streisand/issues/391#issuecomment-243773324>, or mute
the thread

**Comment by TheNomad11** [comment]
Thanks for your reply and thanks again for your suggestion to install via another DO-droplet, @kydan That was very helpful. 

Regarding the keys, I've used these keys before (when creating new droplets) and it worked, I doubt this is the issue. I found many users having similar issues with ansible, especially after upgrading to version 2.

**Comment by cpu** [comment]
I believe this issue is sufficiently stale as to be unactionable. If you're still having trouble please open a new issue providing the information requested by the issue template. Thanks!
