### ISSUE TITLE
[question] OPENVPN profile for multiple endpoint 

### ISSUE THREAD

**Issue by andreagrax** [jlund/streisand#392]
Hi All, 
reading here : 
https://community.openvpn.net/openvpn/wiki/Openvpn23ManPage 
and here:  https://forum.pfsense.org/index.php?topic=70746.0 
I see that in the same profile i can specify multiple connection endpoint .
So my idea is to create a profile which use in order 
1. Direct UDP 
2. Direct TCP
3. TCP SSLH
4. stunnel 

so it automatically tries to connect in descending performance order.

tecnically is just one more profile to create.

Any advice against that ?
Obviously my idea is to use it only in "low security" environment , ie public wi-fi , I'm aware that if I'm trying to evade censorship the standard way is the right way .

**Comment by andreagrax** [comment]
tried manually editing the profile  , and it works and automatically fallback in the order  defined int the client config file


below example  with redacted IP

`client`
`remote 1.2.3.4 8757 udp`
`remote 1.2.3.4 636  tcp`
`remote 1.2.3.4 443  tcp`
`remote 127.0.0.1 41194 tcp`
`dev tun`
`cipher AES-256-CBC`
`auth SHA256`

**Comment by alimakki** [comment]
In my opinion, I don't think this is a viable way forward; assume mobile users for instance that don't have stunnel (iOS) for example. A combined profile like that would fail once it hits the last option.

Having separate profiles allows a user to pick and choose the type of connection they want depending on their environment.

If a combined profile works for you however, then all the better :)

**Comment by andreagrax** [comment]
addressed by https://github.com/jlund/streisand/pull/524

**Comment by jlund** [comment]
And #524 was just merged! Thanks for the feature suggestion, @andreagrax!
