### ISSUE TITLE
streisand fails to install openvpn role when removing other server roles

### ISSUE THREAD

**Issue by pydo** [jlund/streisand#393]
I'm using the ansible playbook to install openvpn and stunnel. I've commented out the other roles in the `streisand.yml`. It fails with this error message 

```
TASK [rc-local : Generate rc.local with Firewall and dnsmasq settings for OpenConnect, OpenVPN,  and L2TP/IPsec] ***
fatal: [158.69.204.14]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable:     'ocserv_firewall_rule' is undefined"}
```

The roles I'm currently using:
`- common`
`- openvpn` 
`- stunnel`

It seems to me that the playbooks were written in a monolithic way. It's either I install everything or nothing. Is this the case?

Thanks in advance!

**Comment by jlund** [comment]
There are a few crossover things like this where variables are shared between roles, but they're extremely rare. I think it would a be a good goal to make sure each role can be used independently. It's on the list :)

**Comment by cpu** [comment]
Updated the issue title to reflect the root cause is the removal of some roles with cross dependencies from the openvpn role.

**Comment by cpu** [comment]
Removing Streisand roles is not supported. We are working towards modularization support but in the mean time by removing roles you **will** break Streisand and we can't support you. Thanks!
