### ISSUE TITLE
Shadowsocks - DNS Leak

### ISSUE THREAD

**Issue by hybtoy** [jlund/streisand#394]
Good day, 
Is there any way to point SS to dnsmasq that is already going to be used by OpenVPN?
After several tests, I noted that there is DNS leak on Shadowsocks but there is no with OpenVPN.
![photo900762931437873076](https://cloud.githubusercontent.com/assets/12900872/18248991/04fa671c-7395-11e6-9fe0-ad7777c38c72.jpg)

![photo900762931437873077](https://cloud.githubusercontent.com/assets/12900872/18248629/dfef7acc-7392-11e6-87a2-b49d28a6ea54.jpg)

**Comment by jlund** [comment]
Are you using Potatso?

**Comment by hybtoy** [comment]
Yes.

**Comment by hybtoy** [comment]
I am already in contact with developer and he is aware of issue. 
The only way for is to us Surge. It has dns forwarder but Potatso not. 
But Surge is too expensive. 
Surge - Web Developer Tool and Proxy Utility by Yachen Liu
https://appsto.re/tm/D0Q_9.i

**Comment by ookangzheng** [comment]
u can just add ur server ip in to /etc/resolv.conf in the first line, restart shadowsocks service
than, everything fine ~~

**Comment by paulg1981** [comment]
I am having the same dos leak issue as originally mentioned. My resolve.conf file already has 127.0.0.1 as the first line. I do not experience any dns leaks with openvpn/openconnect. Anything I can do to fix it?  Thanks for any help you can provide.
