### ISSUE TITLE
Nginx is missing, and other features not enabled

### ISSUE THREAD

**Issue by askz** [jlund/streisand#397]
Hi, I've run the playbook on my vps fresh installed.
Nginx isn't installed and when I download manually (sftp) the .ovpn files and try to connect, all of those are saying connection refused.

```console 
# netstat -tlpe
Active Internet connections (only servers)
Proto Recv-Q Send-Q Local Address           Foreign Address         State       User       Inode       PID/Program name
tcp        0      0 *:domain                *:*                     LISTEN      root       60956       6817/dnsmasq    
tcp        0      0 *:ssh                   *:*                     LISTEN      root       15257       2065/sshd       
tcp        0      0 *:8888                  *:*                     LISTEN      root       76573       10616/tinyproxy 
tcp        0      0 localhost.localdom:8388 *:*                     LISTEN      root       72736       9657/ss-server  
tcp6       0      0 [::]:domain             [::]:*                  LISTEN      root       60958       6817/dnsmasq    
tcp6       0      0 [::]:ssh                [::]:*                  LISTEN      root       15266       2065/sshd  
```
What I missed? 
The playbook reported only one error concerning AppArmor missing, but I think this doesn't matters.
Thanks for your help and this awesome project!

**Comment by jlund** [comment]
What provider and Linux distribution are you using?

**Comment by askz** [comment]
Hetzner (CX10 vps) with Ubuntu 16.06.
I finally managed to have the full install when I added nginx in streisand playbook....

**Comment by jlund** [comment]
Hm. Nginx [gets included here](https://github.com/jlund/streisand/blob/master/playbooks/roles/streisand-gateway/meta/main.yml). Can you detail the steps that you took so that I can try to reproduce the problem?

**Comment by TychoSchenkeveld** [comment]
I have this issue too - Ubuntu 16.04 on Scaleway.

No nginx installed, also no generated_docs folder on the installing server so I don't know how it's supposed to work. I also got the AppArmor error by the way. I'll try it again now but installing AppArmor first, manually.

I simply followed the instructions under "Running Streisand on Other Providers"

**Comment by jlund** [comment]
AppArmor is now part of the common package list and this issue should be resolved.

@TychoSchenkeveld Thanks!
