### ISSUE TITLE
Make sure distribution warning is shown on Ubuntu 16.10

### ISSUE THREAD

**Issue by damongant** [jlund/streisand#398]
As it's currently set up in /playbooks/roles/common/tasks/main.yml, Ubuntu 16.10 users will not be warned that the installation might fail.

**Comment by cpu** [comment]
@damongant Can you clarify what needs to be changed to fix this? What is the issue with the current set up?

**Comment by cpu** [comment]
Going to close this - not enough information to address without setting up a 16.10 machine. We can reopen if someone has reproduction details and a proposed fix.

**Comment by damongant** [comment]
https://github.com/jlund/streisand/blob/master/playbooks/roles/common/tasks/main.yml#L5

Only checking the major version means this test passes two versions of Ubuntu, in this case 16.04 and 16.10.

**Comment by cpu** [comment]
@damongant Thanks for clarifying. I believe #774 will resolve this, can you test?
