### ISSUE TITLE
azure troubles

### ISSUE THREAD

**Issue by psifertex** [jlund/streisand#4]
Was trying a manual setup of a streisand instance on azure, but unfortunately, it looks like obfsproxy port changes and needs to be added manually, but this hangs the setup process? Or maybe that step takes a long time.

Additionally, the correct external IP address (which is specified manually in my inventory) isn't used for some of the service configurations, but rather, the internal IP address of the azure node is, which isn't helpful since it won't be routable.

**Comment by joaocc** [comment]
Hi.
I started working on Azure support here (https://github.com/joaocc/jlund--streisand/commit/95fba5648c35a2410913f81bed8c0ea141277544).
It may take a few days, and all help is welcomed.
J

**Comment by blotzu** [comment]
Hi guys, I finished the Azure implementation here: (https://github.com/jlund/streisand/pull/598)

**Comment by jlund** [comment]
Azure support was just merged into the master branch. Thanks to @blotzu and @joaocc for making it happen!
