### ISSUE TITLE
Add SmartDNS technology 

### ISSUE THREAD

**Issue by AriaShishegaran** [jlund/streisand#403]
hey there, is it possible to add any SmartDNS technology into the mix? something that can bypass websites like Netflix? there are providers out there who offer this kind of service, i wanted to know if it is possible to implement a similar open source solution or not and if yes would we see this in Streisand or not?

**Comment by cpu** [comment]
>  if yes would we see this in Streisand or not?

Hard to say without it existing :-) If you find a specific project you think would be worth including you should open a feature request for that software. I'm going to close this issue for now since it's not actionable. Thanks!
