### ISSUE TITLE
US-West2 (Oregon) Instances reachability check fails

### ISSUE THREAD

**Issue by nickkilla** [jlund/streisand#406]
Set up 3 new instances at the AWS US West 2 region and while they start fine and all is good, within 2-4 hours the status check fails and states:

These checks monitor your software and network configuration for this instance.
Instance reachability check failed at September 20, 2016 at 8:02:00 AM UTC+8 (4 hours and 23 minutes ago)

I kill the instance and rerun Streisand and the same thing occurs in a few hours. Not sure if the firewall is having issues or what, but the server is unreachable from outside connections (http, ssh etc).

[root:~/.ssh]# ssh -i ~/.ssh/id_rsa ubuntu@52.10.XX.XX
ssh_exchange_identification: read: Connection reset by peer
[root:~/.ssh]#

**Comment by kapr1k0rn** [comment]
Same thing happened to me, my instance has been running without issue for 2 weeks. So it's something wrong with the Oregon servers?

**Comment by pravindahal** [comment]
Happened to me too in ap-southeast-1 and us-east-1.

**Comment by VerTiGoEtrex** [comment]
Same here

**Comment by jlund** [comment]
This should be fixed. Can someone who was affected by this please confirm?
