### ISSUE TITLE
add apt-transport-https to prereqs

### ISSUE THREAD

**Issue by saveyour** [jlund/streisand#407]
the package apt-transport-https is needed on ubuntu for:

TASK [openvpn : Add the official OpenVPN repository] ***************************

also something people building this in a lxc container might run into is missing a tun/tap device. that can be solved by following these steps:  http://heider.io/blog/2013/10/26/openvpn-in-a-lxc-container/

thanks, keep up the good work

**Comment by antagonismorg** [comment]
Should this be closed as the PR has been merged?

**Comment by DavidWittman** [comment]
Closed by #412
