### ISSUE TITLE
Is it possible to create use streisand to create a raspbian image?

### ISSUE THREAD

**Issue by dmfrey** [jlund/streisand#408]
Would love to be able to put this on an rpi 3

**Comment by Rich700000000000** [comment]
Seconded. That would be AMAZING.

**Comment by askz** [comment]
@dmfrey did you tested it?

**Comment by dmfrey** [comment]
Test what? I didn't know an image existed for this for rpi. If there is a
procedure to build the image, I will gladly test it.

**Comment by askz** [comment]
To run the playbook as you would do it with your vps/server/whatever but with your RPi? ;)

**Comment by dmfrey** [comment]
are there instructions for that somewhere I missed? If you point me to them
I will attempt it this weekend when I am home from my trip.

**Comment by askz** [comment]
Simply do the same thing as described in the README.
I will test when I'll have time too. But running the playbook with your Pi as target should be a good start !

**Comment by dmfrey** [comment]
I tried to run the script against the lasted raspbian image from 9/23. It failed installing openconnect with the following error:

    TASK [openconnect : Install the ocserv dependencies] ***************************
    failed: [192.168.100.15] (item=[u'gnutls-bin', u'libev-dev', u'libgnutls-dev', u'libgnutls30', u'libnl-route-3-dev', u'libpam0g-dev', u'libreadline-dev', u'libseccomp-dev', u'libwrap0-dev', u'pkg-config']) => {"failed": true, "item": ["gnutls-bin", "libev-dev", "libgnutls-dev", "libgnutls30", "libnl-route-3-dev", "libpam0g-dev", "libreadline-dev", "libseccomp-dev", "libwrap0-dev", "pkg-config"], "msg": "No package matching 'libgnutls-dev' is available"}

In debian, the package libgnutls-dev is libgnutls28-dev

**Comment by askz** [comment]
Did you test to update the deps to match with raspbian's ?

**Comment by dmfrey** [comment]
How do I go about doing that? I will gladly try it out.

**Comment by askz** [comment]
Here : https://github.com/jlund/streisand/blob/15993fe27533515c38c1f9619b7d19ca92983e17/playbooks/roles/openconnect/vars/main.yml#L10 
just put the right package name and re-try ;)

**Comment by dmfrey** [comment]
I got past the previous issue. Dependencies now look like this:

    ocserv_dependencies:
      - gnutls-bin
      - liblz4-dev
      - libev-dev
      - libgnutls28-dev
      - libgnutls-deb0-28
      - libnl-route-3-dev
      - libpam0g-dev
      - libreadline-dev
      - libseccomp-dev
      - libwrap0-dev
      - libkrb5-dev
      - pkg-config

Looks like there is an issue with the version of python pexpect installed.

    fatal: [192.168.100.15]: FAILED! => {"changed": false, "failed": true, "msg": "Insufficient version of pexpect installed (3.2), this module requires pexpect>=3.3. Error was __init__() got an unexpected keyword argument 'echo'"}

Question...should I be using the ubuntu mate image instead of raspbian?

**Comment by askz** [comment]
Maybe you could give it a try ! Not a bad idea ;)

**Comment by dmfrey** [comment]
making more headway with the ubuntu mate image.  Getting an issue now installing shadowsocks-libev

    fatal: [192.168.100.15]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'shadowsocks-libev' is available"}

There doesn't appear to be an armhf architecture support in the added repos. Looks like it can be performed from a git repo. Is something like that possible with ansible?

**Comment by askz** [comment]
getting closer :)
yep you can execute remote command so I think you can get the source and install it like that !

**Comment by cpu** [comment]
We don't presently have the resources to support any OS but Ubuntu 16.04, and can not support the ARM architecture the Rpi uses. PR's are welcome for improved ARM support.
