### ISSUE TITLE
Cannot connect to GCE instance after restart

### ISSUE THREAD

**Issue by FlyClover** [jlund/streisand#414]
I cannot connect to my GCE instance (asia-east) after restarting it. There's no change in the instance's IP address. There is an issue where people cannot connect to their AWS instance using OpenVPN. But in my case none of the connection methods work. I use the latest code to setup my instance.

**Comment by FlyClover** [comment]
I think I've found the cause. In /etc/network/interfaces.d/50-cloud-init.cfg, it says
```
# This file is generated from information provided by
# the datasource.  Changes to it will not persist across an instance.
# To disable cloud-init's network configuration capabilities, write a file
# /etc/cloud/cloud.cfg.d/99-disable-network-config.cfg with the following:
# network: {config: disabled}

```

So I guess Google's cloud-init's script reset network interface configuration after instance restart. I tried manually disable this feature as said in the instruction above and my instance works perfectly after restart.

**Comment by jlund** [comment]
This should be fixed. I attempted to resolve the issue elsewhere (the bug is actually with OpenVPN), but your workaround was really helpful in tracking down the problem. Can you confirm whether or not this still happens for you with the latest version?

**Comment by FlyClover** [comment]
The fix works. Thanks!

**Comment by jlund** [comment]
Good to hear. You're welcome! Thanks for your help with diagnosis and testing.
