### ISSUE TITLE
Can this be used as an alternative to a logless vpn?

### ISSUE THREAD

**Issue by maxisme** [jlund/streisand#415]
If I put this on a DO instance for example. The DO instance will still log the connections from my network to the instance when using streisand? And thus is this not a great alternative to a logless vpn?

Thank you

**Comment by alimakki** [comment]
From the README.md:

- The IP addresses of connecting clients are never logged. There's nothing to find if a server gets seized or shut down.

**Comment by andreagrax** [comment]
I think that @maxisme is asking if the provider of the VM is logging the connection from the clients to the streisand instance.
I'm right?

**Comment by alimakki** [comment]
In that case I would encourage OP to thoroughly read DO's legal and privacy policy: 

https://www.digitalocean.com/legal/enforcement/
https://www.digitalocean.com/legal/privacy/

Perhaps OP can reach out to DO for them to further clarify what info they do collect.

**Comment by andreagrax** [comment]
from https://www.digitalocean.com/legal/enforcement/ 
it seems that DO does not log the connection from your clients (t'sssh , vpn , etc ) to the VM 

>     What Information Is Unavailable?
>     Here are some examples of data which we are unable to provide:
>     Connection Logs.
>     Credit Card information.
>     Local and long distance telephone connection records.
>     Records of session times and durations.
>     MAC addresses.
>     Telephone or instrument numbers.

at the end the problem is how much you trust DO

**Comment by jlund** [comment]
@maxisme With a third-party VPN provider, you have to place blind faith in their claims that they do not log information and just hope for the best. With Streisand, interested parties can examine the complete source code to see exactly where logging gets disabled, and the behavior can also be verified on running servers by examining the final configuration. The community has found a few logging-related bugs in the past ([like this one](https://github.com/jlund/streisand/issues/48)), and I have fixed the reported issues as quickly as possible. There's no reason for Streisand to log client information, and that's a goal that I take seriously.

Having said that, you should be using Tor if you have strong anonymity requirements. Streisand sets up a Tor Bridge too :)
