### ISSUE TITLE
Error using stunnel on Android

### ISSUE THREAD

**Issue by stefanolande** [jlund/streisand#416]
I followed the instructions to set a OpenVPN + stunnel on Android using SSLDroid.
When connecting OpenVPN returns a generic network error and SSLDroid logs this messages:

09-30 11:48:54.132 D/SSLDroid( 3244): [type: MOBILE[HSPA+], state: CONNECTED/CONNECTED, reason: (unspecified), extra: mobile.vodafone.it, failover: false, available: true, roaming: false, metered: true]
09-30 11:48:54.208 D/SSLDroid( 3244): Tunnelcount: 1
09-30 11:48:54.208 W/SSLDroid( 3244): Not starting service as directed by explicit stop
09-30 12:20:21.539 D/SSLDroid( 3244): Starting service
09-30 12:20:21.584 D/SSLDroid( 3244): Tunnel: muraglia 41194 myip 993 /storage/emulated/0/Download/stunnel.p12
09-30 12:20:21.587 D/SSLDroid( 3244): Listening for connections on 127.0.0.1:41194 ...
09-30 12:20:21.593 D/SSLDroid( 3244): SSLDroid Service Started; version='9', versionname='1.2.6'
09-30 12:20:33.194 D/SSLDroid( 3244): muraglia/1: Tunnelling port 41194 to port 993 on host myip ...
**09-30 12:20:34.705 D/SSLDroid( 3244): muraglia/1: javax.net.ssl.SSLException: Read error: ssl=0x6f97836300: I/O error during system call, Software caused connection abort**
09-30 12:20:34.705 D/SSLDroid( 3244): muraglia/1: Quitting server-side stream proxy...
09-30 12:20:34.727 D/SSLDroid( 3244): muraglia/1: java.net.SocketException: Software caused connection abort
09-30 12:20:34.727 D/SSLDroid( 3244): muraglia/1: Quitting client-side stream proxy...
09-30 12:20:35.022 D/SSLDroid( 3244): [type: MOBILE[HSPA+], state: CONNECTED/CONNECTED, reason: (unspecified), extra: mobile.vodafone.it, failover: false, available: true, roaming: false, metered: true]
09-30 12:20:35.029 D/SSLDroid( 3244): Tunnelcount: 0
09-30 12:20:35.043 D/SSLDroid( 3244): Accept failure: java.net.SocketException: Socket closed
09-30 12:20:35.045 D/SSLDroid( 3244): Stopping tunnel 41194:myip:993
09-30 12:20:35.052 D/SSLDroid( 3244): SSLDroid Service Stopped
09-30 12:20:35.079 D/SSLDroid( 3244): Tunnel: muraglia 41194 myip 993 /storage/emulated/0/Download/stunnel.p12
09-30 12:20:35.135 D/SSLDroid( 3244): Listening for connections on 127.0.0.1:41194 ...
09-30 12:20:35.145 D/SSLDroid( 3244): SSLDroid Service Started; version='9', versionname='1.2.6'
09-30 12:20:35.147 D/SSLDroid( 3244): [type: MOBILE[HSPA+], state: CONNECTED/CONNECTED, reason: (unspecified), extra: mobile.vodafone.it, failover: false, available: true, roaming: false, metered: true]
09-30 12:20:35.162 D/SSLDroid( 3244): Tunnelcount: 0
09-30 12:20:35.183 D/SSLDroid( 3244): Accept failure: java.net.SocketException: Socket closed
09-30 12:20:35.186 D/SSLDroid( 3244): Stopping tunnel 41194:myip:993
09-30 12:20:35.191 D/SSLDroid( 3244): SSLDroid Service Stopped
09-30 12:20:35.213 D/SSLDroid( 3244): Tunnel: muraglia 41194 myip 993 /storage/emulated/0/Download/stunnel.p12
09-30 12:20:35.223 D/SSLDroid( 3244): SSLDroid Service Started; version='9', versionname='1.2.6'
09-30 12:20:35.230 D/SSLDroid( 3244): Listening for connections on 127.0.0.1:41194 ...
09-30 12:20:35.324 D/SSLDroid( 3244): muraglia/1: Trying socket operation on a null socket, returning
09-30 12:20:37.632 D/SSLDroid( 3244): muraglia/0: Trying socket operation on a null socket, returning

It could be a problem in SSLDroid and not in streiand. Any ideas?

**Comment by jlund** [comment]
What version of Android are you running? I haven't tried this on Nougat yet.

**Comment by stefanolande** [comment]
Same problem on Android 6 and 7.

**Comment by Symbiotichat** [comment]
I am running Android 7 and I'm having the same issue.

**Comment by antagonismorg** [comment]
I am running the latest version of SSLDroid running the latest version of Android 7. I show the exact same error in my SSLDroid logs. I am running the latest version of Ubuntu with all patches.

Below is the output of the stunnel logs with debug enabled

Dec 10 20:22:50 streisand stunnel[2025]: LOG5[0]: Service [stunnel] connected remote server from 127.0.0.1:48592
Dec 10 20:22:50 streisand stunnel[2025]: LOG7[0]: Remote descriptor (FD=8) initialized
Dec 10 20:22:53 streisand stunnel[2025]: LOG3[0]: SSL_read: Connection reset by peer (104)
Dec 10 20:22:53 streisand stunnel[2025]: LOG5[0]: Connection reset: 4496 byte(s) sent to SSL, 4007 byte(s) sent to socket
Dec 10 20:22:53 streisand stunnel[2025]: LOG7[0]: Remote descriptor (FD=8) closed
Dec 10 20:22:53 streisand stunnel[2025]: LOG7[0]: Local descriptor (FD=3) closed
Dec 10 20:22:53 streisand stunnel[2025]: LOG7[0]: Service [stunnel] finished (0 left)

**Comment by cpu** [comment]
I believe this issue is too stale to be actionable. Please open a new issue providing the information requested by the issue template if you are still having trouble. Thanks
