### ISSUE TITLE
AnyConnect SSL protocol in favor to Stunnel+OpenVPN

### ISSUE THREAD

**Issue by dimzon** [jlund/streisand#417]
Is'nt it better to just use native-by-nature AnyConnect SSL protocol instead of Stunnel+OpenVPN combo?

Also there are perfect SoftEther VPN server wich implements SSTP and it's own VPN-SSL protocols - is it possible to add them too (to support as much protocols as possible)

Also it's possible to run SQID as HTTPS proxy - it's very usefull for Desktops when you doesn't need to tunnel whole traffic

**Comment by tomchiverton** [comment]
Instead of? Goes a bit against the project ethis. Please provide a detailed pro/con breakdown to justify the replacement.

**Comment by cpu** [comment]
I'm going to close this issue as stale. It isn't a fully formed feature request and there hasn't been a reply to the last comment from 2016. Please feel free to open a new issue if you are still interested in pursuing this discussion.
