### ISSUE TITLE
apparmor is never installed

### ISSUE THREAD

**Issue by xyzz** [jlund/streisand#418]
```
TASK [tor-bridge : Restart AppArmor so the abstraction takes effect] ***********
fatal: [163.172.146.75]: FAILED! => {"changed": false, "failed": true, "msg": "Could not find the requested service \"'apparmor'\": "}
```

It seems that apparmor is never installed. Solved by ssh'ing into the server and doing `apt install apparmor`. This is on scaleway "Starter VC1S" tier running ubuntu 16.04.

**Comment by jlund** [comment]
Huh. It's bizarre that Scaleway's server images don't have this installed by default. It's definitely part of the core distribution.

**Comment by jlund** [comment]
@alimakki's pull request resolves this issue on Scaleway servers.

**Comment by jlund** [comment]
Thanks for the bug report!

**Comment by sundmoon** [comment]
Hey, I got a sequel story, in the same environment 

TASK [tor-bridge : Reload the system_tor AppArmor profile for the override to take effect] **********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["apparmor_parser", "-r", "/etc/apparmor.d/system_tor"], "delta": "0:00:00.007428", "end": "2017-07-31 22:39:06.209950", "failed": true, "rc": 1, "start": "2017-07-31 22:39:06.202522", "stderr": "Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)\nWarning: unable to find a suitable fs in /proc/mounts, is it mounted?\nUse --subdomainfs to override.", "stderr_lines": ["Cache read/write disabled: interface file missing. (Kernel needs AppArmor 2.4 compatibility patch.)", "Warning: unable to find a suitable fs in /proc/mounts, is it mounted?", "Use --subdomainfs to override."], "stdout": "", "stdout_lines": []}

**Comment by cpu** [comment]
@sundmoon This is a different issue than the one posted originally. Your machine has app armour installed but is missing kernel compatibility. This is a problem with Scaleway, and not Streisand. Please try a supported provider or start a new thread for the specific kernel compatibility patch problem you're experiencing on [the Streisand-discussions repo](https://github.com/jlund/streisand-discussions).

**Comment by quite** [comment]
@sundmoon Regarding Scaleway, https://github.com/StreisandEffect/discussions/issues/51
