### ISSUE TITLE
Mirror Streisand across other public git repositories

### ISSUE THREAD

**Issue by alimakki** [jlund/streisand#421]
Alternative methods of being able to access the Streisand repository as a countermeasure in case Github gets blocked at a national level, as exemplified by recent [events](https://news.ycombinator.com/item?id=12670560) in Turkey and avoid a single point of 'failure' so to speak.

**Comment by cpu** [comment]
I set up a new mirror accessible at:
[https://area51.threeletter.agency/mirrors/streisand](https://area51.threeletter.agency/mirrors/streisand)

It's synchronized automatically every hour (I might look into ways to shorten the gap between new commits & the mirror updating).

I'm going to leave this issue open for now as a reminder that it should be documented somewhere & to make sure my mirror is going to stay current over the next few days.

**Comment by alimakki** [comment]
@cpu very nice!

Oddly enough it seems like the French README is showing by default.

**Comment by cpu** [comment]
@alimakki I noticed that too! There doesn't seem to be a setting for which README file is rendered, and I think since `README-fr.md` is earlier in the listing of files it's using that. I'll have to look into it more. 

Tant pis! ¯\_(ツ)_/¯

**Comment by cpu** [comment]
Looks like [this is a known thing with localized READMEs](https://gitlab.com/gitlab-com/support-forum/issues/1555) and support's answer to-date is to change the ordering of the files by renaming the localized versions to appear later :roll_eyes:

**Comment by cpu** [comment]
Note: This issue was closed by #807 but if folks start additional mirrors & we can ascertain that they are reliable I'm open to adding those to the README as well.
