### ISSUE TITLE
Shadowsock "UDP forwarding" problem 

### ISSUE THREAD

**Issue by 3lessar** [jlund/streisand#422]
Hi,
I installed streisand successfully several time on Amzon, Digitalocean and even my personal ubuntu server, but in all of them, shadowsocks are not allow UDP forwarding option and traffic.
In my android app when I active this option, I cant reach internet anymore.
So why is that? And is it possible for me to enable this option from server side?
tnx.

**Comment by theduderino** [comment]
If you're in China, your internet provider has most lilekely blocked all ports. You can google for a port checker and see if they're open or not.  
The only way is either to get your own router and configure it or to get the telecom admin password for your IP router and open ports but this is almost impossible to find for newer routers.

**Comment by cpu** [comment]
I'm going to close this issue since it has not seen any activity for some time. If you are having similar problems with Shadowsocks using a newly provisioned server using the latest code from master please open a new issue and we will do our best to help. Thanks!
