### ISSUE TITLE
Installation taking over 3 hours, no end in sight

### ISSUE THREAD

**Issue by raubreywhite** [jlund/streisand#424]
I initially tried to run a Streisand installation on Digital Ocean. It was stuck for an hour on the 

`TASK [l2tp-ipsec : Install the Libreswan dependencies that are required for compilation] ***`

line, and then I quit the installation. I am now trying to install it on Linode, and I'm stuck on the same line -- for 3 hours so far and counting.

I've done nothing special with the installation, just copied and pasted the code in the instructions. I'm running this on a Mac, if that is important...

Any ideas?

**Comment by raubreywhite** [comment]
8 Hours into installation and this happens:

TASK [l2tp-ipsec : Install the Libreswan dependencies that are required for compilation] ***
failed: [45.118.132.26] (item=[u'bison', u'flex', u'libcap-ng-dev', u'libcap-ng-utils', u'libcurl4-nss-dev', u'libevent-dev', u'libnspr4-dev', u'libnss3-dev', u'libnss3-tools', u'libpam0g-dev', u'libselinux1-dev', u'libsystemd-dev', u'libunbound-dev', u'pkg-config', u'xmlto']) => {"item": ["bison", "flex", "libcap-ng-dev", "libcap-ng-utils", "libcurl4-nss-dev", "libevent-dev", "libnspr4-dev", "libnss3-dev", "libnss3-tools", "libpam0g-dev", "libselinux1-dev", "libsystemd-dev", "libunbound-dev", "pkg-config", "xmlto"], "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
fatal: [45.118.132.26]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": ["bison", "flex", "libcap-ng-dev", "libcap-ng-utils", "libcurl4-nss-dev", "libevent-dev", "libnspr4-dev", "libnss3-dev", "libnss3-tools", "libpam0g-dev", "libselinux1-dev", "libsystemd-dev", "libunbound-dev", "pkg-config", "xmlto"], "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}]}

**Comment by raubreywhite** [comment]
I'm now trying this:

ansible-playbook --ssh-extra-args="-o ControlPath=none" --sftp-extra-args="-o ControlPath=none" playbooks/linode.yml

As suggested by: https://github.com/ansible/ansible/issues/13401#issuecomment-209554276

**Comment by raubreywhite** [comment]
Again failed: 

TASK [l2tp-ipsec : Install the Libreswan dependencies that are required for compilation] ***
failed: [139.162.56.180] (item=[u'bison', u'flex', u'libcap-ng-dev', u'libcap-ng-utils', u'libcurl4-nss-dev', u'libevent-dev', u'libnspr4-dev', u'libnss3-dev', u'libnss3-tools', u'libpam0g-dev', u'libselinux1-dev', u'libsystemd-dev', u'libunbound-dev', u'pkg-config', u'xmlto']) => {"item": ["bison", "flex", "libcap-ng-dev", "libcap-ng-utils", "libcurl4-nss-dev", "libevent-dev", "libnspr4-dev", "libnss3-dev", "libnss3-tools", "libpam0g-dev", "libselinux1-dev", "libsystemd-dev", "libunbound-dev", "pkg-config", "xmlto"], "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}
fatal: [139.162.56.180]: UNREACHABLE! => {"changed": false, "msg": "All items completed", "results": [{"_ansible_item_result": true, "item": ["bison", "flex", "libcap-ng-dev", "libcap-ng-utils", "libcurl4-nss-dev", "libevent-dev", "libnspr4-dev", "libnss3-dev", "libnss3-tools", "libpam0g-dev", "libselinux1-dev", "libsystemd-dev", "libunbound-dev", "pkg-config", "xmlto"], "msg": "SSH Error: data could not be sent to the remote host. Make sure this host can be reached over ssh", "unreachable": true}]}

**Comment by raubreywhite** [comment]
Now trying the following ansible.cfg:

raw$ vim ansible.cfg 

[defaults]
inventory = inventory

# This is a convenient setting for a brand-new Streisand server that
# you are connecting to for the first time. However, this line should be
# commented out if you are connecting to an existing server where a
# known_hosts entry has already been created. Host key checking happens
# by default in Ansible.
host_key_checking = False

# Workaround for https://github.com/ansible/ansible/issues/13401
scp_if_ssh = True

# Some providers take a long time to actually begin accepting
# connections even after the OpenSSH daemon has started.
timeout = 10

[ssh_connection]
pipelining = True
retries = 5

**Comment by raubreywhite** [comment]
Now it stalls on

`
TASK [common : Ensure the APT cache is up to date] *****************************
`

**Comment by raubreywhite** [comment]
I'm now running the installation software on ubuntu 16.04, and it seems to work.

Looks like the issue is something to do with macOS Sierra.

**Comment by evaryont** [comment]
Not sure about the sierra stuff, I think this is more a problem similar to #484. Before 9dfa11c, installing libreswan would pull in xmlto, which recommends *gigabytes* of extra packages. Ansible would time out waiting for the apt command to finish. And in particular, it seems the mirrors that apt selects when you run it within DigitalOcean's NY datacenters tend to be a bit slow. Not sure if it's multiple hours slow, but others have had issues before.

**Comment by ryanwmarsh** [comment]
Same

**Comment by cpu** [comment]
I believe this issue is too stale to be actionable. If you still have this problem with the latest code from  master please open a new issue providing the information requested in the issue template. Thanks!
