### ISSUE TITLE
DNS - Not an Issue really but a question

### ISSUE THREAD

**Issue by wicknet** [jlund/streisand#425]
Joshua - absolutely LOVE your solution and really appreciate the enormous amount of time you've spent to make Streisand the only kind of AIO censorship-defeating toolkit.

I've deployed multiple Streisand servers without a hitch, all using the default Google DNS resolvers. Now, I need to re-direct the DNS of 1 operational Streisand server to OpenDNS, which has a semi-restrictive policy in effect for that one static IP to block just pornography and bittorrent sites, leaving everything else open. 

My question is, can we change DNS resolvers post-fact, after the server has been spun up? If not, I can change the DNS resolvers in the playbook and spin up a new instance, but it would save some time it can be changed on the production server itself.

THANKS for your help.

**Comment by andreagrax** [comment]
Just modify playbooks/group_vars/all and re run  on the existing server

Andrea

**Comment by wicknet** [comment]
Thanks Andrea. I ended up doing that, but with a clean VPS, as the quantum of effort would have been the same.
