### ISSUE TITLE
Install on Ubuntu 14.04 in 2016

### ISSUE THREAD

**Issue by yanicklandry** [jlund/streisand#428]
I know we are now in 2016, but my cloud provider only supports up to Ubuntu 14.04. When I still try to install, the `ocserv` installation fails so I reverted to an older version (commit #0daa52c01d2dd86f9553eb041e34e4855526ec76) but I feel this may not be safe. Is there a better way to install on Ubuntu 14.04 with the latest version of Streisand ?

**Comment by cpu** [comment]
I don't believe 14.04 is considered supported. I'm afraid you may have to find a provider that will install Ubuntu 16.04 if you want to use Streisand out of box.
