### ISSUE TITLE
[Issues] Shadowsocks OTA

### ISSUE THREAD

**Issue by denoza** [jlund/streisand#430]
Hi Joshua,

I would like to report some issues that I have come across with a fresh install of Streisand with Shadowsocks OTA.
1. I am not able to access the server with .json config file. Whenever I use sslocal to connect: my traffic doesn't route properly and I receive "There is no Internet Connection" error on my Chromium. My config file is as under:

`{
  "server": "xxx",
  "server_port": 8530,
  "local_address": "127.0.0.1",
  "local_port": 1080,
  "password": "xxx",
  "timeout": 600,
  "method":"aes-256-cfb",
  "auth": true
}`

Solution: I am using Shadowsocks GUI client from https://github.com/shadowsocks/shadowsocks-qt5, which seems to work fine for me.
1. When using QR Code for Android, the client doesn't set the option of OTA to true (by default). Additionally, the method is set to Table which has to be manually set to "aes-256-cfb".

**Comment by FlyClover** [comment]
Try change "auth" to "one_time_auth". They mentioned it [here](https://github.com/shadowsocks/shadowsocks/issues/588).

**Comment by denoza** [comment]
@FlyClover Thanks for the help. But even trying "one_time_auth" instead of "auth" doesn't help. Have you been able to work through it at your end?

**Comment by cpu** [comment]
As mentioned in https://github.com/jlund/streisand/issues/586 OTA mode is deprecated and Streisand will be updating the shadowsocks server config to remove it. I'm going to close this issue since it will soon won't apply. Thanks!
