### ISSUE TITLE
Request for OpenVPN Instructions for Chromebook

### ISSUE THREAD

**Issue by Ev3y** [jlund/streisand#432]
Could you add instructions for connecting to the OpenVPN server on a Chromebook? Among other things, I'm unaware of the username/password requested by the Chromebook connection dialogue. Or is there a work-around that doesn't require a username/password and just requires the client.ovpn file?

**Comment by DavidWittman** [comment]
@Ev3y Have you tried L2TP/IPsec instead? It's supported natively in ChromeOS.

**Comment by Ev3y** [comment]
@DavidWittman I have. That's what I'm using currently; however, OpenVPN is more secure, easier to hide, and faster, so I would rather use it if I can.

**Comment by andreagrax** [comment]
There is a long standing bug on chromium about this issue.
https://bugs.chromium.org/p/chromium/issues/detail?id=217624

Still no luck at the moment, but it's a chrome os fault
Andrea

**Comment by Ev3y** [comment]
@andreagrax I see. It seems rather odd that Chrome OS would have such broken support for OpenVPN for so long. As I imagine the steps to setup an OpenVPN connection would be fairly self-explanatory if/when Chrome OS fully supports it, I'll close the issue.
