### ISSUE TITLE
FYI: L2TP/IPsec VPN might not work on Android 6.x/7.x due to SHA-2

### ISSUE THREAD

**Issue by lazerhawk** [jlund/streisand#439]
Thought this might be helpful to people who search for this, so feel free to close.

https://code.google.com/p/android/issues/detail?id=196939

Basically android 6.x/7.x implementations for SHA-2 use draft and not final RFC spec, so 96 bit only rather than 128 bit. This may cause connection problems for L2TP/IPSEC based VPN connections (some users reporting 100% failure). Google allegedly fixed it, but maybe not quite enough.

Some VPN server software have a truncate mode/bug compatibility mode to provide interoperability, but otherwise the fallback is to downgrade to SHA-1.

**Comment by cpu** [comment]
@lazerhawk Thanks for sharing! I'll close the issue like you suggested but hopefully any affected users will be able to find their way to this issue.
