### ISSUE TITLE
Install fails on non-KVM VPS

### ISSUE THREAD

**Issue by pjrobertson** [jlund/streisand#443]
Commit eb7731034e45978d236c66b33bbbc233723df14a breaks on all non-KVM machines because the `sysctl` option `net.ipv4.tcp_fastopen` is not present.

This is what my existing VPS provider told me:

> I have checked with my colleagues, looks like for that you would need a KVM-based VPS.

I suggest this commit be rolled back
ping @yuanl

**Comment by atulsian89** [comment]
I have the same problem with openvz. Is there an option to comment out the tcp_fastopen option before the installation begins?

**Comment by yuanl** [comment]
[TCP-Fast-Open](https://github.com/shadowsocks/shadowsocks/wiki/TCP-Fast-Open) require Linux Kernel >= 3.7.1 and it was [turn on by default](https://kernelnewbies.org/Linux_3.13#head-159ff61ea3acfd67b88855e75dbbb140f8825c4a) with kernel >= 3.13. Ubuntu 14.04 should had it enable by default.
I am able to install it with this setting turn on in my Linode non-KVM VPS and Amazon EC2. So, I think this might not had something to do with KVM.

**Comment by atulsian89** [comment]
I think you are right @yuanl . I just checked my VPS's kernel version and it is still at 2.6.32. I'll drop an email to support team to update the kernel version if possible.

**Comment by cpu** [comment]
This issue pertains to outdated versions of Ubuntu. Streisand supports Ubuntu 16.04. I'm going to close this issue. If you are unable to use the latest code in master to provision a 16.04 machine please open a new issue and we will help triage. Thanks!
