### ISSUE TITLE
Can't access server after creation

### ISSUE THREAD

**Issue by asiajason** [jlund/streisand#444]
The script works well - creating the server on AWS.

But there are no instructions on what to do next. ie, I can't figure out anything about the server created, nor how to connect to it.

This happens on at least Mac OS X 10.12.x.  I suspect it's just a matter of telling the user where the instructions are located, but I have no real idea.

**Comment by andreagrax** [comment]
please check the **generated-docs** folder in the local copy of the streisand repo
Are the docs generated?

from [streisand site](https://github.com/jlund/streisand)

>>>Wait for the setup to complete (this usually takes around ten minutes) and look for the corresponding files in the 'generated-docs' folder in the Streisand repository directory. The HTML file will explain how to connect to the Gateway over SSL, or via the Tor hidden service. All instructions, files, mirrored clients, and keys for the new server can then be found on the Gateway. You are all done!

**Comment by asiajason** [comment]
Hi andreagrax,

i couldn't find the repo directory.  
i eventually found the html docs under the .ssh directory, so maybe this is a bug?

~/.ssh/streisand/generated-docs/streisand.html

also, for the benefit of those not familiar on where to look, maybe include hints like "$ find ~ -name streisand.html".  Took me 10 minutes to set the server up, but 1/2 day to find the html file.  

and also suggest:

file:///<pathToHtml> 
to view in their browser.

**Comment by andreagrax** [comment]
it depends from where you checked out from git.
Seems to me that you run the command `` git clone `` under ~/.ssh , so git checked out the streisand directory just here.

**Comment by asiajason** [comment]
ahh thank you andreagrax!  much appreciated.  suggestion for adding the instructions might be useful for some however...
