### ISSUE TITLE
Serial number of cert doesn't match

### ISSUE THREAD

**Issue by asiajason** [jlund/streisand#445]
I've installed the server from MacOSX 10.12 to AWS, and downloaded the cert from the streisand.html file, but the serial number doesn't match when i try to install it on iOS.

**Comment by CorbanR** [comment]
@asiajason is this similar to the problem you're experiencing? https://github.com/jlund/streisand/issues/386

**Comment by asiajason** [comment]
ahh yes, that is it.  thank you kindly for pointing this out!
