### ISSUE TITLE
Dynamic/Floating IP Address

### ISSUE THREAD

**Issue by Ev3y** [jlund/streisand#449]
Would it be possible to implement a script to change the outward facing IP address of the server? Perhaps a script that will automatically change all references to the new IP address of the server (for example, when spinning up a new Digital Ocean droplet from a Streisand snapshot) and generating a new instructions file and connection profiles. Or perhaps working with firewall rules to use Digital Ocean's floating IP system for the outgoing connections.
Something like this would make it much easier to circumvent IP-banning.
Forgive me if this is not the place for such suggestions, and in that case please tell me where I should post them.

**Comment by nickolasclarke** [comment]
@Ev3y this is a known issue on DO that is addressed in #413 and elsewhere. My script still isnt done, but you can track the progress of it in the link below. I'm hoping to commit the real MVP this weekend.

**Comment by Ev3y** [comment]
Ah okay; I'll move this to #413.
