### ISSUE TITLE
tor-bridge: wait for obfs4proxy fails

### ISSUE THREAD

**Issue by nikksno** [jlund/streisand#450]
I'm trying to install streisand on a Ubuntu 16 VPS on an Italian provider's platform. I know external services are not supported, but I'll try asking anyway. Not knowing what the problem is here, and not having found anything relevant around, after the first time I got the error, I installed all dependencies listed for the 5 supported providers on the readme, with no change. If you could point me in the right direction, I'd be happy to help. The /var/lib/tor/pt_state/obfs4_state.json file doesn't exist, /var/lib/tor/ is empty, tor service is running. I'm running this from a Mac. Here's the error:

```
TASK [tor-bridge : Restart Tor so the server fingerprint will be available in the state file, and the hidden service for the Gateway will start running] ***
changed: [$ip]

TASK [tor-bridge : Wait until obfs4proxy information has shown up in its state file] ***
fatal: [$ip]: FAILED! => {"changed": false, "elapsed": 300, "failed": true, "msg": "Timeout when waiting for search string node-id in /var/lib/tor/pt_state/obfs4_state.json"}
	to retry, use: --limit @/Users/$user/streisand/playbooks/streisand.retry

PLAY RECAP *********************************************************************
$ip              : ok=150  changed=31   unreachable=0    failed=1
```

Thank you in advance and thank you for your amazing work!

**Comment by drewmu** [comment]
I too am getting the exact same error. 

Tried installing into Ubuntu 16.04 on an external (non-"supported") American server. Same issue with installing all dependencies not helping, missing obfs4_state.json file, empty /var/lib/tor, running tor service. I'm deploying from a Ubuntu 16.04 virtual machine and have not had a problem setting up Streisand servers elsewhere.

I also tried bypassing the installation of tor. To do so I commented-out _-tor-bridge_ in streisand.yml. I did the same for lines or sections referring to _tor_ and _obfs4_ in the roles subfolders and files (ufw, streisand-mirror, streisand-gateway). I'm getting this error instead:

''
TASK [streisand-mirror : Generate the Markdown mirror page] ********************
fatal: [$ip]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'tor_browser_bundle_linux32_filename' is undefined"}
	to retry, use: --limit @/home/$user/streisand/playbooks/streisand.retry

PLAY RECAP *********************************************************************
$ip             : ok=195  changed=52   unreachable=0    failed=1
''

**Comment by nikksno** [comment]
I'm sorry I can't add any helpful detail. I tried again the next day and to my surprise it worked without an issue. No idea why...

**Comment by drewmu** [comment]
I spoke to my VPS provider and once they provisioned me a KVM server (I had been using LXC) the Streisand installation completed without a hitch! My IP address also changed but I don't think that contributed to the original problem. It is also possible that the image of Ubuntu 16.04 was different from that deployed previously, but I have no way of knowing.

At this point, I would guess that the switch to KVM fixed the issue.

**Comment by robertovalerio** [comment]
Well, it is easier than that. Just run the playbook again.

**Comment by cpu** [comment]
I don't believe this issue is actionable in its current state. Please open a new issue providing the information requested in the issue template if you are still having trouble with the latest code from master. Thanks!

**Comment by aboanas93** [comment]
I'm also having this issue with Arubacloud Smart VPS

**Comment by cpu** [comment]
@aboanas93 Please open a new issue providing the information requested in the issue template
