### ISSUE TITLE
[issue] Amazon EC2 setup 

### ISSUE THREAD

**Issue by DsOIL** [jlund/streisand#455]
i keep getting this issue i have no idea what to do next 

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ***
fatal: [xx.xxx.xxx.xxx]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added 'xx.xxx.xxx.xxx' (ECDSA) to the list of known hosts.\r\nControl socket connect(/home/ubuntu/.ansible/cp/ansible-ssh-xx.xxx.xxx.xxx-22-ubuntu): Connection refused\r\nFailed to connect to new control master\r\n", "unreachable": true}
	to retry, use: --limit @/home/ubuntu/streisand/playbooks/amazon.retry

PLAY RECAP *********************************************************************
xx.xxx.xxx.xxx            : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=17   changed=9    unreachable=0    failed=0

**Comment by tomchiverton** [comment]
Did you try again via the hint at the end of the message? Maybe Amazon had a delay starting the instance?

**Comment by cpu** [comment]
This issue is missing information that would make it actionable. I'm going to close it. Please open a new issue providing the information requested by the issue template if you are still having trouble using the latest code from master. Thanks!
