### ISSUE TITLE
Use reduced privilege Amazon user

### ISSUE THREAD

**Issue by tomchiverton** [jlund/streisand#461]
Right now, the root account's API key is used. Instead the recommendation should be to create an IAM role with just the minimal privileges required. 
I don't know enough Ansible to go through and dig out everything the scripts do to produce this list and at least add it to the docs.

**Comment by DavidWittman** [comment]
@tomchiverton AFAIK you can use the credentials of _any_ IAM user when creating streisand hosts. It doesn't have to be the root account as long as that particular user has the appropriate permissions.

Are you asking for some documentation on which permissions specifically this user should have?

**Comment by tomchiverton** [comment]
Exactly. Ideally an IAM role that can be imported. 
I found that the built in 'full EC2' role is sufficient, but clearly over privileged still. 
-- 
Tom

**Comment by MartinLeeUK** [comment]
It may be a good idea to spell out how to create a specific IAM user with API keys specifically for streisand.

I'm happy to help put together a low privilege policy if that would be useful.

**Comment by tomchiverton** [comment]
Yes, that would be awesome! 
-- 
Tom

**Comment by MartinLeeUK** [comment]
Well, here's a starting point.

Testing so far - I've used it to create an image in the default VPC & subnet.
[streisandPolicy.json.zip](https://github.com/jlund/streisand/files/702981/streisandPolicy.json.zip)

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/11
