### ISSUE TITLE
Feature Request - Local Provisioning

### ISSUE THREAD

**Issue by wicknet** [jlund/streisand#468]
Hi Joshua,

Your script continues to rock in the new year, working flawlessly to spin up new AIO anti-censorship servers for friends and family. 

I was wondering if support for local provisioning is still on the development road-map? The only “weak-ish” link in the project (that I’ve encountered with users) is their local system (which in many cases is a Mac clogged with other, conflicting apps/OS). It needs to be perfectly configured to run the installer packages properly, else the installation of the remote server fails with errors. 

However, if local provisioning could be supported (perhaps as an initial choice - local or remote install), I’m confident that your wonderful script would become almost “universally usable”, as many folks over here in the US are not trying to circumvent the Great Fire Wall but annoying workplace surfing restrictions via a self-hosted Streisand server at home, instead of one with a hosting provider, that also comes with a recurring monthly cost. 

Local provisioning would be of great help, especially to rookies who can't figure out how to edit the inventory file and direct the install to another, local server.

FWIW!

**Comment by cpu** [comment]
Local provisioning has been added as of #724 being merged. Thanks!
