### ISSUE TITLE
additional ports for OpenVPN

### ISSUE THREAD

**Issue by mlevin2** [jlund/streisand#471]
Hi,

I have Streisand up and running and I love it!

I'd like to have OpenVPN listen for additional ports (specifically, I'd like it to also respond on 3128/tcp).

What's the easiest way to do this? Duplicate OpenVPN configuration? Do a port forward in iptables?

Thanks!

**Comment by mlevin2** [comment]
I'm not sure if this is the _best_ way (I suspect not since it doesn't actually fix any of this in ansible), but it seems to work.

First I duplicated `/etc/openvpn/server.conf` and made a new configuration that listens on 3128.

Then I manually edited the following files as appropriate to reference my additional openvpn configuration and the new IP range (I chose 10.10.0.1):

`/etc/rc.local
/etc/dnsmasq.conf
/etc/ufw/user.rules
/etc/ufw/user6.rules
/etc/monit/monitrc`

**Comment by jlund** [comment]
Can you help me understand the use case for this a little bit better? By default, OpenVPN will listen for TCP connections on both ports 636 and 443.

You can modify the `openvpn_port` variable in `playbooks/roles/openvpn/defaults/main.yml` if you want to choose a port other than 636.

You could also add a line like `openvpn_port: 3128` to `playbooks/group_vars/all` which would supersede the default and cause port 3128 to be used instead.

**Comment by cpu** [comment]
This isn't a use case we have the resources to support at present. Thanks!
