### ISSUE TITLE
Google Cloud installation fails

### ISSUE THREAD

**Issue by valarmorghuli** [jlund/streisand#472]
<img width="983" alt="untitled" src="https://cloud.githubusercontent.com/assets/9086874/21745309/92842d4a-d531-11e6-9567-c4d2ec70f0d5.png">

**Comment by jlund** [comment]
It looks like you don't have a GCE service account JSON credentials file located at `/Users/redacted-username/streisand.json`. You'll either need to put the file there or specify the correct location when you are prompted for it instead of leaving that prompt blank.

**Comment by valarmorghuli** [comment]
Thank you.

**Comment by jlund** [comment]
Sure thing! I hope it works for you.

**Comment by 0-chen** [comment]
Where could I get the JSON file?

**Comment by cpu** [comment]
@0-chen Please try to open new issues for new questions.

Please see https://docs.ansible.com/ansible/guide_gce.html#credentials and https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts

The latter "support.google.com" link explains where to get the credentials JSON.

**Comment by 0-chen** [comment]
@cpu  OK！ Thank you！ I've got it ！
