### ISSUE TITLE
Streisand Shadowsocks Setup with Errors in Config on OpenVZ

### ISSUE THREAD

**Issue by BastianG** [jlund/streisand#473]
When running Streisand on OpenVZ Virtual Machines, during setup of Shadowsocks the following has occured on the last three machines I installed the setup on:
```
TASK [shadowsocks : Apply the sysctl value to enable TCP Fast Open] ************
fatal: [x.x.x.x]: FAILED! => {"changed": false, "failed": true, "msg": "Failed to reload sysctl: net.ipv4.ip_forward = 1\nnet.ipv4.tcp_syncookies = 1\nkernel.msgmnb = 65536\nkernel.msgmax = 65536\nkernel.shmmax = 68719476736\nkernel.shmall = 4294967296\nnet.ipv4.conf.all.accept_source_route = 0\nnet.ipv4.conf.default.accept_source_route = 0\nnet.ipv4.conf.all.log_martians = 1\nnet.ipv4.conf.default.log_martians = 1\nnet.ipv4.conf.all.accept_redirects = 0\nnet.ipv4.conf.default.accept_redirects = 0\nnet.ipv4.conf.all.send_redirects = 0\nnet.ipv4.conf.default.send_redirects = 0\nnet.ipv4.conf.all.rp_filter = 0\nnet.ipv4.conf.default.rp_filter = 0\nnet.ipv4.icmp_echo_ignore_broadcasts = 1\nnet.ipv4.icmp_ignore_bogus_error_responses = 1\nnet.ipv4.conf.all.secure_redirects = 0\nnet.ipv4.conf.default.secure_redirects = 0\nkernel.randomize_va_space = 1\nsysctl: permission denied on key 'kernel.sysrq'\nsysctl: permission denied on key 'kernel.core_uses_pid'\nsysctl: permission denied on key 'net.core.wmem_max'\nsysctl: permission denied on key 'net.core.rmem_max'\nsysctl: cannot stat /proc/sys/net/ipv4/tcp_fastopen: No such file or directory\n"}
```
Running the Streisand Script again will smoothly install, no matter whether or not TCP fast-open is enabled or disabled in the shadowsocks role (./shadowsocks/default/main.yml).

However, shadowsocks will not be functional after installation. The config-file will look as follows:

```

{
    "server":"x.x.x.x",
    "server_port":8530,
    "local_port":1080,
    "password":"RW63s02Zod3NNeFnIWrXyWVJVLXNeH6PMhqegUSNTgvneEFeRj5bqbT4KkTwtkmb",
    "timeout":600,
    "method":"aes-256-cfb",
    "fast_open":"?~@~\true?~@~]",
    "auth":"true"
}

```
Mind the quotemarks and markup around values for "fast_open" and "auth".

After fixing the config file, fast-open will not work. After setting the value to "false", and restarting the service, everything works like a charm. Config file looks like this:

```
{
    "server":"x.x.x.x",
    "server_port":8530,
    "local_port":1080,
    "password":"RW63s02Zod3NNeFnIWrXyWVJVLXNeH6PMhqegUSNTgvneEFeRj5bqbT4KkTwtkmb",
    "timeout":600,
    "method":"aes-256-cfb",
    "fast_open": false,
    "auth": true
}

```
Running systemctl status systemd-sysctl gives me this, which to me indicates a limitation on the kernel parameters due to the virtual machine setup with OpenVZ:

>Jan 08 01:36:34 gongfoo2 systemd[1]: Starting Apply Kernel Variables...
>Jan 08 01:36:34 gongfoo2 systemd-sysctl[28651]: Couldn't write '12582912' to 'net/core/rmem_max', ignoring: Permission denied
>Jan 08 01:36:34 gongfoo2 systemd-sysctl[28651]: Couldn't write '1' to 'kernel/yama/ptrace_scope', ignoring: No such file or directory
>Jan 08 01:36:34 gongfoo2 systemd[1]: systemd-sysctl.service: Main process exited, code=exited, status=1/FAILURE
>Jan 08 01:36:34 gongfoo2 systemd[1]: Failed to start Apply Kernel Variables.
>Jan 08 01:36:34 gongfoo2 systemd[1]: systemd-sysctl.service: Unit entered failed state.
>Jan 08 01:36:34 gongfoo2 systemd[1]: systemd-sysctl.service: Failed with result 'exit-code'.

I'd like to have fast-open working for speed. Can anyone advise on how to fix this?

**Comment by cpu** [comment]
> Running systemctl status systemd-sysctl gives me this, which to me indicates a limitation on the kernel parameters due to the virtual machine setup with OpenVZ:

This might be something the shadowsocks role should detect & work around.

**Comment by cpu** [comment]
Can you please try running the latest code from master against your OpenVZ virtual machine to see if the problem still occurs?

**Comment by cpu** [comment]
There hasn't been a reply to my question from 27 days ago, and the shadowsocks role has evolved quite a bit since the issue was initially reported. I'm going to close this issue as stale. Please open a new issue if you find that the tip of master causes you this problem with a fresh server install.
