### ISSUE TITLE
DigitalOcean fails to create droplet (basestring not defined)

### ISSUE THREAD

**Issue by joopdorresteijn** [jlund/streisand#474]
Thank you for this wonderful playbook. I thought i'd try it out but failed. It's an unmodified clone and prerequirements are met on the local machine. (arch) Execute Streisand with the following details:

**Which provider are you using?** > DigitalOcean
What region should the server be located in? > Singapore

**What should the server be named?** Press enter for default (streisand). > Various names tried including variable names

**What is your DigitalOcean Access Token?** > Old and new tokens tried. 

> PLAY [Provision the DigitalOcean Server] ***************************************

> TASK [setup] *******************************************************************
> ok: [localhost]
> 
> TASK [genesis-digitalocean : Set the DigitalOcean Access Token fact to the value that was entered, or attempt to retrieve it from the environment if the entry is blank] ***
ok: [localhost]
> 
> TASK [genesis-digitalocean : Get the default SSH key] **************************
changed: [localhost]
> 
> TASK [genesis-digitalocean : Add the SSH key to DigitalOcean if it doesn't already exist] ***
ok: [localhost]
> 
> TASK [genesis-digitalocean : Create the new Droplet] ***************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: NameError: name 'basestring' is not defined
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "name 'basestring' is not defined"}
> 
> TASK [genesis-digitalocean : fail] *********************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Unable to create the Droplet. > Please ensure that the API Access Token you provided has the Write Scope enabled."}
	to retry, use: --limit @/home/joop/clones/streisand/playbooks/digitalocean.retry
> 
> PLAY RECAP *********************************************************************
> localhost                  : ok=4    changed=1    unreachable=0    failed=1   

I don't think my token or SSH Key are in error. When I purposely change one of these, the playbook fails at the 'Add the SSH key' step.

**Comment by joopdorresteijn** [comment]
My bad. Problem only occurs in Arch. Ubuntu works fine.

**Comment by jlund** [comment]
Just saw this. Is your Arch system using Python 3 by any chance?

**Comment by joopdorresteijn** [comment]
Affirmative: Python 3.5.2

**Comment by jlund** [comment]
Ah, yeah. Ansible just barely added support for Python 3 as a [tech preview in version 2.2](https://docs.ansible.com/ansible/python_3_support.html). I switched to that as the minimum version in the Streisand helper script a few days ago. I plan on testing a run with Python 3 soon.

My guess is that this was the issue though.

**Comment by joopdorresteijn** [comment]
Thanks for the reply. Perhaps next weekend I can try on my Arch machine with a python 2 venv. Right now I got it working by ssh'ing to an ubuntu machine so problem solved for now.

**Comment by dwightgunning** [comment]
I had had exactly the same error while under a Python 3 virtualenv on OSX. Switching to a Python 2 venv solved the problem.

**Comment by muffl0n** [comment]
> Ah, yeah. Ansible just barely added support for Python 3 ...

Actually it's not Ansible's fault but an outdated and not longer maintained "dopy". See https://github.com/Wiredcraft/dopy/issues/61

https://github.com/rolylolypoly/dopy feels like a good fork.
