### ISSUE TITLE
Feature Request: An "entirely hands-off mode" that just requires my Amazon/DigitalOcean username and password as command-line arguments.

### ISSUE THREAD

**Issue by Rich700000000000** [jlund/streisand#478]
All the keys will be made and downloaded completely automatically.

**Comment by ryanohoro** [comment]
Just as best practice, credentials should go in a file in the users' home directory with appropriate permissions. They shouldn't be entered via command arguments.

**Comment by Rich700000000000** [comment]
Oh, right. Well then a JSON, or something like that:


    {
        "email": "mymail@servserver.com",
        "password": "knotpassword",
        "servername": "sarasserver",
    }

**Comment by cpu** [comment]
I don't think there are resources to support this. I recommend that you write a wrapper script that does what you want before invoking `./streisand`. Thanks
