### ISSUE TITLE
Cannot resolve DNS queries.

### ISSUE THREAD

**Issue by OrangeTux** [jlund/streisand#479]
I just installed Streisand on a clean Ubuntu 16.04 server. Both on Linux and Android I'm able to connect the server using OpenVPN, but on both devices DNS queries seems to fail.

The Chrome browser on Android shows the error:

> DNS address of website.com can't be found. **DNS_PROBE_FINISHED_BAD_CONFIG**

On my Linux machine `drill` exists with an error:

```
$ drill nos.nl
Error: error sending query: Could not send or receive, because of network error`
```

Both on my Linux and Android I see this error in the logs:

```
Unrecognized option or missing or extra parameter(s) in [PUSH-OPTIONS]:3: block-outside-dns (2.4.0)
```

Does someone has a clue how to fix it?

**Comment by jlund** [comment]
Which Linux distro are you using, and which Android client?

The unrecognized block-outside-dns option is a Windows-specific setting that other clients don't use, so that error is not the cause (even though it looks related in this context).

**Comment by OrangeTux** [comment]
On my Linux machine I run Arch Linux:
```
Linux robin 4.7.6-1-ARCH #1 SMP PREEMPT Fri Sep 30 19:28:42 CEST 2016 x86_64 GNU/Linux
```

On Android I use [OpenVPN for Android](https://play.google.com/store/apps/details?id=de.blinkt.openvpn&hl=nl).

**Comment by cpu** [comment]
I think this issue has become sufficiently stale that it isn't actionable. If you're still having problems using a fresh Streisand instance provisioned using the latest code in master I recommend you create a new issue providing the information requested by the issue template. Thanks!
