### ISSUE TITLE
[MacOS] Cannot use Shadowsocks for any website in Shanghai, China

### ISSUE THREAD

**Issue by PeterRistCMS** [jlund/streisand#482]
`Location: Shanghai, China`

The last 2 days, i've created numerous streisand instances. I've started from scratch and cloned the repo (7cd0f5c). I've tried it in four different AWS regions: Seoul, Tokyo, Mumbai and Singapore. 

All of them have the same problem, the shadowsocks server (potentially) doesn't work. Neither on Mac OS, nor on my Android. Doesn't matter which site i'm trying to access, all the websites i've used, don't work for me with shadow socks. The SSH tunnel is working though. 

Used browsers: Safari, Chrome and Firefox.

I'm getting the following error message:

```
Secure Connection Failed

The connection to www.facebook.com was interrupted while the page was loading.

    The page you are trying to view cannot be shown because the authenticity of the received data could not be verified.
    Please contact the website owners to inform them of this problem.
```

I can provide more information if needed.

Regards,
PeterRistCMS

**Comment by jlund** [comment]
Was this same setup working previously, or was two days ago the first time you tried?

**Comment by df-sh** [comment]
I'm also in Shanghai New aws servers spun up in the last couple days are a
little slower than usual but all working.   Could be an ISP issue.   China
unicom for mobile working for me and telecom for home Internet.   Good luck

**Comment by PeterRistCMS** [comment]
@jlund I'm running streisand since over a year now, but recently the IPs getting blocked by the GFW and i have to spin up a new one. The last working streisand was https://github.com/jlund/streisand/commit/698cecbb774e6f429e64e7a1b3566bee641e4d50 

The last few weeks i had to spin up new streisand regularly, because the IP got flagged by the GFW.

@df-sh I'm running exactly the same setup with unicom and china telecom, but somehow it doesn't work for me. Shadowsocks-NG is at 1.2(1). Which datacenter are you using? 

When i'm back home, I'm spinning up a new one.

**Comment by nickolasclarke** [comment]
@PeterRistCMS Also in Shanghai, and its still working for me. I'm on DO based out of SFO2. We also use SS at work (not through streisand) and that server works both on our company network and on my home/mobile networks. I'm going to say this isnt a Streisand issue. What provider are you on?

**Comment by nickolasclarke** [comment]
Actually now that I think about it, I reverted back to a previous snapshot on my personal server, so I am running outdated Streisand at this point. I can test tonight and report back some initial findings.

**Comment by df-sh** [comment]
I'm using us east at the moment.  If your going to spin up a new server
anyway,  post your qr code for a server and I can see if I can connect

**Comment by df-sh** [comment]
Also if you think it's an IP block,  AWS uses elastic IP just release the
one you think is blocked,  grab a new one and assign it to your streisand
instance and reboot,  change the server ip to match the new ip address and
it should be working again

**Comment by nickolasclarke** [comment]
@df-sh I believe he'll also need to edit the /etc/shadowsocks-libev/config.json to reflect the new IP and then restart the service with `sudo service shadowsocks-libev restart`.

**Comment by df-sh** [comment]
I didn't need to do that...  But maybe I just lucked out..

**Comment by PeterRistCMS** [comment]
@df-sh I'm spinning up a new one in Seoul. I will send you the QR code once it's done. 
@nickolasclarke Curious on your findings. Thank you.

**Comment by PeterRistCMS** [comment]
@df-sh attached the QR code for the freshly created Seoul streisand. Does it work for you?

![shadowsocks-qr-code](https://cloud.githubusercontent.com/assets/16235754/22018367/76a8f3d4-dce9-11e6-983a-562a22ae0855.png)

**Comment by nickolasclarke** [comment]
@PeterRistCMS I'll test now.

**Comment by nickolasclarke** [comment]
@PeterRistCMS tested on my android phone with China Mobile briefly. So far works excellent!

**Comment by nickolasclarke** [comment]
@PeterRistCMS I'll keep it on through the evening at least to let you know how it goes.

**Comment by df-sh** [comment]
Tested on China unicom mobile and China telecom house and works...  But
it's in Korean.   Does it work for you?

**Comment by PeterRistCMS** [comment]
@nickolasclarke I've reinstalled shadow socks on my android and surpringlsy it's working there now, but somehow on my mac with shadowsocks-ng 1.2(1) installed it doesn't work. Are you by any chance on a MAC to verify it's working with my QR-Code?

**Comment by df-sh** [comment]
There was previously an issue with one time authentication and the qr code
not setting correctly,  I don't have an OSX box to test it out for you at
the moment though sorry.

**Comment by joopdorresteijn** [comment]
Confirmed for users in different cities. Tested this out of curiosity (Different provence) and indeed experience same behaviour. 

```
[joop@almond joop]# sslocal -s 52.79.XXX.XXX -p 8530 -k  VmoCMDAPASSWORDS
2017-01-17 20:10:50 INFO     loading libcrypto from libcrypto.so.1.0.0
2017-01-17 20:10:50 INFO     starting local at 127.0.0.1:1080
2017-01-17 20:11:05 INFO     connecting drive.google.com:443 from 127.0.0.1:45094
2017-01-17 20:11:05 INFO     connecting ac.duckduckgo.com:443 from 127.0.0.1:45098
2017-01-17 20:11:05 INFO     connecting ac.duckduckgo.com:443 from 127.0.0.1:45102
2017-01-17 20:11:06 INFO     connecting twitter.com:443 from 127.0.0.1:45106
2017-01-17 20:11:10 INFO     connecting twitter.com:443 from 127.0.0.1:45110
2017-01-17 20:11:12 INFO     connecting twitter.com:443 from 127.0.0.1:45114
2017-01-17 20:11:15 INFO     connecting ac.duckduckgo.com:443 from 127.0.0.1:45118
2017-01-17 20:11:15 INFO     connecting ac.duckduckgo.com:443 from 127.0.0.1:45122
2017-01-17 20:11:15 INFO     connecting ac.duckduckgo.com:443 from 127.0.0.1:45126
2017-01-17 20:11:16 INFO     connecting dnsleaktest.com:443 from 127.0.0.1:45130
2017-01-17 20:11:35 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45138
2017-01-17 20:11:35 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45142
2017-01-17 20:11:36 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45146
2017-01-17 20:11:36 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45150
2017-01-17 20:11:37 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45156
2017-01-17 20:11:38 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45160
2017-01-17 20:11:38 INFO     connecting www.speedtest.net:80 from 127.0.0.1:45164
```

**Comment by nickolasclarke** [comment]
@PeterRistCMS sounds like this may not be needed at this point, but I ran this all night on my android connecting at work (unknown isp) , china mobile, and China Telecom, and it seemed to be just fine.

**Comment by nickolasclarke** [comment]
@df-sh re: updating the config and restarting the service; It would probably be fine until the service has to be reloaded for whatever reason (update/reboot/etc)

**Comment by PeterRistCMS** [comment]
@nickolasclarke agreed, that it's working on Android, but sadly not on Shadowsocks-NG 1.2(1) on a MAC. I've also tried another shadowsocks version 2.6.3 https://github.com/shadowsocks/shadowsocks-iOS/releases but no success.

**Comment by PeterRistCMS** [comment]
I've installed Shadowsocks-NG 1.3.1 now, but getting a 500 back.

```
500 Internal Privoxy Error

Privoxy encountered an error while processing your request:

Could not load template file no-server-data or one of its included components.

Please contact your proxy administrator.

If you are the proxy administrator, please put the required file(s)in the (confdir)/templates directory. The location of the (confdir) directory is specified in the main Privoxy config file. (It's typically the Privoxy install directory, or /etc/privoxy/).
```

**Comment by PeterRistCMS** [comment]
I've fixed the problem.

After debugging, i've found out, that there was an old shadow socks version installed on my system, which prevented shadowsocks-NG to bind the address.

```
2017-01-19 20:22:09 ERROR: bind: Address already in use
 2017-01-19 20:22:09 ERROR: Could not bind
 2017-01-19 20:22:09 ERROR: bind() error
```

Looking at `~/Library/Logs/ss-local.log` showed the problem. I properly cleaned shadow socks and reinstalled the latest version and it's working again.

Thank you @jlund for maintaining streisand, Good job 👍

**Comment by jlund** [comment]
That is great to hear! I am really glad that it is working now. This issue will be helpful to anyone who might run into the same thing in the future.
