### ISSUE TITLE
Request: Amazon Lightsail

### ISSUE THREAD

**Issue by ptm2x1NyqFB2RY** [jlund/streisand#483]
Amazon has introduced new VPS with flat rate pricing. Worth considering as a new provider? 
 
https://aws.amazon.com/blogs/aws/amazon-lightsail-the-power-of-aws-the-simplicity-of-a-vps/?sc_ichannel=ha&sc_icampaign=launch_lightsail_consolehome_68576a17_2564&trkCampaign=launch_lightsail_consolehome_68576a17&trk=%20launch_lightsail_consolehome_68576a17_2564

**Comment by Rich700000000000** [comment]
Is seconding a request allowed? Because this sounds interesting.

**Comment by MartinLeeUK** [comment]
https://github.com/ansible/ansible/pull/19846 this needs to be merged into ansible before this can be developed easily.  For now, you could use the scripts after manually creating a VPS.

**Comment by ev3y2** [comment]
[ansible/ansible#19846](https://github.com/ansible/ansible/pull/19846) has just been merged.

**Comment by alimakki** [comment]
I have already started work on this and have it more or less working, the caveat being I have to manually open ports on Amazon's firewall for lightsail, as there is no lightsail firewall module for ansible.

Currently exploring options to write the module and push it to upstream ansible.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/8
