### ISSUE TITLE
AWS Issue with Credentials and Slash Delimiting

### ISSUE THREAD

**Issue by zabcheckmate** [jlund/streisand#485]
Trying this for the first time with AWS, and this is the error I'm getting:

TASK [ec2-security-group : Create the EC2 security group] **********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Response><Errors><Error><Code>AuthFailure</Code><Message>Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got '[REDACTED]//20170120/us-east-1/ec2/aws4_request,SignedHeaders=host;x-amz-date,Signature=bd4a583e21419d742df93e2aae0cb2d08a685831de3a5103490c1a0fda7b3796'</Message></Error></Errors><RequestID>a291e378-f070-4016-8783-0685ace3234f</RequestID></Response>
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_NMQkIE/ansible_module_ec2_group.py\", line 478, in <module>\n    main()\n  File \"/tmp/ansible_NMQkIE/ansible_module_ec2_group.py\", line 275, in main\n    for curGroup in ec2.get_all_security_groups():\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 2984, in get_all_security_groups\n    [('item', SecurityGroup)], verb='POST')\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>AuthFailure</Code><Message>Credential must have exactly 5 slash-delimited elements, e.g. keyid/date/region/service/term, got '[REDACTED]/20170120/us-east-1/ec2/aws4_request,SignedHeaders=host;x-amz-date,Signature=bd4a583e21419d742df93e2aae0cb2d08a685831de3a5103490c1a0fda7b3796'</Message></Error></Errors><RequestID>a291e378-f070-4016-8783-0685ace3234f</RequestID></Response>\n", "module_stdout": "", "msg": "MODULE FAILURE"}
	to retry, use: --limit @/home/test/streisand/playbooks/amazon.retry

**Comment by jlund** [comment]
Did you leave the access key or secret key fields blank? You'll need to make an IAM admin user (best) or use your root account access key credentials.

**Comment by zabcheckmate** [comment]
I used root account access key credentials, which I redacted in the below,
but I'll try with an IAM admin user.

**Comment by jlund** [comment]
It will work both ways, but I would check for typos or extraneous spaces in the ID or Secret Key. I'm pretty sure the error you are seeing is because the credentials aren't valid.

**Comment by zabcheckmate** [comment]
With an IAM User I was able to circumvent whatever was happening, which may
very well have been bad credentials.

**Comment by jlund** [comment]
Excellent!
