### ISSUE TITLE
Unable to SSH AWS instance

### ISSUE THREAD

**Issue by joelchen** [jlund/streisand#487]
Fails to SSH AWS instance on both Mac OSX and Docker Linux container https://github.com/joelchen/docker-streisand:
```
TASK [genesis-amazon : Wait until the server has finished booting and OpenSSH is accepting connections] ***
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 600, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in <server IP>:22"}
	to retry, use: --limit @/streisand/playbooks/amazon.retry

PLAY RECAP *********************************************************************
localhost                  : ok=13   changed=7    unreachable=0    failed=1
```
Running `ssh -i <private key> ubuntu@<server IP>` returns:
```
ssh: connect to host <server IP> port 22: Operation timed out
```
Running again with `./streisand --limit @/streisand/playbooks/amazon.retry` on Mac OSX repeats the prompts from step 1 (Which provider are you using?) and fails the same at OpenSSH.

**Comment by joelchen** [comment]
Only clue I have got is from https://github.com/ansible/ansible/issues/14237 where the issue is caused by different variable names being used.

**Comment by antoineclaval** [comment]
I've run into the same issue with similar configuration.

**Comment by MartinLeeUK** [comment]
What's the state of the server in the EC2 web console?

Is it a member of any security groups, and what are the contents of those security groups?

Are you using an IAM role's API keys for the build or your root keys?

**Comment by cpu** [comment]
This issue is pretty stale and there are outstanding questions that the OP hasn't replied to. I'm going to close this issue. Please open a new issue if you still have this problem with the tip of master & a new AWS EC2 instance.
