### ISSUE TITLE
ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

### ISSUE THREAD

**Issue by DaveFlowberries** [jlund/streisand#488]
When setting up Streisand on a new Vultr server on Ubuntu 16.04, I get the following error now:

`ERROR! no action detected in task. This often indicates a misspelled module name, or incorrect module path.

The error appears to have been in '/Users/joe/streisand/playbooks/roles/wireguard/tasks/main.yml': line 59, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Enable the WireGuard service so it starts at boot, and bring up the WireGuard network interface
  ^ here

The error appears to have been in '/Users/joe/streisand/playbooks/roles/wireguard/tasks/main.yml': line 59, column 3, but may
be elsewhere in the file depending on the exact syntax problem.

The offending line appears to be:

- name: Enable the WireGuard service so it starts at boot, and bring up the WireGuard network interface
  ^ here
`

Here is what my main.yml file says on  line 59 to 63:

`- name: Enable the WireGuard service so it starts at boot, and bring up the WireGuard network interface
  systemd:
    name: wg-quick@wg0-server.service
    enabled: yes
    state: started`

**Comment by jlund** [comment]
I will have to test this, but do Vultr 16.04 servers not ship with systemd? Also, what Ansible version do you have installed?

**Comment by DaveFlowberries** [comment]
ansible 2.1.1.0

Not sure if it has systemd, how would I test this?

**Comment by jlund** [comment]
I can't replicate this, but it's possible that there's only an issue with the Vultr 16.04 image in a certain region. Would you mind telling me which Vultr location you chose?

And how did you install Ansible? Via pip, or via Homebrew, or via a git checkout?

**Comment by DaveFlowberries** [comment]
I am using Singapore region. I installed Ansible via Homebrew on OSX 10.11.6.

As far as troubleshooting, I deleted the "Striesand" folder, and reinstalled, I also updated and reinstalled brew and Ansible. Finally, I deleted the server and tried a Tokyo server. Still get the same error. 

I used Striesand many times BEFORE the WireGuard update and never had any issues.

**Comment by DaveFlowberries** [comment]
Removing line 38 `- wireguard` from streisand/playbooks/streisand.yml allows me to bypass the issue, but then when installing it fails with "fatal: [123.123.123.123]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'wireguard_firewall_rules' is undefined"}

**Comment by jlund** [comment]
Oh! Duh! I totally misread your Ansible version number earlier today. Nice work, my brain!

You need to upgrade to Ansible 2.2. The systemd module is new in that version.

`brew update && brew install ansible` and you should be all set.

**Comment by DaveFlowberries** [comment]
That did the trick! I actually updated it previously but did not brew link it correctly because it was still using the old version for some reason. Anyhow, thank you so much for the help!
