### ISSUE TITLE
SporeStack support for streisand

### ISSUE THREAD

**Issue by teran-mckinney** [jlund/streisand#489]
Hi,

This is a pretty nifty project. I think it might be a bit overkill in some cases, but completely necessary in others.

I've been wanting to do a similar thing (on demand VPN as a service) with [SporeStack](https://sporestack.com/), but it'd probably be just a simple OpenVPN static key setup for starters.

If I wanted to integrate streisand with SporeStack, what would you need? Would you need a Ansible SporeStack provider of sorts? How would that would with payment involving a QR code printed to the terminal? Not sure if I'd be breaking any existing conventions or not.

I'm planning to add json launch file support to `sporestack`, along with a public Github repo where it will fetch json launch files from (not sure if directly or indirectly). This will be here: https://github.com/sporestack/sporestack-python

Curious to hear your thoughts on this.

Thanks,
Teran

Edit: VPN service is up: https://sporestack.com/launch/vpn

**Comment by cpu** [comment]
I don't believe we have the resources to support SporeStack at this point. Please let us know if there is something specific that you require to support it yourself. Thanks!
