### ISSUE TITLE
Download link for stunnel-5.40-installer.exe is broken, leads to 404 Not Found error.

### ISSUE THREAD

**Issue by ShenZhouHong** [jlund/streisand#493]
# Bug description
When a user attempts to download the stunnel software for Windows (`stunnel-5.40-installer.exe`), the link does not work, and results in a 404 Not Found error.

## Steps to reproduce
1. Visit the stunnel link under "Client Mirrors" at the streisand gateway (e.g. `https://198.51.100.24/mirror/#stunnel`)
2. Click on the link to download stunnel for windows (e.g. `https://198.51.100.24/mirror/stunnel/stunnel-5.40-installer.exe`)

Resulting page is the default nginx 404 Not Found error page/

## Expected behaviour
Clicking on the link should result in the stunnel installer for windows downloading.

# Workaround
Currently, it is possible to access the right download by navigating to the topmost directory of the stunnel mirrors, as directory listing is enabled on nginx. Going to the link `https://198.51.100.24/mirror/stunnel/` would reveal the mirrored stunnel files:

```
Index of /mirror/stunnel/

../
stunnel-5.40-win32-installer.exe                   29-Jan-2017 10:38             3258299
stunnel-5.40-win32-installer.exe.asc               29-Jan-2017 10:38                 811
stunnel-5.40.tar.gz                                29-Jan-2017 10:38              648828
stunnel-5.40.tar.gz.asc                            29-Jan-2017 10:38                 811
```

In this case, the correct file to download would be `stunnel-5.40-win32-installer.exe`, as opposed to the erronously linked `stunnel-5.40-installer.exe`

# Proposed solution
In the markdown template file, change the link from  `stunnel-5.40-installer.exe` to `stunnel-5.40-win32-installer.exe`. In the future, such a link should not be hardcoded but symbolically referenced, allowing the correct path in spite of updates or version changes.

**Footnote**: 198.51.100.24 is a part of an reserved IP address space made for the [purposes of documentation and training](https://tools.ietf.org/html/rfc5737), by the IETF. Concerned contributers need not to worry that I accidentally exposed my streisand instance IP.

**Comment by ShenZhouHong** [comment]
# Additional notes
In order to verify that this broken link is not symptomatic of a broader breakage, I went ahead and manually checked all mirrored files on the streisand mirrors page. It appears that the stunnel for windows link is the only link that is broken.

**Comment by ShenZhouHong** [comment]
I have fixed the problem, and created a pull request. @jlund can you check this solution, and merge? Thank you.

**Comment by jlund** [comment]
Thank you for the detailed bug report and pull request!

**Comment by jlund** [comment]
I also appreciate your thorough testing too.

**Comment by ShenZhouHong** [comment]
No problem, thank you. I appreciate the quick response and turnaround. Streisand has been very useful for me, and it's a pleasure to help out! :)
