### ISSUE TITLE
how can I change all the services conf and password

### ISSUE THREAD

**Issue by ookangzheng** [jlund/streisand#497]
Server: DigitalOcean, Ubuntu 16.04 64bit
I have my custom Lighttpd and DNSMasq already to block Ads
I want to change my custom DNS IP and Login Password from Nginx

how can I do it , like openvpn /etc/openvpn/server.conf etc
I dont know where can I change shadowsocks, openconnect, tor DNS settings

Thanks

**Comment by nickolasclarke** [comment]
All of this information can be found if you google the various services or if you poke through the `roles` folders for each service found in the `/playbooks` directory. Often what you'll need is found in the `main.yml` file under `/roles/$Service/tasks/`. Off the top of my head I know that the shadowsocks is configured at `/etc/shadowsocks-libev/config.json`

**Comment by cpu** [comment]
The intention of Streisand is not to have the configuration files manually edited after deployment. We don't have the resources to support this use case and I believe @nickolasclarke has already given some pointers so I'm going to close this issue.
