### ISSUE TITLE
Why Openconnect so slow?

### ISSUE THREAD

**Issue by ookangzheng** [jlund/streisand#499]
My internet speed is 100Mbps, and I use Cisco anyconnect on my mac and android phone, It reach 5Mbps only.
But I switch to Shadowsocks, or L2tp, Openvpn tcp mode, I can get at least 50Mbps.
Is there any tweak for the Openconnect config?

Thanks

**Comment by cpu** [comment]
I would ask this question of the OpenConnect maintainers. I'm not sure the answer and I don't believe it is a Streisand specific question at this point. Thanks!
