### ISSUE TITLE
Shadowsocks OTA has been deprecated - what does it mean for users in China of Streisand + Shadowsocks.

### ISSUE THREAD

**Issue by ortonomy** [jlund/streisand#502]
Hey, anybody know about this: http://shadowsocks.org/en/spec/one-time-auth.html 

The page reads:

```
One Time Auth
**(Deprecated)** (my emphasis)
One-time authentication (shortened as OTA) is a new experimental feature designed to improve the security against CCA. You should understand the protocol before reading this document.
```

Is there a replacement technology planned? Does anyone know the timeline for removal? Support for Shadowsocks is now in a Google group which I do not have access to. Thoughts? Feelings?

**Comment by hybtoy** [comment]
3 minutes earlier from you, I suggested to use ShadowsocksR (https://github.com/jlund/streisand/issues/501) with obfs instead of Shadowsocks + OTA
SSR more secure than SS.

**Comment by ortonomy** [comment]
@hybtoy  - thing is, OTA works well. Doesn't get blocked. why has it been deprecated?

**Comment by hybtoy** [comment]
@ortonomy not safe anymore, can be detected/hijacked by GFW

**Comment by jlund** [comment]
Here's what is being proposed to replace OTA in mainline Shadowsocks:

https://github.com/shadowsocks/shadowsocks-org/issues/30#issuecomment-272088373

https://shadowsocks.org/en/spec/AEAD.html

**Comment by cokebar** [comment]
@hybtoy OTA is used to avoid CCA attack. Not relating to GFW's dection method.

**Comment by hybtoy** [comment]
@cokebar verify_sha1 = OTA
https://github.com/breakwa11/shadowsocks-rss/blob/master/ssr.md#协议特性

<img src="https://lh3.googleusercontent.com/-RcJ-UIZNVt0/WJgFxyEskAI/AAAAAAAAANM/eQ1NYn-_Ebk/s0/screenshot%2525202017-02-06%252520001.png" border=0><br/>&nbsp;<br/>

**Comment by cokebar** [comment]
@hybtoy You are wrong.
see http://shadowsocks.org/en/spec/one-time-auth.html

**Comment by denoza** [comment]
Any comments on SS OTA performance? I am facing serious problems while using it for last couple of days. I have changed quite a few servers and gotten new IP addresses, still I am not able to get the right speed that I used to get.

**Comment by cokebar** [comment]
@denoza Your problem isn't related to OTA.

**Comment by jlund** [comment]
Let's merge this into #501.
