### ISSUE TITLE
Failed to install on custom VPS

### ISSUE THREAD

**Issue by ookangzheng** [jlund/streisand#503]
Server: Ubuntu 16.04 64bit
My Computer: Mac OSX 10.12

I already config the ansible.cfg and inventory files. but when I executed ansible-playbook playbooks/streisand.yml, it shows like this without and erros message. b4 that, I tried to install on vultr VPS, it works~~ dont know why
<img width="925" alt="screenshot 2017-02-06 02 15 11" src="https://cloud.githubusercontent.com/assets/6301735/22631688/226d7b0e-ec12-11e6-8cde-f5a91e66efdf.png">

**Comment by jlund** [comment]
Are the inventory lines commented out?

**Comment by ookangzheng** [comment]
yap~~ 
<img width="623" alt="screenshot 2017-02-06 02 27 58" src="https://cloud.githubusercontent.com/assets/6301735/22631832/ee971d7e-ec13-11e6-9c30-240113b62c7d.png">

**Comment by jlund** [comment]
Looks like you have the `[streisand-host]` line commented out above the IP.

**Comment by ookangzheng** [comment]
ah... sorry for that ~~
Thanks anyway

**Comment by jlund** [comment]
No problem! It should work once that line is uncommented.

**Comment by ookangzheng** [comment]
<img width="950" alt="screenshot 2017-02-06 03 01 53" src="https://cloud.githubusercontent.com/assets/6301735/22632337/a9cfffb2-ec18-11e6-9c1d-2b17a42141df.png">
the error

**Comment by jlund** [comment]
What provider are you using? This typically happens on extremely low-end VPS systems or virtualization types where performance is unlikely to be acceptable.

**Comment by atulsian89** [comment]
@ookangzheng are you by any chance using Openvz. I get similar error on openvpz. If you kernel version is 2.7 or less, you will get that error.

**Comment by ookangzheng** [comment]
I use https://www.vps.ag/cloud, cause cheap lol.. I also think is OpenVZ
if i use this https://www.vps.ag/kvm will be ok? haven't try yet

**Comment by atulsian89** [comment]
Yes it should work. It works on xen, Kvm vps

**Comment by ookangzheng** [comment]
I use apt-get install virt-what and check is lxc
also when I tried to enable tun with cmd "modprobe tun" 
It comes error "modprobe: ERROR: ../libkmod/libkmod.c:586 kmod_search_moddep() could not open moddep file '/lib/modules/4.4.35-2-pve/modules.dep.bin'
modprobe: FATAL: Module tun not found in directory /lib/modules/4.4.35-2-pve" 

I think i just change another vps provider lol

**Comment by AnObfuscator** [comment]
> Looks like you have the `[streisand-host]` line commented out above the IP.

I just made the same mistake. :(

Maybe the playbook could print an error if the value isn't set.

**Comment by cpu** [comment]
Better support for [existing servers](https://github.com/jlund/streisand#running-streisand-on-other-providers-advanced) was added recently. I'm going to close this issue since its no longer actionable. Thanks!
