### ISSUE TITLE
checking for content of /etc/apt/source.list

### ISSUE THREAD

**Issue by antoineclaval** [jlund/streisand#506]
Hi guys,

After successfully installed streisand on a EC2 instance, I've try with a noname VPS.
I've run into one minor issue that forced me to do manual modification to /etc/apt/sources.list.

I had 
```
deb http://us.archive.ubuntu.com/ubuntu xenial main
deb http://security.ubuntu.com/ubuntu xenial-updates main

```
and the package `expect` is not in those repo. By adding 
```
deb http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ xenial universe
deb-src http://us-east-1.ec2.archive.ubuntu.com/ubuntu/ xenial universe
```
The process can go further. 

Is that something we could test before hand? ( testing that the sources.list has the minimum set of repo, and if not adding them )

**Comment by antoineclaval** [comment]
In the same spirit, listing the kernels modules installed with lsmod could be helpfull for a fast fail of the install.

**Comment by antoineclaval** [comment]
Hi, 

I'm running on the same issue again when I deploy on really bare-bone custom servers, manually it's straightforward to fix it. Or they could be provisioned before hands. Unfortunatly I can't do that.

Would that be do-able to use apt_repository to ensure correct /etc/apt/source.list?
http://docs.ansible.com/ansible/apt_repository_module.html

If someone point me in the right direction I can prepare a PR, I'm just not super familiar with ansible.
Should apt be a folder in playbooks/roles? 

Thanks

**Comment by cpu** [comment]
Hi @antoineclaval - We don't have the resources to support more providers at this point. If you are able to reduce your problem to the minimum changes required and submit a PR we would review it but substantial new code for unsupported providers is unlikely to be merged presently. Thanks!
