### ISSUE TITLE
Failed adding Shadowsocks-libev repository

### ISSUE THREAD

**Issue by applestoooranges** [jlund/streisand#507]
I'm following the instructions using a clean DigialOcean server. Looks like the shadowsocks.org repo cannot be found.

![error](https://cloud.githubusercontent.com/assets/25688909/22829923/ad1517f0-efdf-11e6-8e1e-f12947a6b3f4.png)

**Comment by edobry** [comment]
I'm having the same issue. I'd go in and fix it, but even then, idk how to re-run only that one step.

**Comment by ddvzlnz** [comment]
Same problem on Vultr at 2:30 pm Eastern.

TASK [shadowsocks : Add the Shadowsocks-libev repository] **********************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: , E:Some index files failed to download. They have been ignored, or old ones used instead.
fatal: [45.32.207.153]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_t2P7Ih/ansible_module_apt_repository.py\", line 538, in <module>\n    main()\n  File \"/tmp/ansible_t2P7Ih/ansible_module_apt_repository.py\", line 527, in main\n    cache.update()\n  File \"/usr/lib/python2.7/dist-packages/apt/cache.py\", line 440, in update\n    raise FetchFailedException(e)\napt.cache.FetchFailedException: W:Failed to fetch http://shadowsocks.org/ubuntu/dists/trusty/main/binary-amd64/Packages  404  Not Found [IP: 104.28.19.85 80]\n, W:Failed to fetch http://shadowsocks.org/ubuntu/dists/trusty/main/binary-i386/Packages  404  Not Found [IP: 104.28.19.85 80]\n, E:Some index files failed to download. They have been ignored, or old ones used instead.\n", "module_stdout": "", "msg": "MODULE FAILURE"}

**Comment by ddvzlnz** [comment]
Does anyone know where the files have moved to?  I can't find them on the shadowsocks site.

**Comment by ddvzlnz** [comment]
Ugh, looks like it won't work with anything earlier than 16.10 because of a libsodium dependancy.

https://github.com/shadowsocks/shadowsocks-libev/issues/1170

**Comment by libussa** [comment]
this fails on 16.04 here too

**Comment by denoza** [comment]
> I'm using 14.04, so much for LTS.

@ddvzlnz I think you should use Ubuntu 16.04 LTS, Streisand documentation mentions that too.

> this fails on 16.04 here too

@libussa try `sudo apt update && sudo apt dist-upgrade` on your newly run VPS, sometimes the image templates provided by the providers are outdated. I was able to deploy a streisand server with the most recent code just two days ago.

**Comment by libussa** [comment]
@denoza Looks like the error is due to a 404 on http://shadowsocks.org/ubuntu/dists/trusty/main/binary-amd64/Packages
Let's hope that's temporary...

**Comment by eteete** [comment]
I hope so.

**Comment by ookangzheng** [comment]
me too@@

**Comment by eteete** [comment]
That would be nice if they put an option for it or others etc. so we can able to avoid future similar problems.

**Comment by cyberthal** [comment]
So we should not attempt to provision a Digital Ocean Streisand server until this link no longer 404s or a solution is posted to this thread?

http://shadowsocks.org/ubuntu/dists/trusty/main/binary-amd64/Packages

**Comment by ddvzlnz** [comment]
It is not a Digital Ocean problem, it is a problem witht the files not being available for download problem, which in turn might be because of changes to shadowsocks and things it depends on.

**Comment by cyberthal** [comment]
Ok. So Streisand is currently broken for everyone, correct?

**Comment by lizardman1999** [comment]
You can still install so long as you comment out or delete Shadowsox sections out of the following playbooks:
streisand.yml
roles/streisand-gateway/templates/firewall.md.j2
roles/ufw/tasks.yml
roles/streisand-mirror/tasks/main.yml

**Comment by eteete** [comment]
@lizardman1999 I tried to remove Shadowsocks section from the playbooks but did not work. installation failed with below msg and streisand did not up.

TASK [streisand-mirror : Generate the Markdown mirror page] ********************
fatal: [45.33.110.127]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'shadowsocks_python_filename' is undefined"}

**Comment by lizardman1999** [comment]
Sorry missed one - you will also need to comment out or remove the Shadowsocks line in:

roles/streisand-mirror/tasks/main.yml

**Comment by eteete** [comment]
@lizardman1999 no, you did not. you typed in previous post as last line.

**Comment by lizardman1999** [comment]
Try editing Shadowsocks sections out of this one:

roles/streisand-mirror/templates/mirror-index.md.j2

**Comment by eteete** [comment]
it worked, thanks @lizardman1999..

**Comment by jlund** [comment]
Hey, everyone! I just pushed a fix for this. I am really sorry about the delay. Both my work and personal life have been pretty crazy lately and I was not expecting this repository to disappear :)

Shadowsocks is now being compiled from source while I investigate a long-term replacement strategy. Things will either be moving to ShadowsocksR or Shadowsocks2. This is being tracked in issue #501.

Thanks for your patience!

**Comment by applestoooranges** [comment]
Thanks @jlund, you're awesome.
