### ISSUE TITLE
WireGuard only

### ISSUE THREAD

**Issue by bpinto** [jlund/streisand#509]
Is it possible to configure a server with wireguard support only?

**Comment by sjug** [comment]
Came here for this. @jlund, let me know if you need help or if that's not planned I can fork.

**Comment by bpinto** [comment]
Problem with that is that for instance the role `ufw` or `monit` will fail. If I don't have everything enabled.

**Comment by sjug** [comment]
Yeah I worked through it last night, there are a few undefined variables set like `ocserv_port` that make disabling some roles a PITA. If I have time I'll put in a PR, there's a few issues that I've found so far.

**Comment by jlund** [comment]
I am also currently working on this. Everything will soon be untangled so you can just comment out the roles you don't want and live the pure, unsullied, next-gen VPN lifestyle of a WireGuard-only user.

**Comment by cpu** [comment]
I've picked up the torch to carry towards support for modular roles in Streisand. I'll be creating an "omnibus" issue with a plan in the near future. For now I'm going to close this as a duplicate since its a subset of the larger request to enable/disable Streisand services selectively. Thanks!

**Comment by agrieco** [comment]
@cpu Can you please link the larger request into this one for those that might find it to know when it is resolved?

**Comment by cpu** [comment]
@agrieco Sure. The related issue is https://github.com/jlund/streisand/issues/746
