### ISSUE TITLE
Compile and install Libreswan hangs EC2 instance

### ISSUE THREAD

**Issue by ryanwmarsh** [jlund/streisand#516]
Steps to reproduce:

`./streisand`

1. Option 1 for AWS
1. Option 10 for US East 
1. Default VPC
1. Default subnet 
1. Default name
1. Enter access key ID
1. Enter access secret key
1. Wait for instance to launch, immediately SSH in to the box.
1. Run `top` and just watch, see what you would expect for each step in the Ansible playbook
1. When it gets to `TASK [l2tp-ipsec : Compile and install Libreswan (this will take a while)] *****` it will freeze the script and your ssh session. 
1. Try to ssh back into the instance, you will not be able to connect. It's like `sshd` dies or something.
1. Check instance monitoring, you should see CPU usage dropped to nil

**Comment by cpu** [comment]
Hi @ryanwmarsh - are you still able to reproduce this with a fresh EC2 instance and the tip of master cloned?

**Comment by cpu** [comment]
There hasn't been a reply to my question from April 6th so I'm going to close this issue as stale. Please reopen if you find that the tip of master reproduces this problem for a fresh server install. Thanks!
