### ISSUE TITLE
Failure in setup: msg: unsupported parameter for module: rules_egress

### ISSUE THREAD

**Issue by rmusser01** [jlund/streisand#52]
In trying to setup streisand on a fresh Amazon EC2 Instance, I continue to get this error:

TASK: [ec2-security-group | Open the SSH port in the EC2 security group] ******
failed: [127.0.0.1] => {"failed": true}
msg: unsupported parameter for module: rules_egress

FATAL: all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/home/ubuntu/amazon.retry

127.0.0.1                  : ok=7    changed=1    unreachable=0    failed=1

**Comment by propic** [comment]
Hello, I had a similar issue during install (Default EC2-VPC and Ansible 1.9):


TASK: [ec2-security-group | Create the EC2 security group] ******************** 
changed: [localhost -> 127.0.0.1]

TASK: [ec2-security-group | Pause for fifteen seconds to ensure the EC2 security group has been created] *** 
(^C-c = continue early, ^C-a = abort)
[localhost]
Pausing for 15 seconds
ok: [localhost]

TASK: [ec2-security-group | Open the SSH port in the EC2 security group] ****** 
failed: [localhost -> 127.0.0.1] => {"failed": true, "parsed": false}
Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1424161838.77-114736410875057/ec2_group", line 2189, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1424161838.77-114736410875057/ec2_group", line 349, in main
    cidr_ip=ip)
  File "/usr/lib/python2.6/site-packages/boto/ec2/connection.py", line 3229, in authorize_security_group_egress
    params, verb='POST')
  File "/usr/lib/python2.6/site-packages/boto/connection.py", line 1226, in get_status
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Only Amazon VPC security groups may be used with this operation.</Message></Error></Errors><RequestID>24c0acc0-6084-494a-80d0-b52cf2bd3aac</RequestID></Response>


FATAL: all hosts have already failed -- aborting

PLAY RECAP ******************************************************************** 
           to retry, use: --limit @/root/amazon.retry

localhost                  : ok=7    changed=1    unreachable=0    failed=1

**Comment by BBB** [comment]
@propic @jlund I also have the same issue. EC2 VPC and ansible 1.8.3. See issue #139.

**Comment by jlund** [comment]
Sadly, I still haven't found a way to automatically provision new servers within AWS accounts where EC2 Classic is enabled. It's not feasible to perform a considerable refactor of the relevant Ansible modules in order to enable this either. The best option is to configure a single instance manually using the instructions from the README. Now that the upgrade to Ubuntu 14.04 is complete, making it easier to configure individual servers that were created outside of Streisand is going to be my top priority.

**Comment by SunSparc** [comment]
One solution could be to just specify a VPC ID. Of course, that requires setting up a VPC. I have an account that supports classic. When I setup a security group I have the option of specifying a vpc_id or not. If I do not, the group is assigned to classic. But if you are trying to specify egress rules, then you are required to specify a VPC. Making a VPC is annoying, but a basic one is pretty easy to set up. If you have a bunch of existing infrastructure in classic, Amazon is trying to get you to "upgrade" to using VPCs. Might as well head that direction.

**Comment by jlund** [comment]
This was just fixed in #371. Hooray!
