### ISSUE TITLE
Shanghai Linux Meetup - Streisand Workshop 24 Feb 2017

### ISSUE THREAD

**Issue by vrms** [jlund/streisand#520]
https://www.meetup.com/Shanghai-Linux-Meetup/events/237645001/

**Comment by nickolasclarke** [comment]
signed up!

**Comment by vrms** [comment]
great, thanks. See you next Friday then

**Comment by cpu** [comment]
Hope you had a great meetup! I'm going to close this issue since the event has already passed.
