### ISSUE TITLE
The issue is mine, little doubts: 1) Kill Switch  2) P2P

### ISSUE THREAD

**Issue by github3210** [jlund/streisand#523]
Yes, I need to say that you are the ******* best folks out there! Tens of stars for you!

My doubt:  Does Streisand have automatic...

1) Kill Switch ?

 2) P2P over VPN functionality when someone uses torrent, emule...  clients ?

Great job my amigos (friends)!  :)

**Comment by github3210** [comment]
Thank you for your participation.

For example, the user opens a torrent app and emule, starting to download
and share files. These connections are in or out of the VPN tunnel?In many
commercial apps would be out. You could find more details using a search
engine, keywords: VPN software torrent. Some examples have been listed
here: https://www.privacytools.io

El viernes, 7 de abril de 2017, Daniel McCarney <notifications@github.com>
escribió:
> My doubt: Does Streisand have automatic...
> Kill Switch ?
It does not. Sounds like an interesting idea.
>
> P2P over VPN functionality when someone uses torrent, emule... clients ?
>
> It does not - can you explain what you mean?
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly, view it on GitHub, or mute the thread.<
https://ci4.googleusercontent.com/proxy/ZhqnggxwzNCvgB4YgBPflRjqThvxq8tuX3qHmzYm4VHMUopn9EeZFASzPGhJuvgBpQvjd9cMIQXEHt7OTqOAmwQQ3wzK_cQMEMIOfRXuNlhbiyuRvUfkjwedlzpt25lubVSlw6o4K6-AheyHKJ3Si6TijyNVyQ=s0-d-e1-ft#https://github.com/notifications/beacon/AYrCzDKYOqgeyfjHmNB7fFI2u1F26ezdks5rtZHtgaJpZM4MFQ_q.gif>

**Comment by cpu** [comment]
#726 was asking for a "kill switch" as well. I'm still uncertain what this actually means. Can someone specify this feature request in greater detail? Perhaps you can point at an existing open source implementation of the concept?

**Comment by kar2013** [comment]
Dear all,

the issu # 726 it's mine.
killswitch exist in many other VPN.

Imagine OpenVPN drop out you real IP will be reveal.

Killswitch turn off immedialtly your internet connection in this case.

Thanks for your solutions

**Comment by cpu** [comment]
@kar2013 That sounds like a feature request for a client. How can the Streisand server do anything to help in this case? I would recommend that you request this feature from the OpenVPN client that you are using.

**Comment by kar2013** [comment]
@cpu thanks for your replying!
It's true, This request concern the openvpn client.

Sorry for the inconvenience
I will continue my research on this side

**Comment by cpu** [comment]
No inconvenience :-) Thanks!

**Comment by github3210** [comment]
Thank you very much for your help. Ok, Closed #523
<https://github.com/jlund/streisand/issues/523>. Please, kar2013, if you
find a solution let us know.

Yep, sure, Streisand, an amazing project!


2017-06-05 18:05 GMT+00:00 Daniel McCarney <notifications@github.com>:

**Comment by nopdotcom** [comment]
I think it might be worthwhile to do a survey of timeouts and behavior when VPN connectivity is lost. Think I'm going to save that for an upcoming group of tests.

**Comment by rdbox** [comment]
Anyone have any ideas for creating a kill-switch?
on the network I can not find a way for windows 7
