### ISSUE TITLE
OpenVPN Ubuntu instructions should mention Gnome

### ISSUE THREAD

**Issue by mangyfox** [jlund/streisand#531]
Whilst following the setup instructions for OpenVPN on Linux (Ubuntu) I hit a snag. After installing network-manager-openvpn as instructed, I was unable to select OpenVPN in the network settings.

After some searching, I discovered that I also had to install network-manager-openvpn-gnome. Once this package was installed I could select OpenVPN, follow the rest of the instructions, and everything worked perfectly.

I'm running Ubuntu 16.04, with no relevant changes from the default setup, so I imagine other users will also be running into this problem. For this reason, I think it would be useful to mention network-manager-openvpn-gnome in the Ubuntu instructions.

**Comment by mlcdf** [comment]
I had the same issue. I just opened a PR in order to add a little notice about this.

**Comment by jlund** [comment]
Thanks for the bug report!
