### ISSUE TITLE
For the FAQ: DigitalOcean blocks UDP on ports 80 and 443

### ISSUE THREAD

**Issue by quinncomendant** [jlund/streisand#532]
I discovered DigitalOcean blocks UDP on ports 80 and 443. This may make DigitalOcean unsuitable as a host for some people. The result is failure to use some services over the VPN, e.g.: dnscrypt-proxy, Chrome's QUIC protocol, and probably more. [Full thread here](https://github.com/trailofbits/algo/issues/229).

**Comment by josephlhall** [comment]
I had followed up with DO support to see if they can do per-droplet lifting of the UDP ban on 80/443, and while there is evidence that they've done this in the past, no longer:

>There has been a response to your ticket:
>
>Hi Joseph,
>
>I'd like to apologize for the confusion in how this ticket was handled - removing the UDP block isn't something we're going to be able to do.
>
>Regards,
>
>Trust & Safety,
>Digital Ocean Support

**Comment by quinncomendant** [comment]
I asked them too, if there is any possibility to remove the filtering of UDP on port 443/80 and they replied:

> Unfortunately we wouldn't be able to remove this filter as it exposes many security risks to the droplets running on the physical machine and to the network in general.

**Comment by josephlhall** [comment]
Hi, I've been working with DO support today and can confirm that there are no UDP blocks on 80/443. Are you still seeing this on new or old droplets?

**Comment by quinncomendant** [comment]
Plot twist! [Cross-posted from [Algo #229](https://github.com/trailofbits/algo/issues/229).]

DigitalOcean followed up on my earlier support request, this time with a positive twist. They were able to remove the port 80/443 UDP block for my account. They plan to remove the block entirely from their infrastructure, but in the meantime, anyone can request to have the block removed from their account. 

I've setup a new Algo VPN droplet, and DNS over port 443 UDP is working. 👍

Here's the full thread of our conversation:

On Sat, 04 Mar 2017 22:16:26 +0000, DigitalOcean (Jon Schwenn) wrote:
> I wanted to let you know that after more testing I believe I have 
> narrowed down the filtering issue. I'm going to see what we can do to 
> resolve that on Monday.

On Mon, 06 Mar 2017 21:41:18 +0000, DigitalOcean (Jon Schwenn) wrote:
> To follow up on our earlier conversation, I have narrowed down where 
> there is still a remaining block on that port and protocol 
> combination.  I've escalated a request to remove it for you.  I'll be 
> in touch when that is processed.  Also, I have a longer running task 
> of working with various teams to remove it on a more general basis as 
> we have done with the blocks in other areas of the network stack.

On Fri, 10 Mar 2017 06:33:44 +0530, Quinn Comendant wrote:
> Cool! I'll also need some certainty that future droplets created at DO 
> will not have this block if I am going to recommend DO to my colleagues. 
> Please let me know if you can make a statement that I can share publically.

On Fri, 10 Mar 2017 01:18:58 +0000, DigitalOcean (Jon Schwenn) wrote:
> As soon as my request is completed through engineering you'll be all 
> set and I'll update this ticket. All of your future Droplets would be 
> affected and will be able to pass the traffic. I do not have any 
> platform-wide answers or statements, but that is something we are 
> working on as well.  It's much faster to clear it for just a few 
> accounts, so that is what we are doing in the interim. The 
> engineering team specific to this work is a bit backed up and that is 
> why it's taking longer than I'd like.  Please know that it is 
> something that we are working on and I will be getting back to you 
> soon.

On Fri, 10 Mar 2017 08:08:52 +0530, Quinn Comendant wrote:
> I have a few collegues who are waiting on an answer to this as well. 
> I had suggested they go with DO, but then it's like, oh, wait, no. 
> After they setup their account, is it as simple as submitting a 
> request to have the block removed? Can you promise that will be 
> achievable for every new account?

On Fri, 10 Mar 2017 02:54:15 +0000, DigitalOcean (Jon Schwenn) wrote:
> The goal is to loosen this restriction platform wide.  We already 
> removed them from other areas of the platform, and this is the last 
> remaining place where it is blocked. At this time I can not make any 
> promises or give specific ETA's, but I don't foresee a problem 
> getting this done at the platform level. 

On Fri, 10 Mar 2017 10:15:35 +0530, Quinn Comendant wrote:
> When you say "from other areas of the platform" does that mean from 
> other regions? Eg., If N California has blocks, perhaps East coast 
> doesn't?

On Fri, 10 Mar 2017 04:57:03 +0000, DigitalOcean (Jon Schwenn) wrote:
> I apologize for not being clearer. The block was in place in multiple 
> locations within the platform. 
> 
> Some of the "locations" would be the edge routers in our Network, 
> hypervisors, and the virtual switch software that provides Droplets 
> with connectivity.  We've already had this block removed at the edge 
> routers and other areas of the network.
> 
> If and when we clear the remaining block, every region would be open 
> at that point.  

On Fri, 10 Mar 2017 19:25:16 +0000, DigitalOcean (Jon Schwenn) wrote:
> You should be good to create new Droplets to test this out further.  
> Please note that this was done for your account and is not yet a 
> default behavior for all accounts.  I'm still working on that and it 
> may take awhile until we're able to get that change put into 
> production.

**Comment by cpu** [comment]
@josephlhall @quinncomendant Thanks for chasing this down! Do you know what the current state of the world is? Is the block fully removed or should there be an addition to the README that documents that they will remove it if asked?

**Comment by quinncomendant** [comment]
I haven't spoken with DO again since my last post, when Jon Schwenn said this “is not yet a default behavior for all accounts.” It's worth asking DO support if the block has been removed system-wide.

DO has been working well for me, although sometimes I'd discover that my VPN IP is blocked by some sites, or triggers solving captchas before accessing google.com, in which case I'll just rebuild Algo to get a new IP address. I'm using a droplet in the SFO2 datacenter now, and it works works well.

**Comment by cpu** [comment]
Assigning to myself to remember to follow up with Digital Ocean support to hopefully close this once and for all.

**Comment by cpu** [comment]
I opened a support ticket to inquire if the block has been removed across the whole Digital Ocean infrastructure, or if it hasn't if there is an ETA. I'll close or update this ticket based on the response.

**Comment by tam7t** [comment]
FYI this block should be removed fleet-wide now

**Comment by cpu** [comment]
@tam7t How recently did this happen? I was told on the 21st by support that it wasn't removed fleet wide and there was no ETA, I hadn't had a chance to update this issue with that response. Is it possible support has stale information?

**Comment by tam7t** [comment]
@cpu yeah, the networking team pushed the change and notified support this afternoon

**Comment by cpu** [comment]
@tam7t That's awesome! Please pass our thanks on. I appreciate you following up on issue. I'm going to close this.
