### ISSUE TITLE
Streisand possible without SSH key authentication

### ISSUE THREAD

**Issue by dylanypyen** [jlund/streisand#533]
Hi all,
I've tried running the streisand.yml directly onto a running linux box at my provider. The problem is, the provider doesn't like public keys as authentication, preferring to use root passwords. Is streisand still possible?

Thank you very much.

**Comment by Xeoncross** [comment]
How in the world could a provider not allow public keys? That is like saying they don't accept credit cards - only cash.

**Comment by dylanypyen** [comment]
It's Aliyun by Alibaba; the Chinese govt doesn't like keys that it can't crack. So it doesn't allow Alibaba to even use public keys, because it can't intercept the information. It's complicated.

**Comment by Xeoncross** [comment]
I would think running an open, unencrypted proxy inside China is kind of a lost cause. Maybe you are wanting to tunnel into China to see what is blocked from inside?

At any rate, you can search using `ansible without ssh keys`. Most likely you will have to clone the digitalocean/linode script and remove the SSH key and add `ansible_pass` and maybe a wrapper to setup the password for the run.

- http://serverfault.com/questions/550561/how-to-make-ansible-use-password-if-key-was-rejected

**Comment by dylanypyen** [comment]
Nope, trying to run it on a Hong Kong based VPS running on Alibaba cloud. They have the best peering into China, thus are the best for a VPN solution. Thank you very much though.

**Comment by cpu** [comment]
@dylanypyen Streisand assumes key authentication is supported presently. It might be possible to work around this - if you do please submit a PR! In the mean time I'm not sure that the project will be able to support this provider.

**Comment by CorbanR** [comment]
I'm not sure Streisand would accept a pull request where it uses password authentication as an option to provision a server. Frankly I think that is a bad idea. I think the best advice, if you want to do this, would be as @Xeoncross suggested and google `ansible without ssh keys`.

**Comment by cpu** [comment]
I'm going to close this issue. We don't have the resources/interest in supporting providers that aren't able to accomodate SSH key access. Thanks!
