### ISSUE TITLE
maybe it is good idea to add these vpns in future

### ISSUE THREAD

**Issue by gsdu8g9** [jlund/streisand#536]
The author of govpn said that it works in China.
http://www.govpn.info/Modes-of-operation.html
https://github.com/stargrave/govpn

Also this vpn looks interesting.
But I am not sure that it will work everywhere. 
https://github.com/unbit/vpn-ws

**Comment by denoza** [comment]
I recently heard about Tinc VPN as well, however I don't know much about its security details and performance benchmarks:
https://www.tinc-vpn.org/

**Comment by strixaluco** [comment]
Tinc VPN has been discussed here: #144

**Comment by gsdu8g9** [comment]
Article about govpn advantages written by author
https://blogs.fsfe.org/stargrave/archives/158

**Comment by denoza** [comment]
> Tinc VPN has been discussed here: #144

Thanks for sharing this @strixaluco 

Recently, I came across the idea of using Openvpn over Shadowsocks. The documentation is mentioned here: https://github.com/shadowsocks/shadowsocks/wiki/Connect-to-OpenVPN-over-Shadowsocks. I think this idea can be explored as well, in addition to the option of having OpenVPN over stunnel.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/7
