### ISSUE TITLE
How to open a port ?

### ISSUE THREAD

**Issue by silvetti** [jlund/streisand#538]
Hi, I am running streisand on digitalocean. I have a Raspberry Pi connected to streisand via OpenVPN (direct). I want to be able to use Transmission (torrent app on the raspberry) to download ISO images but the app requires port (for example) 51415 open. How do I open the port on the streisand server ?

Cheers!

**Comment by denoza** [comment]
You can try `sudo ufw allow "port number"`. You have to replace "port number" with your desired port number, which is 51415 in this case.

**Comment by silvetti** [comment]
I have tried that with different ports (plus some other things) but I still get ports closed :/ Here is my output from ufw rules:

PS - If on the app I set 443 (it shows open obviously) so I'm not really sure what I am missing here :(

`root@streisand:~# sudo ufw status
Status: active

To                         Action      From
--                         ------      ----
22/tcp                     ALLOW       Anywhere                  
500/udp                    ALLOW       Anywhere                  
1701/udp                   ALLOW       Anywhere                  
4500/udp                   ALLOW       Anywhere                  
443/tcp                    ALLOW       Anywhere                  
53/udp                     ALLOW       192.168.1.0/24            
4443                       ALLOW       Anywhere                  
53/udp                     ALLOW       10.8.0.0/24               
53/udp                     ALLOW       10.9.0.0/24               
636/tcp                    ALLOW       Anywhere                  
8757/udp                   ALLOW       Anywhere                  
8530/tcp                   ALLOW       Anywhere                  
993/tcp                    ALLOW       Anywhere                  
8443/tcp                   ALLOW       Anywhere                  
9443/tcp                   ALLOW       Anywhere                  
53/udp                     ALLOW       10.192.122.0/24           
51820/udp                  ALLOW       Anywhere                  
51413/tcp                  ALLOW       Anywhere                  
51413/udp                  ALLOW       Anywhere                  
51413                      ALLOW       Anywhere                  
22/tcp (v6)                ALLOW       Anywhere (v6)             
500/udp (v6)               ALLOW       Anywhere (v6)             
1701/udp (v6)              ALLOW       Anywhere (v6)             
4500/udp (v6)              ALLOW       Anywhere (v6)             
443/tcp (v6)               ALLOW       Anywhere (v6)             
4443 (v6)                  ALLOW       Anywhere (v6)             
636/tcp (v6)               ALLOW       Anywhere (v6)             
8757/udp (v6)              ALLOW       Anywhere (v6)             
8530/tcp (v6)              ALLOW       Anywhere (v6)             
993/tcp (v6)               ALLOW       Anywhere (v6)             
8443/tcp (v6)              ALLOW       Anywhere (v6)             
9443/tcp (v6)              ALLOW       Anywhere (v6)             
51820/udp (v6)             ALLOW       Anywhere (v6)             
51413/tcp (v6)             ALLOW       Anywhere (v6)             
51413/udp (v6)             ALLOW       Anywhere (v6)             
51413 (v6)                 ALLOW       Anywhere (v6)             

root@streisand:~# 
`

**Comment by silvetti** [comment]
I have also tested from a different computer (diff OS as well) and same issue while connected to streisand. As soon as I disable tunnelbrick (osx) I get the port open.

**Comment by denoza** [comment]
I don't understand the problem: in the `ufw status` above on the streisand instance. It shows that your port number `51415` is not open. So perhaps you need to run `ufw allow 51415` on your streisand instance. (No need to sudo since you are root) My hunch is that since you use openvpn, therefore all your local traffic goes to the remote port functioning for openvpn. May be you should try some proxy service like 'shadowsocks' for browsing and use your the other port for torrenting?

**Comment by cpu** [comment]
@silvetti How are you testing that the ports are not opened? Have you tried enabling logging (`ufw logging on`) and seeing if there are messages in syslog from UFW blocking traffic on the ports you believe you opened?

**Comment by cpu** [comment]
I'm going to close this issue as stale since there hasn't been a response to my question from April 6th. Thanks - please reopen if you still require assistance.

**Comment by frybread** [comment]
If your OpenVPN runs on the streisand default port 636, then forward 51415 to 636.

1) Login to your Streisand server as root
2) Allow the port you need
`ufw allow 51415`
3) Add a before filter section in /etc/ufw/before.rules (at the top of file):

> *nat
> :PREROUTING ACCEPT [0:0]
> -A PREROUTING -p tcp --dport 51415 -j REDIRECT --to-port 636
> COMMIT

4) reboot the server
