### ISSUE TITLE
Slow speeds when using Linode

### ISSUE THREAD

**Issue by samstarling** [jlund/streisand#539]
I just provisioned a Streisand server on Linode, in the London region. What kind of throughput should I expect? Speedtest.net tells me I have a download speed of around 50 Mb/sec, but after connecting to my Streisand instance (over any method, I tried a few) this drops down to 0.25 Mb/sec.

**Comment by nickolasclarke** [comment]
this is dependent on many factors such as your location relative to the DC,
which connection method you are using, peering arrangements between you and
the DC etc.  I would often see low speeds like that from China on my
connections to DC's abroad. When you say that speedtest.net said you had a
DL of 50 Mb/sec, are you talking about a speedtest.net using the london DC
as the target?

**Comment by saadibrahim** [comment]
https://cloudharmony.com/speedtest-for-linode:compute

Use this to check which Linode location is the fastest for you (factoring in the ping/latency) and use that for streisand.

**Comment by cpu** [comment]
I don't believe there is enough information present here to help. Without the OP returning to provide it this issue will likely be closed as stale in the coming days. Thanks!

**Comment by samstarling** [comment]
Sure – I'll close this now, thanks everyone for the replies!
