### ISSUE TITLE
Instruction for OpenConnect GUI?

### ISSUE THREAD

**Issue by andinus** [jlund/streisand#540]
For OpenConnect, the generate doc currently only describes usage with command line.
I wonder if anyone is adding instruction for the [GUI](https://github.com/openconnect/openconnect-gui). Its UI isn't very user-friendly but I eventually manage to set it up. After that, it's quite convenient.

**Edit:** I realized that there is GUI for Windows, just, not for macOS, which I am using.

I could make a PR if it is deemed worthwhile.

**Comment by cpu** [comment]
Hi @andyshuhsin,

It sounds worthwhile to me provided you think the setup isn't too complex to document :-)

**Comment by cpu** [comment]
@andyshuhsin Ping - still interested in making a PR?

**Comment by cpu** [comment]
Closing this issue since it has gone unanswered so far.
