### ISSUE TITLE
Remote desktop

### ISSUE THREAD

**Issue by joopdorresteijn** [jlund/streisand#544]
Until now there seems to be a lot of effort to get the user's access to the free and uncensored internet through modern VPN technologies. How about returning to the terminal-server setup where the client would connect to via vnc/x2go/x11/insert solution session, and let's the streisand server act as the x server?

I'm asking because the dynamics would work differently. It would be about optimising the remote desktop speed (which can go to low and unstable bandwidths) and not optimising the actual browsing speed.

With shadowsockets on streisand/AWS i'm averaging 0.5mbps on various locations. 

In my own attempt, first with x11 (too slow to be functional) and then x2go, found that browsing the web is super fast (from mainland china) but found the rendering was choppy. suddenly I had a >100mbps connection. The effect to 'browse' was certainly different. I explored further and keep on testing. 

In terms of experiencing this approach.. You can see the browser get's the whole page at once (rendering the page doesn't 'build up' but enters the screen at once)... but just imagine you have a refresh rate of... 1.

It seems a bit dated though... Googling about this approach led to tons of posts < 2012. It would be likely that gfw can detect my type of traffic, but I wonder; would it be better with stunnel? just an direction that came up that I'd like to share with you.

**Comment by cpu** [comment]
I think this is sufficiently divergent from the goals/implementation of Streisand as it exists now that you're best to fork & start working towards this goal on your own. Thanks for understanding.
