### ISSUE TITLE
bbr support?

### ISSUE THREAD

**Issue by iaMeteor** [jlund/streisand#546]
Would you consider to add bbr support for tcp?

**Comment by cpu** [comment]
@iaMeteor Can you elaborate & provide some more documentation? I'm missing some context here and have to admit I don't know what "bbr support for tcp" is.

**Comment by yuanl** [comment]
BBR is a new congestion control algorithm developed at Google.
To do so, we need 4.9+ kernel which may not support on some provider.

**Comment by cpu** [comment]
@yuanl Aha! Thanks for commenting. I updated the tags to mark that this is a feature request blocked on a kernel dependency.

**Comment by cpu** [comment]
Closed in favour of https://github.com/jlund/streisand-discussions/issues/6
