### ISSUE TITLE
AWS L2TP not working

### ISSUE THREAD

**Issue by helderrodrigues** [jlund/streisand#550]
Hi just deployed streisand on AWS and unfortunatelly L2TP seems not being working. I checked the service  and it seems to be fine adn I don't see anything related with connection attemps. I tried from windows 10 and an iPhone.
Could you please assist?

Thanks.
`root@ip-172-23-23-23:~# /etc/init.d/xl2tpd status
● xl2tpd.service - LSB: layer 2 tunelling protocol daemon
   Loaded: loaded (/etc/init.d/xl2tpd; bad; vendor preset: enabled)
   Active: active (running) since Sun 2017-03-26 09:32:52 UTC; 5h 52min ago
     Docs: man:systemd-sysv-generator(8)
  Process: 2764 ExecStop=/etc/init.d/xl2tpd stop (code=exited, status=0/SUCCESS)
  Process: 2784 ExecStart=/etc/init.d/xl2tpd start (code=exited, status=0/SUCCESS)
    Tasks: 1
   Memory: 132.0K
      CPU: 4ms
   CGroup: /system.slice/xl2tpd.service
           └─2798 /usr/sbin/xl2tpd

Mar 26 09:32:52 ip-172-31-12-71 systemd[1]: Starting LSB: layer 2 tunelling protocol daemon...
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2792]: setsockopt recvref[30]: Protocol not available
Mar 26 09:32:52 ip-172-31-12-71 systemd[1]: Started LSB: layer 2 tunelling protocol daemon.
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2784]: Starting xl2tpd: xl2tpd.
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2798]: xl2tpd version xl2tpd-1.3.6 started on ip-172-23-23-23 PID:2798
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2798]: Written by Mark Spencer, Copyright (C) 1998, Adtran, Inc.
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2798]: Forked by Scott Balmos and David Stipp, (C) 2001
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2798]: Inherited by Jeff McAdams, (C) 2002
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2798]: Forked again by Xelerance (www.xelerance.com) (C) 2006
Mar 26 09:32:52 ip-172-31-12-71 xl2tpd[2798]: Listening on IP address 0.0.0.0, port 1701
`

**Comment by lgrimani** [comment]
I can get L2TP working on iphone but not working for me on Windows 10.  What error message do you get?

**Comment by cpu** [comment]
There hasn't been a reply from the OP about the error message and I believe this issue is too stale to be actionable. I'm going to close it. If you are still having trouble with a fresh Streisand instance created with the latest code from master please open a new issue and provide the information the issue template requests. Thanks!
