### ISSUE TITLE
How to cope with Ephemeral external IPs

### ISSUE THREAD

**Issue by hugocore** [jlund/streisand#555]
Hi guys,

Quick question, how do you cope with ephemeral external IPs on your cloud instances?

If I restart (stop and start) and instance, the external IP changes, then everything seems to brake. Tunnelblick config stops working, although I've tried to edit the .ovpn file. OpenVPN seems to brake too, not to mention the HTTPs connection to the gateway and instructions.

I guess you just assume that instances will have static IP, but not being able to change external IP it looks to me, like a deal breaker. To be anonymous you would need to able to change your IP, otherwise concerning parties could keep track and profile that static IP.

Cheers

**Comment by cpu** [comment]
I think presently the best bet is to fully tear down & re-provision the server when the external IP has changed. It might be best to favour a cloud provider with less ephemeral IP addresses given this limitation.

**Comment by cpu** [comment]
I'm going to close this issue since the question has been answered.

Better support for reprovisioning an existing server with a new IP address can be discussed in https://github.com/jlund/streisand/issues/184.

Thanks!
