### ISSUE TITLE
CentOS 6.5 additional steps

### ISSUE THREAD

**Issue by rmcentyre** [jlund/streisand#556]
Following the guide on from a Digital Ocean CentOS 6.5 server, I ran across the following errors out of the box.

`fatal: [ip]: UNREACHABLE! => {"changed": false, "msg": "jinja2", "unreachable": true}`

`fatal: [ip]: UNREACHABLE! => {"changed": false, "msg": "Incompatible ssh peer (no acceptable kex algorithm)", "unreachable": true}`

The first was resolved by installing and the second by updating paramiko:
`$ sudo yum install python-paramiko`
`$ sudo pip install paramiko --upgrade`

Installing paramiko is already listed as one of the steps for certain distros (and old CentOS version are certainly an edge case here), but I wanted to document the resolution of these specific error messages in case it helped a fellow user.

Feel free to close this issue if there's no compelling reason to update the README for this.

**Comment by cpu** [comment]
@rmcentyre Would you open a PR against the README? Seems like it should be possible to add a small note about this.

**Comment by cpu** [comment]
I'm going to close this issue for now. I haven't seen any others tripped up by this and there isn't a PR to evaluate. Thanks!

**Comment by its0x08** [comment]
this is what happens in CentOS -_- and it is really ugly!!

``` [WARNING]: Found both group and host with same name: localhost


PLAY [Prepare the new server for Ansible] *****************************************************************************************************************************************************************************************

TASK [Install Python using a raw SSH command to enable the execution of Ansible modules] ******************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "msg": "non-zero return code", "rc": 127, "stderr": "/bin/bash: apt: command not found\n", "stderr_lines": ["/bin/bash: apt: command not found"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/opt/streisand/playbooks/localhost.retry

PLAY RECAP ************************************************************************************************************************************************************************************************************************
localhost                  : ok=0    changed=0    unreachable=0    failed=1   

```

**Comment by cpu** [comment]
@its0x08 You're running Streisand to configure a CentOS server and it *exclusively* supports Ubuntu 16.04. This will not work and is unrelated to this original issue, which was about running Streisand on CentOS to configure a Ubuntu 16.04 server.

I'm going to lock this thread so it doesn't accumulate more off-topic responses. Thanks!
