### ISSUE TITLE
setup failure\issues on aws

### ISSUE THREAD

**Issue by ausoro** [jlund/streisand#560]
fatal: [54.148.0.175]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '54.148.0.175' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}
	to retry, use: --limit @/home/xxxx/streisand/playbooks/amazon.retry

PLAY RECAP *********************************************************************
54.148.0.175               : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=17   changed=9    unreachable=0    failed=0   

A couple issues.
 
First of all, the failure above reproduces consistently. Initially I assumed it was a timing issue so I increased the timeout from 90mins to 300 mins. It didn't work. 

It is also not clear how "--limit ..." retry step is to be used. If I invoke "./streisand --limit ..." after each failure, it just creates a new machine instance each time. does seem to be the expected result.

Lastly, where can I find the .pem file created with the machine instance eg. "streisand-ssh.pem"? I am unable to connect to the VM otherwise.

**Comment by blizzbhaller** [comment]
Just create an ec2 instance normally.  Edit the inventory file in the streisand folder and uncomment the last two lines.  Change the default ip there to the ip of your instance.  Add the following line:
ansible_ssh_private_key_file="your pem key and the path to it"
ansible_ssh_user=ubuntu

save the file and run
sudo ansible-playbook playbooks/streisand.yml

it should go through with the installation

**Comment by ausoro** [comment]
Thanks. It worked. 
A couple things...

1.) When editing the ~/streisand/inventory, make sure to each line specifies the IP address of the instance
e.g.
[streisand-host]
10.1.1.1 ansible_user=ubuntu
10.1.1.1 ansible_ssh_private_key_file=~/.ssh/your-2017.pem

2.) More of a request for ec2,  the setup (sudo ansible-playbook playbooks/streisand.yml) took a bit of time. I am don't know why but it would be great if the timeout for ec2 is increased. The current 90s seems too short (error in my previous post I meant secs not minutes). 

3.) When using this method, make sure the necessary port exceptions are present in the machine instance security group. In my case none of the exceptions were present after the setup and I had to add them manually.

**Comment by go-gitter** [comment]
hello,
I am facing the same issue and included below is the error message

< TASK [Wait for cloud-init to complete] >
fatal: [52.40.104.243]: UNREACHABLE! => {"changed": false, "msg": "Failed to connect to the host via ssh: Warning: Permanently added '52.40.104.243' (ECDSA) to the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable": true}
	to retry, use: --limit @/home/user1/streisand/playbooks/amazon.retry
 ____________
< PLAY RECAP >
 ------------
52.40.104.243              : ok=0    changed=0    unreachable=1    failed=0   
localhost                  : ok=17   changed=9    unreachable=0    failed=0  

@blizzbhaller - "Change the default ip there to the ip of your instance." - by IP of your instance, I am guessing you meant the IP of the EC2 instance, please let me know if it should be something else.

@ausoro - "10.1.1.1 ansible_user=ubuntu" - the IP 10.1.1.1 is that of your EC2?
