### ISSUE TITLE
SSH root access

### ISSUE THREAD

**Issue by wjkendall** [jlund/streisand#563]
So I have successfully deployed the streisand server and I am able to use it for VPN, however I am wondering how I'm supposed to make an SSH root access connection to the server now? I would like to be able to gain root access to the server for updates/upgrades and whatnot. How can I get the pem key to the new server please?

**Comment by andreagrax** [comment]
If streisand completes successfully (as I suppose is your case) your key is
already present on the server.
Which provider do you use?

**Comment by wjkendall** [comment]
Amazon EC2 instance...I see the 'streisand-ssh' key pair in AWS console but I am unclear on how to obtain the key to load into Putty.

**Comment by cbdumas** [comment]
I am having a similar issue on GCE, used the ansible playbook to create a new streisand instance about a week ago and it's been working great. However I would like to be able to log in as root and have so far been unable to do so. The 'SSH' button on the google cloud console does not work on this instance, and AFAIK that is the only way for me to get in as root. Did streisand change some sshd config that would prevent this from working properly? Is there another method or SSH key set up by Streisand that I should use?

**Comment by cbdumas** [comment]
@wjkendall I was able to get root access to my instance with two things: the rsa key that was used by ansible when standing up the instance (discussed in the prerequisites section of the instructions), and logging in as the user 'ubuntu'. Getting the user name correct is what I was missing I believe. Hope that helps.

**Comment by wjkendall** [comment]
@cbdumas Thanks! I will give that a shot.

**Comment by cpu** [comment]
I don't believe there are any outstanding actions for the project to take for this issue so I'm going to close it. Thanks! Please open a new issue if you're still having difficulty with SSH access.

**Comment by rolero** [comment]
Please reopen. It is still very unclear how to connect to the console now.

**Comment by cpu** [comment]
@rolero Please open a new [Streisand discussions thread](https://github.com/streisandeffect/discussions) if you have questions about SSH access.
