### ISSUE TITLE
Feature request: Third party cloud provider support for local key production and transfer

### ISSUE THREAD

**Issue by stuwags** [jlund/streisand#569]
User just supplies the ip, username, and password and we produce the key on client if a pub doesn't exist, and then it puts it into authorized keys on the client along with permissions. We then restart the ssh service to ensure it goes into effect.  This would be cool and helpful. 

This was an issue for me as configuration to bring up the server was annoying and number of issues caused it.

**Comment by cpu** [comment]
Hi @stuwags,

I'm not sure I understand the feature request as you've written it. Can you help by elaborating & clarifying?

When you say "User just supplies the ip, username, and password " -> the IP to the Streisand server to be provisioned? The username and password to what account/resource/service?

When you say "puts it into authorized keys on the client" you mean the host machine running the Ansible playbooks?

**Comment by stuwags** [comment]
Hi CPU, 

Sure. So I setup streisand on RamNode, and it was really easy once the script could connect to the server. However, it wasn't clear without googling, etc that I couldn't just login with username and password, even when supplying the command line arguments to use a username and password I supplied. The issue was I needed to setup an ssh rsa key. 

The thought is that perhaps instead of adding support for third parties, making the experience for any box on the net better would be good. Could we check to see if an RSA public key exists on the local machine (if not generate), and then call ssh-copy-id from the user's machine to the future streisand machine? Or enable username/password ansible support so that once a box is on the net, it can be setup as fast as possible.

**Comment by cpu** [comment]
Hi @stuwags - Thanks for taking the time to explain! I think I have a better handle on what you're asking for.

I believe https://github.com/jlund/streisand/issues/491 and https://github.com/jlund/streisand/issues/478 cover these requests so I'm going to close this issue for now to try and help with the backlog of open issues. If you think 491 and 478 aren't exactly what you were looking for maybe you could comment with your thoughts there and see if we can find some common ground without more duplication.

Thanks!

**Comment by stuwags** [comment]
Yep, that's exactly correct! Those feature requests are the same. Sorry I
missed them :)

**Comment by cpu** [comment]
No problem! Thanks for confirming.
