### ISSUE TITLE
Don't understand this error

### ISSUE THREAD

**Issue by gmmitche** [jlund/streisand#570]
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: libcloud.common.google.ResourceNotFoundError: {u'domain': u'global', u'message': u"The resource 'projects/gce-nvme/global/licenses/debian-8-jessie' was not found", u'reason': u'notFound'}
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_iY7nvD/ansible_module_gce.py\", line 671, in <module>\n    main()\n  File \"/tmp/ansible_iY7nvD/ansible_module_gce.py\", line 633, in main\n    module, gce, inames)\n  File \"/tmp/ansible_iY7nvD/ansible_module_gce.py\", line 464, in create_instances\n    name, lc_machine_type, lc_image(), **gce_args\n  File \"/tmp/ansible_iY7nvD/ansible_module_gce.py\", line 661, in __call__\n    self.image = self.gce.ex_get_image(self.name)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 3858, in ex_get_image\n    image = self._match_images(ex_project_list, partial_name)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 4286, in _match_images\n    ex_include_deprecated=True)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 1290, in list_images\n    ex_include_deprecated=dep))\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 1337, in ex_list_project_images\n    list_images.append(self._to_node_image(img))\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 5007, in _to_node_image\n    lic_objs = self._licenses_from_urls(licenses=image['licenses'])\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 5518, in _licenses_from_urls\n    name=lic_name))\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/compute/drivers/gce.py\", line 3725, in ex_get_license\n    response = self.connection.request(request, method='GET').object\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py\", line 684, in request\n    *args, **kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py\", line 736, in request\n    response = responseCls(**kwargs)\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/base.py\", line 119, in __init__\n    self.object = self.parse_body()\n  File \"/usr/local/lib/python2.7/dist-packages/libcloud/common/google.py\", line 259, in parse_body\n    raise ResourceNotFoundError(message, self.status, code)\nlibcloud.common.google.ResourceNotFoundError: {u'domain': u'global', u'message': u\"The resource 'projects/gce-nvme/global/licenses/debian-8-jessie' was not found\", u'reason': u'notFound'}\n", "module_stdout": "", "msg": "MODULE FAILURE"}

**Comment by gmmitche** [comment]
Sorted: I reran sudo pip install "apache-libcloud>=0.17.0" using --upgrade and it worked after that.

**Comment by jlund** [comment]
Good to hear!
