### ISSUE TITLE
403 Forbidden and Access Denied through OpenVPN on certain sites

### ISSUE THREAD

**Issue by jparmelee** [jlund/streisand#572]
Just setup a server on DigitalOcean, I am able to connect and use it from my Mac via TunnelBlick.  Have issues on two sites (so far) I am getting a 403 on ticketmaster.com and Access Denied on stubhub.com.  All other sites and functions seem to be working.

**Comment by cpu** [comment]
Hi @jparmelee,

Can you confirm that using a brand new non-Streisand Digital Ocean instance you are able to access ticketmaster and stubhub through the virtual server?

I suspect this issue isn't Streisand related but a policy decision by these websites to block access from hosting providers to try and combat ticket scalping.

**Comment by jparmelee** [comment]
Interesting thought.  Stubhub still gives me "Access Denied You don't have permission to access "http://www.stubhub.com/" on this server. Reference #18.302c1ab8.1491575400.2f140e1".  So that is likely DO blocking.  But Ticketmaster does work correctly on a non-Streisand virtual server.  I am getting "Forbidden" through my Streisand server.

**Comment by cpu** [comment]
@jparmelee Interesting. Digging through issues last night I also saw https://github.com/jlund/streisand/issues/481 which seems related in the observed effect & confirmation that it was a policy by the site in question.

Similar to @jlund's [comment on that issue](https://github.com/jlund/streisand/issues/481#issuecomment-273051132) could you try running a few `curl` commands from a SSH connection on your Streisand server to Ticketmaster? Does that generate the Forbidden response?

**Comment by jparmelee** [comment]
More interesting data.  I am getting this curl output from both the streisand and non-streisand boxes:

root@streisand:~# curl https://ticketmaster.com
<!DOCTYPE HTML PUBLIC "-//IETF//DTD HTML 2.0//EN">
<html><head>
<title>301 Moved Permanently</title>
</head><body>
<h1>Moved Permanently</h1>
<p>The document has moved <a href="http://www.ticketmaster.com/?dma_id=345">here</a>.</p>
</body></html>

But in Lynx I am getting the full page loading on the non-streisand box.  So it seems to be working but through the VPN I am getting Forbidden.

**Comment by cpu** [comment]
@jparmelee I believe you need to add `-L` to your curl command to get it to follow redirects like Lynx will. When you say "Through the VPN" - is your client configured to use OpenVPN or one of the other services (e.g. Wireguard, L2Tp, etc)?

**Comment by jparmelee** [comment]
Yeah, sorry I was just saying that Ticketmaster seems to work via curl on both hosts.  I am using the OpenVPN connection to route traffic through the VPN.

**Comment by cpu** [comment]
@jparmelee out of curiosity I tried accessing Ticketmaster.com through my own Streisand instance hosted in DigitalOcean using Wireguard and can confirm that I receive the same 403 Forbidden error. I strongly suspect they're using a WAF or some kind of heuristic blocking that might be hard to troubleshoot without their participation.

I would be interested in seeing if this is provider specific (e.g. since we're both using DigitalOcean to test) or a product of something Streisand related. Do you have the capability to run a Streisand server in a different provider (AWS, Linode, etc) to test? I will probably have a reason to create some test instances in the coming week if not.

**Comment by alimakki** [comment]
@cpu I've tried accessing ticketmaster.com through my OpenVPN (manually setup) server on DO hosted in the NY region, as well as a streisand setup in the AMS region. 

Neither gave me a 403 forbidden.

I suspect only a subset of DO IP address ranges are being affected.

**Comment by johnvoncolln** [comment]
I've got Streisand installed on Amazon US East Ohio and can confirm I cannot access these sites either.

**Comment by ZD4LIFE** [comment]
My Streisand instance is running in Linode and I also am receiving the same error
Forbidden
You don't have permission to access / on this server.

I would assume they are doing like Netflix and blocking specific IP/cidr ranges for hosting companies, to what end I cannot say.  
This is in their FAQ - http://help.ticketmaster.com/why-am-i-getting-a-blocked-forbidden-or-403-error-message/

Basically probably people set up bots on hosting providers to buy tickets faster once released so they can be scalped later.

Later,
C

**Comment by cpu** [comment]
@alimakki @johnvoncolln @jparmelee Thanks for all of the additional testing & information! 

Given this data & the link from @ZD4LIFE it seems unlikely that there is much that can be done to help this problem from Streisand's perspective. I'm going to close this issue as a result.

If the Ticketmaster blocking is particularly tough for you to work around I would encourage you to contact their support channels to express dissatisfaction at the privacy harming side effects of their bot detection strategy. Good luck!

**Comment by fbicknel** [comment]
Another site: kirklands.com:
```ASUSWRT-Merlin RT-AC68U 384.5-0 Sun May 13 01:53:17 UTC 2018
admin@RT-AC68U-4BB8:/tmp/home/root# curl -L https://kirklands.com
<html>
<head><title>403 Forbidden</title></head>
<body bgcolor="white">
<center><h1>403 Forbidden</h1></center>
</body>
</html>
admin@RT-AC68U-4BB8:/tmp/home/root# 
```
I contacted their support and got a big fat shrug, "It must be your VPN," from them.
