### ISSUE TITLE
sshuttle isn't working over 443

### ISSUE THREAD

**Issue by LewisLebentz** [jlund/streisand#575]
Tried changing the port from 22 to 443 and it fails. Using the latest version in AWS.

→ sshuttle --dns -r forward@streisand 0/0 -vv
Starting sshuttle proxy.
firewall manager: Starting firewall with Python version 2.7.10
firewall manager: ready method name pf.
IPv6 enabled: True
UDP enabled: False
DNS enabled: True
Binding redirector: 12300
TCP redirector listening on ('::1', 12300, 0, 0).
TCP redirector listening with <socket._socketobject object at 0x10b7030c0>.
TCP redirector listening on ('127.0.0.1', 12300).
TCP redirector listening with <socket._socketobject object at 0x10b703050>.
Binding DNS: 12300
DNS listening on ('::1', 12300, 0, 0).
DNS listening with <socket._socketobject object at 0x10b703440>.
DNS listening on ('127.0.0.1', 12300).
DNS listening with <socket._socketobject object at 0x10b703600>.
Starting client with Python version 2.7.10
c : connecting to server...
c : executing: ['ssh', 'forward@streisand', '--', 'exec /bin/sh -c \'P=python3.5; $P -V 2>/dev/null || P=python; exec "$P" -c \'"\'"\'import sys, os; verbosity=2; sys.stdin = os.fdopen(0, "rb"); exec(compile(sys.stdin.read(978), "assembler.py", "exec"))\'"\'"\'\'']
ssh_exchange_identification: Connection closed by remote host
c : fatal: failed to establish ssh session (1)

**Comment by LewisLebentz** [comment]
Port 443 was failing due to a Cisco WSA injecting it's own certificate, causing the connection to fail.

**Comment by jlund** [comment]
Ah yes, good ol' Talos :)

Glad that you got it sorted.
