### ISSUE TITLE
AWS Issues

### ISSUE THREAD

**Issue by hostwolf** [jlund/streisand#576]
I get this error while trying to deploy a server on AWS.

TASK [genesis-amazon : Get the default SSH key] ********************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cat", "~/.ssh/id_rsa.p                   ub"], "delta": "0:00:00.002003", "end": "2017-04-06 00:55:22.403418", "failed":                    true, "rc": 1, "start": "2017-04-06 00:55:22.401415", "stderr": "cat: /home/ubun                   tu/.ssh/id_rsa.pub: No such file or directory", "stdout": "", "stdout_lines": []                   , "warnings": []}
        to retry, use: --limit @/streisand/playbooks/amazon.retry

Also is there any way to deploy the server to the server I am on? I have a really cheap and powerful server via an AWS spot request and do not want to pay a ridiculous amount of money for another server. Maybe I missed something that allows me to do this, because the install doesn't work.

**Comment by hostwolf** [comment]
UPDATE [UNRESOLVED]:

Okay I was stupid on the SSH keys, easily fixed that issue. Now I am having a problem towards the end of the installation.

I go through normal AWS installation, then I get this error at the end.

TASK [genesis-amazon : Set the streisand_server_name variable] *****************
ok: [localhost]

TASK [genesis-amazon : New EC2 servers are occasionally slow to process incoming                                                                                                                      SSH connections even after the OpenSSH daemon has started up. Pause for 90 seco                                                                                                                     nds.] ***
Pausing for 90 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

PLAY [Checking instance status] ************************************************

TASK [Wait for cloud-init to complete] *****************************************
fatal: [35.163.157.52]: UNREACHABLE! => {"changed": false, "msg": "Failed to con                                                                                                                     nect to the host via ssh: Warning: Permanently added '35.163.157.52' (ECDSA) to                                                                                                                      the list of known hosts.\r\nPermission denied (publickey).\r\n", "unreachable":                                                                                                                      true}
        to retry, use: --limit @/streisand/playbooks/amazon.retry

PLAY RECAP *********************************************************************
35.163.157.52              : ok=0    changed=0    unreachable=1    failed=0
localhost                  : ok=17   changed=9    unreachable=0    failed=0

root@ip-172-31-47-20:/streisand#

**Comment by jlund** [comment]
It looks like Ansible can't connect to the new AWS instance using that public key.

To install on your existing server, just follow the directions in the README in the "Running Streisand on Other Providers" section. You will need to manually configure the security groups for the existing instances to allow the traffic that you want, but a file will be generated with all of the information that you'll need.

**Comment by hostwolf** [comment]
Awesome, I will try that.

**Comment by hostwolf** [comment]
Still getting the above issue when setting up on Amazon AWS.

**Comment by hostwolf** [comment]
Also, running --limi @/home/ubuntu/streisand/playbooks/amazon.retry as root gives me a permission denied error. This is very frustrating, I have been trying to get this setup on AWS for two weeks and all these errors.

**Comment by hostwolf** [comment]
UPDATE:

I cannot get this to work at all. There is no documentation on how to setup the ssh authorization so that one amazon server can talk to another. This needs to be done. 

Also, since you can only run the install once before losing permissions to access it, that means i have to set up a new server every single time the install fails. This is absurd. I would appreciate someone explaining to me how to properly setup the SSH key authorization for TWO aws servers, one setting the other up.

**Comment by cpu** [comment]
Deploying Streisand from one AWS node to another AWS node is not documented because it is not supported. I'm afraid we don't have the resources to support this mode - I encourage you to try using a better supported provisioning mode or perhaps use localhost mode on a Linode instance that lacks the complexity of AWS floating IPs/security groups. Thanks!
