### ISSUE TITLE
OpenVPN+Streisand wrong location

### ISSUE THREAD

**Issue by weyert** [jlund/streisand#583]
I have followed all the instructions and created a new Streisand server through Linode (Tokyo option 2) by passing my API key. After it completed the creation of the server I followed the instructions and after connecting to the OpenVPN and going to the link to find out the ip address in Google it shows a IPv6 address instead of the IPv4 one. If I then go to a ip2geo site it doesn't say I am in Tokyo. What am I doing wrong? I am using the latest OS X (Sierra) together with Viscosity VPN tool (similar to Tunnelblick)

**Comment by cpu** [comment]
Hi there,

This looks like a duplicate of https://github.com/jlund/streisand/issues/97. I'm going to close this issue and encourage you to subscribe to notifications for #97. Thanks!
