### ISSUE TITLE
Update shadowsocks-libev to 3.0.5, use AEAD cipher

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#586]
Currently the shadowsocks server role installs [shadowsocks-libev version 2.5.6](https://github.com/jlund/streisand/blob/7f1cc442ef99ec3f5cb19e169b809541b0f3446b/playbooks/roles/shadowsocks/vars/main.yml#L21) and an [ota mode](https://github.com/jlund/streisand/blob/7f1cc442ef99ec3f5cb19e169b809541b0f3446b/playbooks/roles/shadowsocks/defaults/main.yml#L7) that was [deprecated in version 3.0.0](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.0).

[Version 3.0.5](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.5) is the latest release as of the time of this issue and Streisand should build & install a deb for it instead of 2.5.6. At the same time the ciphersuite should be changed from [`aes-256-cfb`](https://github.com/jlund/streisand/blob/7f1cc442ef99ec3f5cb19e169b809541b0f3446b/playbooks/roles/shadowsocks/defaults/main.yml#L5) to `chacha20-ietf-poly1305`, a strong elliptic curve based AEAD ciphersuite.

**Comment by ortonomy** [comment]
I tried to build a ss server from ``libev 3.0.5`` last week but couldn't get it working, I'm sooooo happy that you're going to work on this! (As the latest macOS Sierra Shadowsocks-NG 1.5 has also completely deprecated OTA - it gives an error if you try to use it.)

**Comment by cpu** [comment]
@ortonomy Glad to hear it - I'll be looking for volunteers to test clients shortly. I'm likely only going to have the cycles to test a Linux client & an Android client with a shadowsocks-libev 3.0.5 Streisand server. If you have the ability to test OSX that would be great.

I'm also looking for volunteers with access to Windows and iOS clients to test & update the setup instructions as required. For this PR I will likely just delete references to "Enable OTA" in the client setup docs & hope that the clients support the current configuration options.

**Comment by cpu** [comment]
I've pushed my work-in-progress to the [cpu-shadowsocks-libev-3.0.5-nodeb](https://github.com/cpu/streisand/tree/cpu-shadowsocks-libev-3.0.5-nodeb) branch on my fork. 

https://github.com/cpu/streisand/commit/4d00ea478b8c4cd1d7f16a809c580f631d4702ce updates the role to build & install shadowsocks-libev 3.0.5 w/ a modern config. I haven't done any documentation or client mirror updates, or much extensive testing. I'm holding off on these items to make a PR but expect to have one ready inside of a week or so.

**Comment by alimakki** [comment]
@cpu let me know if I can help you with testing. What's pending on your list?

**Comment by ortonomy** [comment]
@cpu - sure, very happy to help with testing. I'm based in China, so long-term, I can also test how fast GFW does / does not detect server + block, or whatever you need me to test. 

One thing to note - there are very few iOS clients that support AEAD cyphers at the moment. The 'go to' software 'Potatso' doesn't support it out of the box. It used to be open source, but their dev took it closed source for v2.0. No release date.

Is it worth maintaining the option to turn OTA on or off as part of the ansible role while we're waiting for clients to catch up?

**Comment by cpu** [comment]
@alimakki - Windows, OSX, and iOS are untested. It sounds like iOS will be a problem based on @ortonomy's comments. For Windows - is https://github.com/shadowsocks/shadowsocks-windows the best client to test & document with? Is it the best maintained?

> sure, very happy to help with testing. I'm based in China, so long-term, I can also test how fast GFW does / does not detect server + block, or whatever you need me to test.

@ortonomy Awesome! Great to know.

> One thing to note - there are very few iOS clients that support AEAD cyphers at the moment. 

Hmmm. That's not very good :-( Do you know what ciphers are supported? I assume `aes-256-cfb` is one supported cipher since that's what is in use now?

> Is it worth maintaining the option to turn OTA on or off as part of the ansible role while we're waiting for clients to catch up?

I don't think so - I believe doing this would require shipping shadowsocks-libev<=v2.6.3. (I think, 3.0.0 marks it deprecated in release notes, not clear how fully removed it is). I don't want to hold back the most secure option by sticking to an old version. I also think running two versions side by side will be a major headache.

One compromise I can think of is to run a second `ss-server` process with a config that uses `aes-256-cfb` but no OTA mode. As I understand it (new to this whole ecosystem/protocol...) that would be a configuration that doesn't have ciphertext integrity. Not ideal and would be something I think you should have to opt-in to with some considerable warning.

**Comment by ortonomy** [comment]
@cpu 

> Hmmm. That's not very good :-( Do you know what ciphers are supported? I assume aes-256-cfb is one supported cipher since that's what is in use now?

Here's a list of cyphers supported in [Potatso](https://itunes.apple.com/gb/app/%E5%9C%9F%E8%B1%86%E4%B8%9D-potatso-%E5%BC%BA%E5%A4%A7%E7%9A%84%E7%BD%91%E7%BB%9C%E5%B7%A5%E5%85%B7/id1070901416?mt=8)

![potatso](https://cloud.githubusercontent.com/assets/6688676/24851534/98353522-1e06-11e7-8328-4a5df6f9d253.png)


> I don't think so - I believe doing this would require shipping shadowsocks-libev<=v2.6.3. 

Yes, then it's not a reasonable solution.

> One compromise I can think of is to run a second ss-server process with a config that uses aes-256-cfb but no OTA mode.

I think that would work. The only issue there is that OTA was invented / deployed so that they could obfuscate from the GFW. Seems that without OTA, GFW machine learning was detecting Shadowsocks connections and blocking the IP fairly quickly.

I wish you luck if you could create two processes and one with no OTA with stream cipher, it would be better than nothing.

**Comment by cpu** [comment]
@ortonomy - Thanks for the cipher list. It's nice to know we can upgrade from `aes-256-cfb` to `chacha20-ietf` in a legacy non-AEAD server.

**Comment by alimakki** [comment]
@cpu I cloned your branch but got the following error when installing shadowsocks on a digital ocean droplet:

`TASK [shadowsocks : Install the shadowsocks-libev dependencies] ****************
failed: [104.236.114.154] (item=[u'git', u'gcc', u'make', u'autoconf', u'automake', u'shtool', u'libtool', u'libev-dev', u'libmbedtls-dev', u'libpcre3-dev', u'libsodium-dev', u'libudns-dev', u'rngtools']) => {"failed": true, "item": ["git", "gcc", "make", "autoconf", "automake", "shtool", "libtool", "libev-dev", "libmbedtls-dev", "libpcre3-dev", "libsodium-dev", "libudns-dev", "rngtools"], "msg": "No package matching 'rngtools' is available"}`

**Comment by cpu** [comment]
@alimakki Thanks for catching that! That was a late addition to my role and I typo'd the package name. It should be `rng-tools` not `rngtools`. I fixed in https://github.com/cpu/streisand/commit/eb889704edcb3e9d1048b30ba9f1bba19e1c7cdf - can you pull & retest when you have time?

**Comment by alimakki** [comment]
@cpu Can do.

**Comment by alimakki** [comment]
@cpu Streisand set up successfully, however I keep getting errors that the proxy is refusing connections.

Tested on both Windows 10 and macOS.

![screen shot 2017-04-10 at 9 01 19 pm](https://cloud.githubusercontent.com/assets/920624/24888383/0eb424ae-1e31-11e7-856f-674834cbeea0.png)

Tried the Window client that comes bundled with Streisand as well as the one you mentioned above, same results (tried differents ciphers as well).

**Comment by hybtoy** [comment]
Latest Shadowsocks Python and Shadowsocks Windows client support AEAD ciphers. 
Will test it now with chacha20-poly1305

**Comment by hybtoy** [comment]
Everything working with chacha20-ietf-poly1305
iOS: latest Shadowrocket from Testflight
Windows: Shadowsocks 4.0.1

**Comment by ortonomy** [comment]
@hybtoy - how do you get the lastest shadowrocket from testflight?

**Comment by cpu** [comment]
> Streisand set up successfully, however I keep getting errors that the proxy is refusing connections.

@alimakki I left the [-v argument](https://github.com/cpu/streisand/blob/cpu-shadowsocks-libev-3.0.5-nodeb/playbooks/roles/shadowsocks/vars/main.yml#L40) in the daemon args. Can you compare the output from `journalctl -u shadowsocks-libev.service --since today --no-pager`  with a working client and one that is refusing connections?

**Comment by cpu** [comment]
I pushed another commit to my branch, https://github.com/cpu/streisand/commit/205dde3a8200e99ad26f1c81dea2757858ee0bdf, to fix the QR code generation. @jlund spotted that it was still appending an `-auth` suffix to the encryption method in the URI to signify OTA mode.

**Comment by alimakki** [comment]
@cpu , from the non-working client:

`Apr 11 22:38:24 djfklasdjf systemd[1]: Started Shadowsocks-libev Default Server Service.
Apr 11 22:38:24 djfklasdjf ss-server[11981]:  2017-04-11 22:38:24 ERROR: Invalid config path.
Apr 11 22:38:24 djfklasdjf systemd[1]: shadowsocks-libev.service: Main process exited, code=exited, status=255/n/a
Apr 11 22:38:24 djfklasdjf systemd[1]: shadowsocks-libev.service: Unit entered failed state.
Apr 11 22:38:24 djfklasdjf systemd[1]: shadowsocks-libev.service: Failed with result 'exit-code'.`

I also attached the generated shadowsocks-libev.service file from the server.
[shadowsocks-libev.service.zip](https://github.com/jlund/streisand/files/914876/shadowsocks-libev.service.zip)


I hope that helps!

**Comment by hybtoy** [comment]
@ortonomy You have to request invitation to testflight in Telegram group of Shadowrocket.
https://t.me/shadowrocketapp

**Comment by cpu** [comment]
@alimakki Very strange that it can't find the config file. Can you share the contents of `/etc/default/shadowsocks-libev` and the output from `stat /etc/shadowsocks-libev/config.json` ?

**Comment by cpu** [comment]
@hybtoy When you said you tested with the "Latest Shadowsocks Python" - was that the latest in PyPi? I only see [2.8.2 there](https://pypi.python.org/pypi/shadowsocks) and that's what we already mirror (seems old?).

**Comment by cpu** [comment]
I finished the last touches on my branch and submitted a PR (#611) - thanks for all the help so far everyone!

**Comment by hybtoy** [comment]
@cpu I didn't install it from pip. I have cloned SS python repository. 

git clone -b master https://github.com/shadowsocks/shadowsocks.git

**Comment by cpu** [comment]
@hybtoy Ahh! Interesting. I thought that repo was totally abandoned but it looks like the master branch is still active. In #611 I replaced the Python shadowsocks with go-shadowsocks2. I tested that client and it seemed to work well - have you thought about switching? Is there a downside I didn't see that I should consider?

**Comment by hybtoy** [comment]
@cpu Around 1 or 2 month ago I have tested go-shadowsocks2 but at that time
iOS clients didn't support AEAD ciphers.
Now I am testing clean shadowsocks-libev 3.0.5 (not streisand instance).
The point is that libev version supports udp relay and Shadowrocket has
began to support udp relay.
So it is early to say something convinient.
As I know, the main advantage of ss-libev is that it can be used on low end
boxes.
I will continue to test the all shadowsocks versions and we will see which
one is more stable and could be used by end-users.

If you need any help or to test something just contact me...

**Comment by cpu** [comment]
@hybtoy Sorry, I meant specifically using `go-shadowsocks2` as a client as opposed to using the Python client. Is that an OK default client to recommend from your perspective?

**Comment by hybtoy** [comment]
@cpu with respect to @riobard and his go-shadowsocks2, I think that
Shadowsocks Python client has to be used as a client for now. After a week
of testing, I didn't have any issues with AEAD cipher.

Just try the Python version and tell me your opinion :)

Thanks.

**Comment by cpu** [comment]
> I think that Shadowsocks Python client has to be used as a client for now.

How come? I'm hesitant to keep it as the defacto client for the mirror because the instructions use the `pip` installation method and the pip package is abandoned. To continue recommending it we have to provide instructions for end users to install it from source. In contrast, using `go-shadowsocks2` as the recommended client is easy because there are binary releases. I have tested its AEAD compatibility with shadowsocks-libev as well.

**Comment by hybtoy** [comment]
@cpu I didn't use go-shadowsocks2 as I client and I didn't install
streisand from your repository .
What are the commands to use as I client and what are the steps to install
it?

**Comment by riobard** [comment]
@hybtoy @cpu In addition to being easier to deploy, the go port should also offer better performance and lower memory overhead. If there's anything missing, please let me know.

**Comment by cpu** [comment]
@hybtoy Download the [release for your platform](https://github.com/riobard/go-shadowsocks2/releases/tag/v0.0.8). Extract it (e.g. `gunzip shadowsocks2-linux-x64.gz`), and then run like:
```
 ./shadowsocks2-linux-x64 -c $SERVER_IP:$SERVER_PORT -password "$PASSWORD" -socks localhost:$LOCAL_PORT -verbose -cipher AEAD_CHACHA20_POLY1305
```

**Comment by hybtoy** [comment]
@riobard could you tell us please, udp relay supported by default or there
is special command for it like -u on libev version?

@cpu thanks, will try it later today or tomorrow morning.

**Comment by riobard** [comment]
@hybtoy UDP relay works similar to the libev port. So far I've only used UDP tunnels to reach Google DNS. You can check the README to see how it works. On the server side UDP relay is enabled by default (so no `-u` flag to explicitly turn it on).

**Comment by hybtoy** [comment]
@riobard Just set up go land and started the server. 
I am using last testflight build of shadowrocket (iOS).
What can be the reason of this error? 
https://lh3.googleusercontent.com/-kwGWprC4PI0/WPWUxdlZ2JI/AAAAAAAAAR0/egPP5cvVAL8/s0/screenshot%2525202017-04-18%252520001.png

**Comment by hybtoy** [comment]
Shadowrocket + SS python/libev (AEAD cipher) = working
Shadowrocket + SS Go (AEAD cipher) = not working

**Comment by hybtoy** [comment]
@cpu Tried libev port, it was unstable for me, I don't know why, need to investigate it. 
Python port is stable.
Trying go port now.

**Comment by riobard** [comment]
@hybtoy Looks like either wrong password or wrong cipher suite. What's the configuration you used on the client and the server?

**Comment by hybtoy** [comment]
@riobard Yes. The problem is in the cipher. If I am starting the server with chacha20-poly1305, in shadowrocket I need to choose chacha20-ietf-poly1305.
![photo_2017-04-18_11-19-54](https://cloud.githubusercontent.com/assets/12900872/25116900/fcb4b284-2428-11e7-8189-0f4bc2654ff9.jpg)

It seems that go-ss2 has dns bug.

**Comment by riobard** [comment]
Chacha20-poly1305 was an experimental cipher during the development phase of AEAD in Shadowsocks. The current SS specification lists only AEAD_CHACHA20_POLY1305 (as defined in RFC7539) as the required AEAD cipher. The old name `chacha20-ietf-poly1305` is now an alias to AEAD_CHACHA20_POLY1305 as we adopt the IANA naming scheme (https://www.iana.org/assignments/aead-parameters/aead-parameters.xhtml). You can refer to the SS specification here for details https://shadowsocks.org/en/spec/AEAD-Ciphers.html

**Comment by riobard** [comment]
Shadowrocket is not open sourced. I'm not sure how they deal with DNS. Shadowsocks spec does not define anything in particular about DNS either. I tried another client Surge (https://www.nssurge.com) whose latest beta versions support AEAD ciphers and it works fine. I tend to think it's a Shadowrocket issue unless there's further evidence.

**Comment by hybtoy** [comment]
@riobard Please take a look to https://github.com/shadowsocks/go-shadowsocks2/issues/37
The issue is related to Shadowrocket problem while using it with go-ss2 server. 
Thanks.

**Comment by cpu** [comment]
@hybtoy This is interesting, but not relevant to my PR. I'm only interested in test results against the shadowsocks-libev server & configuration from my PR. That is, I'm **not** interested in testing results against a server with cipher "chacha20-poly1305,", or go-shadowsocks2 as the server, or shadowsocks python as the server :-)

If you have bugs related to using Shadowrocket with a go-shadowsocks2 server please discuss them with @riobard on the go-shadowsocks2 repo to keep this issue's comment history clear. Thanks!

**Comment by hybtoy** [comment]
@cpu Sorry for inconvenience caused.

**Comment by cpu** [comment]
Thanks for understanding!
