### ISSUE TITLE
Install fails on importing GPG keys

### ISSUE THREAD

**Issue by natelandau** [jlund/streisand#594]
I just created a Linode account and am running the Streisand install for the first time.  The instal script has failed repeatedly on the steps where it attempts to download GPG keys for the following:

- OpenVPN
- PuTTY
- stunnel
- Tor Browser

fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"attempts": 10, "changed": true, "cmd": ["gpg", "--keyserver", "x-hkp://pool.sks-keyservers.net", "--recv-keys", "XXXXXXXXXXX"], "delta": "0:00:00.119685", "end": "2017-04-10 03:39:12.766355", "failed": true, "rc": 2, "start": "2017-04-10 03:39:12.646670", "stderr": "gpg: requesting key XXXXXXXXXXX from hkp server pool.sks-keyservers.net\ngpg: no valid OpenPGP data found.\ngpg: Total number processed: 0\ngpg: keyserver communications error: keyserver helper general error\ngpg: keyserver communications error: unknown pubkey algorithm\ngpg: keyserver receive failed: unknown pubkey algorithm", "stdout": "gpgkeys: key XXXXXXXXXXX can't be retrieved", "stdout_lines": ["gpgkeys: key XXXXXXXXXXX can't be retrieved"], "warnings": []}

What is the fix for this issue?

**Comment by cpu** [comment]
Hi @natelandau,

Can you try running `gpg -vv --keyserver hkp://pool.sks-keyservers.net --recv-keys 0xC29D97ED198D22A3` from a SSH connection to your Linode server and share the output?

At first glance it looks like network connectivity issues to the keyserver pool, or maybe a temporary outage?

**Comment by natelandau** [comment]
that worked just fine.  I'm going to blow away the Linode server and start over to see if it was temporary.

**Comment by cpu** [comment]
Sounds good - thanks for testing!

**Comment by natelandau** [comment]
closing this issue.  worked perfectly this time through.  ghost in the machine I suppose.
