### ISSUE TITLE
Local install option

### ISSUE THREAD

**Issue by binkleyz** [jlund/streisand#595]
Know that there is an effort to create a local (non-ansbile, presumably) install option... Is there any sort of ETA on its completion?

Trying to get Streisand installed via a OSX box has proven very frustrating, primarily with broken distribution packages for pip and pycurl.

Trying to avoid using one ec2 instance to just launch another one. :)

**Comment by alimakki** [comment]
@binkleyz no ETA on a local install yet, but you may have luck with [a docker based install](https://github.com/jlund/streisand/pull/442)

**Comment by alimakki** [comment]
@binkleyz I stumbled upon [this](https://gist.github.com/jgamblin/3100b682510119722c56f5667fa2e18b#file-streisand-sh) on the internet, perhaps this could be useful to you:

```
#!/bin/bash
# Installs the Streisand server for you https://github.com/jlund/streisand

sudo apt-get update && sudo apt-get install -y git python-paramiko python-pip python-pycurl python-dev build-essential
sudo pip install ansible markupsafe dopy==0.3.5
git clone https://github.com/jlund/streisand.git && cd streisand/playbooks
sed -i 's/streisand-host/127.0.0.1/g' streisand.yml 
sudo ansible-playbook -i "localhost," -c local streisand.yml 
sed -i "s/localhost/$(curl -s ipecho.net/plain)/g" ../generated-docs/streisand.html
```
