### ISSUE TITLE
Can't connect with Android 7.1.2

### ISSUE THREAD

**Issue by spartanhooah** [jlund/streisand#596]
I recently created my streisand server, and followed the directions to connect with L2TP/IPsec. After I put in the username and password and tap connect, the phone looks like it's trying for about 30 seconds, then says "unsuccessful" This is a Pixel running stock Android 7.1.2. What could be going wrong, and how can I fix it?

**Comment by nickolasclarke** [comment]
@spartanhooah are any of the other connection methods working? I would also try openvpn, and shadowsocks. Depending on where your are based, l2tp/ipsec could be blocked.

**Comment by spartanhooah** [comment]
I was able to connect with shadowsocks, but I could not even get to Google; Firefox told me the server couldn't be found, and Chrome thought I was offline. Interestingly, I did notice that I could not connect to my server using my phone's browser, neither Chrome nor Firefox. I just got a "site can't be reached" message instead.

Using OpenVPN works well, and I get a download speed of about 7.5 Mbps, which is probably good enough for most use-cases. Thanks for suggesting other options!

**Comment by nickolasclarke** [comment]
@spartanhooah shadowsocks will always show it's "connected" even when it cant get data through, due to the nature of the protocol I think. Drives me a bit nuts.

**Comment by mitchellresnick** [comment]
I am also having this issue. I'm running 7.1.2 on a Nexus 6P and following the provided instruction results in an "unsuccessful" error. The network isn't blocking the connection too as I've tested it on my home network and AT&T's cellular network.

**Comment by cpu** [comment]
@mitchellresnick There's a PR open (https://github.com/jlund/streisand/pull/611) to replace the `shadowsocks-libev` server with an updated version & a modern encryption configuration. I would be curious to know if this PR helps with your connectivity problems. Are you up to cloning that branch and provisioning a new Streisand server to test with?

**Comment by mitchellresnick** [comment]
@cpu Sure thing! I will do it later today and let you know what the results are.

**Comment by hwdsl2** [comment]
Android 7.1.2 requires aes256/sha512. See [1] [2] for how to fix this.

[1] https://github.com/hwdsl2/setup-ipsec-vpn/commit/f58afbc84ba421216ca2615d3e3654902e9a1852
[2] https://github.com/jlund/streisand/blob/master/playbooks/roles/l2tp-ipsec/templates/ipsec.conf.j2#L26-L27

**Comment by cpu** [comment]
There's no report back on the latest shadowsocks-libev code and it sounds like a potential workaround for the Android 7.1.2 issue has been proposed. I'm going to close this issue for now. Thanks!
