### ISSUE TITLE
[GCE] ssh problems

### ISSUE THREAD

**Issue by zoof** [jlund/streisand#599]
`ssh` is broken in a number of ways.
1. "Open in browser window" does not work: key exchange appears to work but it gets stuck on `Establishing connection to SSH server`
2. "Open in browser window on custom port" (443) does not work: same as 1.
2. Using an ssh client does not work, either using `ubuntu@<ip-address>` or `<google-username>@<ip-address>`: `Permission denied (publickey).`
4. ssh to `forward@<ip-address>` does work
    - ssh tunnel using `sshuttle` works using command from Debian repo. Google search of <ip-address> shows correct ip.
    - ssh tunnel using `ssh -D` connects but firefox proxy does not: `The proxy server is refusing connections`

I am able to ssh via `gcloud` command.
3 and 4 were attempted using a Debian Jessie box. 1-3 appear to be related but 4 may be completely unrelated. 

I am using an f1-micro instance in us-east1-c.

**Comment by CorbanR** [comment]
Regarding 1:
I can confirm that using the GCE interface to SSH does not work. I would guess this has to do with our use of `The custom metadata "sshKeys" blocks`. But I need to confirm that. 

Regarding 2:
Same answer as 1. Mostly likely due to `The custom metadata "sshKeys" blocks`.

Regarding 3.
I just spun up a new GCE server and am not having any issues with `ssh ubuntu@<IP>` I also downloaded the `forward` user key, and don't have any issues with `ssh forward@<IP>`

**Comment by zoof** [comment]
So having read the GCE documentation more carefully, I think for 3, there was a "user configuration error"...

**Comment by zoof** [comment]
For 3, I have still been unable to `ssh` into the instance by following GCE documentation. I have been able to `ssh` into the instance by manually copying and pasting a public key into `.ssh/authorized_keys`.  This same key was pasted into `Metadata/SSH Keys` but did not work.

**Comment by cpu** [comment]
Is this still an issue that needs to remain open? Was the user error the root cause?

**Comment by zoof** [comment]
It is still not working for me.  I generate a key pair following https://cloud.google.com/compute/docs/instances/connecting-to-instance#generatesshkeypair, copy the public key to metadata/ssh keys and then using the private key, attempt to ssh into the instance.  The ssh attempt fails with a `Permission denied (publickey)` error.

**Comment by zoof** [comment]
Ok, that was dumb.  Figured it out and now working.
