### ISSUE TITLE
Allow user-supplied certs

### ISSUE THREAD

**Issue by DanielHeath** [jlund/streisand#60]
I've replaced (most of) the certs on my streisand box with free startssl ones.
Unfortunately, I don't remember much about how I did it :-1: 

Would it be a desirable feature to support this out of the box?

**Comment by cpu** [comment]
Another option in place of allowing user-supplied certificates is to allow setting a domain name for the Streisand instance & having a role that provisioned a Let's Encrypt/ACME client to issue certificates as required during provisioning.

**Comment by cpu** [comment]
Closing in favour of #639
