### ISSUE TITLE
Workaround for Linode Wireguard Support Pre Ansible 2.4

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#609]
https://github.com/jlund/streisand/issues/500 identified an issue with Wireguard provisioning on Linode servers caused by the default Ansible profile using the wrong kernel option. Installation requires the "GRUB 2" kernel option.

A fix to specify GRUB2 by default was [provided by @rmcintosh](https://github.com/jlund/streisand/pull/574) but is tied to [an Ansible PR](https://github.com/ansible/ansible/pull/23100) which has only landed in devel, [and will not be available in a release until Ansible 2.4](https://github.com/jlund/streisand/issues/500#issuecomment-294304253). Ansible is on a ~4 month release schedule and so we need to evaluate interim solutions.

Brainstorming with @zx2c4 I think there are three to consider:

1. Add some kind of prompt/warning to the Wireguard role conditional to the Linode provider being used.
2. Monkey patch `api.avail_kernels()` from the Linode plugin to specify the required kernel id option
3. Update the Linode genesis role to create but not start the Linode server, issue a CURL based API call to set the kernel ID, and then start & wait on the Linode server.

**Number 1** is "easiest" but solves no real problems and punts to the user.

**Number 2** seems like it will introduce the least amount of short term role churn but needs to be tested. @zx2c4 suggests this monkey patch using the `|` yaml syntax:
```
monkey: |
	from linode import api as linode_api
	linode_api.avail_kernels = lambda: return [ { 'LABEL': 'Latest 64', 'KERNELID': 210 } ]
```

**Number 3** seems doable using the [Linode config.update API](https://www.linode.com/api/linode/linode.config.update), but the genesis role [currently creates & starts the server](https://github.com/jlund/streisand/blob/3894cbda36acd9b42a6605c99d01dd5f4d7495a2/playbooks/roles/genesis-linode/tasks/main.yml#L12:L21) as one action. This will need to be split into two using `state=present` and `wait=no` instead of `state=started` and `wait=yes`. After the API call is made the state can be expected to be started & we can wait on startup.

@zx2c4 points out that a similar curl task is already present in the role:
```
- name: Get the latest Ubuntu 16.04 image ID from the Linode API
  shell: curl -s 'https://api.linode.com/?api_key={{ linode_api_key }}&api_action=avail.distributions' | {{ ansible_python_interpreter }} -c 'import json; import sys; j = json.loads(sys.stdin.read()); print [img for img in j["DATA"] if img["LABEL"]=="Ubuntu 16.04 LTS"][0]["DISTRIBUTIONID"]'
  args:
    warn: no
  register: linode_ubuntu_distribution_id
```

My own take is that option number 2 is the best to pursue until there's additional reasons to reconsider. I'm going to assign this issue to myself but I won't be able to experiment until ~tomorrow at the earliest. If someone else is keen to start, feel free!

**Comment by zx2c4** [comment]
> @zx2c4 suggests this curl task:

What I meant is that this curl task already indicates the Linode playbook is making calls directly to the Linode API, so doing more calls doesn't break an existing barrier. That's all.

**Comment by cpu** [comment]
@zx2c4 - thanks, updated to clarify. My mistake!

**Comment by zx2c4** [comment]
Looks like one route to monkey patching would be to set PYTHONPATH to a directory in Streisand's folder, and then put in there `usercustomize.py` containing the patcher. This seems to be working in my quick tests.

**Comment by cpu** [comment]
I've picked this up to work on this afternoon. I repro'd the original failure and now I'm evaluating monkey patch options now. Will report back with a PR or more information.
