### ISSUE TITLE
Add Privoxy support to weaken mass data collection

### ISSUE THREAD

**Issue by DanielHeath** [jlund/streisand#62]
If we're trying to prevent/avoid mass data collection as well as mass censorship, www.privoxy.org or similar might be a worthwhile addition to the streisand bundle.

Any interest? I might see if I can get it running next weekend.

**Comment by dlmetcalf** [comment]
This would be relevant to mobile users. Chrome mobile is very substantially more hardened than Firefox, but doesn't support plugins/addons. Unless a device is rooted (which breaks security too), then AdAway, etc can't be used.

**Comment by jboolean** [comment]
This is one [Algo](https://github.com/trailofbits/algo)'s great differentiating factors. It's otherwise unreasonable to full-system ad blocking on mobile.

**Comment by cpu** [comment]
I would support this if it were optional and there was a reasonable PR to review.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/22
