### ISSUE TITLE
Feature request: SoftEtherVPN.

### ISSUE THREAD

**Issue by chipitsine** [jlund/streisand#624]
hello,

as I see, there's strong demand in bypassing chinese firewall.
SoftEtherVPN is known to bypass it.

probably I missed it, did you consider adding SoftEtherVPN to streisand ?

**Comment by strixaluco** [comment]
@chipitsine, SoftEther VPN has been already requested in #140

**Comment by cpu** [comment]
@strixaluco Thanks for noticing that.

Closing as a duplicate of #140
