### ISSUE TITLE
client.crt download issue(openvpn)

### ISSUE THREAD

**Issue by kletools** [jlund/streisand#625]
"This is not a certificate authority certificate, so it can’t be imported into the certificate authority list".I get the above alert when i tried to download client.crt.Could not download from client1-client5 in linux(ubuntu).

**Comment by alimakki** [comment]
@kletools What happens when you right click -> Save link as.. ?

**Comment by kletools** [comment]
That fixed it for me.Thanks

**Comment by alimakki** [comment]
@kletools My pleasure.
