### ISSUE TITLE
Error: No module name 

### ISSUE THREAD

**Issue by gmile** [jlund/streisand#629]
Hi,

I'm trying to setup `streisand` on GCE.

Very early on I get an error – **ImportError: No module named `utils.display`**:

```
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named utils.display
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/w8/wtxq2sds7p710nb0cj69wbd00000gn/T/ansible_yA06WC/ansible_module_gce_net.py\", line 557, in <module>\n    from ansible.module_utils.gce import *\n  File \"/var/folders/w8/wtxq2sds7p710nb0cj69wbd00000gn/T/ansible_yA06WC/ansible_modlib.zip/ansible/module_utils/gce.py\", line 30, in <module>\n  File \"/var/folders/w8/wtxq2sds7p710nb0cj69wbd00000gn/T/ansible_yA06WC/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 64, in <module>\nImportError: No module named utils.display\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/Users/gmile/projects/streisand/playbooks/google.retry
```

Full output for `./streisand` below.
<details>

    gmile@Eugenes-MBP ~/p/streisand (master)> ./streisand

      S T R E I S A N D

    Which provider are you using?
      1. Amazon
      2. Azure
      3. DigitalOcean
      4. Google
      5. Linode
      6. Rackspace
    : 4

     [WARNING]: Found both group and host with same name: localhost

    What zone should the server be located in?
      1. Central US       (Iowa A)
      2. Central US       (Iowa B)
      3. Central US       (Iowa C)
      4. Central US       (Iowa F)
      5. Eastern US       (South Carolina B)
      6. Eastern US       (South Carolina C)
      7. Eastern US       (South Carolina D)
      8. Western US       (Oregon A)
      9. Western US       (Oregon B)
      10. Western Europe  (Belgium B)
      11. Western Europe  (Belgium C)
      12. Western Europe  (Belgium D)
      13. East Asia       (Taiwan A)
      14. East Asia       (Taiwan B)
      15. East Asia       (Taiwan C)
      16. Northeast Asia  (Tokyo A)
      17. Northeast Asia  (Tokyo B)
      18. Northeast Asia  (Tokyo C)
    Please choose the number of your zone. Press enter for default (#3) zone.
     [3]: 10

    What should the server be named? Press enter for default (streisand).
     [streisand]: stayfocused

    The full path of your unique service account credentials file. Details on generating this can be found at
    https://docs.ansible.com/ansible/guide_gce.html#credentials
     and
    https://support.google.com/cloud/answer/6158849?hl=en&ref_topic=6262490#serviceaccounts
     [{{ lookup('env','HOME') }}/streisand.json]:

    Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
    :

    PLAY [Provision the GCE Server] *****************************************************************************************************************************************************************************

    TASK [Gathering Facts] **************************************************************************************************************************************************************************************
    ok: [localhost]

    TASK [Set the Google Compute Engine Zone fact] **************************************************************************************************************************************************************
    ok: [localhost]

    TASK [Register JSON file contents] **************************************************************************************************************************************************************************
    changed: [localhost]

    TASK [Set JSON file contents fact] **************************************************************************************************************************************************************************
    ok: [localhost]

    TASK [Set the Google Compute Engine Service Account Email] **************************************************************************************************************************************************
    ok: [localhost]

    TASK [Set the Google Compute Engine Project ID] *************************************************************************************************************************************************************
    ok: [localhost]

    TASK [gce-network : Create network] *************************************************************************************************************************************************************************
    An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named utils.display
    fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/w8/wtxq2sds7p710nb0cj69wbd00000gn/T/ansible_yA06WC/ansible_module_gce_net.py\", line 557, in <module>\n    from ansible.module_utils.gce import *\n  File \"/var/folders/w8/wtxq2sds7p710nb0cj69wbd00000gn/T/ansible_yA06WC/ansible_modlib.zip/ansible/module_utils/gce.py\", line 30, in <module>\n  File \"/var/folders/w8/wtxq2sds7p710nb0cj69wbd00000gn/T/ansible_yA06WC/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 64, in <module>\nImportError: No module named utils.display\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
            to retry, use: --limit @/Users/gmile/projects/streisand/playbooks/google.retry

    PLAY RECAP **************************************************************************************************************************************************************************************************
    localhost                  : ok=6    changed=1    unreachable=0    failed=1

</details>

**Comment by x8x** [comment]
Had that error when trying with Ansible 2.4, reverted to 2.2.2 problem disappeared.

**Comment by x8x** [comment]
On macOS, now `brew update && brew upgrade` upgrades Ansible to version `2.3.0.0` and above error comes out:
```
TASK [gce-network : Create network] ******************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named utils.display
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/_c/_np_h6v11ssdjcm1h6g2n7qh0000gn/T/ansible_NiNjfq/ansible_module_gce_net.py\", line 557, in <module>\n    from ansible.module_utils.gce import *\n  File \"/var/folders/_c/_np_h6v11ssdjcm1h6g2n7qh0000gn/T/ansible_NiNjfq/ansible_modlib.zip/ansible/module_utils/gce.py\", line 30, in <module>\n  File \"/var/folders/_c/_np_h6v11ssdjcm1h6g2n7qh0000gn/T/ansible_NiNjfq/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 64, in <module>\nImportError: No module named utils.display\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
```

**Comment by gmile** [comment]
Yeah, that is exactly my issue.

**Comment by x8x** [comment]
I was able to revert to Ansible `2.2.2.0` with this:
```
brew uninstall ansible
brew install https://raw.githubusercontent.com/Homebrew/homebrew-core/339af3801cd3fc12174d728978804739d0af70e8/Formula/ansible.rb
```
You may give it a try :-)

**Comment by CorbanR** [comment]
@gmile @x8x  I've been using Ansible `2.3.0.0` with no problems.  Are you using the latest Streisand branch? I had a similar error at one time and it was due to Ansible using the wrong python interpreter.

**Comment by gmile** [comment]
@CorbanR I'm using master branch, yeah. How did you knew ansible was picking up the wrong python?

**Comment by CorbanR** [comment]
When I got a similar error it was due to `ansible_python_interpreter=python` missing from the inventories file. I have an updated python version which I installed with homebrew.  If you have a custom python install you could try specifying the custom path `[localhost]
localhost ansible_connection=local ansible_python_interpreter=/usr/local/bin/python` although with the updated Streisand script, I wouldn't think that would be necessary.

**Comment by gmile** [comment]
@CorbanR yes, I do use homebrew-installed python. I've changed ansible_python_interpreter to `/usr/local/bin/python` (my local installation), but no luck.

Also, just for the record I do have the following (per Readme):

```
$ cat ~/Library/Python/2.7/lib/python/site-packages/homebrew.pth
/usr/local/lib/python2.7/site-packages
$
```

**Comment by gmile** [comment]
I installed ansible via `pip install ansible`, and everything works now.

**Comment by nodje** [comment]
I just did a `brew upgrade` this morning and I've got the problem now.
And I did it with Ansible homebrew module, so I've got no idea what was actually updated :| this module needs a report option somehow.

You closed the issue but it seems like it's actually not solved, or either it should be opened in the Homebrew ansible recipe if it is really the source of the issue.
Reverting to another Ansible version is quite easy with Homebrew, but it's also not possible anymore with the Master branch of Streisand which requires Ansible `2.3.0.0`.

Was Python recently updated on Homebrew? Could it be the issue?
On my install typing `ansible --version` gives me
```ansible 2.3.0.0
  config file = /Users/usr/project/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Dec 17 2016, 23:03:43) [GCC 4.2.1 Compatible Apple LLVM 8.0.0 (clang-800.0.42.1)]
```

**Comment by nodje** [comment]
Odd, I double checked, I've been using ansible 2.3.0.0 as my default since Apr 27, and didn't have the problem until today after a `brew upgrade`.
But running the playbook with Ansible 2.2.2.0 actually works...
`/usr/local/Cellar/ansible/2.2.2.0/bin/ansible-playbook google.yml`

So it feels like Ansible version is causing the issue, but it can't be. It has to be something else that has been updated that Ansible 2.3.0.0 depends on, but not 2.2.2.0.

**Comment by dizeee** [comment]
I have this issue on both macOS and Ubuntu 16.04 with Ansible 2.3.0.0. Tried installing by apt and pip.
