### ISSUE TITLE
`dnsmasq` upgrade broken

### ISSUE THREAD

**Issue by zoof** [jlund/streisand#631]
Running `sudo apt upgrade` broke dnsmasq on a GCE instance.

    $ systemctl status dnsmasq.service
    ● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
       Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
      Drop-In: /run/systemd/generator/dnsmasq.service.d
               └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
       Active: failed (Result: exit-code) since Fri 2017-04-21 02:32:28 UTC; 14s ago
      Process: 4993 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
      Process: 4980 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
     Main PID: 1745 (code=exited, status=0/SUCCESS)
    Apr 21 02:32:28 streisand systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
    Apr 21 02:32:28 streisand dnsmasq[4980]: dnsmasq: syntax check OK.
    Apr 21 02:32:28 streisand dnsmasq[4993]: dnsmasq: failed to create listening socket for port 53: Address already in use
    Apr 21 02:32:28 streisand systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
    Apr 21 02:32:28 streisand systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
    Apr 21 02:32:28 streisand systemd[1]: dnsmasq.service: Unit entered failed state.
    Apr 21 02:32:28 streisand systemd[1]: dnsmasq.service: Failed with result 'exit-code'.

    $ journalctl -xe
    -- 
    -- Unit dnsmasq.service has begun starting up.
    Apr 21 02:32:28 streisand dnsmasq[4980]: dnsmasq: syntax check OK.
    Apr 21 02:32:28 streisand dnsmasq[4993]: dnsmasq: failed to create listening socket for port 53: Address already in use
    Apr 21 02:32:28 streisand dnsmasq[4993]: failed to create listening socket for port 53: Address already in use
    Apr 21 02:32:28 streisand dnsmasq[4993]: FAILED to start up
    Apr 21 02:32:28 streisand systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
    Apr 21 02:32:28 streisand sudo[4977]: pam_unix(sudo:session): session closed for user root
    Apr 21 02:32:28 streisand systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
    -- Subject: Unit dnsmasq.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit dnsmasq.service has failed.
    -- 
    -- The result is failed.
    Apr 21 02:32:28 streisand systemd[1]: Dependency failed for Host and Network Name Lookups.
    -- Subject: Unit nss-lookup.target has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit nss-lookup.target has failed.
    -- 
    -- The result is dependency.
    Apr 21 02:32:28 streisand systemd[1]: nss-lookup.target: Job nss-lookup.target/start failed with result 'dependency'.
    Apr 21 02:32:28 streisand systemd[1]: dnsmasq.service: Unit entered failed state.
    Apr 21 02:32:28 streisand systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
    Apr 21 02:32:35 streisand stunnel[2076]: LOG3[30064]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:32:35 streisand sslh[1483]: connection from 10.240.16.2:39650 to 10.240.16.2:https forwarded from localhost:49442 to
    Apr 21 02:33:05 streisand stunnel[2076]: LOG3[30065]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:33:05 streisand sslh[1483]: connection from 10.240.16.2:39662 to 10.240.16.2:https forwarded from localhost:49454 to
    Apr 21 02:33:35 streisand stunnel[2076]: LOG3[30066]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:33:35 streisand sslh[1483]: connection from 10.240.16.2:39680 to 10.240.16.2:https forwarded from localhost:49472 to
    Apr 21 02:34:05 streisand stunnel[2076]: LOG3[30067]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:34:05 streisand sslh[1483]: connection from 10.240.16.2:39692 to 10.240.16.2:https forwarded from localhost:49484 to
    Apr 21 02:34:35 streisand stunnel[2076]: LOG3[30068]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:34:35 streisand sslh[1483]: connection from 10.240.16.2:39710 to 10.240.16.2:https forwarded from localhost:49502 to
    Apr 21 02:35:05 streisand stunnel[2076]: LOG3[30069]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:36:05 streisand sslh[1483]: connection from 10.240.16.2:39752 to 10.240.16.2:https forwarded from localhost:49544 to
    Apr 21 02:36:35 streisand stunnel[2076]: LOG3[30072]: SSL_accept: Peer suddenly disconnected
    Apr 21 02:36:35 streisand sslh[1483]: connection from 10.240.16.2:39770 to 10.240.16.2:https forwarded from localhost:49562 to

**Comment by CorbanR** [comment]
@zoof How recent is the server you're running?

**Comment by zoof** [comment]
From April 10.  Do I need to delete it and start a new instance?

**Comment by zoof** [comment]
A subsequent upgrade seems to have worked.

    $ systemctl status dnsmasq.service 
    ● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
       Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
      Drop-In: /run/systemd/generator/dnsmasq.service.d
               └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
       Active: active (running) since Wed 2017-05-03 19:24:48 UTC; 5 days ago
     Main PID: 1628 (dnsmasq)
        Tasks: 1
       Memory: 1.2M
          CPU: 2.649s
       CGroup: /system.slice/dnsmasq.service
               └─1628 /usr/sbin/dnsmasq -x /var/run/dnsmasq/dnsmasq.pid -u dnsmasq -r /var/run/dnsmasq/resolv.conf -7 /etc

**Comment by cpu** [comment]
@zoof Since this seems to have been transient and hasn't occurred for anyone else (that I'm aware of!) I'm going to close this issue. Thanks for reporting - we can certainly reopen if it happens again.
