### ISSUE TITLE
issue SSL cert via Lets Encrypt

### ISSUE THREAD

**Issue by chipitsine** [jlund/streisand#639]
we can issue SSL cert using lets encrypt (actually, we need to renew it every 2-3 months later)

**Comment by cpu** [comment]
Let's Encrypt does not presently issue for IP addresses, this feature request would require support for configuring a domain name.

**Comment by cpu** [comment]
Related: https://github.com/jlund/streisand/issues/60

**Comment by wzyboy** [comment]
I have submitted a PR which implements this function: https://github.com/jlund/streisand/pull/911
