### ISSUE TITLE
Openvpn latest release/Custom release

### ISSUE THREAD

**Issue by aminbolehvpn** [jlund/streisand#64]
I see that debian 7 default is still using the older version (2.2.1) whereas openvpn is now at version 2.3.4
Any possibility of installing the latest version instead of the default?
Thank you

**Comment by shsu** [comment]
+1

**Comment by alimakki** [comment]
I have added this as part of my effort to create UDP profiles for OpenVPN, see PR #303

**Comment by jlund** [comment]
Thanks for making this happen, @alimakki. Streisand servers now run the very latest release of OpenVPN.

**Comment by alimakki** [comment]
![horray im helping](https://cloud.githubusercontent.com/assets/920624/15735644/52693274-28ab-11e6-9e79-07329bd11531.jpg)
