### ISSUE TITLE
setup failure in azure

### ISSUE THREAD

**Issue by yeluolei** [jlund/streisand#645]
```
TASK [genesis-azure : Create the Azure instance] *****************************************************************************************************************************************************
fatal: [localhost -> localhost]: FAILED! => {"changed": false, "failed": true, "msg": "Error creating or updating virtual machine xxx - 'DiskCreateOptionTypes' object is not iterable"}
	to retry, use: --limit @/Users/xxx/Code/streisand/playbooks/azure.retry
```

**Comment by cpu** [comment]
@blotzu - Any thoughts on this?

**Comment by blotzu** [comment]
@yeluolei what region did you select ?
Also did you already have a VM or a resource group with the streisand_* name ?

**Comment by yeluolei** [comment]
I selected azure HK，17。 the resource group was created but the vm created failed with this message.

**Comment by blotzu** [comment]
@yeluolei It's most probably related to the Region. I will take a look at this over the weekend. You can use Korea in the meantime.

**Comment by yeluolei** [comment]
thanks~

**Comment by yeluolei** [comment]
any progress for this issue?

**Comment by blotzu** [comment]
@yeluolei I cannot create instances in HK using my subscription so I cannot test it.
Did you get the same error for Korea or Japan ?

**Comment by rayhu** [comment]
@yeluolei 

I am able to create a Azure HK instance without issue. See the attached log file. 

Please check your azure subscription. Do you already have HK resource group with streisand prefix?
Pickup a different name, it will create differently. In my log, the resource group name is streisand-wanchai.

Azure HK, Singapore and Japan East (16, 17, 20) all work fine.

[azure_hk_streisand_log.pdf](https://github.com/jlund/streisand/files/1172484/azure_hk_streisand_log.pdf)

**Comment by yeluolei** [comment]
ok, I will try again with the latest realease

**Comment by yeluolei** [comment]
seams this is the problem of my local environment, I don't know why. but after I change to use another machine for deploy, there is no problem.

thanks, guys.
