### ISSUE TITLE
Any way to force AnyConnect to connect solely over the domain name?

### ISSUE THREAD

**Issue by trexdinosaur** [jlund/streisand#646]
hi! I was behind a firewall that filters out IP's and does DPI on HTTPS packets to see what domain they are going to. If they are going to a trustable domain. packets are set forward. However, if packets are just being sent to an IP, they get blocked. I have gotten my hands on a domain that is allowed through the firewall. However, when AnyConnect sends packets on the linux client (both the cisco version and open source version) they are routing with IP, causing the DPI to drop the packets. What's interesting in the iOS client is properly putting in a domain name into the proper fields on the packet to route the HTTPS properly. Is there any way I can get around this issue?

**Comment by cpu** [comment]
I think this is a question for the AnyConnect project. I'm not sure of the answer and I don't think it's within the scope of the Streisand project. I'm going to close this issue for now, good luck!
