### ISSUE TITLE
failure 1 running systemctl show for 'shadowsocks-libev'

### ISSUE THREAD

**Issue by tiliarou** [jlund/streisand#651]
Context:
Update of existing Streisand server running on Aruba Cloud VPS, Ubuntu server 16.04 LTS. 
Git repo updated yesterday and today via pull (Retaining ansible.cfg and inventory), same error below. 

fatal: [89.40.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "failure 1 running systemctl show for 'shadowsocks-libev': Failed to get properties: No such interface ''\n"}

**Comment by cpu** [comment]
Hi @tiliarou, thanks for opening a new issue for this.

Can you share more log context? Are you running `ansible-playbook` directly (e.g. not using the `streisand` shell wrapper) ? If so could you add a `-v` and share some of the log context before & after this error? 

Are you able to run `systemctl show sshd` without error from a root shell on the same VPS?

**Comment by tiliarou** [comment]
I'm using ansible-playbook playbooks/streisand.yml
systemctl show sshd gives Failed to get properties: No such interface ''

**Comment by cpu** [comment]
> Edit: systemctl status gives "failed to read server status"... am I good to start from scratch ? (reset the instance)

Since your problem seems to be generic to systemd (e.g. not the shadowsocks service in particular) I suspect you have a larger system wide problem.

As a next step I would recommend trying master against a new server with the same VPS provider and seeing if it fails. If it does we know that the problem isn't an upgrade, but the combination of Streisand & this provider. If it works we know the problem stems from your upgrade.

Thanks!

**Comment by tiliarou** [comment]
Yes, I believe it's a server problem unrelated to shadowsock, but I don't understand how I got into it since I don't do anything with this server except trying to update streisand... will make a backup and start from scratch to see if it push through with latest git.

**Comment by tiliarou** [comment]
Not sure what happened but I reinitialized my instance and could install the newest streisand.
Issue can be closed.

**Comment by cpu** [comment]
Great - thanks for reporting back :+1:
