### ISSUE TITLE
No access to port 587

### ISSUE THREAD

**Issue by zoof** [jlund/streisand#654]
My email clients (thunderbird and k-9 mail) are unable to send email through VPN (either OpenVPN or OpenConnect).  All other traffic seems to work.  I am running a GCE instance.

**Comment by alimakki** [comment]
From the Google GCE [docs](https://cloud.google.com/compute/docs/networks-and-firewalls#blockedtraffic):

---
Compute Engine blocks or restricts traffic through all of the following ports/protocols between the Internet and virtual machines, and between two virtual machines when traffic is addressed to their external IP addresses through these ports (this also includes load-balanced addresses).

- Alloutgoing traffic to port 25 (SMTP) is blocked.
- Most outgoing traffic to port 465 or 587 (SMTP over SSL) is blocked, except for known Google IP addresses.
- Traffic that uses a protocol other than TCP, UDP, and ICMP is blocked, unless explicitly allowed through Protocol Forwarding.
---

**Comment by zoof** [comment]
Ah -- that's unfortunate...

**Comment by zoof** [comment]
Actually, would it be possible to set up an exception on CGE to **not** tunnel ports 465 and 587?

**Comment by alimakki** [comment]
@zoof I doubt that you would be able to do that, perhaps reaching out to their support could yield you some results?

**Comment by zoof** [comment]
Sadly it looks like Google will not allow it.  They suggest using a relay service to send email but I guess this is for sending email from the instance, not sending email through the instance.  I guess I can use a webmail interface.
