### ISSUE TITLE
Cert Issues

### ISSUE THREAD

**Issue by sky305** [jlund/streisand#659]
From a standard successfull streisand run on Azure..  Connecting with open vpn i get;

Sun Apr 30 02:38:39 2017 VERIFY ERROR: depth=1, error=certificate is not yet valid: C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=ca-certificate
Sun Apr 30 02:38:39 2017 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Sun Apr 30 02:38:39 2017 TLS_ERROR: BIO read tls_read_plaintext error
Sun Apr 30 02:38:39 2017 TLS Error: TLS object -> incoming plaintext read error
Sun Apr 30 02:38:39 2017 TLS Error: TLS handshake failed
Sun Apr 30 02:38:39 2017 Fatal TLS error (check_tls_errors_co), restarting
Sun Apr 30 02:38:39 2017 SIGUSR1[soft,tls-error] received, process restarting
Sun Apr 30 02:38:39 2017 Restart pause, 5 second(s)
^CSun Apr 30 02:38:43 2017 SIGINT[hard,init_instance] received, process exiting

All Certs are downloaded;
![image](https://cloud.githubusercontent.com/assets/19628736/25566280/caa8a2e4-2da3-11e7-9c80-026bb8b88076.png)
![image](https://cloud.githubusercontent.com/assets/19628736/25566284/e2a419c8-2da3-11e7-9ef8-99d8e5c6922b.png)
![image](https://cloud.githubusercontent.com/assets/19628736/25566289/000972d8-2da4-11e7-941e-1676910a3df6.png)
![image](https://cloud.githubusercontent.com/assets/19628736/25566294/11b5b942-2da4-11e7-99c6-133095661d3a.png)

Thanks for any assistance, i'm sure I'm just missing one thing!  Thanks!

**Comment by alimakki** [comment]
@sky305 It looks like you've got everything set up right, the only thing I can see missing under TLS authentication is the Server Certificate Check.

First of all, you need to obtain your server generated common name; If you grab one of the unified .ovpn files, you will see a line similar to this:

`verify-x509-name foo.bar name`

In this case, `foo.bar` is your common name.

Under the TLS authentication tab, choose `verify name exactly`, and enter your server common name. Save, and retry connecting.

Let me know if you succeed.

**Comment by sky305** [comment]
@alimakki Thanks!  But no go..
The .ovpn file has;
`verify-x509-name birdies.waterwork name`

my client config was changed to;
![image](https://cloud.githubusercontent.com/assets/19628736/25567476/aa01be5e-2dbc-11e7-982c-484931bfdc43.png)

**Comment by alimakki** [comment]
What version of OpenVPN are you using client side? 
`openvpn --version`

**Comment by alimakki** [comment]
Also, are you able to connect if you just use the CLI version?

`sudo openvpn --config unified-client-file.ovpn`

**Comment by sky305** [comment]
`OpenVPN 2.4.0 `

**Comment by sky305** [comment]
```
Sun Apr 30 06:01:19 2017 VERIFY ERROR: depth=1, error=certificate is not yet valid: C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=ca-certificate
Sun Apr 30 06:01:19 2017 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Sun Apr 30 06:01:19 2017 TLS_ERROR: BIO read tls_read_plaintext error
Sun Apr 30 06:01:19 2017 TLS Error: TLS object -> incoming plaintext read error
Sun Apr 30 06:01:19 2017 TLS Error: TLS handshake failed
Sun Apr 30 06:01:19 2017 Fatal TLS error (check_tls_errors_co), restarting
Sun Apr 30 06:01:19 2017 SIGUSR1[soft,tls-error] received, process restarting
Sun Apr 30 06:01:19 2017 Restart pause, 5 second(s)
Sun Apr 30 06:01:24 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]xxxx:636
Sun Apr 30 06:01:24 2017 Socket Buffers: R=[87380->87380] S=[16384->16384]
Sun Apr 30 06:01:24 2017 Attempting to establish TCP connection with [AF_INET]xxxx:636 [nonblock]
Sun Apr 30 06:01:25 2017 TCP connection established with [AF_INET]xxx:636
Sun Apr 30 06:01:25 2017 TCP_CLIENT link local: (not bound)
Sun Apr 30 06:01:25 2017 TCP_CLIENT link remote: [AF_INET]xxxx:636
Sun Apr 30 06:01:25 2017 TLS: Initial packet from [AF_INET]xxxxx, sid=9707eee0 28e72a23
Sun Apr 30 06:01:25 2017 VERIFY ERROR: depth=1, error=certificate is not yet valid: C=US, ST=California, L=Beverly Hills, O=ACME CORPORATION, OU=Anvil Department, CN=ca-certificate
Sun Apr 30 06:01:25 2017 OpenSSL: error:14090086:SSL routines:ssl3_get_server_certificate:certificate verify failed
Sun Apr 30 06:01:25 2017 TLS_ERROR: BIO read tls_read_plaintext error
Sun Apr 30 06:01:25 2017 TLS Error: TLS object -> incoming plaintext read error
Sun Apr 30 06:01:25 2017 TLS Error: TLS handshake failed
Sun Apr 30 06:01:25 2017 Fatal TLS error (check_tls_errors_co), restarting

```

**Comment by cpu** [comment]
> certificate is not yet valid

Is the clock on your client machine correct? The date/time?

**Comment by alimakki** [comment]
@cpu good catch

**Comment by sky305** [comment]
@cpu definately a good catch!  You got it!!  Thanks @cpu and @alimakki !

**Comment by alimakki** [comment]
Glad to help! Thanks @cpu 👍

**Comment by cpu** [comment]
One less mystery in the world :-) Thanks for the initial triage @alimakki. Glad to help.
