### ISSUE TITLE
Expose onc files for chromebook OpenVpn support

### ISSUE THREAD

**Issue by DukeyToo** [jlund/streisand#663]
Chromebooks support OpenVPN, but require a [onc file](https://github.com/syedaali/configs/blob/master/openvpn-sample.onc) to configure it.  Those files can then be imported at chrome://net-internals/#chromeos on the Chromebook, according to instructions at https://syedali.net/2014/02/17/using-chromebook-to-connect-to-an-openvpn-server/

**Comment by alimakki** [comment]
@DukeyToo, Do you know of any good Chromebook emulators?

**Comment by DukeyToo** [comment]
Nope, I have not heard of anything like that.

**Comment by tobiasboyd** [comment]
@alimakki you can run Cloudready[1] in a vm for testing.

1: https://www.neverware.com/freedownload

**Comment by alimakki** [comment]
@tobiasboyd Thanks for the link, I'll check it out.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/5
