### ISSUE TITLE
No access to Ubuntu i used for set up/upgrading to Ubuntu 17.04

### ISSUE THREAD

**Issue by kletools** [jlund/streisand#665]
I set up my Streisand VPN using Ubuntu 16.04 on a virtual machine and amazon AWS .I'm currently having issues with my virtual machine and can't even get into my ubuntu 16.04.I want to uninstall the VM and dual boot ubuntu 17.04 instead.How does this affect my Streisand?Configuration was done using Ubuntu 16.04 i cannot access.

**Comment by cpu** [comment]
Streisand does not support 17.04. I'm not sure I understand the question about "dual booting". Dual booting the server doesn't make sense to me. Can you elaborate? 

It would probably be better if you opened a new issue describing the issues you're having with the Streisand install on the 16.04 AWS VM.

**Comment by kletools** [comment]
I was able to get back into my VM. No need then installing 17.04.Thanks
