### ISSUE TITLE
Failure during Wireguard installation - "No package matching 'linux-headers-4.9.20-std-1' is available"

### ISSUE THREAD

**Issue by noiseb0y** [jlund/streisand#666]
I'm experiencing the following error when performing an install on a remote server:

```
TASK [wireguard : Install the WireGuard packages] ******************************
failed: [xx.xx.xx.xx] (item=[u'linux-headers-4.9.20-std-1', u'linux-headers-generic', u'wireguard-dkms', u'wireguard-tools']) => {"failed": true, "item": ["linux-headers-4.9.20-std-1", "linux-headers-generic", "wireguard-dkms", "wireguard-tools"], "msg": "No package matching 'linux-headers-4.9.20-std-1' is available"}
```

Distro/version info:

```
root@x:~# uname -r
4.9.20-std-1
root@x:~# lsb_release -a
No LSB modules are available.
Distributor ID:	Ubuntu
Description:	Ubuntu 16.04.2 LTS
Release:	16.04
Codename:	xenial
```

Are there any workarounds?

**Comment by cpu** [comment]
Hi @noiseb0y,

What VPS/server provider are you using? It looks like you're using a non-standard kernel and that it doesn't have headers available. As a workaround you could switch to a stock kernel. It isn't currently possible to disable the Wireguard role trivially but you may have luck editing the various roles that depend on it.

**Comment by noiseb0y** [comment]
@cpu I am attempting an install with the Scaleway Ubuntu Xenial image. I'll look into switching kernels instead of disabling the Wireguard role (I attempted to do that before raising this issue, and failed miserably).

Thanks!

**Comment by cpu** [comment]
>   I am attempting an install with Scaleway's (the provider) Ubuntu Xenial image

@noiseb0y Aha. I have no first hand experience with Scaleway but it seems like you're going to have issues with Streisand and Scaleway since the project builds kernel modules for Wireguard and Strongswan both. A quick google indicates [there is limited support for mainline kernels](https://www.scaleway.com/docs/how-your-kernel-works/) on Scaleway.

>  (I attempted to do that before raising this issue, and failed miserably).

This will hopefully be an easy to support thing in the future! Apologies.

**Comment by noiseb0y** [comment]
@cpu Ahh that's a shame! I will look into alternative providers. Thanks for your help!
