### ISSUE TITLE
Bug or feature: Streisand instances inadvertantly exposing password/shared secret info?

### ISSUE THREAD

**Issue by davcarrington** [jlund/streisand#672]
Do a https://www.google.com/#q=streisand+vpn+password query and you'll see results that include different streisand vpn servers (ex.: https://streisand.<xxxxxxx>.com/shadowsocks/

From there, one can visit https://<fqdn server name>/l2tp-ipsec/#ios (or others) and see password/secret info without an authentication prompt.

Is this a setup/configuration error by the user? If so, any ideas on how it was done? Or, do search engine crawls have a way of exposing this secure information?

Of course, it is entirely possible these are not an actual Streisand VPN servers, but I thought it safe to ask.

Thanks for all your help, Joshua. It's great using Streisand.

**Comment by jlund** [comment]
After a server is set up, the user to whom the server belongs (and who therefore has root) could modify the Nginx vhost configuration and restart Nginx to remove the auth layer if they so desire. This is **very much not recommended** and it is not part of the setup process at all. It would need to be a series of manual actions. I've seen a few examples of these instances in the past, and I think it's coming from a place where people are trying to be helpful and perhaps not fully considering the impact of their actions. Some of them even went so far as to set up a new domain and replace the generated SSL certificate for the server IP with a valid certificate for the dedicated domain! Pretty crazy.

Unless you have manually edited your Nginx vhost and made specific changes to the authentication section, your servers are fine. This would definitely be a bug not a feature :)
