### ISSUE TITLE
Create the EC2 security group failed.

### ISSUE THREAD

**Issue by bengstra** [jlund/streisand#676]
Using Ubuntu, got part way through set up and got a "Create the EC2 security group failed" error. ANy ideas?

**Comment by Ajwah** [comment]
I had similar issue. Deleting the security group and redoing the setup worked for me.

**Comment by sukima** [comment]
> Deleting the security group
How do you do this? Is EC2 broken? This makes no sense. What security group? What permissions? What user? Amazon made things so complicated I don't understand any of this. I get an ID and a Secret why is this not enough? Is there a magic command line for _deleting security groups_? Where did the broken one come from?

**Comment by sukima** [comment]
Created a group called `admin` and gave it the `AdministratorAccess`. Ran streisand. **triple** checked every character of the Access ID **and** secret. Still doesn't work:

```
 _________________________________
< PLAY [Provision the EC2 Server] >
 ---------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

 ________________________
< TASK [Gathering Facts] >
 ------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ________________________________
< TASK [Set the AWS Region fact] >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

ok: [localhost]
 ________________________________
< TASK [Set the AWS VPC ID fact] >
 --------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost]
 _______________________________________
< TASK [Set the AWS VPC Subnet ID fact] >
 ---------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

skipping: [localhost]
 ___________________________________________________________
< TASK [ec2-security-group : Create the EC2 security group] >
 -----------------------------------------------------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Response><Errors><Error><Code>AuthFailure</Code><Message>Authorization header or parameters are not formatted correctly.</Message></Error></Errors><RequestID>56c2d795-2ad3-4dd2-82cc-e03468b84ff5</RequestID></Response>
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/x9/rnlkt4c96n5bl_p7h6_f946w0000gq/T/ansible_W3ySGY/ansible_module_ec2_group.py\", line 487, in <module>\n    main()\n  File \"/var/folders/x9/rnlkt4c96n5bl_p7h6_f946w0000gq/T/ansible_W3ySGY/ansible_module_ec2_group.py\", line 283, in main\n    for curGroup in ec2.get_all_security_groups():\n  File \"/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/ec2/connection.py\", line 2984, in get_all_security_groups\n    [('item', SecurityGroup)], verb='POST')\n  File \"/usr/local/Cellar/python/2.7.13/Frameworks/Python.framework/Versions/2.7/lib/python2.7/site-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>AuthFailure</Code><Message>Authorization header or parameters are not formatted correctly.</Message></Error></Errors><RequestID>56c2d795-2ad3-4dd2-82cc-e03468b84ff5</RequestID></Response>\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/Users/suki/source/streisand/playbooks/amazon.retry
 ____________
< PLAY RECAP >
 ------------
        \   ^__^
         \  (oo)\_______
            (__)\       )\/\
                ||----w |
                ||     ||

localhost                  : ok=2    changed=0    unreachable=0    failed=1
```

**Comment by sukima** [comment]
@Ajwah even more confuse:

![screen shot 2017-05-16 at 10 27 00](https://cloud.githubusercontent.com/assets/70075/26111145/4fdf35ba-3a22-11e7-9ef9-8f644f843c19.png)

**Comment by neeksor** [comment]
Still broken.
TASK [ec2-security-group : Open all of the necessary ports across every service in the EC2 security group] *************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Response><Errors><Error><Code>InvalidParameterValue</Code><Message>Only Amazon VPC security groups may be used with this operation.</Message></Error></Errors><RequestID>X</RequestID></Response>
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_aGJjS9/ansible_module_ec2_group.py\", line 487, in <module>\n    main()\n  File \"/tmp/ansible_aGJjS9/ansible_module_ec2_group.py\", line 439, in main\n    cidr_ip=thisip)\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 3231, in authorize_security_group_egress\n    params, verb='POST')\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1207, in get_status\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 400 Bad Request\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error>**<Code>InvalidParameterValue</Code><Message>Only Amazon VPC security groups may be used with this operation.</Message></Error></Errors>**<RequestID>x0</RequestID></Response>\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/nick/streisand/playbooks/amazon.retry

PLAY RECAP *************************************************************************************************************************************************************************************
localhost                  : ok=4    changed=1    unreachable=0    failed=1

**Comment by cpu** [comment]
@neeksor What is your client operating system? What is the output from `ansible --version` and `pip show boto`? You're using the latest code from master?

**Comment by cpu** [comment]
I can't reproduce this issue with EC2 and it's missing information to try and make that easier. If someone wants to provide the information listed in the new issue template I will reopen this issue for investigation. In the meantime I'm going to close it as unactionable. Thanks!

**Comment by jesusangelm** [comment]
i have this issue too:

`TASK [ec2-security-group : Open necessary ports across supported services in the EC2 security group] *********************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ClientError: An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupEgress operation: Only Amazon VPC security groups may be used with this operation.
fatal: [localhost]: FAILED! => {"changed": false, "error": {"code": "InvalidParameterValue", "message": "Only Amazon VPC security groups may be used with this operation."}, "msg": "Unable to authorize out for ip 0.0.0.0/0 security group 'streisand-streisand' - An error occurred (InvalidParameterValue) when calling the AuthorizeSecurityGroupEgress operation: Only Amazon VPC security groups may be used with this operation.", "response_metadata": {"http_headers": {"connection": "close", "date": "Sat, 03 Feb 2018 16:41:38 GMT", "server": "AmazonEC2", "transfer-encoding": "chunked"}, "http_status_code": 400, "request_id": "6e7f7367-2aaa-40c5-93e1-143d76f5cd27", "retry_attempts": 0}}
`

using a user with permissions:
- AdministratorAccess 
- AmazonVPCFullAccess 

Using:
Ubuntu 16.04 LTS 
ansible 2.4.3.0

boto:
Name: boto
Version: 2.48.0

boto3
Name: boto3
Version: 1.5.22

**Comment by nopdotcom** [comment]
Could you open a fresh issue?

**Comment by jesusangelm** [comment]
@nopdotcom done: https://github.com/StreisandEffect/streisand/issues/1178
