### ISSUE TITLE
Update shadowsocks OSX mirror to 1.5.1

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#679]
The Shadowsocks mirror is [mirroring the 1.5-beta.2 version](https://github.com/jlund/streisand/blob/ff3fde73f7f282c2e9fb0eeb816bab652599b62a/playbooks/roles/streisand-mirror/vars/shadowsocks.yml#L25) of the Shadowsocks OSX app.  A finalized 1.5 release has been cut, and [1.5.1](https://github.com/shadowsocks/ShadowsocksX-NG/releases/tag/v1.5.1) is the most recent release. The Streisand mirror should be updated to 1.5.1.

**Comment by alimakki** [comment]
@cpu I tried that version on my machine, would crash immediately on connection attempt.

**Comment by cpu** [comment]
@alimakki Oh! That was 1.5.1? I forgot about that. Thanks - I'll close this for now since there isn't a replacement option.

**Comment by alimakki** [comment]
yessir
