### ISSUE TITLE
Mirring Tunnelblick for OSX failed...

### ISSUE THREAD

**Issue by Koopman** [jlund/streisand#684]
TASK [streisand-mirror : Mirror Tunnelblick for OS X] *************************************************
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "dest": "/var/www/streisand/mirror/openvpn", "failed": true, "gid": 33, "group": "www-data", "mode": "0755", "msg": "Request failed", "owner": "www-data", "response": "HTTP Error 404: Not Found", "size": 4096, "state": "directory", "status_code": 404, "uid": 33, "url": "https://tunnelblick.net/release/Tunnelblick_3.7.0_build_4790.dmg"}

**Comment by cpu** [comment]
I believe https://github.com/jlund/streisand/pull/683 fixes this. @Koopman can you verify that pulling the latest code from master resolves this for you?

**Comment by Koopman** [comment]
It is fixed.

I am not a Apple user, but I thought I would report it in case it bit 
someone else.

Dirk

**Comment by cpu** [comment]
Great - thanks!
