### ISSUE TITLE
cannot connect via ssh Permission denied

### ISSUE THREAD

**Issue by Wingzzzzz** [jlund/streisand#690]
At first, i have to blame myself for not taking notes at the beginning since i can run .yml once.

Trying to install streisand  on an vm. SSH to the server ok
But running ansible-playbook playbooks/streisand.yml --ask-become-pass gives:

fatal: [192.168.1.113]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/family/.ansible/cp/36f850729c\" does not exist\r\ndebug2: resolving \"192.168.1.113\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 192.168.1.113 [192.168.1.113] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 100000 ms remain after connect\r\ndebug1: identity file /home/family/.ssh/id_rsa type 1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_rsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_dsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_dsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ecdsa type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ecdsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ed25519 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2\r\ndebug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to 192.168.1.113:22 as 'vpn'\r\ndebug3: hostkeys_foreach: reading file \"/home/family/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/family/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from 192.168.1.113\r\ndebug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:gqBRLdvZFEvFp8+tFoRdkasl2zHBw7Lp5Dv9NVi/yZk\r\ndebug3: hostkeys_foreach: reading file \"/home/family/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/family/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from 192.168.1.113\r\ndebug1: Host '192.168.1.113' is known and matches the ECDSA host key.\r\ndebug1: Found key in /home/family/.ssh/known_hosts:1\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug2: key: /home/family/.ssh/id_rsa (0x5572a4c409c0), agent\r\ndebug2: key: /home/family/.ssh/id_dsa ((nil))\r\ndebug2: key: /home/family/.ssh/id_ecdsa ((nil))\r\ndebug2: key: /home/family/.ssh/id_ed25519 ((nil))\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug3: start over, passed a different list publickey,password\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Offering RSA public key: /home/family/.ssh/id_rsa\r\ndebug3: send_pubkey_test\r\ndebug3: send packet: type 50\r\ndebug2: we sent a publickey packet, wait for reply\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug1: Trying private key: /home/family/.ssh/id_dsa\r\ndebug3: no such identity: /home/family/.ssh/id_dsa: No such file or directory\r\ndebug1: Trying private key: /home/family/.ssh/id_ecdsa\r\ndebug3: no such identity: /home/family/.ssh/id_ecdsa: No such file or directory\r\ndebug1: Trying private key: /home/family/.ssh/id_ed25519\r\ndebug3: no such identity: /home/family/.ssh/id_ed25519: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug1: No more authentication methods to try.\r\nPermission denied (publickey,password).\r\n", 
    "unreachable": true
}

From my memory, i succeeded without any key injection.
Inventory uncommented last two line:
[streisand-host]
192.168.1.113 ansible_user=vpn

Hope someone can point out which step i missed. Thanks

**Comment by Wingzzzzz** [comment]
if i do ssh-keygen -t ecdsa

fatal: [192.168.1.113]: UNREACHABLE! => {
    "changed": false, 
    "msg": "Failed to connect to the host via ssh: OpenSSH_7.2p2 Ubuntu-4ubuntu2.1, OpenSSL 1.0.2g  1 Mar 2016\r\ndebug1: Reading configuration data /etc/ssh/ssh_config\r\ndebug1: /etc/ssh/ssh_config line 19: Applying options for *\r\ndebug1: auto-mux: Trying existing master\r\ndebug1: Control socket \"/home/family/.ansible/cp/36f850729c\" does not exist\r\ndebug2: resolving \"192.168.1.113\" port 22\r\ndebug2: ssh_connect_direct: needpriv 0\r\ndebug1: Connecting to 192.168.1.113 [192.168.1.113] port 22.\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: fd 3 clearing O_NONBLOCK\r\ndebug1: Connection established.\r\ndebug3: timeout: 99999 ms remain after connect\r\ndebug1: identity file /home/family/.ssh/id_rsa type 1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_rsa-cert type -1\r\ndebug1: identity file /home/family/.ssh/id_dsa type 2\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_dsa-cert type -1\r\ndebug1: identity file /home/family/.ssh/id_ecdsa type 3\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ecdsa-cert type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ed25519 type -1\r\ndebug1: key_load_public: No such file or directory\r\ndebug1: identity file /home/family/.ssh/id_ed25519-cert type -1\r\ndebug1: Enabling compatibility mode for protocol 2.0\r\ndebug1: Local version string SSH-2.0-OpenSSH_7.2p2 Ubuntu-4ubuntu2.1\r\ndebug1: Remote protocol version 2.0, remote software version OpenSSH_7.2p2 Ubuntu-4ubuntu2.2\r\ndebug1: match: OpenSSH_7.2p2 Ubuntu-4ubuntu2.2 pat OpenSSH* compat 0x04000000\r\ndebug2: fd 3 setting O_NONBLOCK\r\ndebug1: Authenticating to 192.168.1.113:22 as 'vpn'\r\ndebug3: hostkeys_foreach: reading file \"/home/family/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/family/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from 192.168.1.113\r\ndebug3: order_hostkeyalgs: prefer hostkeyalgs: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521\r\ndebug3: send packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT sent\r\ndebug3: receive packet: type 20\r\ndebug1: SSH2_MSG_KEXINIT received\r\ndebug2: local client KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group-exchange-sha1,diffie-hellman-group14-sha1,ext-info-c\r\ndebug2: host key algorithms: ecdsa-sha2-nistp256-cert-v01@openssh.com,ecdsa-sha2-nistp384-cert-v01@openssh.com,ecdsa-sha2-nistp521-cert-v01@openssh.com,ecdsa-sha2-nistp256,ecdsa-sha2-nistp384,ecdsa-sha2-nistp521,ssh-ed25519-cert-v01@openssh.com,ssh-rsa-cert-v01@openssh.com,ssh-ed25519,rsa-sha2-512,rsa-sha2-256,ssh-rsa\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com,aes128-cbc,aes192-cbc,aes256-cbc,3des-cbc\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: zlib@openssh.com,zlib,none\r\ndebug2: compression stoc: zlib@openssh.com,zlib,none\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug2: peer server KEXINIT proposal\r\ndebug2: KEX algorithms: curve25519-sha256@libssh.org,ecdh-sha2-nistp256,ecdh-sha2-nistp384,ecdh-sha2-nistp521,diffie-hellman-group-exchange-sha256,diffie-hellman-group14-sha1\r\ndebug2: host key algorithms: ssh-rsa,rsa-sha2-512,rsa-sha2-256,ecdsa-sha2-nistp256,ssh-ed25519\r\ndebug2: ciphers ctos: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: ciphers stoc: chacha20-poly1305@openssh.com,aes128-ctr,aes192-ctr,aes256-ctr,aes128-gcm@openssh.com,aes256-gcm@openssh.com\r\ndebug2: MACs ctos: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: MACs stoc: umac-64-etm@openssh.com,umac-128-etm@openssh.com,hmac-sha2-256-etm@openssh.com,hmac-sha2-512-etm@openssh.com,hmac-sha1-etm@openssh.com,umac-64@openssh.com,umac-128@openssh.com,hmac-sha2-256,hmac-sha2-512,hmac-sha1\r\ndebug2: compression ctos: none,zlib@openssh.com\r\ndebug2: compression stoc: none,zlib@openssh.com\r\ndebug2: languages ctos: \r\ndebug2: languages stoc: \r\ndebug2: first_kex_follows 0 \r\ndebug2: reserved 0 \r\ndebug1: kex: algorithm: curve25519-sha256@libssh.org\r\ndebug1: kex: host key algorithm: ecdsa-sha2-nistp256\r\ndebug1: kex: server->client cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug1: kex: client->server cipher: chacha20-poly1305@openssh.com MAC: <implicit> compression: zlib@openssh.com\r\ndebug3: send packet: type 30\r\ndebug1: expecting SSH2_MSG_KEX_ECDH_REPLY\r\ndebug3: receive packet: type 31\r\ndebug1: Server host key: ecdsa-sha2-nistp256 SHA256:gqBRLdvZFEvFp8+tFoRdkasl2zHBw7Lp5Dv9NVi/yZk\r\ndebug3: hostkeys_foreach: reading file \"/home/family/.ssh/known_hosts\"\r\ndebug3: record_hostkey: found key type ECDSA in file /home/family/.ssh/known_hosts:1\r\ndebug3: load_hostkeys: loaded 1 keys from 192.168.1.113\r\ndebug1: Host '192.168.1.113' is known and matches the ECDSA host key.\r\ndebug1: Found key in /home/family/.ssh/known_hosts:1\r\ndebug3: send packet: type 21\r\ndebug2: set_newkeys: mode 1\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS sent\r\ndebug1: expecting SSH2_MSG_NEWKEYS\r\ndebug3: receive packet: type 21\r\ndebug2: set_newkeys: mode 0\r\ndebug1: rekey after 134217728 blocks\r\ndebug1: SSH2_MSG_NEWKEYS received\r\ndebug1: Skipping ssh-dss key /home/family/.ssh/id_dsa - not in PubkeyAcceptedKeyTypes\r\ndebug2: key: /home/family/.ssh/id_rsa (0x55af90540a20), agent\r\ndebug2: key: /home/family/.ssh/id_ecdsa (0x55af9054e650)\r\ndebug2: key: /home/family/.ssh/id_ed25519 ((nil))\r\ndebug3: send packet: type 5\r\ndebug3: receive packet: type 7\r\ndebug1: SSH2_MSG_EXT_INFO received\r\ndebug1: kex_input_ext_info: server-sig-algs=<rsa-sha2-256,rsa-sha2-512>\r\ndebug3: receive packet: type 6\r\ndebug2: service_accept: ssh-userauth\r\ndebug1: SSH2_MSG_SERVICE_ACCEPT received\r\ndebug3: send packet: type 50\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug3: start over, passed a different list publickey,password\r\ndebug3: preferred gssapi-with-mic,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_lookup publickey\r\ndebug3: remaining preferred: ,gssapi-keyex,hostbased,publickey\r\ndebug3: authmethod_is_enabled publickey\r\ndebug1: Next authentication method: publickey\r\ndebug1: Offering RSA public key: /home/family/.ssh/id_rsa\r\ndebug3: send_pubkey_test\r\ndebug3: send packet: type 50\r\ndebug2: we sent a publickey packet, wait for reply\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug1: Offering ECDSA public key: /home/family/.ssh/id_ecdsa\r\ndebug3: send_pubkey_test\r\ndebug3: send packet: type 50\r\ndebug2: we sent a publickey packet, wait for reply\r\ndebug3: receive packet: type 51\r\ndebug1: Authentications that can continue: publickey,password\r\ndebug1: Trying private key: /home/family/.ssh/id_ed25519\r\ndebug3: no such identity: /home/family/.ssh/id_ed25519: No such file or directory\r\ndebug2: we did not send a packet, disable method\r\ndebug1: No more authentication methods to try.\r\nPermission denied (publickey,password).\r\n",

**Comment by Wingzzzzz** [comment]
what i really don't understand is how come i can ssh but can't ansible

**Comment by cpu** [comment]
@Wingzzzzz How do you SSH to the server? What SSH key did you use with the VM/VPS provider during provisioning? What username are you using? 

I would recommend that if you aren't especially comfortable setting up SSH with keybased authentication on your own that you use a first-party provider that Streisand supports better (e.g. Digital Ocean, EC2, Linode, etc).

**Comment by Wingzzzzz** [comment]
my goal is to set up a vpn in my local network

ssh vpn@192.168.1.113(local network) = ok
then enter password needed for vpn and ok to ssh

At the first time, i manager to run the yml with connection but stopped because unauthenticated package.
However, i lost the steps to get to that step

**Comment by tiliarou** [comment]
Did you generate the ssh keys with the same account as the one running the playbook command ?
I had issues where my ssh wasn't generated with the root account and it was simply not finding my key...3
Are we sure that ` --ask-become-pass` works with ansible playbook ? Can you post content of inventory and ansible cfg files ?

**Comment by Wingzzzzz** [comment]
"ssh wasn't generated with the root"
is that necessary?
according to the guide, use ssh-keygen.
should use sudo ssh-keygen?

"--ask-become-pass works with ansible playbook ?"
as i remember, i used --ask-become-pass in my successful case

inventory:
[localhost]
localhost ansible_connection=local ansible_python_interpreter=python

# Uncomment the following lines and update the IP address if you would
# like to use Streisand to configure a server that is already running
# (e.g. a server at a provider not natively supported by Streisand).
#
# Multiple servers can be configured simultaneously if multiple IP
# addresses are defined.
#
# If you already have SSH fingerprints for the hosts you are configuring
# (e.g. using `ssh-keyscan`) then you should also comment out the
# 'host_key_checking = False' line in the ansible.cfg file. That setting
# is only sensible and convenient when connecting to a brand-new host.
#
# [streisand-host]
# 255.255.255.255
#
# If the SSH user to be used to login is not "root", specify it here with
# the ansible_user directive. Streisand will sudo automatically. If sudo
# requires a password, use the --ask-become-pass command line option.
#
[streisand-host]
192.168.1.113 ansible_user=vpn

cfg (default):
[defaults]
inventory = inventory

# This is a convenient setting for a brand-new Streisand server that
# you are connecting to for the first time. However, this line should be
# commented out if you are connecting to an existing server where a
# known_hosts entry has already been created. Host key checking happens
# by default in Ansible.
host_key_checking = False

# Workaround for an Ansible issue with temporary paths:
# https://github.com/ansible/ansible/issues/21562
remote_tmp = $HOME/.ansible/tmp
local_tmp = $HOME/.ansible/tmp

# Some providers take a long time to actually begin accepting
# connections even after the OpenSSH daemon has started.
timeout = 100

[ssh_connection]
pipelining = True

**Comment by Wingzzzzz** [comment]
`

**Comment by Wingzzzzz** [comment]
One more question:
if password authentication used, any manual key transfer needed?

**Comment by cpu** [comment]
> ssh vpn@192.168.1.113(local network) = ok
> then enter password needed for vpn and ok to ssh

Streisand only support SSH key authentication at this time.

> if password authentication used, any manual key transfer needed?

Yes, you will have to set up key authentication manually. I recommend trying to find a guide or resources for this online.

I'm going to close this issue since provisioning your own VM with SSH key support is outside of the scope of this project. 

Thanks!

**Comment by Wingzzzzz** [comment]
strange thing happens:
ansible-playbook playbooks/streisand.yml --ask-become-pass
Failed to connect to the host via ssh: Permission denied (publickey,password).

change inventory:
[streisand-host]
192.168.1.113 ansible_user=vpn ansible-password=[password]
sudo: a password is required

ansible-playbook playbooks/streisand.yml --ask-become-pass
Incorrect sudo password

change back inventory:
[streisand-host]
192.168.1.113 ansible_user=vpn
ansible-playbook playbooks/streisand.yml --ask-become-pass
succeed to make connect

As my point of view: i just reverted the settings to original settings, nothing should be affect and should keep showing the error

**Comment by Wingzzzzz** [comment]
temp solution
inventory:
[streisand-host]
192.168.1.113 ansible_user=vpn ansible_password=[password]
ansible-playbook playbooks/streisand.yml --ask-become-pass

question:
why i have to double enter password
