### ISSUE TITLE
cannot get Tor Browser Bundle files

### ISSUE THREAD

**Issue by Wingzzzzz** [jlund/streisand#697]
messages shown below show no tor browser bundle files got
i chose to skip that.
what functionality will be affected?

TASK [streisand-mirror : Mirror the Tor Browser Bundle files and signatures] ***
changed: [192.168.1.113] => (item=https://dist.torproject.org/torbrowser/6.5.2/torbrowser-install-6.5.2_en-US.exe)
failed: [192.168.1.113] (item=https://dist.torproject.org/torbrowser/6.5.2/torbrowser-install-6.5.2_en-US.exe.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/6.5.2/torbrowser-install-6.5.2_en-US.exe.asc", "mode": "0755", "msg": "Request failed: <urlopen error ('_ssl.c:574: The handshake operation timed out',)>", "owner": "www-data", "size": 4096, "state": "directory", "uid": 33, "url": "https://dist.torproject.org/torbrowser/6.5.2/torbrowser-install-6.5.2_en-US.exe.asc"}
changed: [192.168.1.113] => (item=https://dist.torproject.org/torbrowser/6.5.2/TorBrowser-6.5.2-osx64_en-US.dmg)
changed: [192.168.1.113] => (item=https://dist.torproject.org/torbrowser/6.5.2/TorBrowser-6.5.2-osx64_en-US.dmg.asc)
changed: [192.168.1.113] => (item=https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux32-6.5.2_en-US.tar.xz)
changed: [192.168.1.113] => (item=https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux32-6.5.2_en-US.tar.xz.asc)
changed: [192.168.1.113] => (item=https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux64-6.5.2_en-US.tar.xz)
failed: [192.168.1.113] (item=https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux64-6.5.2_en-US.tar.xz.asc) => {"dest": "/var/www/streisand/mirror/tor", "failed": true, "gid": 33, "group": "www-data", "item": "https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux64-6.5.2_en-US.tar.xz.asc", "mode": "0755", "msg": "Request failed: <urlopen error ('_ssl.c:574: The handshake operation timed out',)>", "owner": "www-data", "size": 4096, "state": "directory", "uid": 33, "url": "https://dist.torproject.org/torbrowser/6.5.2/tor-browser-linux64-6.5.2_en-US.tar.xz.asc"}

TASK [streisand-mirror : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
Press 'C' to continue the play or 'A' to abort 
ok: [192.168.1.113]

**Comment by cpu** [comment]
> messages shown below show no tor browser bundle files got
> i chose to skip that.
> what functionality will be affected?

@Wingzzzzz The only functionality affected is the mirrored copy of some of the Tor browser installers. If you don't need these installers you won't be affected.
