### ISSUE TITLE
dnsmasq cannot be restarted

### ISSUE THREAD

**Issue by Wingzzzzz** [jlund/streisand#698]
i got error when restarting dnsmasq.

```
vpn@ubuntu:~$ systemctl status dnsmasq
● dnsmasq.service - dnsmasq - A lightweight DHCP and caching DNS server
   Loaded: loaded (/lib/systemd/system/dnsmasq.service; enabled; vendor preset: enabled)
  Drop-In: /run/systemd/generator/dnsmasq.service.d
           └─50-dnsmasq-$named.conf, 50-insserv.conf-$named.conf
   Active: failed (Result: exit-code) since Sun 2017-05-21 02:10:37 PDT; 27min ago
  Process: 59697 ExecStop=/etc/init.d/dnsmasq systemd-stop-resolvconf (code=exited, status=0/SUCCESS)
  Process: 59711 ExecStart=/etc/init.d/dnsmasq systemd-exec (code=exited, status=2)
  Process: 59708 ExecStartPre=/usr/sbin/dnsmasq --test (code=exited, status=0/SUCCESS)
 Main PID: 32181 (code=exited, status=0/SUCCESS)

May 21 02:10:37 ubuntu systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
May 21 02:10:37 ubuntu dnsmasq[59708]: dnsmasq: syntax check OK.
May 21 02:10:37 ubuntu dnsmasq[59711]: dnsmasq: failed to create listening socket for 10.9.0.1: Cannot assign requested address
May 21 02:10:37 ubuntu systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
May 21 02:10:37 ubuntu systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
May 21 02:10:37 ubuntu systemd[1]: dnsmasq.service: Unit entered failed state.
May 21 02:10:37 ubuntu systemd[1]: dnsmasq.service: Failed with result 'exit-code'.
```

**Comment by cpu** [comment]
@Wingzzzzz Can you share the contents of `/etc/dnsmasq.conf`? Have you modified the system or its configuration at all? 

> May 21 02:10:37 ubuntu dnsmasq[59711]: dnsmasq: failed to create listening socket for 10.9.0.1: Cannot assign requested address

Can you share the output of `ip addr`? If I had to guess I would say that one of your `tun` interfaces (the one intended to have address 10.9.0.1) wasn't created properly.

Based on https://github.com/jlund/streisand/issues/690 - I'm guessing this also relates to your non-standard provider. Have you tried running Streisand in a well supported provider (e.g. DigitalOcean, Linode, AWS, etc) - it will be significantly easier.

**Comment by Wingzzzzz** [comment]
thank you for your reply
no config has been made

`/etc/dnsmasq.conf`
`listen-address=127.0.0.1,10.8.0.1,10.9.0.1,10.192.122.1`

`# Never forward plain names (without a dot or domain part)`
`domain-needed`

`# Never forward addresses in the non-routed address spaces.`
`bogus-priv`

`# If you don't want dnsmasq to read /etc/resolv.conf or any other`
`# file, getting its servers from this file instead (see below), then`
`# uncomment this.`
`no-resolv`

`server=8.8.8.8`
`server=8.8.4.4`

`vpn@ubuntu:~$ ip addr`
```
1: lo: <LOOPBACK,UP,LOWER_UP> mtu 65536 qdisc noqueue state UNKNOWN group default qlen 1
    link/loopback 00:00:00:00:00:00 brd 00:00:00:00:00:00
    inet 127.0.0.1/8 scope host lo
       valid_lft forever preferred_lft forever
    inet6 ::1/128 scope host 
       valid_lft forever preferred_lft forever
2: ens33: <BROADCAST,MULTICAST,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UP group default qlen 1000
    link/ether 00:0c:29:a7:45:98 brd ff:ff:ff:ff:ff:ff
    inet 192.168.1.113/24 brd 192.168.1.255 scope global dynamic ens33
       valid_lft 6980sec preferred_lft 6980sec
    inet6 fe80::863a:3eef:2bc1:70b7/64 scope link 
       valid_lft forever preferred_lft forever
3: tun0: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none 
    inet 10.8.0.1 peer 10.8.0.2/32 scope global tun0
       valid_lft forever preferred_lft forever
    inet6 fe80::8ced:80df:83d9:6eba/64 scope link flags 800 
       valid_lft forever preferred_lft forever
4: tun1: <POINTOPOINT,MULTICAST,NOARP,UP,LOWER_UP> mtu 1500 qdisc pfifo_fast state UNKNOWN group default qlen 100
    link/none 
    inet 10.9.0.1 peer 10.9.0.2/32 scope global tun1
       valid_lft forever preferred_lft forever
    inet6 fe80::e861:df3b:366e:d672/64 scope link flags 800 
       valid_lft forever preferred_lft forever
5: wg0-server: <POINTOPOINT,NOARP,UP,LOWER_UP> mtu 1420 qdisc noqueue state UNKNOWN group default qlen 1
    link/none 
    inet 10.192.122.1/24 scope global wg0-server
       valid_lft forever preferred_lft forever
6: ip_vti0@NONE: <NOARP> mtu 1332 qdisc noop state DOWN group default qlen 1
    link/ipip 0.0.0.0 brd 0.0.0.0
```

**Comment by cpu** [comment]
@Wingzzzzz Interesting, so the `tun1` interface is there. Ok.

To make sure nothing was cut off, can you share the output from `journalctl --unit dnsmasq.service --since yesterday --no-pager`?

Can you also share the output from `lsof -Pn +M  | grep ":53"` to see if anything is using the port already?

Have you tried running Streisand in a well supported provider (e.g. DigitalOcean, Linode, AWS, etc) - it will be significantly easier.

**Comment by Wingzzzzz** [comment]
from online research
it looks like related to openvpn
and there is some config related:
# EXAMPLE: Suppose you want to give
# Thelonious a fixed VPN IP address of 10.9.0.1.
# First uncomment out these lines:
;client-config-dir ccd
;route 10.9.0.0 255.255.255.252
# Then add this line to ccd/Thelonious:
#   ifconfig-push 10.9.0.1 10.9.0.2
# This example will only work
# if you are routing, not bridging, i.e. you are
# using "dev tun" and "server" directives.

is that related to the face that my vm is using bridging to host pc?

**Comment by Wingzzzzz** [comment]
```
vpn@ubuntu:~$ journalctl --unit dnsmasq.service --since yesterday --no-pager
-- Logs begin at Sun 2017-05-21 06:00:32 PDT, end at Sun 2017-05-21 06:11:02 PDT. --
May 21 06:00:50 ubuntu systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
May 21 06:00:51 ubuntu dnsmasq[914]: dnsmasq: syntax check OK.
May 21 06:00:53 ubuntu dnsmasq[944]: dnsmasq: failed to create listening socket for 10.192.122.1: Cannot assign requested address
May 21 06:00:53 ubuntu systemd[1]: dnsmasq.service: Control process exited, code=exited status=2
May 21 06:00:53 ubuntu systemd[1]: Failed to start dnsmasq - A lightweight DHCP and caching DNS server.
May 21 06:00:53 ubuntu systemd[1]: dnsmasq.service: Unit entered failed state.
May 21 06:00:53 ubuntu systemd[1]: dnsmasq.service: Failed with result 'exit-code'.

```

**Comment by Wingzzzzz** [comment]
nothing is shown with `~$ lsof -Pn +M | grep ":53"`

not yet tried with standard provider

**Comment by cpu** [comment]
> May 21 06:00:53 ubuntu dnsmasq[944]: dnsmasq: failed to create listening socket for 10.192.122.1: Cannot assign requested address

Interesting. This is a different interface (10.192.122.1 - `wg0-server`) than before (10.9.0.1 - `tun1`).

Since there isn't anything else listening on port 53 on any interfaces I'm at a loss.

> not yet tried with standard provider

All of your problems so far (the three issues I've seen anyway) seem to stem from your own virtual machine provider. I'm going to close this issue since there isn't an obvious cause and I'm not able to spend too much more of my own time debugging an environment I can't access or understand.

I recommend that you try using one of the supported providers to get a known working configuration. You might be able to use that to try and debug your own non-standard VM instance by comparing between the two.
