### ISSUE TITLE
Install do-agent when running on DigitalOcean

### ISSUE THREAD

**Issue by z0rc** [jlund/streisand#705]
Per https://www.digitalocean.com/community/tutorials/how-to-install-and-use-the-digitalocean-agent-for-monitoring

This gives better overview of DO droplet.

**Comment by cpu** [comment]
I think provider-specific monitoring is perhaps outside of the scope of the project. Speaking personally I'd rather see generalized solutions that work across providers ala what Streisand did with monit. Maybe using munin or something similar.

**Comment by z0rc** [comment]
I investigated this a bit. Initially I though this can be done on droplet creation via API as mentioned in linked article. But it appears that ansible `digital_ocean` module doesn't support this, mainly because `dopy` doesn't support this either, see https://github.com/Wiredcraft/dopy/pull/57.

I agree that adding provider-specific monitoring after instance creation isn't that straight forward. Feel free to close this issue. Thanks!

**Comment by cpu** [comment]
@z0rc thanks for looking into it! If the deps were using for Digital ocean end up updating to do this in an easy way maybe it would be something to revisit.
