### ISSUE TITLE
Port forwarding.

### ISSUE THREAD

**Issue by ScareFeratis** [jlund/streisand#706]
Hello. The thing is, I have a gameserver that I need to maintain while under VPN. Can I somehow open necessary port and pass them through the VPN connection, so that I would be able to listen that port on my local machine which is connected to Streisand server?

**Comment by cpu** [comment]
Hi @ScareFeratis - I don't know of a way to do this off-hand. The request is far enough from the base goals of this project that I'm going to close this issue for now. You can continue to debug & comment in here but unfortunately I suspect we don't have the support bandwidth to help you with this one. Good luck!

**Comment by frybread** [comment]
Yes you can, it's fairly simple. I just tested this with OpenVPN and Streisand, the basic idea is to forward the port you need to the port your VPN is using.

The port I needed was 25565. My OpenVPN runs on port 636, therefore I'll forward 25565 to 636.

1) Login to your Streisand server as root
2) Allow the port you need
`ufw allow 25565`
3) Add a before filter section in /etc/ufw/before.rules (at the top of file):

> *nat
> :PREROUTING ACCEPT [0:0]
> -A PREROUTING -p tcp --dport 25565 -j REDIRECT --to-port 636
> COMMIT

4) reboot the server
