### ISSUE TITLE
openvpn : Generate certificate for the Server

### ISSUE THREAD

**Issue by hansgans** [jlund/streisand#709]
I tried to setup streisand using amazon AWS. My host system is macOS. 
During setup the task `TASK [openvpn : Generate certificate for the Server]` fails with the error `The commonName field needed to be supplied and was missing`. I attached a detailed log file: [err.txt](https://github.com/jlund/streisand/files/1033261/err.txt)

Since I'm new to setting up a VPN server etc. I have no idea where to start looking for a solution.

**Comment by cpu** [comment]
Hi @hansgans, sorry to hear you're running into trouble here.

Can you access the server via SSH? If so could you try sharing the output of these commands:
*  `openssl version`
* `cat /etc/openvpn/openssl-certificate.cnf` 
* `cat /etc/openvpn/openvpn_server_common_name`

**Comment by alimakki** [comment]
@hansgans I tried spinning up a new streisand instance on AWS west region, I can't seem to be able to reproduce your issue:

```
TASK [openvpn : Generate a random server common name] ***************************************************************************************************************
changed: [xxx]

TASK [openvpn : Set permissions on the OpenVPN server common name file] *********************************************************************************************
changed: [xxx]

TASK [openvpn : Register the OpenVPN server common name] ************************************************************************************************************
changed: [xxx]

TASK [openvpn : Generate the OpenSSL configuration that will be used for the Server certificate's req and ca commands] **********************************************
changed: [xxx]
``` 

Would you be able to give it another go?

**Comment by cpu** [comment]
Can you ensure you're using the latest code from master & provisioning a brand new EC2 instance when you try again? Thanks!

**Comment by hansgans** [comment]
Hi @cpu, this is the information from the instance that I launched yesterday and at which the error occurred:
`openssl version`

> OpenSSL 1.0.2g  1 Mar 2016

`sudo cat /etc/openvpn/openssl-certificate.cnf`

>[openssl-certificate.txt](https://github.com/jlund/streisand/files/1033929/openssl-certificate.txt)

`sudo cat /etc/openvpn/openvpn_server_common_name`

>sudo: unable to resolve host ip-xxx-xx-xx-x

Here, I used yesterdays version of the master branch. And the instance were launched in region 5 (Japan).

Today, I updated the repo and tried to create a new instance exactly the same way as yesterday (same region etc) and it worked like a charm.

**Comment by alimakki** [comment]
@hansgans Good to know that you're up and running!

**Comment by cpu** [comment]
> sudo cat /etc/openvpn/openvpn_server_common_name
> sudo: unable to resolve host ip-xxx-xx-xx-x

The failed instances having an empty `openvpn_server_common_name file explains why that particular TASK failed. Quite mysterious.

**Comment by nonsequitur** [comment]
This error has bitten me, too. It occurs when the `common` role is disabled in `streisand.yml`.
The `wamerican-huge` dictionary is not installed and subsequently the `Generate a random server common name` task generates an empty `openvpn_server_common_name` file.

**Comment by cpu** [comment]
@nonsequitur Interesting. That makes sense. Disabling roles is not supported (yet).
