### ISSUE TITLE
Windows provisioning support

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#710]
From [Jim Salter](https://arstechnica.com/gadgets/2017/05/how-to-build-your-own-vpn-if-youre-rightfully-wary-of-commercial-options/?comments=1&post=33391773):

> First gripe - you can't run the initial setup on a Windows machine.

While likely low on the priority list this issue captures this feature request. It seems [there is some Ansible support](http://docs.ansible.com/ansible/intro_windows.html) and with the newer ["Windows subsystem for Linux"](https://msdn.microsoft.com/en-us/commandline/wsl/install_guide) it might not be as hard to implement as it was at the time Streisand was started.  Alternatively: perhaps there's a way to provide a VM/docker image.

**Comment by nickolasclarke** [comment]
@cpu I run win10 daily and use WSL heavily. I can help with this as needed. In fact, I've used WSL to set up many a new instance. However, given some of the problems I've run into with provisioning a remote machine over SSH from in-country, I think that the more important way to work around this would be to allow single machine configuration (there is an issue open for this already somewhere).

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/4
