### ISSUE TITLE
Document and consolidate software installation sources

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#711]
From [Jim Salter](https://arstechnica.com/gadgets/2017/05/how-to-build-your-own-vpn-if-youre-rightfully-wary-of-commercial-options/?comments=1&post=33391773):
> There's also a mishmash of repositories used for installing the software - a little from your distro, a lot from pip. Are you automatically updating the stuff you installed with pip? If so, how, and how frequently?

We should try and form a comprehensive picture of where the software Streisand provisions comes from. As pointed out, currently there is a mix of PPAs, source compilation, and pip. Ideally we could reduce the number of distinct sources and ensure that the ones that are easiest to automatically update are preferred.

**Comment by nickolasclarke** [comment]
This is an easy task I can take on. Where should we document this? In a separate SOURCES.md file, or elsewhere? I dont know of any common or standard way to capture this info in a project like this.

**Comment by cpu** [comment]
@nickolasclarke How about making a new `.md` file in the `documentation/` directory? That seems like an OK place to start. Thanks for taking this one!

**Comment by cpu** [comment]
@nickolasclarke Is this still something on your plate for the near future? If not can I unassign it?

**Comment by nickolasclarke** [comment]
@cpu yep, I can do it. I off the grid last week, sorry!

**Comment by cpu** [comment]
No need to be sorry :-) Just checking in, thanks!

**Comment by nickolasclarke** [comment]
quick sanity check: t = things to install, and thus a source, f = nothing to install

```
azure-security-group = F
common = T
diffie-hellman-group = F
dnsmasq = T
download-and-verify = F
ec2-security-group = F
gce-network = F
genesis-amazon = f
genesis-azure = f
genesis-digitalocean =f
genesis-google = f
genesis-linode = f
genesis-rackspace = f
ip-forwarding = f
l2tp-ipsec = f
monit = t
nginx = t
openconnect = t
openvpn = t
rsyslog = f
shadowsocks = t
ssh = f
sslh = t
streisand-gateway = f
streisand-mirror = t (why are ssh related stuff here?)
stunnel = t (why stunnel source, if we install from apt?)
test-client = f (what is this? for vagrant testing?)
tinyproxy = t
tor-bridge = t
ufw/tasks = t
validation/tasks = f
wireguard = t
```
