### ISSUE TITLE
Failed to install on Ubuntu 16.04 on aarch64

### ISSUE THREAD

**Issue by WGH-** [jlund/streisand#718]
Occurs at current `master` (eb3bcd991e4d)

Might be somewhat related to #405.

```
TASK [tor-bridge : Install the package to keep the Tor signing key current] ***************************************************************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": false, "failed": true, "msg": "No package matching 'deb.torproject.org-keyring' is available"}
```

**Comment by nickolasclarke** [comment]
@WGH- what provider are you doing this on?

**Comment by WGH-** [comment]
https://www.scaleway.com/

**Comment by cpu** [comment]
@WGH- At this time we're not able to support Scaleway as a provider, or deploying Streisand to an ARM host. I would welcome non-intrusive PRs if you're interested in trying to improve support. Thanks for understanding.
