### ISSUE TITLE
Impossible to find "generated-docs/ streisand.html"

### ISSUE THREAD

**Issue by karnivans** [jlund/streisand#721]
Hi all?

I'm trying to install STREISAND on debian OS from DigitalOcean by imposible to find the 
"generated-docs/ streisand.html" file.

The install seems to be good, what what i did do wrong ?

Thanks for your help

**Comment by alimakki** [comment]
Hi @karnivans - The generated-docs folder will be in the same directory where you cloned the Streisand projected to .

**Comment by kar2013** [comment]
Hi alimakki,

Sorry but my install is not good, i have the error below :
It's seems to be a mistake with my ssh key but i add the content of the file MyKeySSH.pub
in panel security of Digitalocean website.

Someone know what i do wrong?

Thanks

TASK [genesis-digitalocean : Set the DigitalOcean Access Token fact to the value that was entered, or attempt to retrieve it from the environment if the entry is blank] ***********
ok: [localhost]

TASK [genesis-digitalocean : Get the default SSH key] ******************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": true, "cmd": ["cat", "~/.ssh/id_rsa.pub"], "delta": "0:00:00.013221", "end": "2017-06******20.86***214", "failed": true, "rc": 1, "start": "2017-06-02 1*****55993", "stderr": "cat: /root/.ssh/id_rsa.pub: No such file or directory", "stderr_lines": ["cat: /root/.ssh/id_rsa.pub: No such file or directory"], "stdout": "", "stdout_lines": []}
        to retry, use: --limit @/root/streisand/playbooks/digitalocean.retry

PLAY RECAP *************************************************************************************************************************************************************************
localhost                  : ok=2    changed=0    unreachable=0    failed=1

root@MASTER-DEBIAN:~/streisand#

**Comment by alimakki** [comment]
@kar2013 - It looks like you don't have an SSH key generated, this can be fixed by doing the following:

`ssh-keygen -t rsa -b 2048 `

Have a go at that and try again.

**Comment by kar2013** [comment]
alimakki  it's ok your command work well !
Thanks a lot !

A last questions, when i use openvpn, where are  stored all  connections logs ?

Should I delete them to preserve my private life or it's automatic?

Regards

**Comment by alimakki** [comment]
@kar2013 Streisand does not log VPN connections :)

**Comment by kar2013** [comment]
Cool, nothing to do !

ali makki thanks a lot !

**Comment by alimakki** [comment]
@kar2013 You're welcome.
@karnivans Have you been able to resolve your issue?

**Comment by kar2013** [comment]
Yes, my vpn Works good with openvpn on Windows 

But i need to untersand how to use it like a real VPS with Windows.

**Comment by cpu** [comment]
Since the original problem has been resolved I'm going to close this issue. Thanks!
