### ISSUE TITLE
[Feature Request] Provide SSTP support by adding Softether VPN

### ISSUE THREAD

**Issue by HowardMei** [jlund/streisand#722]
Could you please add Softether VPN support as an option?
http://www.softether.org/
I'm not sure if it's conflicting with existing L2TP/OpenVPN setup,
so I'd better file a request.

**Comment by cpu** [comment]
Hi @HowardMei - this is a duplicate of https://github.com/jlund/streisand/issues/140, so I'm going to close it. Thanks for the suggestion, please follow #140 for that discussion.
