### ISSUE TITLE
STREISAND/OPENVPN - KILL SWITCH

### ISSUE THREAD

**Issue by kar2013** [jlund/streisand#726]
Dear all,

For more sécurity in use of  STREISAND
 how it's possible to use a kill switch,  if  OPENVPN is down ?

Thanks for help

**Comment by atulsian89** [comment]
Kill switch  is more of a client based feature. All the professional vpn provider have this feature coded in to their client. I don't think it is possible on openvpn default  client.

**Comment by kar2013** [comment]
@atulsian89  thanks for your answer.

if openVPN drop out it's a big problem, no?

**Comment by cpu** [comment]
Hi @kar2013, "kill switch" is a duplicate feature request for https://github.com/jlund/streisand/issues/523
