### ISSUE TITLE
Timeout when waiting for search string OpenSSH in xx.xxx.xx.xxx:xx

### ISSUE THREAD

**Issue by doginpants** [jlund/streisand#731]
### Expected behavior:
Not sure how to show what was supposed to happen but I have fixed all other issues and got so far but I am stuck on this one and can use some help. I will provide any info asked for. Not sure what you need to fix it so I will give what I ran
### Actual Behavior:

```
[admin@doginpants streisand]$ ./streisand

  S T R E I S A N D  

Which provider are you using?
  1. Amazon
  2. Azure
  3. DigitalOcean
  4. Google
  5. Linode
  6. Rackspace
: 1


 [WARNING]: Found both group and host with same name: localhost

In what region should the server be located?
  1. Asia Pacific   (Mumbai)
  2. Asia Pacific   (Seoul)
  3. Asia Pacific   (Singapore)
  4. Asia Pacific   (Sydney)
  5. Asia Pacific   (Tokyo)
  6. Canada         (Central)
  7. EU             (Frankfurt)
  8. EU             (Ireland)
  9. EU             (London)
  10. South America (Sao Paulo)
  11. US East       (Northern Virginia)
  12. US East       (Ohio)
  13. US West       (Northern California)
  14. US West       (Oregon)
Please choose the number of your region. Press enter for default (#3) region.
 [3]: 13

In which VPC would you like to create the server and security group
(e.g. vpc-89d740ee)?

Press enter to use the default VPC.
: vpc-e8fa6b8c

From which subnet should the server receive an address (e.g. subnet-78d9a232)?

Press enter to use the default subnet.
: subnet-a12259f9

What should the server be named? Press enter for default (streisand).
 [streisand]: 


The following information can be found in the IAM Management Console.
https://console.aws.amazon.com/iam/home?#security_credential

What is your AWS Access Key ID?
: (My key)

What is your AWS Secret Access Key?
: (my key)

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the EC2 Server] ************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Set the AWS Region fact] *************************************************
ok: [localhost]

TASK [Set the AWS VPC ID fact] *************************************************
ok: [localhost]

TASK [Set the AWS VPC Subnet ID fact] ******************************************
ok: [localhost]

TASK [ec2-security-group : Create the EC2 security group] **********************
changed: [localhost]

TASK [ec2-security-group : Pause for fifteen seconds to ensure the EC2 security group has been created] ***
Pausing for 15 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [ec2-security-group : Open all of the necessary ports across every service in the EC2 security group] ***
changed: [localhost]

TASK [genesis-amazon : Remove the 'streisand' SSH key from Amazon if it already exists. This is to prevent problems if two people with two different keys are sharing the same AWS account.] ***
changed: [localhost]

TASK [genesis-amazon : Get the default SSH key] ********************************
changed: [localhost]

TASK [genesis-amazon : Add the SSH key to Amazon under the name of 'streisand-ssh'] ***
changed: [localhost]

TASK [genesis-amazon : Determine which AMI to use] *****************************
ok: [localhost]

TASK [genesis-amazon : Create the EC2 instance] ********************************
changed: [localhost]

TASK [genesis-amazon : Create CloudWatch alarm to auto-recover instance] *******
changed: [localhost]

TASK [genesis-amazon : Wait until the server has finished booting and OpenSSH is accepting connections] ***
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 600, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in xx.xx.xx.xxx:xx"}
	to retry, use: --limit @/home/admin/streisand/playbooks/amazon.retry

PLAY RECAP *********************************************************************
localhost                  : ok=13   changed=7    unreachable=0    failed=1   

[admin@doginpants streisand]$ --limit
bash: --limit: command not found...
./streisand --limit @/homFailed to search for file: Timeout was reached
[admin@doginpants streisand]$ ./streisand --limit @/home/admin/streisand/playbooks/amazon.retry

  S T R E I S A N D  

Which provider are you using?
  1. Amazon
  2. Azure
  3. DigitalOcean
  4. Google
  5. Linode
  6. Rackspace
: 1


 [WARNING]: Found both group and host with same name: localhost

In what region should the server be located?
  1. Asia Pacific   (Mumbai)
  2. Asia Pacific   (Seoul)
  3. Asia Pacific   (Singapore)
  4. Asia Pacific   (Sydney)
  5. Asia Pacific   (Tokyo)
  6. Canada         (Central)
  7. EU             (Frankfurt)
  8. EU             (Ireland)
  9. EU             (London)
  10. South America (Sao Paulo)
  11. US East       (Northern Virginia)
  12. US East       (Ohio)
  13. US West       (Northern California)
  14. US West       (Oregon)
Please choose the number of your region. Press enter for default (#3) region.
 [3]: 13

In which VPC would you like to create the server and security group
(e.g. vpc-89d740ee)?

Press enter to use the default VPC.
: vpc-e8fa6b8c

From which subnet should the server receive an address (e.g. subnet-78d9a232)?

Press enter to use the default subnet.
: subnet-a12259f9

What should the server be named? Press enter for default (streisand).
 [streisand]: 


The following information can be found in the IAM Management Console.
https://console.aws.amazon.com/iam/home?#security_credential

What is your AWS Access Key ID?
: my key

What is your AWS Secret Access Key?
: my key

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the EC2 Server] ************************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [Set the AWS Region fact] *************************************************
ok: [localhost]

TASK [Set the AWS VPC ID fact] *************************************************
ok: [localhost]

TASK [Set the AWS VPC Subnet ID fact] ******************************************
ok: [localhost]

TASK [ec2-security-group : Create the EC2 security group] **********************
changed: [localhost]

TASK [ec2-security-group : Pause for fifteen seconds to ensure the EC2 security group has been created] ***
Pausing for 15 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

TASK [ec2-security-group : Open all of the necessary ports across every service in the EC2 security group] ***
changed: [localhost]

TASK [genesis-amazon : Remove the 'streisand' SSH key from Amazon if it already exists. This is to prevent problems if two people with two different keys are sharing the same AWS account.] ***
changed: [localhost]

TASK [genesis-amazon : Get the default SSH key] ********************************
changed: [localhost]

TASK [genesis-amazon : Add the SSH key to Amazon under the name of 'streisand-ssh'] ***
changed: [localhost]

TASK [genesis-amazon : Determine which AMI to use] *****************************
ok: [localhost]

TASK [genesis-amazon : Create the EC2 instance] ********************************
changed: [localhost]

TASK [genesis-amazon : Create CloudWatch alarm to auto-recover instance] *******
changed: [localhost]

TASK [genesis-amazon : Wait until the server has finished booting and OpenSSH is accepting connections] ***
fatal: [localhost]: FAILED! => {"changed": false, "elapsed": 600, "failed": true, "msg": "Timeout when waiting for search string OpenSSH in xx.xxx.xx.xxx:xx"}
	to retry, use: --limit @/home/admin/streisand/playbooks/amazon.retry

PLAY RECAP *********************************************************************
localhost                  : ok=13   changed=7    unreachable=0    failed=1   

[admin@doginpants streisand]$ 
```
### Steps to Reproduce:
1. Install fedora 25
2. Have lots of trouble installing dependancies and updates
3. Figure out most things
4. download deluge because it had the dependancies I need.
5. clone into streisand and get this issue. 
6. Not sure what else? Profit?

**Comment by cpu** [comment]
Hi @doginpants,

Is the network you're running Streisand from unusual in any way? Is it possible that it's blocking/munging outbound SSH? 

As a first step it might be worth increasing [the timeout for this step in the Amazon genesis role](https://github.com/jlund/streisand/blob/54b11886d5c436e8ecf7b82c04cf08568a7fd10e/playbooks/roles/genesis-amazon/tasks/main.yml#L78). That is, edit the file `playbooks/roles/genesis-amazon/tasks/main.yml` from the Streisand code you cloned. Change line 78 to a larger value (maybe try 2000) to start? I'm interested in hearing if this helps.

Are you able to confirm that the EC2 instance(s?) Streisand created are running when you log in to your AWS account?

**Comment by doginpants** [comment]
I have not tried changing line 78 to a larger value but I did try running it again with the limit command and got the same error. on the front of the EC2 instance here is what I believe you are talking about for instances. the 2 times I ran streisand, it created these 2. 
![str](https://user-images.githubusercontent.com/11380316/26896149-af287b8c-4b78-11e7-87e2-61e9533373f2.png)

**Comment by cpu** [comment]
@doginpants Are you able to SSH to any of those three instances using the `~/.ssh/id_rsa` keypair from the machine you're running Streisand on? E.g:
`ssh -i ~/.ssh/id_rsa ubuntu@XX.XX.XX.XX whoami`

**Comment by doginpants** [comment]
I tried the to ssh to the 3 instances currently running using the command replacing the x's with my instance ips. All 3 timed out when I tried to SSH.

**Comment by cpu** [comment]
@doginpants Are you able to ping the 3 instance IPs without error? Can you SSH to other machines without a timeout? E.g. what does `sshgithub.com` say? 

Is the network you're running Streisand from unusual in any way? Is it possible that it's blocking/munging outbound SSH?

**Comment by doginpants** [comment]
I think something is up in the background of what I am doing but I dont have the knowledge of the system enough to know what it is. Something must be configured wrong with the network or ssh. This is what I get when I try to ping github.com.  ```
[admin@doginpants ~]$ ssh github.com
The authenticity of host 'github.com (192.30.255.112)' can't be established.
RSA key fingerprint is .
RSA key fingerprint is .
Are you sure you want to continue connecting (yes/no)? y
Please type 'yes' or 'no': yes
Warning: Permanently added 'github.com,192.30.255.112' (RSA) to the list of known hosts.
Permission denied (publickey).
[admin@doginpants ~]$ 


```
so the permission is being denied but I have a ssh key generated not sure how this stuff works quite yet tho so not sure what it means.

**Comment by cpu** [comment]
@doginpants That error is expected - you don't have an SSH key authorized for github.com. I just wanted to see if it failed with a timeout - it did not.

I'm not sure why you aren't able to reach your EC2 instances but it does not appear to be Streisand related. I'm short of ideas to try next.

**Comment by doginpants** [comment]
maybe this  [WARNING]: Found both group and host with same name: localhost that I get at the start has something to do with it?

**Comment by cpu** [comment]
@doginpants Unfortunately not. That warning can be ignored.

**Comment by doginpants** [comment]
So what should I do. Things I am debating are, clean install clean aws and try again, wait for someone to magic fix, or keep scouring google for the possible cause. Idk someone has got to be able to figure this out.

**Comment by cpu** [comment]
@doginpants It may be worth trying a different provider (e.g. Linode, Digital Ocean, GCE) and seeing if you have the same problem with the initial SSH connection.

When you ran the `ssh -i ~/.ssh/id_rsa ubuntu@XX.XX.XX.XX whoami` command, what IP did you use? Can you ping that IP? Can you share the exact output?

**Comment by doginpants** [comment]
I can share the exact output I just was not sure if I should paste the ips in here because I dont know if that is safe. if you give me the heads up that its ok I can.
Then I will try a different provider.

**Comment by cpu** [comment]
> @cpu I can share the exact output I just was not sure if I should paste the ips in here because I dont know if that is safe. if you give me the heads up that its ok I can.

No problem. Best to be on the cautious side :-) I asked mostly to check that you were using the **public** IPv4 address. You can skip sharing the exact IP if you're able to confirm its the public address. Alternatively we could share that piece of information by IRC or E-mail if you prefer.

> Then I will try a different provider. Also should I try to ssh to the private or public ipv4 of the instances?

@doginpants Definitely the public IPv4 address.

**Comment by doginpants** [comment]
If you have a IRC or email you like I would like to share all the info with you as it maybe can help and I would really like to get this working. and it was always the public ipv4

**Comment by cpu** [comment]
> @cpu If you have a IRC or email

@doginpants Ok! `daniel <at> binaryparadox.net` for email. `ccppuu` on freenode for IRC. I'll be in/out today but can try and help more. 

When you have a chance to try another provider I'd be very interested in seeing those results as well.

> it was always the public ipv4

Darn :-( so much for that theory.

**Comment by doginpants** [comment]
@cpu I FOUND AN ERROR this could be it. the error occurs at wait for ssh again but there is a error not just the lack of connection. (connecting with rackspace now)
```
[admin@doginpants streisand]$ ./streisand

  S T R E I S A N D  

Which provider are you using?
  1. Amazon
  2. Azure
  3. DigitalOcean
  4. Google
  5. Linode
  6. Rackspace
: 6


 [WARNING]: Found both group and host with same name: localhost

What region should the server be located in?
  1. Chicago
  2. Dallas
  3. Hong Kong
  4. Northern Virginia
  5. Sydney
Please choose the number of your region. Press enter for default (#1) region.
 [1]: 4

What should the server be named? Press enter for default (streisand).
 [streisand]: 

What is your Rackspace username?
: doginpants


The following information can be found in the Rackspace Cloud Control Panel.
https://mycloud.rackspace.com/

What is your Rackspace API key?
:my key

Streisand will now set up your server. This process usually takes around ten minutes. Press Enter to begin setup...
: 

PLAY [Provision the Rackspace Server] ******************************************

TASK [Gathering Facts] *********************************************************
ok: [localhost]

TASK [genesis-rackspace : Create the server] ***********************************
changed: [localhost]

TASK [genesis-rackspace : Wait until the server has finished booting and OpenSSH is accepting connections] ***
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: socket.error: [Errno 104] Connection reset by peer
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_lwlFg3/ansible_module_wait_for.py\", line 585, in <module>\n    main()\n  File \"/tmp/ansible_lwlFg3/ansible_module_wait_for.py\", line 525, in main\n    response = s.recv(1024)\nsocket.error: [Errno 104] Connection reset by peer\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/home/admin/streisand/playbooks/rackspace.retry

PLAY RECAP *********************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   


```

**Comment by cpu** [comment]
> [Errno 104] Connection reset by peer

@doginpants interesting data point! That seems like it may add some weight to the theory that your SSH connections are being disrupted between Streisand/Ansible and the provider. 

Can you share your `~/.ssh/id_rsa.pub` file from the machine you're running Streisand on? Make double sure before you share that the file ends in `.pub` and isn't the **private key**. I'd like to add your SSH public key to one of my own servers to see if you can SSH to that as an experiment (if you're willing!).

**Comment by doginpants** [comment]
Sure thing
cant upload .pub here is the text unless you want it in a different way
[id_rsa (copy).zip](https://github.com/jlund/streisand/files/1062483/id_rsa.copy.zip)

**Comment by doginpants** [comment]
Welp still dont know what was wrong but I recloned streisand and set timeout for ssh to 2000 and error seemed to dissapear. I would still like to figure out what was wrong but seems to be finishing up the install just fine I will tell you if it works

**Comment by doginpants** [comment]
@cpu thanks for all the help got it up and running smooth!

**Comment by cpu** [comment]
@doginpants Great! I'm super happy to hear that!

**Comment by lihuibng** [comment]
The same issue happened to me

**Comment by cpu** [comment]
@lihuibng Please open a new issue & answer the template help questions. It's easier to coordinate in a separate issue and without the template questions being answered there isn't enough information to help you. Thanks!

**Comment by armandvedel** [comment]
I had the same issue but resolved it by switching my AWS server region
