### ISSUE TITLE
Timeout when waiting for 188.166.....

### ISSUE THREAD

**Issue by Bafrianboy** [jlund/streisand#732]
I have a  problem while instaling steisand

each time i got this , can you help please

![untitled](https://user-images.githubusercontent.com/11059376/26935677-dc7e170a-4c6c-11e7-9b66-1eb6ec90fc69.png)

**Comment by cpu** [comment]
@Bafrianboy - This is a Digital Ocean machine, yes? Can you SSH to it and as `root` share the output from:
1. `systemctl status shadowsocks-libev`
2. `cat /etc/shadowsocks-libev/config.json | grep "server"`

Is it safe to assume you're running the latest code from master without any modifications?

**Comment by Bafrianboy** [comment]
Yes this is Digital Ocean machine and i didn't modify any line of code (running the last code)

Here is what i get 

![1](https://user-images.githubusercontent.com/11059376/26936238-6162dad6-4c6e-11e7-8805-84ac6e2129a3.png)

**Comment by cpu** [comment]
@Bafrianboy Thanks for that information. Can you also share the output from `ip addr` on the server?

**Comment by Bafrianboy** [comment]
![1](https://user-images.githubusercontent.com/11059376/26936525-3dafc648-4c6f-11e7-9d24-10e501ee0525.png)

**Comment by cpu** [comment]
@Bafrianboy Was this a Digital Ocean droplet you created yourself, or one that was created by `./streisand` and choosing "Digital Ocean" from the list of improvisers? It was totally brand new?

I'm slightly confused. Your initial screenshots showed the Streisand server IP as `188.166.144.8`, and a failure to connect to the Shadowsocks service on that IP. Your Shadowsocks config is listening on `178.62.95.54:8530` which, is a different IP explaining the connection failure. Your screenshots of `ip addr` shows that `eth0` has the same IP as your Shadowsocks config, different than the IP from the initial screenshots.

Where did the `188.166.144.8` IP from the first screenshots come from? When I create a new droplet the IP that Streisand uses for everything matches the IP on `eth0`.

**Comment by Bafrianboy** [comment]
i will right the steps for what i did to make it clear :
1 -  i created the droplet within Digital Ocean 
2-  i logged in the server using SSH 
3 -  i followed the steps to how to install streisand (from Github)
  within this step o followed the tutorial (
     the pre-request for git , etc
      1-   git clone https://github.com/jlund/streisand.git && cd streisand
       2- ./streisand
   then 
     followed the prompt to choose your provider , etc

after the installation started 3 or 4 mins i got the massage i sent fist 
  ) 

That's All

**Comment by cpu** [comment]
@Bafrianboy You are describing a provisioning mode that Streisand doesn't officially support right now. The intention of Streisand is closer to:
1. Clone the Streisand repo to **your client computer** (e.g. your laptop, home PC)
2. Install the required dependencies (pip, Ansible, etc)
3. Run `./streisand` **on your client computer**
4. Choose Digital Ocean and enter your API key
5. A brand new Droplet is created **by Streisand** and the Streisand software is installed to it.

There is an open PR ( https://github.com/jlund/streisand/pull/724 ) to add support for provisioning existing servers or the localhost but this feature but it isn't merged yet.

Right now it sounds like you are deploying Streisand from one Droplet to another Droplet. This should work, but unfortunately it's sufficiently far from the supported use cases that I won't be able to help you troubleshoot it.

I recommend that you follow the README instructions for running Streisand from a Linux/OSX computer to create/deploy to Digital Ocean or wait until #724 is merged.

Thanks!
