### ISSUE TITLE
Can't access some sites from AWS instance.

### ISSUE THREAD

**Issue by keyboardbanger** [jlund/streisand#736]
### Expected behavior:
I have a PfSense firewall configured as an OpenVPN client to my Streisand AWS instance.  All outbound traffic is routed through this VPN.

### Actual Behavior:
Recently noticed when trying to access https://discussions.apple.com, I get an 'Access Denied' message saying 'You don't have permission to access "http://discussions.apple.com/" on this server.'  Within the last week, I noticed my Apple News App stopped updating and wouldn't display any new articles.  My iCloud Photos also stopped syncing between all my devices.

### Steps to Reproduce:
1. On my firewall, I created a rule to force any traffic from my LAN to 'discussions.apple.com' over my WAN gateway, not the VPN, and it worked.
2. I ran a packet capture while using the Apple News app.  I was able to identify the IP the app was trying to connect to.  I added that to my 'Bypass VPN' rule and the News app started working again.  Did the same with iCloud Photos sync and that works as long as it's not going through the VPN.

I'm wondering if anyone else has experienced anything like this or if anyone has any advice to workaround this without bypassing the VPN.  It could be that Apple is doing DPI and blocking VPN's, though it's not all Apple sites/services.  Apple could be blocking AWS IP's, again it's not all Apple sites.  Or maybe they started blocking port 636.

**Comment by cpu** [comment]
Hi @keyboardbanger,

> I'm wondering if anyone else has experienced anything like this

Yes, there was a similar report in https://github.com/jlund/streisand/issues/572 regarding Ticketmaster & Stubhub.

>  It could be that Apple is doing DPI and blocking VPN's.

I don't think that's the case. There's no OpenVPN traffic to apply DPI to between your AWS node and Apple.

> Apple could be blocking AWS IP's

This is likely the case. I'd recommend trying to deploy a new Streisand instance to a different provider (linode, digital ocean, etc) and testing to see if you can access the blocked site through an OpenVPN connection to the new Streisand server.

> Or maybe they started blocking port 636.

Again this port is between your client & the Streisand instance not the Streisand AWS node & Apple, so unlikely to be the case.

Like #572 I'm afraid I'm going to close this issue - there's nothing to do on the Streisand side. I'd recommend trying to contact Apple to let them know how their administrative decision has impacted your privacy.

Thanks!
