### ISSUE TITLE
Support `simple-obfs` for Streisand shadowsocks-libev service

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#741]
[One observation](https://github.com/jlund/streisand/issues/501#issuecomment-308970827) from the longer discussion in https://github.com/jlund/streisand/issues/501 is that using `simple-obfs` with the existing `shadowsocks-libev` service in Streisand can improve conditions for users relying on SS from a censored network:

> With shadowsocks without simple-obfs, the latency increases to 290-300 ms while I browse the internet.
> 
> With shadowsocksR having obfs configured, the latency increases to 250-270 ms.
> 
> However, with SS simple obfs, I am writing this comment now and browsing for almost 30 minutes while my latency is back to 204-208 ms.

It would be interesting to evaluate how we could integrate `simple-obfs` support into the existing `shadowsocks-libev` service.

**Comment by denoza** [comment]
1. In my opinion, the simplest way is to install `simple-obfs` plugin while the `shadowsocks-libev` installation task is carried out.

2. The `simple-obfs` plugin can be enabled by default on the server side (in the server config JSON). As even if the client doesn't wish to have obfs feature, he/she has a choice to enable/disable it on his/her side. In my experience, it doesn't matter if I don't enable it on the client side, I am still able to use SS without it, however on the server side I have enabled it by default.

3. Addition of a couple of lines in the documentation section of shadowsocks, mentioning to add couple of flags on client config JSON and restarting the shadowsocks service.

**Comment by ortonomy** [comment]
I'd be happy to try this out and let you know how it goes, but I can't find any client-side settings in Shadowsocks-NG for Mac.

On iOS I'm using Shadowrocket which has the option for ``http`` or ``tls``.

As I have a pretty stable Streisand server already spun up on Digital Ocean using the latest version with AEAD, I'm in a pretty good place to A/B/C/... with different configs.

**Comment by denoza** [comment]
> I'd be happy to try this out and let you know how it goes, but I can't find any client-side settings in Shadowsocks-NG for Mac.

@ortonomy Any success with Shadowsocks-NG for Mac? Since 'simple-obfs' is now part of master, it would be good to know about your experience while using it on Mac and iOS.

**Comment by ortonomy** [comment]
I'm sorry, I didn't see that you've added a PR / merge. I'll roll a new server and let you know.

**Comment by cpu** [comment]
Closing this now that https://github.com/jlund/streisand/issues/743 is merged. We can continue to talk here about compatibility if appropriate. Just want to make sure it's marked "done" :-)

Thanks!

**Comment by baimafeima** [comment]
@cpu Is simple-obfs automatically installed on the server or do I need to do something in addition? Would I be able to make use of it when using the regular shadowsocks client on my Android phone or the shadowsocks-qt client on a Linux-based distro?

**Comment by cpu** [comment]
> @cpu Is simple-obfs automatically installed on the server or do I need to do something in addition? 

@baimafeima It's automatically installed when shadowsocks is enabled.

> Would I be able to make use of it when using the regular shadowsocks client on my Android phone or the shadowsocks-qt client on a Linux-based distro?

I don't know about shadowsocks-qt but it does work with the Android shadowsocks client once you've installed a separate plugin: https://play.google.com/store/apps/details?id=com.github.shadowsocks.plugin.obfs_local

**Comment by ortonomy** [comment]
@cpu -- don't you have to explicitly update the configuration to _turn on_ ``simpleobfs``?

**Comment by cpu** [comment]
> @cpu -- simpleobfs comes installed, but from what I can tell you have to explicitly update the configuration to turn on simpleobfs?

@ortonomy Nothing needs to be changed on the server. On the **client** you do need to enable `simpleobfs` in the `shadowsocks-android` profile you're using after installing the simpleobfs Android plugin.
