### ISSUE TITLE
Custom SSH port for Existing server

### ISSUE THREAD

**Issue by hybtoy** [jlund/streisand#742]
Good day, 

I am using different from 22 port for SSH. When I am choosing option to install streisand on existing server, it fails to install. 

Is it possible to add option to set the port of ssh connection?

**Comment by cpu** [comment]
@hybtoy This isn't officially supported at present. You might find [this workaround from @jlund](https://github.com/jlund/streisand/issues/96#issuecomment-65343979) useful.

In the meantime I'm going to close this issue - we can't support this use-case right now.
