### ISSUE TITLE
how to upgrade those services after I deployed onto my VPS?

### ISSUE THREAD

**Issue by walkerwzy** [jlund/streisand#747]
I got a connection issue suddenly (which mean it works fine before at least for 1 year): 
```
sudo openconnect --cafile PATH-TO-MY/ca-cert.pem --certificate PATH-TO-MY/client.p12 --key-password 'Web-petrifications' --pfs xx.xx.xx.xx:4443
POST https://xx.xx.xx.xx:4443/
Failed to connect to xx.xx.xx.xx:4443: Invalid argument
Failed to connect to host xx.xx.xx.xx
打开到 xx.xx.xx.xx 的 HTTPS 连接失败
Failed to obtain WebVPN cookie
```

and I found a similar  [issue](https://github.com/jlund/streisand/issues/274), it metions to upgrade streisand and the open connect to the latest code. 

I have `brew upgrade openconnect` my openconnect, not work, so how to upgrade the server?

**Comment by cpu** [comment]
@walkerwzy At present Streisand doesn't really support "upgrading" an existing server beyond security updates that are auto-installed. I recommend that you provision a new Streisand instance using the latest code from master and transition to it. I understand that's not a great solution from a usability perspective but unfortunately we don't have a better option at present.

Alternatively you can try and manually update the Streisand instance but at that point you aren't using the Streisand playbooks and we can't support you.

Apologies - I hope we can move towards a better solution for long term server management in the future.
