### ISSUE TITLE
Add `pip install pycurl` to getting started instructions

### ISSUE THREAD

**Issue by clairity** [jlund/streisand#756]
### Expected behavior:
streisand installs smoothly using `./streisand`

### Actual Behavior:
streisand gave me this error instead: 
```
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "pycurl required for this module"}
```

i would just suggest adding a quick line in the getting started guide about installing pycurl for those of us who are not regular python users. thanks!

##### *Target Cloud Provider:*
linode
##### *Operating System of target host:*
ubuntu 16.04 lts
##### *Operating System of client:*
os x 10.12
##### *Version of Ansible, using `ansible --version` :*
ansible 2.3.1.0

**Comment by clairity** [comment]
oh my goodness, i see that it's already in the instructions. i could have sworn i executed all the commands in order but i guess i missed that one.

**Comment by GPX-NSlog** [comment]
how to solve it ?

**Comment by clairity** [comment]
run `pip install pycurl` (it's in the instructions but i somehow missed it the first time around).

**Comment by kylebrowning** [comment]
that command fail's to run.

```Command "/usr/bin/python -u -c "import setuptools, tokenize;__file__='/private/var/folders/7l/k7scybm57yq29h76_rh70h100000gn/T/pip-build-Xyw87u/pycurl/setup.py';f=getattr(tokenize, 'open', open)(__file__);code=f.read().replace('\r\n', '\n');f.close();exec(compile(code, __file__, 'exec'))" install --record /var/folders/7l/k7scybm57yq29h76_rh70h100000gn/T/pip-9aW1Lg-record/install-record.txt --single-version-externally-managed --compile" failed with error code 1 in /private/var/folders/7l/k7scybm57yq29h76_rh70h100000gn/T/pip-build-Xyw87u/pycurl/
```

**Comment by kylebrowning** [comment]
I had to use `--user` to fix it.

**Comment by cpu** [comment]
Anyone having difficulty with the OSX setup instructions should open a new issue answering the questions in the new issue template. Thanks!

I'm going to lock this issue for future discussion since it was specifically about a missing instruction in the README that wasn't missing and I'd like to encourage discussion about separate problems to be handled in a separate issue.
