### ISSUE TITLE
Access gateway via SSL

### ISSUE THREAD

**Issue by guillaumededrie** [jlund/streisand#76]
Hi,
I've tested this role on a brand new server (Debian 7) but not using Amazon EC2/DigitalOcean/… When I try to reach the gateway via SSL (to access the htpasswd id/password window), the server does not respond …

Removing 127.0.0.1 on https://github.com/jlund/streisand/blob/master/playbooks/roles/streisand-gateway/templates/vhost.j2#L3 and restarting nginx, the gateway is now reachable.

I was wandering if I needed to restart the server instead of removing the localhost IP? Or something else?

Regards,
Guillaume

**Comment by cpu** [comment]
I think this issue is sufficiently old as to be closed - if you are able to reproduce the problem with a Ubuntu 16.04 server provisioned with the latest git master of Streisand please reopen with updated details. Thanks!
