### ISSUE TITLE
Update `shadowsocks-libev` to 3.0.7

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#765]
[shadowsocks-libev 3.0.7](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.7) was released:
* Refine manager mode 
* Fix a potential memory leak 

Streisand [is using 3.0.6](https://github.com/jlund/streisand/blob/4e736241b25ec9ee6437cb0d38e01ab2f7678bdf/playbooks/roles/shadowsocks/vars/main.yml#L22) and should be updated.

**Comment by denoza** [comment]
Since `shadowsocks-libev` is installed via git repository, therefore it is always the most recent version. I think changing the version number [here](https://github.com/jlund/streisand/blob/4e736241b25ec9ee6437cb0d38e01ab2f7678bdf/playbooks/roles/shadowsocks/vars/main.yml#L22) will solve the issue, right?

Also `shadowsocks_source_filename` and `shadowsocks_source_location` are stale, unless we decide to use the source code on [release page](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.7) for installation.

**Comment by cpu** [comment]
> Since shadowsocks-libev is installed via git repository, therefore it is always the most recent version.
@denoza That's not quite right - we do clone from git, but [its pinned to a specific tag](https://github.com/jlund/streisand/blob/d1336ca07863380d077680b85a480911e9509638/playbooks/roles/shadowsocks/tasks/main.yml#L19), so even when master changes Streisand won't automatically.

>  I think changing the version number here will solve the issue, right?

Yup! That will change the tag we clone from git to be the newest release.

> Also shadowsocks_source_filename and shadowsocks_source_location are stale, unless we decide to use the source code on release page for installation.

Good catch! These can be removed.

> Edit: I have added a branch, if you approve I will submit a PR. I am a little confused if we are still pursuing the git repository way or we will switch to release page.

https://github.com/denoza/streisand/commit/6f87d661659b806e47d6d97ff1c535fe661d661f looks great! If you submit a PR from this I will +1 it and merge. Thanks for doing that :-)

I'd prefer to keep things using the "git clone a specific tag" approach versus downloading a release .tar.gz for now.

**Comment by alimakki** [comment]
@denoza 

> I think changing the version number here will solve the issue, right?

As @cpu says, yes, but don't forget to update the SHA256 checksum :)

**Comment by cpu** [comment]
@alimakki Yes! Thanks for pointing out that omission :-) You definitely need to update the checksum too :laughing: :white_check_mark:

**Comment by denoza** [comment]
> denoza/streisand@6f87d66 looks great! If you submit a PR from this I will +1 it and merge. Thanks for doing that :-)

I have added the PR #770. 

> As @cpu says, yes, but don't forget to update the SHA256 checksum :)

@alimakki I am not sure how to verify/update SHA256 checksum here. The role of [`shadowsocks`](https://github.com/jlund/streisand/blob/d1336ca07863380d077680b85a480911e9509638/playbooks/roles/shadowsocks/tasks/main.yml) doesn't use checksum anywhere. Could you please guide me here?

Additionally, do you mean the `SHA1` checksum which can be seen by `git show-ref --tags`? [Releases page](https://github.com/shadowsocks/shadowsocks-libev/releases/tag/v3.0.7) doesn't mention any checksum. Do we calculate it manually, after downloading the zipped file? In that case why should we do it if we are not using that?

**Comment by cpu** [comment]
> @alimakki I am not sure how to verify/update SHA256 checksum here. The role of shadowsocks doesn't use checksum anywhere. Could you please guide me here?

Oops! You're right, I think both @alimakki and I were confused and were thinking about updating a shadowsocks client mirror, not the daemon. You're correct - there isn't a checksum to update here, we're relying on git to ensure consistency against network/download error. Apologies for creating confusion!

**Comment by alimakki** [comment]
my bad 😛
