### ISSUE TITLE
Host key verification failed.

### ISSUE THREAD

**Issue by sange-x** [jlund/streisand#773]
When I choose the "Existing Server", It doesn't work.   CentOS 7. 

Please enter the word 'streisand' to continue: streisand

Confirmed. Continuing
Host key verification failed.

How to fix it?

**Comment by cpu** [comment]
Hi @sange-x, sorry to hear you ran into trouble with the existing server provisioning support!

In the future can you please **answer all of the template questions**, particularly:
### Additional Details:
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
##### *Target Cloud Provider:*
##### *Operating System of target host:*
##### *Operating System of client:*
##### *Version of Ansible, using `ansible --version` :*

In particular it's not clear to me which machine is running CentOS 7. The server you're trying to provision? The machine you're running Streisand from?

> Confirmed. Continuing
> Host key verification failed.

This is likely from the [test SSH connection](https://github.com/jlund/streisand/blob/e76ba03e5218880a265b263a2f4cf024873be80f/streisand#L113:L115) the wrapper script makes before trying to provision the server. 

You must be able to run `ssh -i ~/.ssh/id_rsa "root@SERVER_IP" ` (replacing SERVER_IP) with your existing server's ip **without any errors** before you can run Streisand.

Can you verify that you are able to run that command?

_Note: The Streisand script explicitly mentions that existing server mode is an **advanced** feature. Our team is small enough that it's very hard to support users that choose to use this mode and aren't already experts at configuring SSH with key based authentication. If you're having trouble getting the test SSH command working I strongly encourage you to reconsider using this mode and try a supported provider (Linode, DigitalOcean, etc)._

**Comment by sange-x** [comment]
Thank you @cpu ! It works! I use the Amazon EC2. Everything is going well

**Comment by cpu** [comment]
Great - I will close this issue then. Glad to hear everything is working for you with EC2!!!
