### ISSUE TITLE
ArubaCloud Smart VPS: Install Interrupted and Incomplete after Rerun

### ISSUE THREAD

**Issue by aboanas93** [jlund/streisand#777]
### Expected behavior:
Full and complete installation on local server

#### 1st Run:
Installation halts when reaches installing TOR bridge part and exits with instruction to rerun using (IIRC, --limit) parameter.
#### 2nd Run: 
Installation goes through TOR bridge part but halts on Shadowsocks Ofsc installation part and exits with instruction to rerun using (--limit) parameter.
#### Further Runs:
 Same results except when deleting previously installed shadowsocks directory, and even after an apparent successful install, clients don't work with provided settings.

### Steps to Reproduce:
1. SSH into VM
2. Install (Python+Libraries , Git, Ansible)
3. Clone Repo and Enter Repo Directory
4. Run Streisand installation process

###### *: I can't provide the output because it's a sandbox and been re-purposed since then.

**Comment by cpu** [comment]
> *: I can't provide the output because it's a sandbox and been re-purposed since then.

@aboanas93 Without the full log output this isn't something anyone will likely be able to help you with.

As an aside the localhost provisioning mode is marked "advanced" and specifically mentions we aren't able to provide comprehensive support for users using this mode. Please consider using one of the supported providers if you are having difficulty. 

I will reopen this issue if you can provide the full logs with the observed errors as a Gist.

Thanks!
