### ISSUE TITLE
add webhook for docker?

### ISSUE THREAD

**Issue by gdoteof** [jlund/streisand#78]
Per https://github.com/gdoteof/docker-streisand/issues/2 it would be convenient if you would add a webhook for the docker image on this repo.  I will provide you with path/secret if you are willing.

**Comment by jlund** [comment]
@cpu asked me about this yesterday. I went sifting through old emails and couldn't find anything about the webhook. I apologize for getting distracted and not following up until now.

It looks like there's a fair amount of overlap between your up-to-date repo (nice!) and PR #442. Would you be interested in contributing to an official solution that we can include in the repository? I think that's the direction we should probably head towards, so I'm going to close this issue and consolidate the discussion there.

**Comment by gdoteof** [comment]
Hey I didn't realize people were still using my (now probably stale) docker repo until I got an issue today..  Maybe half a decade later we can set this up, unless there is an officially supported docker version I can point users to instead.  @jlund

**Comment by nopdotcom** [comment]
Aside from the perennial issue of "how do I get my SSH keys from one spot to another", we should be in pretty good shape to Dockerize if somebody wants it. The `utils/ubuntu-dependencies.sh` script does almost all of the work.
