### ISSUE TITLE
Failed to discover the Tor server fingerprint

### ISSUE THREAD

**Issue by DeepAQ** [jlund/streisand#780]
#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
```
TASK [tor-bridge : Discover the server fingerprint] ****************************
fatal: [xxx.xxx.xxx.xxx]: FAILED! => {"changed": true, "cmd": ["awk", "{ print $2 }", "/var/lib/tor/fingerprint"], "delta": "0:00:00.068089", "end": "2017-07-04 12:27:47.707887", "failed": true, "rc": 2, "start": "2017-07-04 12:27:47.639798", "stderr": "awk: fatal: cannot open file `/var/lib/tor/fingerprint' for reading (No such file or directory)", "stderr_lines": ["awk: fatal: cannot open file `/var/lib/tor/fingerprint' for reading (No such file or directory)"], "stdout": "", "stdout_lines": []}
```
##### *Version of Ansible, using `ansible --version` :* ansible 2.3.1.0 (Python 2.7.12)

However, after some time, the `/var/lib/tor/fingerprint` file can be found. Looks like the Tor service needs some time to generate the fingerprint.

**Comment by cpu** [comment]
Hi @DeepAQ, 

Thanks for reporting this. I have a fix out in https://github.com/jlund/streisand/pull/797 - Do you want to give it a shot and see if your problem persists?

**Comment by cpu** [comment]
I'm reasonably confident in this fix so I've merged it to master after a review. If it did not fix the problem for you please feel free to reopen this issue and I'll dig further. Thanks again!
