### ISSUE TITLE
Can't connect with L2tp in ios

### ISSUE THREAD

**Issue by bino7** [jlund/streisand#790]
Can't connect with L2tp in ios.

**Comment by cpu** [comment]
@bino7 Please fill out the new issue template, providing the information it requests. This is nowhere near enough information to be able to help! I'm going to close this issue for now. Please reopen or submit a new issue once you have all of the requested information.

Above & beyond what's in the issue template it would be worth knowing:
* Details about your iOS device & operating system version
* Any error messages you observe from the client side
