### ISSUE TITLE
missing_subjectAltName error loading Streisand gateway in Chrome

### ISSUE THREAD

**Issue by mmmooorrrttt** [jlund/streisand#793]
### Steps to Reproduce:
1. 

##### *Version of Ansible, using `ansible --version` :* ?

My apologies, but I've searched the web and asked for help on Reddit, and this is the only place left I can find to turn to. If there's somewhere else I should go to ask my question, then please direct me there.

I am not technically proficient -- I was hoping to follow the "cook book" to install and run, but I've encountered an error I cannot overcome (there were others).

Streisand seemed to install okay, but I when I try to log in, I get a privacy error. I downloaded the certificate, dragged it into Keychain, and changed the Get Info to "Always Trust." (notably, when I dragged in the certificate, Keychain did not ask whether I wanted to trust it as stated in the directions).

Curiously, I get the privacy error on Chrome. With Safari and Firefox, the access times out.

There were warnings when installing Pycurl about SSL:

 creating build/temp.macosx-10.12-intel-2.7/src
    cc -fno-strict-aliasing -fno-common -dynamic -arch x86_64 -arch i386 -g -Os -pipe -fno-common -fno-strict-aliasing -fwrapv -DENABLE_DTRACE -DMACOSX -DNDEBUG -Wall -Wstrict-prototypes -Wshorten-64-to-32 -DNDEBUG -g -fwrapv -Os -Wall -Wstrict-prototypes -DENABLE_DTRACE -arch x86_64 -arch i386 -pipe -DPYCURL_VERSION="7.43.0" -DHAVE_CURL_SSL=1 -I/System/Library/Frameworks/Python.framework/Versions/2.7/include/python2.7 -c src/docstrings.c -o build/temp.macosx-10.12-intel-2.7/src/docstrings.o
    In file included from src/docstrings.c:4:
    src/pycurl.h:190:5: warning: "libcurl was compiled with SSL support, but configure could not determine which "      "library was used; thus no SSL crypto locking callbacks will be set, which may "      "cause random crashes on SSL requests" [-W#warnings]
    #   warning \
        ^
    1 warning generated.

Is this the source of the problem?

Thank you for your time and consideration. 

UPDATE: I was able to access the certificate, as seen by the browser, using Safari, and found Avast was the name on the certificate! I turned off Avast, and I can access Streisand securely, but not on Chrome or Firefox. Notably, I have no extensions in Safari. In Chrome and Firefox I have these extension in common: Badger, uBlock, HTTPS everywhere. Firefox also has Blur and NoScript.

The error changed as well, now: [missing_subjectAltName]

Thoughts?

**Comment by cpu** [comment]
Hi @mmmooorrrttt

> UPDATE: I was able to access the certificate, as seen by the browser, using Safari, and found Avast was the name on the certificate! 

Your update makes a lot of sense! A number of AV products intercept HTTPS by performing a trusted Man-In-The-Middle attack and replacing the real certificate. It's a problematic design and the TLS/HTTPS security community is almost universally against the practice. I'm sorry it was causing you trouble! Very annoying!!!!

> I can access Streisand securely, but not on Chrome or Firefox. Notably, I have no extensions in Safari. In Chrome
> The error changed as well, now: [missing_subjectAltName]

I'm afraid this is a known issue. We don't add a "Subject Alternate Name (SAN)" to the certificates that Streisand generates. I have an open issue to fix that https://github.com/jlund/streisand/issues/641 - Apologies! I have part of a solution ready and need to find the time to finish it. I believe it's possible to ignore this error in Chrome in the meantime.

**Comment by cpu** [comment]
I've updated the title of this issue to reflect the problem you arrived at. I'm going to close it for now since #641 already exists to solve the problem. Thanks again for reporting! If you have any other questions or run into other errors please feel free to open a new issue.
