### ISSUE TITLE
Feature request: Add script function to destroy running cloud instances

### ISSUE THREAD

**Issue by andrewcockerham** [jlund/streisand#798]
I just want to suggest the feature of a simple part of the ./streisand script that would allow you to shut down running EC2 instances. I fired up a VPN, for a few days, but then stopped using it. At the end of the month I got a bill from AWS because I had left that instance running non-stop for the whole month, even when I wasn't using it. Would be great to 1) have a way to shut it down through the ./streisand script (rather than having to go to AWS console), and 2) even better would be a way for streisand to automatically shut down any running instances when I stop using the VPN on my mac. Don't know if that's possible?

**Comment by cpu** [comment]
Hi @andrewcockerham,

I updated the title of your feature request slightly. For many cloud providers stopping a created instance won't halt charges, the instance has to be outright destroyed.

>  2) even better would be a way for streisand to automatically shut down any running instances when I stop using the VPN on my mac. Don't know if that's possible?

I don't think this is likely to be feasible.

**Comment by andrewcockerham** [comment]
Thanks! I imagine #2 would only be feasible with a native Mac app

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/1.
