### ISSUE TITLE
Readme - install dependencies in virtual environment

### ISSUE THREAD

**Issue by krzysztofr** [jlund/streisand#8]
It is considered good practice to install any external python libraries in the virtual environment (using `virtualenv`, [docs here](http://docs.python-guide.org/en/latest/dev/virtualenvs/)), so you don't contaminate your system and have control over the different versions of libraries for different projects.
Such environment could be in any situation easily destroyed and recreated.

So, instead of, for example:
`sudo pip install boto`

You should create and activate virtual environment:

`sudo pip install virtualenv`
`virtualenv venv`
`source venv/bin/activate`

and install external dependencies locally, in the context of this environment:
`pip install boto`

Moreover, you can create list of all dependencies:
`pip freeze > requirements.txt`

...and then install them with one command:
`pip install -r requirements.txt`

If you find my comment useful I can modify Readme file or, if it is needed, provide more detailed explanation.

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/23
