### ISSUE TITLE
up issue #16 problem setup on debian

### ISSUE THREAD

**Issue by xila76** [jlund/streisand#80]
on debian 7 for me :

root@debian:~/streisand# ansible-playbook playbooks/streisand.yml

PLAY [Configure the Server and install required software] *********************

GATHERING FACTS ***************************************************************
fatal: [212.xx.XX.XXX] => SSH encountered an unknown error during the connection. We recommend you re-run the command using -vvvv, which will enable SSH debugging output to help diagnose the issue

TASK: [common | Set the streisand_ipv4_address variable to the value provided by a 'genesis' role if one is defined] ***
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
to retry, use: --limit @/root/streisand.retry

212.xx.XX.XXX : ok=0 changed=0 unreachable=1 failed=0

second try with -vvvv option : 
root@debian:~/streisand# ansible-playbook playbooks/streisand.yml -vvvv

PLAY [Configure the Server and install required software] *********************

GATHERING FACTS ***************************************************************
ESTABLISH CONNECTION FOR USER: root
REMOTE_MODULE setup
EXEC ['ssh', '-C', '-tt', '-vvv', '-o', 'ControlMaster=auto', '-o', 'ControlPersist=60s', '-o', 'ControlPath=/root/.ansible/cp/ansible-ssh-%h-%p-%r', '-o', 'KbdInteractiveAuthentication=no', '-o', 'PreferredAuthentications=gssapi-with-mic,gssapi-keyex,hostbased,publickey', '-o', 'PasswordAuthentication=no', '-o', 'ConnectTimeout=10', '212.xx.XX.XXX', "/bin/sh -c 'mkdir -p $HOME/.ansible/tmp/ansible-tmp-1406716440.77-157501025930687 && echo $HOME/.ansible/tmp/ansible-tmp-1406716440.77-157501025930687'"]
fatal: [212.xx.XX.XXX] => SSH encountered an unknown error. The output was:
OpenSSH_6.0p1 Debian-4+deb7u2, OpenSSL 1.0.1e 11 Feb 2013
debug1: Reading configuration data /etc/ssh/ssh_config
debug1: /etc/ssh/ssh_config line 19: Applying options for *
debug1: auto-mux: Trying existing master
debug1: Control socket "/root/.ansible/cp/ansible-ssh-212.xx.XX.XXX-22-root" does not exist
debug2: ssh_connect: needpriv 0
debug1: Connecting to 212.xx.XX.XXX [212.xx.XX.XXX] port 22.
debug2: fd 3 setting O_NONBLOCK
debug1: connect to address 212.xx.XX.XXX port 22: Connection timed out
ssh: connect to host 212.xx.XX.XXX port 22: Connection timed out

TASK: [common | Set the streisand_ipv4_address variable to the value provided by a 'genesis' role if one is defined] ***
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
to retry, use: --limit @/root/streisand.retry

212.xx.XX.XXX : ok=0 changed=0 unreachable=1 failed=0

any help will be appreciated :)

**Comment by cpu** [comment]
This issue is quite stale & Debian is no longer the base OS. I'm going to close this in preparation for centralizing the localhost provider support feature request into one master issue. Thanks!
