### ISSUE TITLE
Install error at TASK [gce-network : Create network]

### ISSUE THREAD

**Issue by markwyner** [jlund/streisand#805]
I can't seem to get past this issue. When I run the install (locally) I get through the first six tasks, then it stops for the error on the gce-network task. The error is `ImportError: No module named utils.display`.

### Expected behavior:
Installation process will complete.

### Actual Behavior:
Installation process is cancelled because of the gce-network error.

### Steps to Reproduce:
1. Run `./streisand`
2. Choose Google as provider
3. Choose 11 as zone
4. Key "enter" for default server name
5. Enter location of my streisand.json file
6. Key "enter" to begin install process

One interesting note. After step 2, a warning appears before step 3:
`[WARNING]: Found both group and host with same name: localhost`

Then after step 6, during the install process, the task "Register JSON file contents" returns:
`changed: [localhost]`

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
```
TASK [gce-network : Create network] **************************************************************************************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: ImportError: No module named utils.display
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/var/folders/mw/dy_2c7mn5cvcx10813llsr840000gn/T/ansible_VPsEQh/ansible_module_gce_net.py\", line 557, in <module>\n    from ansible.module_utils.gce import *\n  File \"/var/folders/mw/dy_2c7mn5cvcx10813llsr840000gn/T/ansible_VPsEQh/ansible_modlib.zip/ansible/module_utils/gce.py\", line 30, in <module>\n  File \"/var/folders/mw/dy_2c7mn5cvcx10813llsr840000gn/T/ansible_VPsEQh/ansible_modlib.zip/ansible/module_utils/gcp.py\", line 64, in <module>\nImportError: No module named utils.display\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
	to retry, use: --limit @/Users/markwyner/Documents/VPN/streisand/playbooks/google.retry

PLAY RECAP ***************************************************************************************************************************************************************************************************
localhost                  : ok=6    changed=1    unreachable=0    failed=1
```
#### *Version of Ansible, using `ansible --version` :* 2.3.10

When I check my version of Ansible I get the following returned:

```
ansible 2.3.1.0
  config file = /mypath/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.13 (default, Jul  7 2017, 17:40:26) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
I'm running Homebrew 1.2.4 and Python 2.7.10, my Google Cloud instance is brand new, and I just cloned the Streisand repo, so that's current. Perhaps is there an issue with ansible seeking that python version 2.7.13?

I have already referenced issues #584 and #629, but solutions there aren't fixing my issue. I understand a lot of this and use terminal for many daily workflows in development, but a lot of this server stuff is new to me.

I'd love any help anyone might have. Thanks in advance.

**Comment by alimakki** [comment]
@markwyner, Sorry to hear you're having issues! I attempted to follow the same steps as you have, as it turns out I was able to reproduce your issue locally, and did manage to find a temporary workaround.

Assuming that you have followed the instructions in the README and you've created the 
`~/Library/Python/2.7/lib/python/site-packages/homebrew.pth` file, go ahead and open it up in a text editor, and replace the contents with 
`/usr/local/Cellar/ansible/2.3.1.0/libexec/lib/python2.7/site-packages`

Once done you can source your bash profile (or close and re-open your terminal), then try running the Streisand script once more.

Let me know the results once done!

**Comment by markwyner** [comment]
`TASK [streisand-gateway : Success!]`

@alimakki, thank you so much! Super smooth transition after I made this change, and I'm up and running. Your time is greatly appreciated.

**Comment by alimakki** [comment]
@markwyner Glad to hear that you're up and running!
