### ISSUE TITLE
mirror: openvpn-latest-stable.tar.gz gpg signature validation fails - pubkey not found

### ISSUE THREAD

**Issue by caroseuk** [jlund/streisand#811]
Using this script today with Digital Ocean from my Mac and it is failing at the following task:

TASK [download-and-verify : Register GPG signiture verification results]

### Expected behavior:
OK Passed

### Actual Behavior:
```
TASK [download-and-verify : Register GPG signature verification results] ***********************************************
fatal: [188.166.147.195]: FAILED! => {"changed": true, "cmd": "for file in *.asc; do gpg --verify $file; done", "delta": "0:00:00.063374", "end": "2017-07-17 12:35:18.591376", "failed": true, "rc": 2, "start": "2017-07-17 12:35:18.528002", "stderr": "gpg: assuming signed data in `openvpn-install-latest-stable.exe'\ngpg: Signature made Wed Mar 22 16:51:46 2017 UTC using RSA key ID 40864578\ngpg: Can't check signature: public key not found\ngpg: assuming signed data in `openvpn-latest-stable.tar.gz'\ngpg: Signature made Wed Mar 22 15:35:16 2017 UTC using RSA key ID 40864578\ngpg: Can't check signature: public key not found", "stderr_lines": ["gpg: assuming signed data in `openvpn-install-latest-stable.exe'", "gpg: Signature made Wed Mar 22 16:51:46 2017 UTC using RSA key ID 40864578", "gpg: Can't check signature: public key not found", "gpg: assuming signed data in `openvpn-latest-stable.tar.gz'", "gpg: Signature made Wed Mar 22 15:35:16 2017 UTC using RSA key ID 40864578", "gpg: Can't check signature: public key not found"], "stdout": "", "stdout_lines": []}

TASK [streisand-mirror : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
```

### Steps to Reproduce:
1. Install all pre-reqs
2. Run script ./streisand and provide relevant Digital Ocean token and details

**Comment by cpu** [comment]
Hi @caroseuk - thanks for reporting. I noticed this on the weekend myself and didn't remember to open an issue.

> Using this script today with Digital Ocean from my Mac and it is failing at the following task:

To clarify: it shouldn't fail the overall Streisand setup. It will pause at the end of mirroring to warn that this particular signature validation failed but the overall setup should complete as expected.

(We of course should still fix this! I just wanted to make it clear that it shouldn't stop you from using Streisand in the meantime).

**Comment by caroseuk** [comment]
Apologies, you are correct, it didnt fail it paused and then continued 👍

**Comment by cpu** [comment]
No need to apologize :-) Happy to hear it didn't break!
