### ISSUE TITLE
Wireguard: can't browse after activating client 

### ISSUE THREAD

**Issue by ORARiccardo** [jlund/streisand#815]
Server is using ubuntu 16.04, on my device I'm running ubuntu 16.04 as well. The POSTUP works fine if I don't have dnsmasq installed: the resolv.conf includes 10.192.122.1 but I can't browse.

If I install dnsmasq, POSTUP fails, I need to manually add 10.192.122.1 to resolv.conf but I can't browse either.

What could be causing this issue here? How can I fix it? Thanks

### Expected behavior:
10.192.122.1 included in resolv.conf and possibility to connect to internet

### Actual Behavior:
if I don't have dnsmasq installed, the POSTUP works fine and in the resolv.conf there's 10.192.122.1 but I can't connect.
If I install dnsmasq, POSTUP fails, I need to manually add 10.192.122.1 to resolv.conf but I can't connect.

### Steps to Reproduce:
I installed streisand directly on the server and used the guidelines provided in the .html file to setup wireguard. LT2P works fine, tested both on iOS and Android.

##### *Version of Ansible, using `ansible --version` :* ansible 2.3.1.0

Thanks for your help!

**Comment by cpu** [comment]
@ORARiccardo Are you using `wg-quick` on your client machine to start the connection? Can you share the full output from that?

Can you also share the output from `sudo wg` on your client and the server?

**Comment by cpu** [comment]
Can you also provide the output from `dpkg -l wireguard-dkms` and `dpkg -l wireguard-tools` from **both** the client and server?

**Comment by ORARiccardo** [comment]
**Client machine wg-quick**
```
[#] ip link add wg0-client type wireguard
[#] wg setconf wg0-client /dev/fd/63
[#] ip address add 10.192.122.2/32 dev wg0-client
[#] ip link set mtu 65456 dev wg0-client
[#] ip link set wg0-client up
[#] wg set wg0-client fwmark 51820
[#] ip -4 route add 0.0.0.0/0 dev wg0-client table 51820
[#] ip -4 rule add not fwmark 51820 table 51820
[#] ip -4 rule add table main suppress_prefixlength 0
[#] echo nameserver 10.192.122.1 | resolvconf -a tun.wg0-client -m 0 -x
```

**Client machine sudo wg**
```
interface: wg0-client
  public key: tNSqAnqyGJrBhFGcGnjS5u1TPwaSIN6uLBVAmNj8220=
  private key: (hidden)
  listening port: 43076
  fwmark: 0xca6c

peer: 3Fso322njn3vCZ50gbDSuiQf57Q30ORF/DRnaUVWaz4=
  endpoint: 127.0.0.1:51820
  allowed ips: 0.0.0.0/0
  transfer: 0 B received, 3.04 KiB sent
```

**Server sudo wg**
```
interface: wg0-server
  public key: 3Fso322njn3vCZ50gbDSuiQf57Q30ORF/DRnaUVWaz4=
  private key: (hidden)
  listening port: 51820

peer: tNSqAnqyGJrBhFGcGnjS5u1TPwaSIN6uLBVAmNj8220=
  allowed ips: 10.192.122.2/32
```

**Server dpkg -l wireguard-dkms** 
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/ Name           Version      Architecture Description
+++-==============-============-============-=================================
ii  wireguard-dkms 0.0.20170706 all          fast, modern, secure kernel VPN t
```


**Server dpkg -l wireguard-tools** 
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/                Name           Version               Architecture              Description
+++-==============-============-============-=================================
ii          wireguard-tool 0.0.20170706              amd64        fast, modern, secure kernel VPN t
```

**Client machine dpkg -l wireguard-dkms** 
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/                 Name           Version              Architecture         Description
+++-==============-============-============-=================================
ii  wireguard-dkms            0.0.20170706              all          fast, modern, secure kernel VPN t
```

**Client machine dpkg -l wireguard-tools**
```
Desired=Unknown/Install/Remove/Purge/Hold
| Status=Not/Inst/Conf-files/Unpacked/halF-conf/Half-inst/trig-aWait/Trig-pend
|/ Err?=(none)/Reinst-required (Status,Err: uppercase=bad)
||/               Name           Version                 Architecture                Description
+++-==============-============-============-=================================
ii  wireguard-tool             0.0.20170706          amd64           fast, modern, secure kernel VPN t
```

**Comment by cpu** [comment]
Interesting. It seems like your wireguard connection isn't being established. The resolvconf update is a separate issue. I would have expected to see something about the last handshake in both the client and server `wg` output like:
>    latest handshake: 1 minute, 56 seconds ago

Can you share the output from `ufw status | grep 51820` on the server?

**Comment by ORARiccardo** [comment]
On the server
```
51820/udp                  ALLOW       Anywhere                  
51820/udp (v6)             ALLOW       Anywhere (v6)
```

I'm testing from my home network

**Comment by cpu** [comment]
@zx2c4 Are you able to take a peek at this thread? I'm coming up blank on what the root cause could be or further steps to diagnose.

**Comment by zx2c4** [comment]
Why is your endpoint 127.0.0.1? What's the actual endpoint line in your configuration file?

**Comment by ORARiccardo** [comment]
The endpoint line is:

`Endpoint = localhost:51820`

**Comment by zx2c4** [comment]
That is without a doubt the cause of the issue.

**Comment by cpu** [comment]
@ORARiccardo I'll follow up later today/tomorrow to try and determine how that got set incorrectly in your config, need to switch back to the dayjob.

**Comment by ORARiccardo** [comment]
@cpu @zx2c4 Thank you very much! localhost should be replaced by streisand server right?

**Comment by cpu** [comment]
> Thank you very much! localhost should be replaced by streisand server right?

@ORARiccardo Yes, `localhost` should be replaced by the IPv4 address of the Streisand digital ocean server.

**Comment by ORARiccardo** [comment]
Sorry guys, my bad, now I realized I misconfigured the streisand.yml file on the server while poking at other stuff, switched the server variable. Thanks for helping me to solve the issue!

**Comment by cpu** [comment]
@ORARiccardo Great! :tada: I'm glad to hear that the problem is resolved and that it wasn't a Streisand bug. Thanks for replying with the root cause, I really appreciate it.

**Comment by firepmi** [comment]
I got exactly same issue, but my issue is not solved by matching the endpoint.
what did I miss something else?
