### ISSUE TITLE
Installation fails on AWS with latest ubuntu 16.04 and python (2.7.12) 

### ISSUE THREAD

**Issue by indyaah** [jlund/streisand#818]
### Expected behavior:
Installation succeeds
### Actual Behavior:
Ansible fails "Generate the language selection markdown file" task
### Steps to Reproduce:
1. Checkout current master from GitHub (57d5219ca0730796618801e1e11938ca2630355b)
2. Start installation with AWS

##### *Version of Ansible, using `ansible --version`* : ansible 2.3.1.0  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

# Note:
Works fine after mass replacing 'streisand_languages.iteritems' with 'streisand_languages.items' in project.  I am not sure why python3 behaviour is creeping into installation but I double checked both my local and remote server has python2 as default python.

## Failure 
![screenshot from 2017-07-20 00-44-32](https://user-images.githubusercontent.com/1032931/28393171-b1831a5c-6ce5-11e7-8ddf-a7e9a1b6ef28.png)

# Files affected by mass search and replace
![screenshot from 2017-07-20 00-51-30](https://user-images.githubusercontent.com/1032931/28393172-b18325c4-6ce5-11e7-8b0c-d3effd2959ea.png)

**Comment by cpu** [comment]
@indyaah What does `python --version` output on the machine you're running Streisand from?

**Comment by indyaah** [comment]
@cpu : Hi Daniel, It is 2.7.12

I verified multiple times that I do not have any other python version in path. I do have python3 installed but that one is also stock installation from apt.

**Comment by cpu** [comment]
@indyaah Do you want to submit a PR with the replacements you made? I'd be interested in testing it on a few systems to see if its incompatible. I'm also puzzled how your system is using Python3.

**Comment by indyaah** [comment]
Sure. I will, once I am on personal machine. :)

PS : Just finished an installation using Macbook/macOS sierra successfully.

**Comment by alimakki** [comment]
@cpu, @indyaah, I tested locally by following the same steps that @indyaah undertook by mass-replacing `iteritems()` withs `items()`, and haven't run into any issues (in a vagrant run) on macOS Sierra.

**Comment by cpu** [comment]
@alimakki Do you think we should make this replacement across master?

**Comment by alimakki** [comment]
@cpu, I don't see why not. I don't mind doing a quick PR for this.

**Comment by alimakki** [comment]
Fixed in #855
