### ISSUE TITLE
[ASK] Install on OpenVZ

### ISSUE THREAD

**Issue by NanoG6** [jlund/streisand#821]
Sorry, not an issue, just curious is there any workaround for installing streisand on OpenVZ VPS?
Thank you

**Comment by chipitsine** [comment]
OpenVZ does not allow creation of network interfaces (because it requires loading kernel modules)
so, OpenVZ is not a proper solution for vpn gateway (even, you seem to have root rights)

I think, we should add a check "are we running inside OpenVZ container" and stop deploying with proper error message

**Comment by NanoG6** [comment]
> I think, we should add a check "are we running inside OpenVZ container" and stop deploying with proper error message

Yeah I agree on this one. Or modular services that will install only vpn services that work with OpenVZ, like OpenVPN, ipsec, etc

**Comment by chipitsine** [comment]
OpenVPN requires "tap" (or "tun") kernel module.

**Comment by NanoG6** [comment]
Sure, many OpenVZ VPS provider have tun/tap enabled (or can be easily enabled in VPS control panel) :)

**Comment by cpu** [comment]
> I think, we should add a check "are we running inside OpenVZ container" and stop deploying with proper error message

PR welcome!

> Or modular services that will install only vpn services that work with OpenVZ, like OpenVPN, ipsec, etc

I think this is the best approach to a workaround for motivated users to deploy to OpenVZ. Please follow https://github.com/jlund/streisand/issues/746 for this work.

I'm going to close this issue since I think you have the information you were after. Thanks!
