### ISSUE TITLE
`tor` is not starting correctly

### ISSUE THREAD

**Issue by zoof** [jlund/streisand#825]
### Expected behavior:
`tor` should be running
### Actual Behavior:
after reboot, `tor` is not running
### Steps to Reproduce:
1. reboot

### Additional Details:

`tor.service` is active but `tor@default.service` is not. Manually starting it does not work.

    $ sudo journalctl -xe
    sudo: unable to resolve host streisand2
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit tor@default.service has failed.
    -- 
    -- The result is failed.
    Jul 21 12:57:51 streisand2 systemd[1]: tor@default.service: Unit entered failed state.
    Jul 21 12:57:51 streisand2 systemd[1]: tor@default.service: Failed with result 'exit-code'.
    Jul 21 12:57:51 streisand2 systemd[1]: tor@default.service: Service hold-off time over, scheduling restart.
    Jul 21 12:57:51 streisand2 systemd[1]: Stopped Anonymizing overlay network for TCP.
    -- Subject: Unit tor@default.service has finished shutting down
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit tor@default.service has finished shutting down.
    Jul 21 12:57:51 streisand2 systemd[1]: tor@default.service: Start request repeated too quickly.
    Jul 21 12:57:51 streisand2 systemd[1]: Failed to start Anonymizing overlay network for TCP.
    -- Subject: Unit tor@default.service has failed
    -- Defined-By: systemd
    -- Support: http://lists.freedesktop.org/mailman/listinfo/systemd-devel
    -- 
    -- Unit tor@default.service has failed.
    -- 
    -- The result is failed.
    Jul 21 12:58:01 streisand2 ocserv[3410]: worker:  tlslib.c:475: no certificate was found
    Jul 21 12:58:01 streisand2 ocserv[1738]: sec-mod: session open but with non-existing SID!
    Jul 21 12:58:01 streisand2 ocserv[1732]: main: 71.121.238.183:51294 could not open session
    Jul 21 12:58:01 streisand2 ocserv[1732]: main: 71.121.238.183:51294 failed authentication attempt for user ''
    Jul 21 12:58:01 streisand2 ocserv[3410]: worker: 71.121.238.183 failed cookie authentication attempt
    Jul 21 12:58:01 streisand2 ocserv[1732]: main: 71.121.238.183:51294 user disconnected (reason: unspecified, rx: 0, tx:
    Jul 21 12:58:18 streisand2 sudo[3413]: xxxx : unable to resolve host streisand2
    Jul 21 12:58:18 streisand2 sudo[3413]: xxxx : TTY=pts/0 ; PWD=/home/xxxx ; USER=root ; COMMAND=/bin/jo
    Jul 21 12:58:18 streisand2 sudo[3413]: pam_unix(sudo:session): session opened for user root by xxxx(uid=0)

##### *Target Cloud Provider:*
GCE
##### *Operating System of target host:*
Ubuntu 16.04 -- this instance has been running for at least a month.

**Comment by cpu** [comment]
@zoof What version of tor is installed? can you share `tor --version`? Can you verify that you have a `/etc/apparmor.d/local/system_tor` file present on the system?

**Comment by zoof** [comment]
$ tor --version
    Tor version 0.3.0.9 (git-100816d92ab5664d).
    $ cat /etc/apparmor.d/local/system_tor
    # Site-specific additions and overrides for system_tor.
    # For more details, please see /etc/apparmor.d/local/README.

**Comment by cpu** [comment]
Hi @zoof,

That version of Tor has an apparmor problem that we've been working around in master with https://github.com/jlund/streisand/commit/975e2cf95376f4ca92a22df5426bc13c92d010be It looks like your server was provisioned before this change landed and so you are missing the workaround. I suspect this is the problem.

You can fix it by reprovisioning a fresh server from master, or by manually adding the following line to the `/etc/apparmor.d/local/system_tor` file and restarting tor:
> capability dac_read_search,

_(Note: The trailing `,` is not a mistake and is required)_

Can you try that and confirm that tor starts successfully? If so I will close this issue. Thanks!

**Comment by zoof** [comment]
Yes, working again.  Thank you!
