### ISSUE TITLE
Vimeo Blocking Me While Using Streisand

### ISSUE THREAD

**Issue by markwyner** [jlund/streisand#833]
Hey, all.

While using Streisand Vimeo blocks me. The warning screen returns a no-robot captcha, then upon checking the box it returns a loading message about the servers needing to update to let me back in. But that doesn't seem to ever flip.

Does anyone know why Vimeo may not like my connection? I'm not using my setup with anyone else, and this happened the first time I tried to access Vimeo. I have been using it for about a week and all other sites are loading fine. This is the first time I have seen a block.

I would love any insights.

Thanks much in advance.

![vimeo-block](https://user-images.githubusercontent.com/737330/28597747-878a81d6-7154-11e7-821d-997e87729b07.png)

### Expected behavior:
When I visit vimeo.com, the website is accessible.

### Actual Behavior:
When I visit vimeo.com, the website is inaccessible.

### Steps to Reproduce:
1. Connect to Streisand.
2. Choose any web browser and visit vimeo.com.

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
n/a

##### *Target Cloud Provider:*
Google

##### *Operating System of target host:*
Default VPN server setup

##### *Operating System of client:*
macOS 10.12.5

##### *Version of Ansible, using `ansible --version` :*
2.3.1.0

**Comment by alimakki** [comment]
Hi @markwyner,

I don't think it's Streisand at fault here, my guess is that most likely the GCE IP addresses have been blacklisted by Vimeo.

You can try contacting them and asking for your address to be whitelisted, that may yield some results.

**Comment by cpu** [comment]
I'm going to close this issue since only Vimeo is in a position to comment on why this block is happening. Thanks!
