### ISSUE TITLE
openvpn : One or more of the VPN clients could not be mirrored of commit 251a7e1

### ISSUE THREAD

**Issue by rayhu** [jlund/streisand#836]
The latest clone today. 

~/streisand$ git rev-parse HEAD
251a7e1c8b3f59c933b5d7378490447a3e717388

Already have Ali's commit of #812 fix.

commit 57d5219ca0730796618801e1e11938ca2630355b
Author: Ali Makki <alimakki@gmail.com>
Date:   Tue Jul 18 19:33:12 2017 -0400

Choose US West, wait until the error message appear.

TASK [download-and-verify : Download the OpenVPN Community files and signatures] *******************************************
changed: [13.64.150.30] => (item=https://build.openvpn.net/downloads/releases/latest/openvpn-latest-stable.tar.gz)
changed: [13.64.150.30] => (item=https://build.openvpn.net/downloads/releases/latest/openvpn-latest-stable.tar.gz.asc)
changed: [13.64.150.30] => (item=https://build.openvpn.net/downloads/releases/latest/openvpn-install-latest-stable.exe)
changed: [13.64.150.30] => (item=https://build.openvpn.net/downloads/releases/latest/openvpn-install-latest-stable.exe.asc)

TASK [download-and-verify : If necessary, rename signature files to match the GPG default of '.asc'] ***********************
skipping: [13.64.150.30]

**TASK [download-and-verify : Register GPG signature verification results] ***************************************************
**fatal: [13.64.150.30]: FAILED! => {"changed": true, "cmd": "for file in *.asc; do gpg --verify $file; done", "delta": "0:00:00.128485", "end": "2017-07-26 10:01:55.114528", "failed": true, "rc": 2, "start": "2017-07-26 10:01:54.986043", "stderr": "gpg: assuming signed data in `openvpn-install-latest-stable.exe'\ngpg: Signature made Fri 14 Jul 2017 01:28:49 PM UTC using RSA key ID 8CC2B034\ngpg: Can't check signature: public key not found\ngpg: assuming signed data in `openvpn-latest-stable.tar.gz'\ngpg: Signature made Wed 21 Jun 2017 10:19:19 AM UTC using RSA key ID 8CC2B034\ngpg: Can't check signature: public key not found", "stderr_lines": ["gpg: assuming signed data in `openvpn-install-latest-stable.exe'", "gpg: Signature made Fri 14 Jul 2017 01:28:49 PM UTC using RSA key ID 8CC2B034", "gpg: Can't check signature: public key not found", "gpg: assuming signed data in `openvpn-latest-stable.tar.gz'", "gpg: Signature made Wed 21 Jun 2017 10:19:19 AM UTC using RSA key ID 8CC2B034", "gpg: Can't check signature: public key not found"], "stdout": "", "stdout_lines": []}****

TASK [openvpn : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***

**Comment by alimakki** [comment]
Hi @rayhu, sorry to hear your having problems.

In any case, I've set up a PR that addresses this: #835.

**Comment by alimakki** [comment]
@rayhu, #835 has been merged to master.

Let us know if you have any issues :)
