### ISSUE TITLE
Add `--failover` to nginx for shadowsocks simple-obfs plugin

### ISSUE THREAD

**Issue by cpu** [jlund/streisand#843]
Presently Streisand configures the simple-obfs Shadowsocks plugin [without --failover](https://github.com/jlund/streisand/blob/2bd2a007dc6230685b1117527037f49c2dbe606b/playbooks/roles/shadowsocks/defaults/main.yml#L12). We should consider using the `--failover` option to route non-Shadowsocks requests to the NGINX instance that is already running. This has the advantage of better masking the purpose of the port. See: https://github.com/shadowsocks/simple-obfs/issues/81

**Comment by denoza** [comment]
@cpu I have created a PR #910 to solve this issue. Your review will be highly appreciated.

**Comment by cpu** [comment]
Closing this for now - using failover made simple-obfs mandatory and since support is spotty in shadowsocks clients we don't want to make obfuscation mandatory at this time.
