### ISSUE TITLE
Update French translation for the mobileconfig support that was added in #822

### ISSUE THREAD

**Issue by jlund** [jlund/streisand#849]
#822 added new functionality for iOS and OS X L2TP clients. We need to update the French documentation to reflect this.

**Comment by shelhezan** [comment]
I am currently writing the German documentation and will incorporate this issue as well.

@jlund While working on the translation stuff I wondered if you wanted the documentation to be formal or informal. I want to retain the original meaning as much as I can.

**Comment by alimakki** [comment]
Resolved in #852

**Comment by nopdotcom** [comment]
@shelhezan, I think any documentation is great; if you need a guide for tone, I would adopt Apple’s tone for instructions like these.

Microsoft uses a more informal style in American English now than Apple. I’m not sure what to think of it; I started parodying it ([single screen](https://www.nop.com/win10/)) and then decided it wasn’t so bad.

**Comment by shelhezan** [comment]
@nopdotcom Apple hasn't a standard. The German support documents are all written in an formal way, but settings in iOS or the page for the Apple ID is informal. At least this holds true for the German website and OSes.

In the German language it is quite important in which way you want to transport information to the addressee. If you do not know each other, it is common to stick to the _Sie_ and it can be seen as rude to use _du_ (see [here](https://en.wikipedia.org/wiki/T%E2%80%93V_distinction#German)). Most stuff in forums or group discussion on the internet is informal, so I woudld stick to an informal way in the instructions, but I wanted to check with @jlund how he wanted it to be. @alimakki stuck to a formal way when he translated the instructions. So did I.

But I agree completely with you, @nopdotcom. Any manual is better than none.
