### ISSUE TITLE
Add IKEv2 support with OpenSwan

### ISSUE THREAD

**Issue by FredericJacobs** [jlund/streisand#85]
iOS 8 has support for Always-On VPN but only with IKEv2: https://developer.apple.com/library/ios/featuredarticles/iPhoneConfigurationProfileRef/Introduction/Introduction.html#//apple_ref/doc/uid/TP40010206-CH1-SW612

**Comment by stevemcquaid** [comment]
+1 same with android. We I'd really like to be able to use always-on VPN :D

**Comment by cpu** [comment]
Closing in favour of https://github.com/jlund/streisand-discussions/issues/21
