### ISSUE TITLE
Streisand fails while generating the language selection markdown file

### ISSUE THREAD

**Issue by esimkowitz** [jlund/streisand#853]
### Expected behavior:
The task for generating the language selection markdown file would be fulfilled.

### Actual Behavior:
The task fails with the error:
```
TASK [common : Generate the language selection markdown file] ******************
fatal: [xx.xx.xx.xx]: FAILED! => {"changed": false, "failed": true, "msg": "AnsibleUndefinedVariable: 'dict object' has no attribute 'iteritems'"}
```

### Steps to Reproduce:
1. I had tried running the Google installation script and encountered the error #805. I used the solution @alimakki provided.
2. I then tried the Amazon installation script
3. I selected the N. Virginia data center with default VPC and Subnet
4. I let the script run until I encountered the error.

##### *Target Cloud Provider:*
Amazon
##### *Operating System of target host:*
Default
##### *Operating System of client:*
macOS 10.12.6
##### *Version of Ansible, using `ansible --version` :*
```
ansible 2.3.1.0
  config file = /Users/xxxxxx/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 3.6.2 (default, Jul 17 2017, 16:44:45) [GCC 4.2.1 Compatible Apple LLVM 8.1.0 (clang-802.0.42)]
```
##### *Output from `git rev-parse HEAD` in your Streisand directory :*
97ff28e7fd6f5ee596d5e6198111131f2fc4a8b5

**Comment by alimakki** [comment]
Hi @esimkowitz, thanks for opening the issue.

There was another user who faced a similar issue, see #818.

I'll be issuing a PR for this later today, but the quick fix is basically doing a search and replace for `streisand_languages.iteritems()` to `streisand_languages.items()`.
