### ISSUE TITLE
Wireguard user guide could be update

### ISSUE THREAD

**Issue by HougeLangley** [jlund/streisand#854]
This is just a suggestion. I have found Wireguard client could use systemctl startup when linux boot. The step 5 could be changed.

5. `sudo systemctl start wg-quick@wg0-client.service` . If active,  `sudo systemctl enable wg-quick@wg0-client.service`
6. So far every time booting Linux, your networking will be safe.

**Comment by cpu** [comment]
@HougeLangley Seems like an OK suggestion. Do you want to open a pull-request to adjust the english documentation?

**Comment by HougeLangley** [comment]
My English not good but I will try.

**Comment by cpu** [comment]
@HougeLangley Thanks! I'd be happy to help proofread :-)

**Comment by HougeLangley** [comment]
Dude, I could not push the changes.

remote: Permission to jlund/streisand.git denied to HougeLangley.
fatal: unable to access 'https://github.com/jlund/streisand.git/': The requested URL returned error: 403

**Comment by cpu** [comment]
@HougeLangley You need to fork the Streisand repository to your own account & push a branch there. You can open a pull request from your fork to the main project that way.

**Comment by HougeLangley** [comment]
OK, I just using first time. sorry.

**Comment by HougeLangley** [comment]
@cpu I think I could translate this project into Chinese (Simplified).

I was a translator who translate Full Circle Magazine into Chinese. I'll try my best to do this things.

**Comment by cpu** [comment]
I merged your proposed update to master and we can close this issue. Thanks!

@HougeLangley One of the other Streisand contributors, @nickolasclarke, opened https://github.com/jlund/streisand/issues/862 to start a Chinese translation. You two should talk more on #862, maybe you could collaborate and edit each other's work :-)

**Comment by nickolasclarke** [comment]
@HougeLangley would gladly accept you to proofread my work!

**Comment by HougeLangley** [comment]
@nickolasclarke You are so kind, I will try my best.
