### ISSUE TITLE
Shadowrocket removed from China App Store

### ISSUE THREAD

**Issue by pjrobertson** [jlund/streisand#856]
I don't yet have a solution for this, but it seems Apple has been forced to remove VPN apps from the China app store, so Chinese users are unable to download it.

Perhaps a short-term solution could be to note saying Shadowrocket is unavailable in the China App Store, and users should use a different App Store to download and install it.

Source (mentioning Shadowrocket explicitly): http://gbtimes.com/china/apple-removes-unauthorised-vpns-china-app-store

**Comment by cpu** [comment]
> Perhaps a short-term solution could be to note saying Shadowrocket is unavailable in the China App Store, and users should use a different App Store to download and install it.

@pjrobertson Seems like a sensible short-term change. Are you interested in submitting a PR to adjust the Shadowsocks iOS instructions?

**Comment by cpu** [comment]
@pjrobertson Is there an alternative client with AEAD ciphersuite support we should recommend on iOS that remains accessible?

**Comment by pjrobertson** [comment]
Sorry I didn't reply sooner. I actually have never used Shadowrocket and don't even have an iPhone so am not the best person to find the solution. I just saw the news about it being taken offline and thought I'd log it here for future reference.

**Comment by cpu** [comment]
@pjrobertson No problem! Thanks for sharing. I'm also not an iOS user and have to rely on the community for suggesting a replacement.

**Comment by cpu** [comment]
I think we can close this issue now that the docs have been updated to mention this restriction. I'm open to suggesting new iOS clients and anyone with ideas is free to open a PR. Thanks!
