### ISSUE TITLE
EC2 build error

### ISSUE THREAD

**Issue by HougeLangley** [jlund/streisand#857]
### Steps to Reproduce:
Follow your steps

#### *Log output from Ansible or other relevant services (link to Gist for longer output):*
PLAY [Provision the EC2 Server] ******************************************************************************************************************************

TASK [Gathering Facts] ***************************************************************************************************************************************
ok: [localhost]

TASK [Set the AWS Region fact] *******************************************************************************************************************************
ok: [localhost]

TASK [Set the AWS VPC ID fact] *******************************************************************************************************************************
ok: [localhost]

TASK [Set the AWS VPC Subnet ID fact] ************************************************************************************************************************
ok: [localhost]

TASK [ec2-security-group : Create the EC2 security group] ****************************************************************************************************
An exception occurred during task execution. To see the full traceback, use -vvv. The error was: <Response><Errors><Error><Code>AuthFailure</Code><Message>Authorization header or parameters are not formatted correctly.</Message></Error></Errors><RequestID>34cce02c-c913-4c59-8b75-034edb0661fc</RequestID></Response>
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "module_stderr": "Traceback (most recent call last):\n  File \"/tmp/ansible_0alZgI/ansible_module_ec2_group.py\", line 487, in <module>\n    main()\n  File \"/tmp/ansible_0alZgI/ansible_module_ec2_group.py\", line 283, in main\n    for curGroup in ec2.get_all_security_groups():\n  File \"/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py\", line 2984, in get_all_security_groups\n    [('item', SecurityGroup)], verb='POST')\n  File \"/usr/local/lib/python2.7/dist-packages/boto/connection.py\", line 1186, in get_list\n    raise self.ResponseError(response.status, response.reason, body)\nboto.exception.EC2ResponseError: EC2ResponseError: 401 Unauthorized\n<?xml version=\"1.0\" encoding=\"UTF-8\"?>\n<Response><Errors><Error><Code>AuthFailure</Code><Message>Authorization header or parameters are not formatted correctly.</Message></Error></Errors><RequestID>34cce02c-c913-4c59-8b75-034edb0661fc</RequestID></Response>\n", "module_stdout": "", "msg": "MODULE FAILURE", "rc": 1}
        to retry, use: --limit @/home/ubuntu/streisand/playbooks/amazon.retry

PLAY RECAP ***************************************************************************************************************************************************
localhost                  : ok=4    changed=0    unreachable=0    failed=1   

ubuntu@ip-172-31-20-109:~/streisand$ 

##### *Version of Ansible, using `ansible --version` : ansible 2.3.1.0
  config file = /home/ubuntu/streisand/ansible.cfg
  configured module search path = Default w/o overrides
  python version = 2.7.12 (default, Nov 19 2016, 06:48:10) [GCC 5.4.0 20160609]

**Comment by cpu** [comment]
> AuthFailureAuthorization header or parameters are not formatted correctly.34cce02c-c913-4c59-8b75-034edb0661fc

Can you double-check the way you're providing the AWS key ID & secret key in the initial Streisand provisioning prompts? It seems like this error is a result of an authentication failure to the AWS API.

**Comment by HougeLangley** [comment]
Thank you for your info. I will re-check.

**Comment by HougeLangley** [comment]
Thank you for your info. I will re-check.
