### ISSUE TITLE
SSL Certs differ

### ISSUE THREAD

**Issue by shelhezan** [jlund/streisand#859]
### Expected behavior:
The embedded SSL certificate in the generated HTML file should match with the SSL certificate the Streisand server uses when connecting to it.
### Actual Behavior:
The fingerprint of the downloaded SSL certificate in .crt format doesn't match the fingerprint the SSL server uses. Upon downloading the .crt, installing it in e.g. iOS  (i.e. installing via the profile procedure), the fingerprints doesn't match. The fingerprints printed in the instruction HTML file differ from the ones of the .crt file.
### Steps to Reproduce:
1. Set up a droplet on DigitalOcean.
2. Proceed to install Streisand with the localhost (advanced) method.
3. Compare the the embedded SSL certificate of the HTML file and its fingerprints with the ones nginx uses when connecting to the newly set up server.

**Comment by cpu** [comment]
Hi @shelhezan 

Can you share the certificate of your Streisand instance & the expected fingerprint?

**Comment by shelhezan** [comment]
Hi @cpu 

while typing the answer I had intended to write I figured that I made a mistake. I compared the fingerprint of the embedded certificate to the one which is given in the end of the HTML file. This is a misconception of me. This is a little dumb and doesn't make any sense anyhow. The certificate won't be tempered during the "download" out of the HTML file on my computer.

The embedded certificate is the certification authority which ensures that the certificate of the server is valid. I got it now! And thanks anyway for your quick response.

**Comment by cpu** [comment]
Hi @shelhezan 

Glad to hear you sorted it out! 

> Edit: But upon importing the embedded certificate into iOS, Safari throws a warning nonetheless saying it can't verify the server identity. This is strange indeed. Firefox on macOS is doing it fine.

I suspect this might be related to a known issue with the certificates that Streisand generates for the gateway HTTPS: https://github.com/jlund/streisand/issues/641

**Comment by shelhezan** [comment]
Hi @cpu 

my sub-issue is a duplicate of #641 indeed.
