### ISSUE TITLE
Shadowsocks android client download error

### ISSUE THREAD

**Issue by HougeLangley** [jlund/streisand#878]
### Steps to Reproduce:
1. 

#### *Log output from Ansible or other relevant services (link to Gist for longer output): 
TASK [shadowsocks : Mirror the Shadowsocks clients] ****************************
failed: [localhost] (item={u'url': u'https://github.com/shadowsocks/shadowsocks-android/releases/download/v4.2.2/shadowsocks-nightly-4.2.2.apk', u'checksum': u'0d15d2bce65f5c7b13a3c86e5d1bd98a216ffdf70460cd273d851d7da8d3f60c'}) => {"failed": true, "item": {"checksum": "0d15d2bce65f5c7b13a3c86e5d1bd98a216ffdf70460cd273d851d7da8d3f60c", "url": "https://github.com/shadowsocks/shadowsocks-android/releases/download/v4.2.2/shadowsocks-nightly-4.2.2.apk"}, "msg": "The checksum parameter has to be in format <algorithm>:<checksum>"}
changed: [localhost] => (item={u'url': u'https://github.com/shadowsocks/shadowsocks-windows/releases/download/4.0.4/Shadowsocks-4.0.4.zip', u'checksum': u'sha256:ead3fa2b98070760c43cc90ba170b75170a7576ba4f73b71969b21b4f245f25e'})
changed: [localhost] => (item={u'url': u'https://github.com/shadowsocks/ShadowsocksX-NG/releases/download/v1.5-beta.2/ShadowsocksX-NG.1.5-beta.2.zip', u'checksum': u'sha256:1d782b272c6ba8505e4791a286d0ac738cbf49c23e6f819e4735096340093d27'})
changed: [localhost] => (item={u'url': u'https://github.com/riobard/go-shadowsocks2/releases/download/v0.0.8/shadowsocks2-linux-x64.gz', u'checksum': u'sha256:02a87348d49c3d0680e8e6e86331ac9d1ef93ce27b8c7f814c88ec7ca65337f3'})

TASK [shadowsocks : One or more of the VPN clients could not be mirrored. Please file a bug report on GitHub so that the version number, checksum, or download location can be updated. Setup will now continue.] ***
Pausing for 20 seconds
(ctrl+C then 'C' = continue early, ctrl+C then 'A' = abort)
ok: [localhost]

**Comment by cpu** [comment]
Hi @HougeLangley,

Thanks for reporting! It looks like I broke this yesterday with https://github.com/jlund/streisand/pull/875. I have a fix out in #879. How embarassing! :blush:

**Comment by HougeLangley** [comment]
Hi @cpu . Thanks for this.
