### ISSUE TITLE
Ubuntu 14.04 obfproxy config with tor-bridge timeout issue

### ISSUE THREAD

**Issue by thundRRR** [jlund/streisand#88]
After running the ansible playbook with the args "ansible-playbook -i ../inventory -kK -s -vvvv -u midas streisand.yml", the playbook seems to run well with no issues, until it hits the task "tor-bridge | Wait until obfsproxy information has shown up in the state file". This times out. 

sshing into the server and running "obfsproxy managed" crashes with the error "pyptlib.config.EnvError: neither TOR_PT_{SERVER,CLIENT}_TRANSPORTS set"

System running playbook and system being configured are both 14.04. 

Quick fix? Or is this part of larger issues that are on the roadmap for later on?

EDIT: After reading issues, this is an inherent Ubuntu/Tor conflict. Waiting for support!

**Comment by jlund** [comment]
This has been completed as part of #174.
