### ISSUE TITLE
OpenConnect fails certificate verification

### ISSUE THREAD

**Issue by lettucehead** [jlund/streisand#884]
This appears after successful install and brew install openconnect:

Server certificate verify failed: certificate does not match hostname

**Comment by alimakki** [comment]
Hi @lettucehead,

does your error look something on the lines of this:

```
Certificate from VPN server "45.79.221.43" failed verification.
Reason: certificate does not match hostname
To trust this server in future, perhaps add this to your command line:
    --servercert sha256:cd30992c3127ebe8d2e0f680afc7995b76f13a337e93918fd3d79c7b7f0b2a01
Enter 'yes' to accept, 'no' to abort; anything else to view: yes
```

**Comment by cpu** [comment]
This issue is missing answers to all of the questions from the issue template. Given that @alimakki's question also hasn't been answered I'm going to close this issue since I don't think its actionable. Please feel free to reopen if you can provide more information. Thanks!
