### ISSUE TITLE
Getting "linode-python required for this module" although this is installed

### ISSUE THREAD

**Issue by ewandavis** [jlund/streisand#886]
Trying to install on Linode from my desktop Ubuntu 16.04
 Getting "linode-python required for this module"
Although it is installed - Output from pip show linode-python
Name: linode-python
Version: 1.1.1
Summary: Python bindings for Linode API
Home-page: https://github.com/tjfontaine/linode-python
Author: TJ Fontaine
Author-email: tjfontaine@gmail.com
License: UNKNOWN
Location: /usr/local/lib/python3.5/dist-packages
Requires: 
ewan@Oak:~/streisand/documentation$

ansible --version
ansible 2.3.2.0
  config file = 
  configured module search path = Default w/o overrides
  python version = 3.5.2 (default, Nov 17 2016, 17:05:23) [GCC 5.4.0 20160609]

git rev-parse HEAD
8bed3bcbb5c9394a14e11fbe6d9b2fb8793506ca

### Actual Behavior:

PLAY [Provision the Linode Server] ****************************************************************************************************************************************************************************************************
TASK [Gathering Facts] ****************************************************************************************************************************************************************************************************************
ok: [localhost]
TASK [genesis-linode : Get the default SSH key] ***************************************************************************************************************************************************************************************
changed: [localhost]
TASK [genesis-linode : Create the server] *********************************************************************************************************************************************************************************************
fatal: [localhost]: FAILED! => {"changed": false, "failed": true, "msg": "linode-python required for this module"}
    to retry, use: --limit @/home/ewan/streisand/playbooks/linode.retry
PLAY RECAP ****************************************************************************************************************************************************************************************************************************
localhost                  : ok=2    changed=1    unreachable=0    failed=1   
ewan@Oak:~/streisand$ sudo -H pip install linode-python
[sudo] password for ewan: 
Requirement already satisfied: linode-python in /usr/local/lib/python3.5/dist-packages
ewan@Oak:~/streisand$ 

### Steps to Reproduce:
1.

**Comment by cpu** [comment]
Hi @ewandavis,

It looks like you've installed the `linode-python` module for Python3 but not Python2.

Try `pip2 install linode-python` and re-trying. Streisand/Ansible will use Python2.

**Comment by cpu** [comment]
I'm going to close this issue since I believe my suggestion will solve the problem and there hasn't been a reply for 8 days. Please feel free to reopen this issue if the proposed solution doesn't work or you need more help. Thanks!
