### ISSUE TITLE
Problem with the default OpenVPN / SSLDroid configuration

### ISSUE THREAD

**Issue by dispose256** [jlund/streisand#891]
### Steps to Reproduce:
1. Follow steps to use OpenVPN/SSLDroid per the streisand server instructions (to the letter).
2. Attempt to connect and bang... the problem happens.

**Comment by dispose256** [comment]
I also tried it from a windows computer, attached are the log files (partial) from the connection attempt for OpenVPN and STUNNEL, again the direct OpenVPN config works Thu Aug 17 19:31:22 2017 OpenVPN 2.4.3 x86_64-w64-mingw32 [SSL (OpenSSL)] [LZO] [LZ4] [PKCS11] [AEAD] built on Jun 20 2017
Thu Aug 17 19:31:22 2017 Windows version 6.2 (Windows 8 or greater) 64bit
Thu Aug 17 19:31:22 2017 library versions: OpenSSL 1.0.2l  25 May 2017, LZO 2.10
Thu Aug 17 19:31:22 2017 MANAGEMENT: TCP Socket listening on [AF_INET]127.0.0.1:25343
Thu Aug 17 19:31:22 2017 Need hold release from management interface, waiting...
Thu Aug 17 19:31:23 2017 MANAGEMENT: Client connected from [AF_INET]127.0.0.1:25343
Thu Aug 17 19:31:23 2017 MANAGEMENT: CMD 'state on'
Thu Aug 17 19:31:23 2017 MANAGEMENT: CMD 'log all on'
Thu Aug 17 19:31:23 2017 MANAGEMENT: CMD 'echo all on'
Thu Aug 17 19:31:23 2017 MANAGEMENT: CMD 'hold off'
Thu Aug 17 19:31:23 2017 MANAGEMENT: CMD 'hold release'
Thu Aug 17 19:31:23 2017 Outgoing Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Aug 17 19:31:23 2017 Incoming Control Channel Authentication: Using 256 bit message hash 'SHA256' for HMAC authentication
Thu Aug 17 19:31:23 2017 TCP/UDP: Preserving recently used remote address: [AF_INET]127.0.0.1:41194
Thu Aug 17 19:31:23 2017 Socket Buffers: R=[65536->65536] S=[65536->65536]
Thu Aug 17 19:31:23 2017 Attempting to establish TCP connection with [AF_INET]127.0.0.1:41194 [nonblock]
Thu Aug 17 19:31:23 2017 MANAGEMENT: >STATE:1503012683,TCP_CONNECT,,,,,,
Thu Aug 17 19:31:23 2017 TCP connection established with [AF_INET]127.0.0.1:41194
Thu Aug 17 19:31:23 2017 TCP_CLIENT link local: (not bound)
Thu Aug 17 19:31:23 2017 TCP_CLIENT link remote: [AF_INET]127.0.0.1:41194
Thu Aug 17 19:31:23 2017 MANAGEMENT: >STATE:1503012683,WAIT,,,,,,

2017.08.17 19:30:55 LOG5[main]: stunnel 5.42 on x86-pc-msvc-1500 platform
2017.08.17 19:30:55 LOG5[main]: Compiled/running with OpenSSL 1.0.2l-fips  25 May 2017
2017.08.17 19:30:55 LOG5[main]: Threading:WIN32 Sockets:SELECT,IPv6 TLS:ENGINE,FIPS,OCSP,PSK,SNI
2017.08.17 19:30:55 LOG5[main]: Reading configuration from file stunnel.conf
2017.08.17 19:30:55 LOG5[main]: UTF-8 byte order mark not detected
2017.08.17 19:30:55 LOG5[main]: FIPS mode disabled
2017.08.17 19:30:55 LOG4[main]: Service [stunnel] needs authentication to prevent MITM attacks
2017.08.17 19:30:55 LOG5[main]: Configuration successful
2017.08.17 19:31:23 LOG5[0]: Service [stunnel] accepted connection from 127.0.0.1:58673
2017.08.17 19:31:23 LOG5[0]: s_connect: connected 178.62.251.191:993
2017.08.17 19:31:23 LOG5[0]: Service [stunnel] connected remote server from 127.0.0.1:58674

**Comment by cpu** [comment]
Hi @dispose256, Please fill out the issue template as completely as possible:
> Version of Ansible, using ansible --version :
> Output from git rev-parse HEAD in your Streisand directory :

> I also tried it from a windows computer, attached are the log files (partial) from the connection attempt for OpenVPN and STUNNEL, again the direct OpenVPN config works

To clarify: OpenVPN on Windows works? Only if you use the Direct OpenVPN profile or others?

> Connection initiates but fails repeatedly reporting MTU size mismatch errors and cypher mismatch error (local vs remote). Connections keep resetting and restarting without completing.

Can you provide a screenshot or copy of the error produced?

**Comment by alimakki** [comment]
Hi @dispose256,

I have tried to replicate your scenario however it seems to be working on my end (w/ Android 6). After you have configured SSLDroid, did you start the SSLDroid service prior to connecting to the stunnel configured profile?

![screenshot_20170820-183741](https://user-images.githubusercontent.com/920624/29499062-c8577c5a-85d6-11e7-9a60-e722b94e7156.png)

**Comment by alimakki** [comment]
Closing this issue as there has been no replies.

**Comment by itsrajivshah** [comment]
I'm having the same issue - when I try to connect on Android 8.0 with stunnel, it gets stuck in a loop. Attached are some screenshots of the logs in openvpn - if you need anything else, let me know.
![screenshot_20170905-112844](https://user-images.githubusercontent.com/18684709/30057196-b7de7be0-922d-11e7-957f-9fa11bdfe5a1.png)
![screenshot_20170905-112846](https://user-images.githubusercontent.com/18684709/30057197-b94011ba-922d-11e7-9e8a-c0bbc7988e24.png)
![screenshot_20170905-112850](https://user-images.githubusercontent.com/18684709/30057198-ba36c3fc-922d-11e7-878b-64ecc43cf46d.png)
![screenshot_20170905-112853](https://user-images.githubusercontent.com/18684709/30057200-bb22e3d6-922d-11e7-8f98-ef5d11f7d4c2.png)
