### ISSUE TITLE
Clarify Shadowsocks OBFS instructions

### ISSUE THREAD

**Issue by nickolasclarke** [jlund/streisand#893]
Its very unclear if the instructions for OBFS are referring to configuration on the server, or on the client. Furthermore, its not clear if you make these changes, if you MUST use the plugin going forward, etc. We need to clarify these instructions.

**Comment by nickolasclarke** [comment]
@cpu I actually may need a bit of info from you on how obfs works and its scope. I've not used it yet. I'll do my own research first though.

**Comment by cpu** [comment]
> Its very unclear if the instructions for OBFS are referring to configuration on the server, or on the client. 

You would make the changes on the client. The server doesn't need to be manually configured.

> Furthermore, its not clear if you make these changes, if you MUST use the plugin going forward, etc. We need to clarify these instructions.

I'm not sure I understand. If you configure the SS client to use the obfuscation you will need to keep using a server that has support, or disable the client obfuscation setting if you want to use a different server. You can use a non-obfuscated client with a server that supports obfuscation, I tested that when the obfs support was added to Streisand.

> @cpu I actually may need a bit of info from you on how obfs works and its scope.

Sure. @denoza added the initial support and may be able to answer questions as well.

**Comment by cpu** [comment]
I updated the issue description to remove the empty fields & updated the title to reflect that there is clarification requested. PRs welcome!

**Comment by nickolasclarke** [comment]
@cpu ok, it works exactly as I expected. The language used here is not clear though. I plan on cleaning up the docs and pushing a PR, fret not :)
