### ISSUE TITLE
Blocking Ads via /etc/hosts

### ISSUE THREAD

**Issue by SethSanchez** [jlund/streisand#904]
Very similar to #250, I have `# no-resolv` commented out in `/etc/dnsmasq.conf`, but I still see ads on Android and macOS when using the VPN.

Here's my dnsmasq status output:

```
Aug 26 08:40:31 seven systemd[1]: Starting dnsmasq - A lightweight DHCP and caching DNS server...
Aug 26 08:40:31 seven dnsmasq[3528]: dnsmasq: syntax check OK.
Aug 26 08:40:31 seven dnsmasq[3543]: started, version 2.75 cachesize 150
Aug 26 08:40:31 seven dnsmasq[3543]: compile time options: IPv6 GNU-getopt DBus i18n IDN DHCP DHCPv6 no-Lua TFTP conntrack ipset auth DNSSEC loop-detect inotify
Aug 26 08:40:31 seven dnsmasq[3543]: using nameserver 8.8.4.4#53
Aug 26 08:40:31 seven dnsmasq[3543]: using nameserver 8.8.8.8#53
Aug 26 08:40:31 seven dnsmasq[3543]: no servers found in /var/run/dnsmasq/resolv.conf, will retry
Aug 26 08:40:31 seven dnsmasq[3543]: bad address at /etc/hosts line 6
Aug 26 08:40:31 seven dnsmasq[3543]: read /etc/hosts - 40537 addresses
Aug 26 08:40:32 seven systemd[1]: Started dnsmasq - A lightweight DHCP and caching DNS server.

root@seven:~# head /etc/hosts
# This hosts file is a merged collection of hosts from reputable sources,
# with a dash of crowd sourcing via Github
#
# Date: August 26 2017
# Extensions added to this file: fakenews, gambling
# Number of unique domains: 40,529
#
# Fetch the latest version of this file: https://raw.githubusercontent.com/StevenBlack/hosts/master/hosts
# Project home page: https://github.com/StevenBlack/hosts
```

I'm using L2TP/IPsec and any help would be appreciated. I feel like I'm missing something simple here.

**Comment by cpu** [comment]
Hi @SethSanchez, 

Blocking ads isn't something that Streisand does currently. There is a [similar feature request](https://github.com/jlund/streisand-discussions/issues/22) in the streisand-discussions repository you might want to follow/comment on.

I would recommend that you open a [streisand-discussions](https://github.com/jlund/streisand-discussions) issue asking for help with this or ask in a general purpose system administration forum like [serverfault](https://serverfault.com/).

Thanks!
