### ISSUE TITLE
FATAL: all hosts have already failed -- aborting

### ISSUE THREAD

**Issue by andysacko** [jlund/streisand#92]
tried to install on a fresh install ubuntu 12.04 and using amazon ec2 i get this error every time i try to install:

TASK: [ec2-security-group | Create the EC2 security group] ********************
failed: [127.0.0.1 -> 127.0.0.1] => {"failed": true, "parsed": false}
invalid output was: Traceback (most recent call last):
  File "/root/.ansible/tmp/ansible-tmp-1415999388.64-274333761396674/ec2_group", line 1899, in <module>
    main()
  File "/root/.ansible/tmp/ansible-tmp-1415999388.64-274333761396674/ec2_group", line 187, in main
    for curGroup in ec2.get_all_security_groups():
  File "/usr/local/lib/python2.7/dist-packages/boto/ec2/connection.py", line 2969, in get_all_security_groups
    [('item', SecurityGroup)], verb='POST')
  File "/usr/local/lib/python2.7/dist-packages/boto/connection.py", line 1182, in get_list
    raise self.ResponseError(response.status, response.reason, body)
boto.exception.EC2ResponseError: EC2ResponseError: 403 Forbidden
<?xml version="1.0" encoding="UTF-8"?>
<Response><Errors><Error><Code>UnauthorizedOperation</Code><Message>You are not authorized to perform this operation.</Message></Error></Errors><RequestID>c1985fed-2515-438b-8473-27ec22f0c574</RequestID></Response>

FATAL: all hosts have already failed -- aborting

any ideas i follwed the instructions to the T

thanks

**Comment by cpu** [comment]
Since this issue is from 2014 I'm going to close it. It doesn't seem to be an issue we can take action on. Thanks - please open a new issue if you still have this problem using the tip of master & a new server provisioned with Streisand.
