### ISSUE TITLE
Setup on Debian

### ISSUE THREAD

**Issue by skeeve42** [jlund/streisand#93]
I am trying to setup streisand on one VPS from another (on the same provider). Both are Debian 7.
I did a fresh install on vps#2 but I keep getting the error below. I have root access via SSH to both servers. 
I don't understand when (if) and where (vps#1 or 2) to run ssh-keygen, so maybe that's the problem? I also don't know if by "following the defaults" I am supposed to leave the password bit blank or not.

root@myvps#1:~/streisand# nano inventory # I uncommented the last two lines and changed the IP to vps#2
root@myvps#1:~/streisand# nano ansible.cfg # I have tried it with host_key_checking both un- and commented out
root@myvps#1:~/streisand# ansible-playbook playbooks/streisand.yml

PLAY [Configure the Server and install required software] *********************

GATHERING FACTS ***************************************************************
fatal: [xxx.xxx.xxx.xxx] => SSH Error: data could not be sent to the remote host
. Make sure this host can be reached over ssh

TASK: [common | Warn users if the server's Linux distribution is not Debian 7] *
**
FATAL: no hosts matched or all hosts have already failed -- aborting

PLAY RECAP ********************************************************************
           to retry, use: --limit @/root/streisand.retry

xxx.xxx.xxx.xxx            : ok=0    changed=0    unreachable=1    failed=0

root@myvps#1:~/streisand#

Edit: I reinstalled Debian 7 on both VPSs and tried installing and running the script on each one (from the other one) and got the error above. I've tried running ssh-keygen on each (using a blank password on both) as well. I feel like I'm missing something...?

**Comment by skeeve42** [comment]
Shadowsocks has continued to work great on two android devices, but because of iOS limitations, it's pretty worthless on on there for using anything besides the shadowsocks browser.
I still haven't been able to get OpenVPN to work, which is really the best option for iOS and my windows machine. Where does streisand put iptables? Usually the ipv4 and ipv6 rules are in ```/etc/iptables``` but I don't see them there.

**Comment by pjrobertson** [comment]
Just as an FYI, I came across this (or a similar problem) on two new Debian installs. Here's my error:

```TASK: [ssh | Register the server's SSH fingerprints] ************************** 
failed: [185.38.46.189] => (item=ssh_host_ecdsa_key.pub) => {"changed": true, "cmd": ["ssh-keygen", "-lf", "/etc/ssh/ssh_host_ecdsa_key.pub"], "delta": "0:00:00.100678", "end": "2015-05-16 00:13:33.600625", "item": "ssh_host_ecdsa_key.pub", "rc": 1, "start": "2015-05-16 00:13:33.499947", "warnings": []}
stderr: /etc/ssh/ssh_host_ecdsa_key.pub: No such file or directory
changed: [185.38.46.189] => (item=ssh_host_rsa_key.pub)

FATAL: all hosts have already failed -- aborting
```

On one, running `sudo apt-get upgrade` worked, on the other I had to run this:

```
sudo ssh-keygen -t ecdsa -f /etc/ssh/ssh_host_ecdsa_key -N ''
```

**Comment by jlund** [comment]
Do you mind me asking which provider this was on?

**Comment by pjrobertson** [comment]
One was with https://bandwagonhost.com/ and the other https://www.weloveservers.net/

Funny thing is - I set up a streisand instance on bandwagonhost just fine about 2 months ago.
The only thing that happened on both servers was that I had internet dropouts/SSH timeouts whilst both were setting up (I'm in China). Perhaps that could be a part of it?

**Comment by skeeve42** [comment]
I never went back in to try to fix this since Shadowsocks worked so well for all my devices. I'd really like to be able to use OpenVPN though. @jlund , I am willing to give you access to one of my VPSs for a bit if you'd like to do some testing/troubleshooting.
Side question @pjrobertson , how were the speeds using those servers in China? The price is certainly right.

**Comment by pjrobertson** [comment]
It's very dependent on the GFW itself. I can get anything from 0.5Mbps-3.5Mbps. It's tcp over tcp, so not ideal of course, but it's stable. I've had trouble getting shadowsocks to work on my Mac, and it's annoying that each app needs to be set up to use the proxy. Hence why I prefer the VPN

**Comment by nickkilla** [comment]
@skeeve42 OpenVPN is a targeted protocol by the GFW. Rarely will it work.

**Comment by pjrobertson** [comment]
I'm using OpenVPN with stunnel. Works perfectly

**Comment by skeeve42** [comment]
@nickkilla It's true that regular OpenVPN has been targeted, but it still works great when obfuscated. @pjrobertson Shadowsocks was updated so that you can use a QRcode to set it up on every device, making it a little easier. Those speeds aren't too bad--thanks for the heads up.

**Comment by nickkilla** [comment]
@skeeve42 Hmm haven't tried it obfuscated yet, might look into that. Happy shadowsocks user here.

**Comment by honglio** [comment]
I get the same error when runing streisand install process on vps1 and hosting the remote server on vps2. I fix the error by running ssh-keygen on vps1, and then copying the resulting id_rsa.pub file from vps1 to /root/.ssh/authorized_keys on vps2. Thanks @skeeve42 @jlund

**Comment by skeeve42** [comment]
I had to do this again: ssh_host_ecdsa_key.pub does not exist. There is a ssh_host_dsa_key.pub

Is streisand supposed to create the key at some point?

I decided to copy the files ssh_host_dsa_key and ssh_host_dsa_key.pub to ssh_host_ecdsa_key and ssh_host_ecdsa_key.pub respectively to see if I could get it to continue and it worked.

**Comment by Rob-Johnson** [comment]
+1 I found I had to create ssh_host_ecdsa_key.pub

**Comment by cpu** [comment]
This thread has covered a few separate issues and it sufficiently old as to be unactionable. I'm going to close it and I encourage anyone still having problems to open fresh issues following the issue template. Thanks!
