### ISSUE TITLE
Amazon Lightsail existing server install fails diagnostics role "AnsibleUndefinedVariable"

### ISSUE THREAD

**Issue by mstarr68** [jlund/streisand#931]
### Expected behavior:
To install without error. Found ubuntu user parameter being ignored. Edited ./streisand script to default to ubuntu instead of root for installer to work
Once triggered for exisiting server, enter IP, connects successfully and installs
(Would rather have native support for Amazon Lightsail instance instead of normal EC2 instance)

### Actual Behavior:
After entering IP, and after a few checks, it gets to "produce the diagnostics markdown file to share if there is an error" and errors out with an error in ansible: "AnsibleUndefinedVariable: 'dict object' has no attribute 'ansible_architecture'
Can not resolve or get passed this point.
I tried several times, in several instances both Ubuntu and Debian. Also inside a linux machine to connect remotely, as well as inside server doing localhost or existing pointing back to itself. Nothing will install on this lightsail instance.

### Steps to Reproduce:
1.  start Amazon Lightsail account, create instance, Ubuntu 16,04. Apt-get update and upgrade. create SSH keygen and copy to server, add to authorized_keys. Make sure you can connect to SSH using said new keys (i find an initial ssh session required and prompted to accept needed before a successful test can connect using troubleshooting steps). Once ssh can connect without error, trigger modified ./streisand script so it connects and runs as ubuntu user to your IP. Enter in IP and wait for error.

[ contents of `streisand-diagnostics.md` here ]

**Comment by nopdotcom** [comment]
Amazon Lightsail is pretty weird right now. The easiest way I’ve found to provision it:
1. Create an Ubuntu instance
1. Upgrade it and install dependencies
1. Create a static IP; associate it with the machine
1. Reboot, just in case
1. Run `streisand`, and deploy to localhost
1. Go edit a bunch of tedious firewall rules :‐)

You may find it useful to install all the dependencies at once. I have a [cloud-init script](https://gist.github.com/nopdotcom/f7f148ce57f2728b9747e8b5ad9066c5) that gets all that right. Add it to the instance when you’re creating it:

![capto_capture 2017-09-08_09-06-38_pm](https://user-images.githubusercontent.com/1357866/30235777-ccb43bcc-94da-11e7-9af0-471bd8ccfcfa.png)

**Comment by cpu** [comment]
@mstarr68 Can you share your Ansible version? `ansible --version`

**Comment by mstarr68** [comment]
Whatever version is currently in the repository. I have done 5 instances so far today, including another one right now per the above suggestion and setup script.  Currently this install is coming back with 2.3.2.0  and python version 2.7.12

**Comment by cpu** [comment]
>  Currently this install is coming back with 2.3.2.0 and python version 2.7.12

Very odd! That's the same Ansible version I'm using and it has `ansible_achitecture` defined.

Apologies for the trouble. Can you try running `git fetch origin && git checkout origin/master` from your Streisand clone and seeing if https://github.com/jlund/streisand/pull/932 fixed the problem for you?

**Comment by mstarr68** [comment]
Well, I did as above, and still getting the same error.

Git rev-parse HEAD = 8697641702d4981a5950367c3fe65b43fc22dba0

**Comment by mstarr68** [comment]
I wasn't able to do the "existing server" option, remotely or locally, due to the error above even after updating to the latest #932.
However, I was able to follow nopdotcom's advice and set it up as localhost just fine. 
Apparently CLI via aws lightsail commands are down/removed at the moment, so I wasn't able to find a way to script out the firewall ports, although that's supposed to be an option.  I just manually added the ports via the web gui for that lightsail instance, following the doc generated during install.
Everything seems to be working fine now.  So at least it's possible.

**Comment by cpu** [comment]
> Well, I did as above, and still getting the same error. Actually slightly different now. no attribute 'ansible_system'

Hmmm. Can you share the output of `ansible -m setup localhost` as a gist?

**Comment by cpu** [comment]
@mstarr68 I think d944277 will resolve this. Are you able to pull master again to see if the existing/local options work for you now? Thanks!

**Comment by nopdotcom** [comment]
I spun up an EC2 builder to do a deploy to a Lightsail server. The things I had to do before running `./streisand` were:
1. Start a new Lightsail instance to be your *server*.
    1. Ensure you have the SSH keys associated with the new *server* on your *builder* (choosing keys is an option on launch). 
    1. Run that [`cloud-init` script](https://gist.github.com/nopdotcom/f7f148ce57f2728b9747e8b5ad9066c5), on the *builder*, either on boot or with `sudo`. This should not be necessary to run on the *server*, just the *builder*, but I usually do it on the builder too anyway.
1. Assign the server a static IP
1. Reboot the server. (Seems to be optional.)
1. `ssh YOUR-NEW-SERVER` from the *builder* must complete without error. 
    1. The first time you run it, it’ll prompt for host key identification. 
    1. You need a passwordless `id_rsa` and `id_rsa.pub` on the *builder* to be used for configuration. Make sure you use the SSH keys you picked in the new instance dialog when you’re creating your server.
1. `export ANSIBLE_SSH_USER=ubuntu`
1. `./streisand`

**Comment by nopdotcom** [comment]
Also note that `pip install awscli` will get you an up-to-date `aws` command with Lightsail support.

**Comment by cpu** [comment]
I'm going to close this issue from inactivity. I believe the original `AnsibleUndefinedVariable` problem has been addressed. Thanks!
