### ISSUE TITLE
HELP on RasPi 2B (Ubuntu 16.04.3): Installation fails on Dmidecode Task Step

### ISSUE THREAD

**Issue by zakattax** [jlund/streisand#941]
### Expected behavior:
Installation complete on localhost.

### Actual Behavior:
The installation stops on the task of the Streisand installation script trying to determine localhost Cloud provider name from the BIOS version (fails or stops on the step of dmidecode).

![screen shot 2017-09-13 at 2 30 36 pm](https://user-images.githubusercontent.com/15940189/30362813-49a5072a-9890-11e7-9d66-5088c424f582.png)

### Steps to Reproduce:
1. After booting a Raspberry Pi to run on Ubuntu 16.04.3, all the dependencies needed by Streisand as seen in the readme were installed.
2. The GitHub repository was cloned to a folder called "streisand" and ./streisand was ran.
3. The option of installing on localhost (option 7) was selected in the install script.
4. The word "streisand" was retyped to confirm the installation or reconfiguration of localhost files.

##### *Operating System of target host:* Ubuntu 16.04.3 on Raspberry Pi 2B

**Comment by cpu** [comment]
Hi @zakattax 

I'll take a crack at working around this for you but Raspberry Pi's and anything other than the `x86_64` architecture isn't officially supported by Streisand. You'll likely find that things will break further down the line when Streisand installs services without upstream ARM support.

**Comment by nopdotcom** [comment]
dmidecode does this:

```
open("/sys/firmware/dmi/tables/smbios_entry_point", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/sys/firmware/efi/systab", O_RDONLY) = -1 ENOENT (No such file or directory)
open("/proc/efi/systab", O_RDONLY)      = -1 ENOENT (No such file or directory)
write(1, "Scanning /dev/mem for entry poin"..., 35) = 35
open("/dev/mem", O_RDONLY)              = 3
fstat64(3, {st_mode=S_IFCHR|0640, st_rdev=makedev(1, 1), ...}) = 0
mmap2(NULL, 65536, PROT_READ, MAP_SHARED, 3, 0xf0000) = -1 EPERM (Operation not permitted)
lseek(3, 983040, SEEK_SET)              = 983040
read(3, 0x55e9c410, 65536)              = -1 EPERM (Operation not permitted)
```

And here’s what the kernel says in dmesg:

```
[  177.016413] Program dmidecode tried to access /dev/mem between f0000->100000.
```

dmidecode *should* fail on random ARM systems. Let’s see what will go wrong next....

**Comment by nopdotcom** [comment]
What goes wrong next is some missing upstream packages (i386/x86_64 only), and then a bunch of disk corruption. Unclear to me who is at fault. (Probably Broadcom; they needed to put a 9V barrel jack on the Pi3 but were too stubborn.)

Yes, I’m still looking at this.

**Comment by nopdotcom** [comment]
We currently use an upstream binary repository for nginx, and they only have binaries for amd64, arm64, and i386. No 32-bit armhf. I think it may be time to move this bug over to [streisand-discussions](https://github.com/jlund/streisand-discussions)? We could build nginx from source, but unless we're doing that for x86_64 too, I think it might be too much of a support tail.

**Comment by nopdotcom** [comment]
See [nopdotcom:awful-rpi-hax](https://github.com/nopdotcom/streisand/tree/awful-rpi-hax), although you need to be comfortable enough with Debian/Ubuntu to build nginx from upstream packaging/source.

**Comment by nopdotcom** [comment]
#953 was merged into mainline so I'm going to close this bug. No, the RPi don't work cleanly, but I don't have the cycles to fix it--PRs definitely welcome. It might be worth looking at [the OpenWrt page](https://wiki.openwrt.org/toh/raspberry_pi_foundation/raspberry_pi) and [the LEDE download page for the brcm family](http://downloads.lede-project.org/releases/17.01.2/targets/brcm2708/).

**Comment by cpu** [comment]
Thanks for taking a look @nopdotcom !
