### ISSUE TITLE
"AnsibleUndefinedVariable: 'streisand_genesis_role' is undefined"

### ISSUE THREAD

**Issue by ape364** [jlund/streisand#956]
### Expected behavior:

Streisand installed to existing server.

### Steps to Reproduce:
1. `git clone https://github.com/jlund/streisand.git && cd streisand`
2. `./streisand`
3. Choose 8 (existing server)
4. Input server ip
5. Skip domain and email inputs.
6. error

##### *Version of Ansible, using `ansible --version` :*
```
[ape364@home ~]$ ansible --version
ansible 2.4.0.0
  config file = /etc/ansible/ansible.cfg
  configured module search path = [u'/home/ape364/.ansible/plugins/modules', u'/usr/share/ansible/plugins/modules']
  ansible python module location = /usr/lib/python2.7/site-packages/ansible
  executable location = /usr/bin/ansible
  python version = 2.7.13 (default, Jul 21 2017, 03:24:34) [GCC 7.1.1 20170630]
```

**Comment by nopdotcom** [comment]
Could you try an Ansible before 2.4? I think we're hitting some teething pains. You can fetch an older one with `pip install "ansible<2.4"`.

**Comment by cpu** [comment]
@nopdotcom This isn't related to the Ansible version.

@ape364 There's an outstanding fix for this in https://github.com/jlund/streisand/pull/955 - I will try to merge tonight. In the meantime can you try checking that branch out?

I also ran into & fixed this in 134e00ab8fe33ebbf6b1b668672b8ce2db66cd46

**Comment by ape364** [comment]
On this branch the error is disappeared. Next i got an error related to the package `libgnutls-dev`. I've renamed it to `libgnutls28-dev` in `/streisand/playbooks/roles/openconnect/vars/main.yml` and it's okay. 
Now i'm getting error related to pgp keys: [gist](https://gist.github.com/ape364/b4131df9ff678ff64eb8a9ac1e48fa3a).

**Comment by cpu** [comment]
I merged the interim fix from @jlund's PR to master.  @ape364 Thanks for reporting the undefined var error!
